### ISSUE TITLE
A type of armor does not seems to be rendering on the floating pirate ship on one of the pirates.

### ISSUE THREAD

**Issue by Slayer5934** [TeamChocoQuest/ChocolateQuestRepoured#100]
![Capture](https://user-images.githubusercontent.com/20819543/71633875-26ff6b80-2be5-11ea-8a56-2dbc93b49be0.PNG)
![Capture2](https://user-images.githubusercontent.com/20819543/71633923-79d92300-2be5-11ea-8d3f-9ca471cf2000.PNG)

**Comment by LordEpos** [comment]
This is the heavy diamond armor, and it's a known issue. It happens because nobody's bothered to texture/model it yet. Most armor models are some degree of unfinished right now.

**Comment by Slayer5934** [comment]
I had a feeling this was the case, as this is the alpha release, some things are bound to be unfinished :3

**Comment by LordEpos** [comment]
Btw, Inquisition armor isn't available in survival yet, but it's also missing its model.
