### ISSUE TITLE
[Maybe-Not-A-Bug] Illagers seem to attack the necromancer and kill him.

### ISSUE THREAD

**Issue by Slayer5934** [TeamChocoQuest/ChocolateQuestRepoured#101]
![Capture](https://user-images.githubusercontent.com/20819543/71634033-814cfc00-2be6-11ea-9354-616cfb7e8250.PNG)
![Capture2](https://user-images.githubusercontent.com/20819543/71634047-a80b3280-2be6-11ea-9aa6-581245649ab7.PNG)

**Comment by LordEpos** [comment]
Yeah, the Necromancer wasn't an Illager in the original CQ and I guess his faction list hasn't been updated. For now let's just say that necromancers are shunned in Illager culture because their magics are considered spooky and unnatural.

**Comment by Slayer5934** [comment]
WE HATE YOUR MAGICS! (Uses flame throwing magic to obliterate necromancer who isn't even fighting back)

Unless the necromancer is just a n00b and is not correctly raising them from the dead, they just come back and destroy him :p

**Comment by DerToaster98** [comment]
that is supposed to be like that. necromancer is in a different factions than the illagers

**Comment by DerToaster98** [comment]
but its a bug that he is assigned as the boss of the wrong faction
