### ISSUE TITLE
game crashes while exploring the overworld

### ISSUE THREAD

**Issue by Aer-ink** [TeamChocoQuest/ChocolateQuestRepoured#103]
Just as the tittle says the game crashed while exploring the overworld not sure if its related to the mod tho

[crash-2019-12-31_14.09.49-server.txt](https://github.com/TeamChocoQuest/ChocolateQuestRepoured/files/4013543/crash-2019-12-31_14.09.49-server.txt)

**Comment by DerToaster98** [comment]
it seems to be caused by a mod changing fields of forge classes, maybe try updating your forge version first?

**Comment by DerToaster98** [comment]
Also the Entity causing the crash is from Ice N Fire Mod so it is probably caused by ice and fire not making their mobs like described in the standards

**Comment by Meldexun** [comment]
It's actually a bug in cqr. Looking at the combineArrays method from the ArrayCollectionMapManipulationUtil class you see that the second part can't be correct.
