### ISSUE TITLE
Protected Pirate Ships 

### ISSUE THREAD

**Issue by orian34** [TeamChocoQuest/ChocolateQuestRepoured#105]
The pirate ships benefit from the protection of dungeons, but they don't have ways to climb in, meaning it's incredibly hard to enter one with conventional means.

Plan was to make pirate ships unprotected(>Arlo), so it's a reminder issue.

**Comment by DerToaster98** [comment]
To fix: just edit the .properties file called ships inside the "dungeons" folder, then you set "protectblocks" to false
