### ISSUE TITLE
Incompatibility

### ISSUE THREAD

**Issue by Baushawat** [TeamChocoQuest/ChocolateQuestRepoured#106]
I just found out that Chocolate Quest Repoured is incompatible with More Creeps and Weirdos Revival (https://www.curseforge.com/minecraft/mc-mods/more-creeps-and-weirdos-revival), I don't know if you're able to fix the issue, I've already sent a post about the problem on their Discord server, just letting you know.

The game crashes while loading in the Forge loading screen.
[crash-2020-01-01_11.21.22-client.txt](https://github.com/TeamChocoQuest/ChocolateQuestRepoured/files/4014155/crash-2020-01-01_11.21.22-client.txt)

**Comment by DerToaster98** [comment]
This bug report isnt valid. We are missing required things for fixing like log files and crash reports

**Comment by Baushawat** [comment]
Sorry I didn't even see I haven't posted the crash report !
Updated, it's now here !

**Comment by DerToaster98** [comment]
thank you

**Comment by DerToaster98** [comment]
that issue should be fixed by now, once we publish the newest fixed build
