### ISSUE TITLE
CQR Armor with custom models  not rendering correctly on endermen

### ISSUE THREAD

**Issue by xDemonBoyy** [TeamChocoQuest/ChocolateQuestRepoured#107]
I think that this issue is ready to stop being invalid, if not tell me what's missing

[2020-01-01-2.log.gz](https://github.com/TeamChocoQuest/ChocolateQuestRepoured/files/4014145/2020-01-01-2.log.gz)

**Comment by Slayer5934** [comment]
![2020-01-01_14 05 11](https://user-images.githubusercontent.com/20819543/71642351-f0befc00-2c77-11ea-816b-c114762888b2.png)

**Comment by xDemonBoyy** [comment]
[crash-2020-01-01_15.01.46-client.txt](https://github.com/TeamChocoQuest/ChocolateQuestRepoured/files/4014195/crash-2020-01-01_15.01.46-client.txt)

**Comment by xDemonBoyy** [comment]
[2020-01-01-6.log.gz](https://github.com/TeamChocoQuest/ChocolateQuestRepoured/files/4014196/2020-01-01-6.log.gz)

**Comment by xDemonBoyy** [comment]
I think that this issue is ready to stop being invalid, if not tell me what's missing
