### ISSUE TITLE
Return from Nether

### ISSUE THREAD

**Issue by Scarfiremmi** [TeamChocoQuest/ChocolateQuestRepoured#108]
I traveled to the nether, spawned in a nether city and when I attempted to return, it instead created an area of chunks of various blocks, stone, cobwebs, water, etc. and Journeymap thought that I was still in the nether. Here are images of what I saw.
![2020-01-01_13 00 29](https://user-images.githubusercontent.com/59420491/71645551-57074700-2c97-11ea-9ad8-2813a583f075.png)
![2020-01-01_13 00 44](https://user-images.githubusercontent.com/59420491/71645552-57074700-2c97-11ea-9afe-9d37a5493c48.png)

![2020-01-01_13 00 50](https://user-images.githubusercontent.com/59420491/71645542-4e167580-2c97-11ea-9a95-363f23742aa9.png)
![2020-01-01_13 00 53](https://user-images.githubusercontent.com/59420491/71645543-4e167580-2c97-11ea-959d-73d58e88b8b0.png)

**Comment by LordEpos** [comment]
Well, you are not top of the nether, but I have no dang clue what else is happening here. We'll look into it.

**Comment by DerToaster98** [comment]
This report is invalid, modlist and log files are missing

I cant do anything without these
