### ISSUE TITLE
Crash upon entering a world

### ISSUE THREAD

**Issue by cybercat5555** [TeamChocoQuest/ChocolateQuestRepoured#109]
When entering a world that previously had CQR installed, I cannot enter it again without a crash
ChocolateQuestRepoured-1.12.2-1.0.1A-DayOnePatch
Forge 14.23.5.2838

[latest.log](https://github.com/TeamChocoQuest/ChocolateQuestRepoured/files/4014822/latest.log)

[crash-2020-01-01_22.00.54-server.txt](https://github.com/TeamChocoQuest/ChocolateQuestRepoured/files/4014817/crash-2020-01-01_22.00.54-server.txt)

**Comment by DerToaster98** [comment]
Thanks for reporting! this is an issue with the protection system.

To fix: Go into your world's folder, then go into data/CQR/
In this folder, delete cq_chunk_data.nbt (if present) and prot_region_defs.zip and protected_regions.zip

Then start your game and it shouldnt crash when entering your world

**Comment by DerToaster98** [comment]
Thanks for reporting! this is an issue with the protection system.

To fix: Go into your world's folder, then go into data/CQR/
In this folder, delete cq_chunk_data.nbt (if present) and prot_region_defs.zip and protected_regions.zip

Then start your game and it shouldnt crash when entering your world

**Comment by jdawg3636** [comment]
Thanks for your report!

I immediately noticed that the ProtectionHandler is being called using ASM, something which (to my knowledge) we do not currently use. Given the numerous coremods you have installed (see below), there is a decent chance that this is an issue with another mod's buggy implementation of ASM.

Also, the part that failed is the bit of code that filters out the dimension id from a file name (turns dim_0\d65cdbb8-054e-464d-b825-d11aace80c63 into integer value 0). Given that you are the only user to report this thus far and that the crash log suggests that a '-' was found in place of the dimension id, I have to assume that the ProtectionHandler was passed an invalid file name by another mod using a hilariously broken implementation of ASM (likely the Ice and Fire mod, given our previous experiences).

Thanks again for reporting, be sure to let us know if you have any reason to believe that this is an issue on our end.

Coremod List:
iceandfire-1.8.3.jar
themidnight-0.3.5.jar
cxlibrary-1.12.1-1.6.1.jar
TheBetweenlands-3.5.4-core.jar
ImmersiveEngineering-core-0.12-92.jar
Forgelin-1.8.2.jar
Bloodmoon-MC1.12.2-1.5.3.jar
llibrary-core-1.0.11-1.12.2.jar
librarianlib-1.12.2-4.19.2-release.jar
bewitchment-1.12.2-0.0.21.5.jar
VanillaFix-1.0.10-99.jar
rats-3.2.3.jar
DynamicSurroundings-core-1.12.2-3.5.5.0.jar

**Comment by Meldexun** [comment]
No, it's the dungeon protection system that is causing the bug. But in the newest version it's disabled until it is fixed.
