### ISSUE TITLE
Incompatability with Item Physics mod

### ISSUE THREAD

**Issue by Yranic** [TeamChocoQuest/ChocolateQuestRepoured#113]
The game instantly crashes when loaded with the Full item physics mod and cqr
i have isolated both mods and i couldnt find a crash report other than it telling me that it crashed

**Comment by DerToaster98** [comment]
Invalid, no log files or crash reports

**Comment by Meldexun** [comment]
Do you have CreativeCore installed? Because it's a dependency of ItemPhysic Full...
