### ISSUE TITLE
Revolver/Musket bug

### ISSUE THREAD

**Issue by rlcraftisharder** [TeamChocoQuest/ChocolateQuestRepoured#114]
![2020-01-03_22 26 37_2](https://user-images.githubusercontent.com/59460450/71766649-c2cff680-2ec7-11ea-9e3d-0bf0ecc01f80.png)

Getting shot to death by any type of musket/revolver by a CQR mob such as a Pirate makes the game think that you killed yourself. (Not to be confused, my minecraft username is Creeper)

**Comment by LordEpos** [comment]
Whoops, I thought we'd fixed that before alpha, my bad.
