### ISSUE TITLE
Updated Attempting to exit Nether bug

### ISSUE THREAD

**Issue by Scarfiremmi** [TeamChocoQuest/ChocolateQuestRepoured#115]
**Describe the bug**
When attempting to exit the Nether, the portal appears to send you to above the roof of the nether instead.

**To Reproduce**
I created a nether portal, went through, marked it with Journeymap, spawned in a Nether City, and attempted to return to the overworld.
![2020-01-01_13 00 29](https://user-images.githubusercontent.com/59420491/71770763-dee68e80-2eed-11ea-91b0-b672b01e9308.png)
![2020-01-01_13 00 44](https://user-images.githubusercontent.com/59420491/71770764-e27a1580-2eed-11ea-8c35-63d078c42014.png)
![2020-01-01_13 00 50](https://user-images.githubusercontent.com/59420491/71770768-ea39ba00-2eed-11ea-8e1e-196d55ba104d.png)
![2020-01-01_13 00 53](https://user-images.githubusercontent.com/59420491/71770766-e7d76000-2eed-11ea-8876-75d28b1ee040.png)

**Versions**
Chocolate Quest Repoured: 
Forge: 14.23.5.2847
Minecraft: 1.12.2

**Other**
Crash report:
Log file: (pretty sure this is far enough back) [Log (incomplete).txt](https://github.com/TeamChocoQuest/ChocolateQuestRepoured/files/4022329/Log.incomplete.txt)
Singleplayer/Multiplayer:
Other mods (that are necessary to produce the bug):
Other mods (that are also installed): [modlist.txt](https://github.com/TeamChocoQuest/ChocolateQuestRepoured/files/4022330/modlist.txt)

**Comment by Meldexun** [comment]
No that part of the log is not enought. Please provide the complete log file from the "logs" folder.

**Comment by Scarfiremmi** [comment]
[2019-05-28-1.log.gz](https://github.com/TeamChocoQuest/ChocolateQuestRepoured/files/4022601/2019-05-28-1.log.gz)
Here it should be then

**Comment by DerToaster98** [comment]
that isnt the complete log. 
First delete your log foler.
Then please completely reproduce the bug, then send over your entire log folder.

**Comment by DerToaster98** [comment]
Tried to reproduce it. went in a nether, generated a nether city, waited until its done, went back to the overworld and no strange rendering issues. must be another mod that causes these issues.

**Comment by Scarfiremmi** [comment]
Here is the full log folder

[debug.log](https://github.com/TeamChocoQuest/ChocolateQuestRepoured/files/4023966/debug.log)



(From Buildcraft folder)
[book.log](https://github.com/TeamChocoQuest/ChocolateQuestRepoured/files/4023968/book.log)
[guide.log](https://github.com/TeamChocoQuest/ChocolateQuestRepoured/files/4023969/guide.log)

**Comment by Scarfiremmi** [comment]
[latest.log](https://github.com/TeamChocoQuest/ChocolateQuestRepoured/files/4023973/latest.log)

**Comment by Meldexun** [comment]
This is the fault of the dungeon protection system which is disabled in the newest version.

**Comment by jdawg3636** [comment]
Meldexun is correct:
> This is the fault of the dungeon protection system which is disabled in the newest version.

Thought that I would clarify for the sake of documentation that the underlying issue is the ProtectionHandler failing to properly handle negative dimension ids.
