### ISSUE TITLE
Diamond heavy armor and Inquisition armor have missing textures

### ISSUE THREAD

**Issue by JeromeVitruvio** [TeamChocoQuest/ChocolateQuestRepoured#116]
Also the dragon helmet's texture displays incorrectly

![2020-01-06_13 04 05](https://user-images.githubusercontent.com/59564293/71817431-1ee07980-3086-11ea-8588-cbe86eb85a12.png)
![2020-01-06_13 03 57](https://user-images.githubusercontent.com/59564293/71817432-1ee07980-3086-11ea-9272-bea7d6afe991.png)

**Versions**
Chocolate Quest Repoured: 1.1.0A
Forge:
Minecraft:

**Other**
Crash report:
Log file:
Singleplayer/Multiplayer:
Other mods (that are necessary to produce the bug):
Other mods (that are also installed):

**Comment by DerToaster98** [comment]
Not an issue, those arent implemented yet.
