### ISSUE TITLE
[INVALID] Mounted Dummy Replacement Does not Work

### ISSUE THREAD

**Issue by Yranic** [TeamChocoQuest/ChocolateQuestRepoured#119]
Dummys mounted on Creatures such as Horses won't be replaced with actual faction mobs like the rest of the dummies 

Screenshots
![2020-01-08_18 01 29](https://user-images.githubusercontent.com/54374689/71999520-dbcb0580-3241-11ea-83e9-73391cbc6285.png)
![2020-01-08_18 04 59](https://user-images.githubusercontent.com/54374689/71999524-dd94c900-3241-11ea-8919-04788f46e36c.png)

****
**Versions**
Chocolate Quest Repoured:1.12.2-1.1.0B
Forge:14.235.2847
Minecraft:1.12.2

**Comment by DerToaster98** [comment]
Invalid without the dungeon congig in use

**Comment by DerToaster98** [comment]
was fixed with latest build
