### ISSUE TITLE
CQ Shields do not lose durability with use.

### ISSUE THREAD

**Issue by LordEpos** [TeamChocoQuest/ChocolateQuestRepoured#12]
CQ shields don't lose durability when used. I'd suggest setting durability to be the same as vanilla shields for now, at least until we come to a more precise decision.

Additionally, no texture while blocking with them, but that is known, and they look weird placed on tables, (would suggest turning them sideways, since they look great in item frames.)

**Comment by Tiviacz1337** [comment]
Partially fixed, needs texture and model
