### ISSUE TITLE
Server crash during worldgen related to banners

### ISSUE THREAD

**Issue by TheGag96** [TeamChocoQuest/ChocolateQuestRepoured#122]
I've been running a relatively light modded server with the latest alpha release, and when my friends attempt to explore new terrain, the server occasionally crashes. From what they've said, it seems as though they can comfortably explore for a while at least before it crashes.

Crash report: [Here](https://pastebin.com/h8MHXH29)

The exception that crashed makes it look like it specifically has to do with generating new terrain containing banners. I'm not sure if any other mods I have conflict in such a way to make this happen (mod list is in the report, of course). 

Let me know if you need more information than just this. Thanks!

**Comment by Meldexun** [comment]
Please use the bug report template next time. Also you are running an outdated version. Though the bug isn't fixed in the newer version.

**Comment by TheGag96** [comment]
Ah, darn - didn't realize an update was released so quickly. I was about to use the template, but it wasn't really applicable to this bug. Using it would just lead to needless redundancy, like:

```
**Describe the bug**
The server crashed on generating terrain

**To Reproduce**
Generate some terrain
```

...etc. All the other info asked for by the template is present already in the crash log. (This arguably could also be said for V4m4cher0n's issue from yesterday.)

**Comment by DerToaster98** [comment]
Bug is known. Issue will be closed cause of not using the template

**Comment by DerToaster98** [comment]
Also: just cause another one didnt use a template does not allow the common not-use of the template. If you read it, you would have seen that we told him that he should use that template. In the future: reports that dont use the template will be ignored and not worked on
