### ISSUE TITLE
Weird crash happening since the most recent release. Happens upons world exploration.

### ISSUE THREAD

**Issue by xDemonBoyy** [TeamChocoQuest/ChocolateQuestRepoured#123]
[crash-2020-01-10_15.22.30-server.txt](https://github.com/TeamChocoQuest/ChocolateQuestRepoured/files/4046344/crash-2020-01-10_15.22.30-server.txt)
[2020-01-10-2.log.gz](https://github.com/TeamChocoQuest/ChocolateQuestRepoured/files/4046345/2020-01-10-2.log.gz)

**Comment by DerToaster98** [comment]
Does not use the issue template. Issue will be closed
