### ISSUE TITLE
Using Hook Shot crashes server

### ISSUE THREAD

**Issue by TheGag96** [TeamChocoQuest/ChocolateQuestRepoured#124]
**Describe the bug**
Was running Alpha 5 on a server. A player held the hook shot in his hand, right clicked, and instantly crashed the server. 

**To Reproduce**
1. Hold a hook shot
2. Right click

**Expected behavior**
The server will crash.

**Screenshots**
N/A

**Versions**
Chocolate Quest Repoured: Alpha 5
Forge: 2847
Minecraft: 1.12.2

**Other**
Crash report: [Link](https://pastebin.com/A6XWVGmQ)
Singleplayer/Multiplayer: Dedicated server

**Comment by LordEpos** [comment]
Hookshot isn't really implemented yet (hence why it's unobtainable in survival) 

I'm pretty sure that we haven't fixed this yet, but you *are* two versions behind. I'd appreciate if bugs were tested with the latest version before being reported, just to make sure they still are problems.

**Comment by DerToaster98** [comment]
Hookshot isn’t implemented yet. This is probably going to be fixed in the next update.

**Comment by DerToaster98** [comment]
should be fixed with latest build
