### ISSUE TITLE
Mobs not spawning in all dungeons on a privately hosted server

### ISSUE THREAD

**Issue by Colaskink** [TeamChocoQuest/ChocolateQuestRepoured#126]
There are no mobs spawning in dungeons when creating a world on a server
Everytime i go in a dungeon there are no enemies besides the naturally spawning mobs from darkness
When there should have been a bunch of enemies
Version 1.12.2
forge version 14.23.5.2847
CQR version 1.12.2-1.3.0A
Mod list:
[ANGRY PIXEL] The Betweenlands	oily_oli	TheBetweenlands-3.5.5-universal.jar	
Advanced Hook Launchers	EnderLanky	AdHooks-1.12.2-3.2.3.0-build.0435.jar	
AppleSkin	squeek502	AppleSkin-mc1.12-1.0.9.jar	
AtomicStryker's Battle Towers	atomicstrykergrumpy	BattleTowers-1.12.2.jar	
Backpacks	Eydamos	backpack-3.0.2-1.12.2.jar	
Baubles	Azanor13	Baubles-1.12-1.5.2.jar	
Better Advancements	way2muchnoise	BetterAdvancements-1.12.2-0.1.0.77.jar	
Better Builder's Wands	Portablejim	BetterBuildersWands-1.12-0.11.1.245+69d0d70.jar	
Better Foliage	octarine_noise	BetterFoliage-MC1.12-2.3.1.jar	
BetterFps	Guichaguri	BetterFps-1.4.8.jar	
BiblioCraft	Nuchaz	BiblioCraft[v2.4.5][MC1.12.2].jar	
Biomes O' Plenty	Forstride	BiomesOPlenty-1.12.2-7.0.1.2441-universal.jar	
Bonsai Trees 2	davenonymous	bonsaitrees-1.1.4-b170.jar	
Bookshelf	DarkhaxDev	Bookshelf-1.12.2-2.3.590.jar	
Chameleon	Texelsaur	Chameleon-1.12-4.1.3.jar	
Chisel	tterrag1098	Chisel-MC1.12.2-1.0.1.44.jar	
Chisels & Bits	AlgorithmX2	chiselsandbits-14.33.jar	
Chocolate Quest Repoured	Lordepos	ChocolateQuestRepoured-1.12.2-1.3.0A.jar
CodeChicken Lib 1.8.+	covers1624	CodeChickenLib-1.12.2-3.2.3.358-universal.jar	
ConnectedTexturesMod	tterrag1098	CTM-MC1.12.2-1.0.1.30.jar	
Construct's Armory	TheIllusiveC4	conarm-1.12.2-1.2.5.3.jar	
Corail Tombstone	Corail_31	tombstone-3.6.4-1.12.2.jar	
Cosmetic Armor Reworked	LainMI	CosmeticArmorReworked-1.12.2-v4a.jar	
CraftTweaker	Jaredlll08	CraftTweaker2-1.12-4.1.20.jar	
Davincis Vessels	darkevilmac	davincisvessels-1.12-6.340-full.jar	
Decocraft	RazzleberryFox	Decocraft-2.6.3_1.12.2.jar	
Dungeon Tactics	PegBeard	DungeonTactics-1.12.2-0.16.6.jar	
Effortless Building	Requioss	effortlessbuilding-1.12.2-2.16.jar	
Electroblob's Wizardry	Electroblob	ElectroblobsWizardry-4.2.7-MC1.12.2.jar	
Enchanting Plus	DarkhaxDev	EnchantingPlus-1.12.2-5.0.176.jar	
Ender IO	CrazyPants_MC	EnderIO-1.12.2-5.1.53.jar	
Ender Storage 1.8.+	covers1624	EnderStorage-1.12.2-2.4.6.137-universal.jar	
EnderCore	tterrag1098	EnderCore-1.12.2-0.5.73.jar	
Exotic Birds	ThePavoReality	Exotic Birds 1.12.2-3.1.0.jar	
Extreme Reactors	ZeroNoRyouki	ExtremeReactors-1.12.2-0.4.5.67.jar	
Familiar Fauna	Forstride	FamiliarFauna-1.12.2-1.0.11.jar	
Fast Leaf Decay	olafskiii	FastLeafDecay-v14.jar	
FastFurnace	Shadows_of_Fire	FastFurnace-1.12.2-1.3.1.jar	
FastWorkbench	Shadows_of_Fire	FastWorkbench-1.12.2-1.7.3.jar	
Flux Networks	sonar_sonic	fluxnetworks-1.12.2-4.0.14-31.jar	
ForgeEndertech	EnderLanky	ForgeEndertech-1.12.2-4.5.0.0-build.0435.jar	
Hats	ohaiiChun	Hats-1.12.2-7.1.0.jar	
Heroic Armory	skeddles	heroicarmory-1.2.0.jar	
Hwyla	TehNut	Hwyla-1.8.26-B41_1.12.2.jar	
Ice and Fire: Dragons in a whole new light!	alex1the1666	iceandfire-1.8.3.jar	
iChunUtil	ohaiiChun	iChunUtil-1.12.2-7.2.2.jar	
Inventory Tweaks	JimeoWan	InventoryTweaks-1.63.jar	
Iron Backpacks	gr8pefish	IronBackpacks-1.12.2-3.0.8-12.jar	
Iron Chests	ProgWML6	ironchest-1.12.2-7.0.72.847.jar	
JourneyMap	techbrew	journeymap-1.12.2-5.5.6.jar	
Just Enough Items (JEI)	mezz	jei_1.12.2-4.15.0.291.jar	
KleeSlabs	BlayTheNinth	KleeSlabs_1.12.2-5.4.12.jar	
LLibrary	_ForgeUser11902522	llibrary-1.7.19-1.12.2.jar	
MalisisCore	Ordinastie	malisiscore-1.12.2-6.5.1.jar	
MalisisDoors	Ordinastie	malisisdoors-1.12.2-7.3.0.jar	
Mantle	mDiyo	Mantle-1.12-1.3.3.55.jar	
MoarFood	Peter1745	moarfood-1.0.jar	
Morpheus	Quetzi	Morpheus-1.12.2-3.5.106.jar	
Mouse Tweaks	YaLTeR	MouseTweaks-2.10-mc1.12.2.jar	
MovingWorld	darkevilmac	movingworld-1.12-6.342-full.jar	
Mowzie's Mobs	bobmowzie	mowziesmobs-1.5.4.jar	
MrCrayfish's Furniture Mod	MrCrayfish	furniture-6.3.1-1.12.2.jar	
Neat	Vazkii	Neat 1.4-17.jar	
NetherPortalFix	BlayTheNinth	NetherPortalFix_1.12.1-5.3.17.jar	
OpenBlocks	OpenMods	OpenBlocks-1.12.2-1.8.1.jar	
OpenModsLib	OpenMods	OpenModsLib-1.12.2-0.12.2.jar	
Ore Excavation	Funwayguy	OreExcavation-1.4.143.jar	
Patchouli	Vazkii	Patchouli-1.0-20.jar	
Phosphor	jellysquid_	phosphor-1.12.2-0.2.6+build50-universal.jar	
Placebo	Shadows_of_Fire	Placebo-1.12.2-1.6.0.jar	
PTRLib	RazzleberryFox	PTRLib-1.0.4.jar	
ReAuth	TechnicianLP	reauth-3.6.0.jar	
Redstone Flux	TeamCoFH	RedstoneFlux-1.12-2.1.0.6-universal.jar	
Refined Storage	raoulvdberge	refinedstorage-1.6.15.jar	
Reliquary v1.3	P3pp3rF1y	Reliquary-1.12.2-1.3.4.796.jar	
Roguelike Dungeons	greymerktv	RoguelikeDungeons-1.12.2-1.8.0.jar	
Ruins (Structure Spawning System)	atomicstrykergrumpy	Ruins-1.12.2.jar	
Rustic	mangoose3039	rustic-1.1.2.jar	
Shadowfacts' Forgelin	ShadowfactsDev	Forgelin-1.8.4.jar	
Sit	bl4ckscor3	sit-1.12.2-v1.3.jar	
Snad	TheRoBrit	Snad-1.12.1-1.7.09.16a.jar	
Storage Drawers	Texelsaur	StorageDrawers-1.12.2-5.4.0.jar	
The Aether	GildedGames	aether_legacy-1.12.2-v1.4.4.jar	
The Aether II	GildedGames	aether_ii-1.12.2-0.2.6+build127-universal.jar	
The Erebus	vadis365	Erebus-1.0.31.jar	
The Midnight	cipher_zero_x	themidnight-0.3.5.jar	
The Twilight Forest	Benimatic	twilightforest-1.12.2-3.10.1013-universal.jar	
Tinkers Aether	Shnupbups	tinkersaether-1.3.0.jar	
Tinkers Construct	mDiyo	TConstruct-1.12.2-2.13.0.171.jar	
Tinkers' Tool Leveling	bonusboni	TinkerToolLeveling-1.12.2-1.1.0.jar	
Tropicraft	Cojomax99	tropicraft-MC1.12.2-7.1.9.115.jar	
ViesCraft - Airships!	Vies	ViesCraft-1.12.2-5.9.13.jar	
Waystones	BlayTheNinth	Waystones_1.12.2-4.0.72.jar	
XL Food Mod	mariot7	XL-Food-Mod-1.12.2-1.9.2.jar	
ZeroCore

Using completely default configs
also sorry for awful formatting on the modlist

**Comment by DerToaster98** [comment]
Please use the issue template. No support otherwise

**Comment by Colaskink** [comment]
> Please use the issue template. No support otherwise

Where is that?

**Comment by DerToaster98** [comment]
I wont explain standard github fearures

**Comment by DerToaster98** [comment]
Also this is missing required information:
- mod version
- mod list
- configs

**Comment by Meldexun** [comment]
> Where is that?

How did you create your issue without seeing the issue template? (This is a serious question. When i would create an issue i would do it like this:
- open the the CQR github page
- go to the issues page
- click on "new issue"
- then i see all the issue templates (currently only "bug report") and i select a fitting one and press on "get started". To create a blank issue i have to click the small text "Don’t see your issue here? Open a blank issue" which is located under all the templates. So how did you manage to not see the issue template?)

Also a log file is needed.

**Comment by DerToaster98** [comment]
So: I tried to reproduce the issue, created a server, spawned a dungeon, checked if there are enemies:
There are enemies and they do spawn, not reproduceable. will be closed.

**Comment by DerToaster98** [comment]
This is probably caused by another mod, i wasnt able to reproduce this bug, sorry
