### ISSUE TITLE
Server Crash - Loading Pirate / NoSuchMethodError

### ISSUE THREAD

**Issue by nabendYT** [TeamChocoQuest/ChocolateQuestRepoured#127]
Hi,

at first: Thanks for the mod! (: Unfortunately there seems to be an error as soon as me and the bois approach a pirate ship!

Server Crash Report:
---- Minecraft Crash Report ----

WARNING: coremods are present:
  HCASM (HammerCore-1.12.2-2.0.6.4.jar)
  SmithsCoreFMLPlugin (smithscore-1.12.2-0.20.14-RELEASE-sponge.jar)
  CTMCorePlugin (CTM-MC1.12.2-1.0.1.30.jar)
  IvToolkit (IvToolkit-1.3.3-1.12.jar)
  evilnotchlib-transformer_fixes (EvilNotchLib-1.2.3.06.jar)
  SpongeCoremod (spongeforge-1.12.2-2838-7.1.8.jar)
Contact their authors BEFORE contacting forge

// You're mean.

Time: 1/15/20 6:52 PM
Description: Ticking entity

java.lang.NoSuchMethodError: net.minecraft.util.math.AxisAlignedBB.<init>(Lnet/minecraft/util/math/Vec3d;Lnet/minecraft/util/math/Vec3d;)V
	at com.teamcqr.chocolatequestrepoured.objects.entity.ai.EntityAIIdleSit.func_75246_d(EntityAIIdleSit.java:83)
	at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:129)
	at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:763)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2359)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:577)
	at com.teamcqr.chocolatequestrepoured.objects.entity.bases.AbstractEntityCQR.func_70636_d(AbstractEntityCQR.java:402)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2179)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295)
	at com.teamcqr.chocolatequestrepoured.objects.entity.bases.AbstractEntityCQR.func_70071_h_(AbstractEntityCQR.java:368)
	at org.spongepowered.common.event.tracking.TrackingUtil.tickEntity(TrackingUtil.java:167)
	at net.minecraft.world.WorldServer.redirect$onCallEntityUpdate$zlj000(WorldServer.java:4740)
	at net.minecraft.world.World.func_72866_a(World.java:1993)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1955)
	at net.minecraft.world.World.func_72939_s(World.java:1759)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:3930)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:748)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at com.teamcqr.chocolatequestrepoured.objects.entity.ai.EntityAIIdleSit.func_75246_d(EntityAIIdleSit.java:83)
	at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:129)
	at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:763)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2359)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:577)
	at com.teamcqr.chocolatequestrepoured.objects.entity.bases.AbstractEntityCQR.func_70636_d(AbstractEntityCQR.java:402)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2179)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295)
	at com.teamcqr.chocolatequestrepoured.objects.entity.bases.AbstractEntityCQR.func_70071_h_(AbstractEntityCQR.java:368)
	at org.spongepowered.common.event.tracking.TrackingUtil.tickEntity(TrackingUtil.java:167)
	at net.minecraft.world.WorldServer.redirect$onCallEntityUpdate$zlj000(WorldServer.java:4740)
	at net.minecraft.world.World.func_72866_a(World.java:1993)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1955)

-- Entity being ticked --
Details:
	Entity Type: cqrepoured:pirate (com.teamcqr.chocolatequestrepoured.objects.entity.mobs.EntityCQRPirate)
	Entity ID: 54993
	Entity Name: Pirate
	Entity's Exact location: -1271.40, 61.00, 635.44
	Entity's Block location: World: (-1272,61,635), Chunk: (at 8,3,11 in -80,39; contains blocks -1280,0,624 to -1265,255,639), Region: (-3,1; contains chunks -96,32 to -65,63, blocks -1536,0,512 to -1025,255,1023)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1759)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:3930)

-- Affected level --
Details:
	Level name: Batzen
	All players: 4 total; [EntityPlayerMP['Fitzifant'/15495, l='Batzen', x=-1256.97, y=62.07, z=634.01], EntityPlayerMP['J4nosch'/17700, l='Batzen', x=-1258.34, y=62.07, z=634.59], EntityPlayerMP['ThEuGaNdAnWeEeYy'/38623, l='Batzen', x=-532.30, y=57.00, z=735.30], EntityPlayerMP['nabend'/3714, l='Batzen', x=-1258.87, y=62.07, z=635.91]]
	Chunk stats: ServerChunkCache: 2281 Drop: 0
	Level seed: -7175271879733514498
	Level generator: ID 10 - BIOMESOP, ver 0. Features enabled: true
	Level generator options: 
	Level spawn location: World: (8,64,8), Chunk: (at 8,4,8 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 115387 game time, 30172 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 26912 (now: false), thunder time: 44546 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false

-- Sponge PhaseTracker --
Details:
	Phase Stack: [Empty stack]
Stacktrace:
	at net.minecraft.server.MinecraftServer.handler$onCrashReport$zje000(MinecraftServer.java:4721)
	at net.minecraft.server.MinecraftServer.func_71230_b(MinecraftServer.java:889)
	at net.minecraft.server.dedicated.DedicatedServer.func_71230_b(DedicatedServer.java:371)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:554)
	at java.lang.Thread.run(Thread.java:748)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Linux (amd64) version 4.15.18-16-pve
	Java Version: 1.8.0_211, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1140358504 bytes (1087 MB) / 2560098304 bytes (2441 MB) up to 4772593664 bytes (4551 MB)
	JVM Flags: 2 total; -Xmx5120M -Xms512M
	IntCache: cache: 2, tcache: 103, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2838 42 mods loaded, 42 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	Mods:

	| State  | ID                | Version                | Source                                        | Signature                                |
	|:------ |:----------------- |:---------------------- |:--------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft         | 1.12.2                 | minecraft.jar                                 | None                                     |
	| LCHIJA | mcp               | 9.42                   | minecraft.jar                                 | None                                     |
	| LCHIJA | FML               | 8.0.99.99              | forge-1.12.2-14.23.5.2838-universal.jar       | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge             | 14.23.5.2838           | forge-1.12.2-14.23.5.2838-universal.jar       | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | ivtoolkit         | 1.3.3-1.12             | minecraft.jar                                 | None                                     |
	| LCHIJA | spongeapi         | 7.1.0-ea50f0c2         | spongeforge-1.12.2-2838-7.1.8.jar             | None                                     |
	| LCHIJA | sponge            | 1.12.2-7.1.8           | spongeforge-1.12.2-2838-7.1.8.jar             | None                                     |
	| LCHIJA | spongeforge       | 1.12.2-2838-7.1.8      | spongeforge-1.12.2-2838-7.1.8.jar             | None                                     |
	| LCHIJA | smithscore-core   | 1.0                    | minecraft.jar                                 | None                                     |
	| LCHIJA | bspkrscore        | 7.6.0.1                | [1.12]bspkrsCore-universal-7.6.0.1.jar        | None                                     |
	| LCHIJA | treecapitator     | 1.43.0                 | [1.12]TreeCapitator-client-1.43.0.jar         | None                                     |
	| LCHIJA | jei               | 4.15.0.291             | jei_1.12.2-4.15.0.291.jar                     | None                                     |
	| LCHIJA | abyssalcraft      | 1.9.15                 | AbyssalCraft-1.12.2-1.9.15.jar                | 220f10d3a93b3ff5fbaa7434cc629d863d6751b9 |
	| LCHIJA | battletowers      | 1.6.5                  | BattleTowers-1.12.2.jar                       | None                                     |
	| LCHIJA | baubles           | 1.5.2                  | Baubles-1.12-1.5.2.jar                        | None                                     |
	| LCHIJA | biomesoplenty     | 7.0.1.2441             | BiomesOPlenty-1.12.2-7.0.1.2441-universal.jar | None                                     |
	| LCHIJA | bookshelf         | 2.3.590                | Bookshelf-1.12.2-2.3.590.jar                  | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | botania           | r1.10-363              | Botania r1.10-363.jar                         | None                                     |
	| LCHIJA | chesttransporter  | 2.8.8                  | ChestTransporter-1.12.2-2.8.8.jar             | None                                     |
	| LCHIJA | chococraft        | 0.9.8.0                | chococraft_1.12.2-0.9.8.0.jar                 | None                                     |
	| LCHIJA | cqrepoured        | 1.2.2A                 | ChocolateQuestRepoured-1.12.2-1.2.2A.jar      | None                                     |
	| LCHIJA | eplus             | 5.0.176                | EnchantingPlus-1.12.2-5.0.176.jar             | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | evilnotchlib      | 1.2.3.07               | EvilNotchLib-1.2.3.06.jar                     | None                                     |
	| LCHIJA | extrabows         | v1.12.2 b10            | extrabows-v1.12.2 b10.jar                     | None                                     |
	| LCHIJA | giant_swords_mod  | 1.0.0                  | GiantSwordsMod.jar                            | None                                     |
	| LCHIJA | hammercore        | 2.0.6.4                | HammerCore-1.12.2-2.0.6.4.jar                 | 9f5e2a811a8332a842b34f6967b7db0ac4f24856 |
	| LCHIJA | hcmb              | @VERSION               | HammerMicroblocks-1.12.2-12.2.2.jar           | 9f5e2a811a8332a842b34f6967b7db0ac4f24856 |
	| LCHIJA | placebo           | 1.6.0                  | Placebo-1.12.2-1.6.0.jar                      | None                                     |
	| LCHIJA | hexxitgear        | 2.8.0                  | Hexxit Gear-1.12.2-2.8.0.jar                  | None                                     |
	| LCHIJA | ichunutil         | 7.2.2                  | iChunUtil-1.12.2-7.2.2.jar                    | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| LCHIJA | infernalmobs      | 1.7.6                  | InfernalMobs-1.12.2.jar                       | None                                     |
	| LCHIJA | mantle            | 1.12-1.3.3.55          | Mantle-1.12-1.3.3.55.jar                      | None                                     |
	| LCHIJA | tbone             | v1.6.8+mc1.12.2        | TBone-v1.6.8+mc1.12.2.jar                     | None                                     |
	| LCHIJA | metalchests       | v6.1.0+mc1.12.2        | MetalChests-v6.1.0+mc1.12.2.jar               | None                                     |
	| LCHIJA | patchouli         | 1.0-20                 | Patchouli-1.0-20.jar                          | None                                     |
	| LCHIJA | portalgun         | 7.1.0                  | PortalGun-1.12.2-7.1.0.jar                    | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| LCHIJA | progressivebosses | 1.5.4                  | ProgressiveBosses-1.5.4-mc1.12.x.jar          | None                                     |
	| LCHIJA | sit               | v1.3                   | sit-1.12.2-v1.3.jar                           | None                                     |
	| LCHIJA | smithscore        | 1.12.2-0.20.14-RELEASE | smithscore-1.12.2-0.20.14-RELEASE-sponge.jar  | None                                     |
	| LCHIJA | tconstruct        | 1.12.2-2.13.0.171      | TConstruct-1.12.2-2.13.0.171.jar              | None                                     |
	| LCHIJA | tombstone         | 3.6.4                  | tombstone-3.6.4-1.12.2.jar                    | None                                     |
	| LCHIJA | wearablebackpacks | 3.1.4                  | WearableBackpacks-1.12.2-3.1.4.jar            | None                                     |

	Plugins:

	| State | ID | Version | Source | Signature |
	|:----- |:-- |:------- |:------ |:--------- |

	Loaded coremods (and transformers): 
HCASM (HammerCore-1.12.2-2.0.6.4.jar)
  com.zeitheron.hammercore.asm.HammerCoreTransformer
SmithsCoreFMLPlugin (smithscore-1.12.2-0.20.14-RELEASE-sponge.jar)
  
CTMCorePlugin (CTM-MC1.12.2-1.0.1.30.jar)
  team.chisel.ctm.client.asm.CTMTransformer
IvToolkit (IvToolkit-1.3.3-1.12.jar)
  
evilnotchlib-transformer_fixes (EvilNotchLib-1.2.3.06.jar)
  com.evilnotch.lib.asm.transformer.Transformer
  com.evilnotch.lib.asm.transformer.EntityTransformer
SpongeCoremod (spongeforge-1.12.2-2838-7.1.8.jar)
  org.spongepowered.common.launch.transformer.SpongeSuperclassTransformer
	HammerCore Debug Information: 
Dependent Mods:
    -Hammer Microblocks (hcmb) @@VERSION

	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)

	Profiler Position: N/A (disabled)
	Player Count: 4 / 12; [EntityPlayerMP['Fitzifant'/15495, l='Batzen', x=-1256.97, y=62.07, z=634.01], EntityPlayerMP['J4nosch'/17700, l='Batzen', x=-1258.34, y=62.07, z=634.59], EntityPlayerMP['ThEuGaNdAnWeEeYy'/38623, l='Batzen', x=-532.30, y=57.00, z=735.30], EntityPlayerMP['nabend'/3714, l='Batzen', x=-1258.87, y=62.07, z=635.91]]
	Is Modded: Definitely; Server brand changed to 'fml,forge,sponge'
	Type: Dedicated Server (map_server.txt)

**Comment by DerToaster98** [comment]
Report not acceptable. Formatting is hell and please use the issue template

**Comment by DerToaster98** [comment]
Also we are missing information we need (single or multiplayer)

**Comment by DerToaster98** [comment]
will be fixed with ALpha 10 build

**Comment by Meldexun** [comment]
This was already fixed in v1.3.0A

**Comment by DerToaster98** [comment]
solution: Actually use the latest version. we do not support older versions in current development state.
