### ISSUE TITLE
Possible CQR/TF2stuff conflict?

### ISSUE THREAD

**Issue by ZcanKal** [TeamChocoQuest/ChocolateQuestRepoured#128]
[crash-2020-01-18_14.32.00-server.txt](https://github.com/TeamChocoQuest/ChocolateQuestRepoured/files/4081941/crash-2020-01-18_14.32.00-server.txt)

I don't know what happened, I just flew around in a Davinci's Vessels airship, and the world crashed, saying the problem was Chocolate Quest Repoured and Rafradek's TF2 mod.  I am also not sure if any other information should be provided.

**Comment by DerToaster98** [comment]
Why is nobody able to use the issue template?
Well at least we have a crash report.... lets see....

Issue is known and being worked on

**Comment by DerToaster98** [comment]
Also we currently think that this bug occurs when a mod (current cases: TF2 and I&F) does not implement its mobs properly
