### ISSUE TITLE
Crash with improved mobs mod

### ISSUE THREAD

**Issue by Zeinoth** [TeamChocoQuest/ChocolateQuestRepoured#131]
The improved mobs mod adds the ability for mobs holding tnt blocks to throw lit tnt. This tnt does not destroy blocks. When the tnt is thrown, it causes the game to crash. The crash is related to the chocolate quest dungeon protection.

1. find mob with tnt in hand
2. let it throw tnt
3. game crashes

**Screenshots**

**Versions**
Chocolate Quest Repoured: 1.4.0A
Forge: 14.23.5.2831
Minecraft: 1.12.2

**Other**
Crash report: https://paste.dimdev.org/ehofaxujan.mccrash
Log file: https://cdn.discordapp.com/attachments/465380866504261635/668742436910137363/latest.log
Singleplayer
Other mods (that are necessary to produce the bug): improved mobs

**Comment by Zeinoth** [comment]
https://paste.dimdev.org/ohewibibay.mccrash same crash, but 1/2 the time it gives this crash instead

**Comment by DerToaster98** [comment]
The first issue isnt caused by cqr

**Comment by DerToaster98** [comment]
Second crash is known and is fixed since alpha11
