### ISSUE TITLE
Hats from the Classy Hats mod doesn't show up on a CQR mob

### ISSUE THREAD

**Issue by rlcraftisharder** [TeamChocoQuest/ChocolateQuestRepoured#132]
![2020-01-20_18 47 13](https://user-images.githubusercontent.com/59460450/72766816-1f652e00-3bb7-11ea-89e5-d1bb432ca7cb.png)

CQR mobs that can have their armor shown when they wear them doesn't work with the hats from the Classy Hats mod. (For example, the CQR Zombie. It can wear the Classy Gear from the Classy Hats mod but doesn't show on its head. The vanilla Minecraft Zombie can wear it and is shown on its head)

**Comment by DerToaster98** [comment]
This is not a bug, it is a problem with how the other mod implemented their hats
