### ISSUE TITLE
Random crash

### ISSUE THREAD

**Issue by Zack7292** [TeamChocoQuest/ChocolateQuestRepoured#133]
**Describe the bug**
i just randomly crash

**To Reproduce**
i was wandering around and this happen

**Expected behavior**
<not crash

**Versions**
Chocolate Quest Repoured:latest
Forge:latest
Minecraft:1.12.2

**Other**
Crash report: https://paste.dimdev.org/okanozowar.mccrash
Singleplayer/Multiplayer: singleplayer
Other mods (that are also installed): look at the crashlog

**Comment by DerToaster98** [comment]
Delete the configs and restart the game, should fix it
