### ISSUE TITLE
crash after shooting weapon

### ISSUE THREAD

**Issue by jjduckvader** [TeamChocoQuest/ChocolateQuestRepoured#134]
hello, the last three updates have been crashing my world after i shoot an explosive bullet from my rifle (techguns mod), this didn't happened after ChocolateQuestRepoured-1.12.2-1.3.0A version, sry for my bad english =(

 

---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 2020-01-20 19:49:13 CST
Description: Ticking entity

java.lang.NullPointerException
at com.teamcqr.chocolatequestrepoured.structureprot.ProtectionHandler.eventHandleExplosion(ProtectionHandler.java:315)
at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_509_ProtectionHandler_eventHandleExplosion_ExplosionEvent.invoke(.dynamic)
at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
at net.minecraftforge.event.ForgeEventFactory.onExplosionDetonate(ForgeEventFactory.java:591)
at net.minecraft.world.Explosion.doExplosionA(Explosion.java:134)
at techguns.entities.projectiles.GenericProjectileExplosive.explode(GenericProjectileExplosive.java:68)
at techguns.entities.projectiles.GenericProjectileExplosive.hitBlock(GenericProjectileExplosive.java:56)
at techguns.entities.projectiles.GenericProjectile.onHit(GenericProjectile.java:455)
at techguns.entities.projectiles.GenericProjectile.onUpdate(GenericProjectile.java:259)
at net.minecraft.world.World.updateEntityWithOptionalForce(World.java:1996)
at net.minecraft.world.WorldServer.updateEntityWithOptionalForce(WorldServer.java:832)
at net.minecraft.world.World.updateEntity(World.java:1958)
at net.minecraft.world.World.redirect$updateEntity$zbc000(World.java:4123)
at net.minecraft.world.World.updateEntities(World.java:1762)
at net.minecraft.world.WorldServer.updateEntities(WorldServer.java:613)
at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:767)
at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:279)
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
at java.lang.Thread.run(Unknown Source)

 

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Entity being ticked --
Entity Type: techguns:genericprojectileexplosive (techguns.entities.projectiles.GenericProjectileExplosive)
Entity ID: 382
Entity Name: entity.GenericProjectileExplosive.name
Entity's Exact location: 190.12, 70.06, -622.36
Entity's Block location: World: (190,70,-623), Chunk: (at 14,4,1 in 11,-39; contains blocks 176,0,-624 to 191,255,-609), Region: (0,-2; contains chunks 0,-64 to 31,-33, blocks 0,0,-1024 to 511,255,-513)
Entity's Momentum: 1.67, -1.61, -4.27
Entity's Passengers: []
Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Entity NBT: {NoGravity:1b,Motion:[1.6683390192559586d,-1.6080275698857949d,-4.272384546587014d],damage:36.8f,ticksToLive:17s,UUIDLeast:-5201971792303940346L,damageDropStart:40s,lifetime:26s,Invulnerable:0b,Air:300s,OnGround:0b,Dimension:0,PortalCooldown:0,damageDropEnd:60s,Rotation:[158.66968f,-19.320505f],UpdateBlocked:0b,speed:3.5f,FallDistance:0.0f,UUIDMost:-659808746296095684L,Pos:[190.11702632935993d,70.05705011240171d,-622.3632762417717d],damageMin:27.599998f,Fire:-1s}

-- Affected level --
Level name: Ivonne All players: 1 total; [EntityPlayerMP['JanRooru'/3, l='Ivonne', x=176.15, y=82.00, z=-586.59]]
Chunk stats: ServerChunkCache: 205 Drop: 0
Level seed: 681006480
Level generator: ID 00 - default, ver 1. Features enabled: true
Level generator options:
Level spawn location: World: (-132,64,256), Chunk: (at 12,4,0 in -9,16; contains blocks -144,0,256 to -129,255,271), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
Level time: 5404061 game time, 28380 day time
Level dimension: 0
Level storage version: 0x04ABD - Anvil
Level weather: Rain time: 61818 (now: false), thunder time: 161262 (now: false)
Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: true

-- System Details --
Minecraft Version: 1.12.2
Operating System: Windows 7 (amd64) version 6.1
Java Version: 1.8.0_231, Oracle Corporation
Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
Memory: 2324803792 bytes (2217 MB) / 3456106496 bytes (3296 MB) up to 3657433088 bytes (3488 MB)
JVM Flags: 8 total; -Xmn128M -Xmx3464M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 96
FML: MCP 9.42 Powered by Forge 14.23.5.2847 Optifine OptiFine_1.12.2_HD_U_F5 96 mods loaded, 96 mods active
States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

| State | ID | Version | Source | Signature |
|:------ |:----------------------- |:------------------------ |:--------------------------------------------------- |:---------------------------------------- |
| LCHIJA | minecraft | 1.12.2 | minecraft.jar | None |
| LCHIJA | mcp | 9.42 | minecraft.jar | None |
| LCHIJA | FML | 8.0.99.99 | forge-1.12.2-14.23.5.2847.jar | None |
| LCHIJA | forge | 14.23.5.2847 | forge-1.12.2-14.23.5.2847.jar | None |
| LCHIJA | ivtoolkit | 1.3.3-1.12 | minecraft.jar | None |
| LCHIJA | techguns_core | 1.12.2-1.0 | minecraft.jar | None |
| LCHIJA | deconstruction | 3.0.4 | [MC1.12.2]DeconTable-3.0.4.jar | None |
| LCHIJA | adventurepack | 1.6.0 | adventurepack-1.7.0.jar | None |
| LCHIJA | animalnet | v1.12.2 b3 | animalnet-v1.12.2+b3.jar | None |
| LCHIJA | baubles | 1.5.2 | Baubles-Mod-1.12.2.jar | None |
| LCHIJA | atum | 2.0.16 | Atum-1.12.2-2.0.16.jar | None |
| LCHIJA | betterbedrockgen | 6.0.2 | BetterBedrockGenerator-1.12-6.1.1.jar | None |
| LCHIJA | bookshelf | 2.3.590 | Bookshelf-1.12.2-2.3.590.jar | d476d1b22b218a10d845928d1665d45fce301b27 |
| LCHIJA | buildcraftlib | 7.99.24.4 | buildcraft-all-7.99.24.4.jar | None |
| LCHIJA | buildcraftcore | 7.99.24.4 | buildcraft-all-7.99.24.4.jar | None |
| LCHIJA | buildcraftbuilders | 7.99.24.4 | buildcraft-all-7.99.24.4.jar | None |
| LCHIJA | buildcrafttransport | 7.99.24.4 | buildcraft-all-7.99.24.4.jar | None |
| LCHIJA | buildcraftsilicon | 7.99.24.4 | buildcraft-all-7.99.24.4.jar | None |
| LCHIJA | buildcraftcompat | 7.99.24.4 | buildcraft-all-7.99.24.4.jar | None |
| LCHIJA | buildcraftenergy | 7.99.24.4 | buildcraft-all-7.99.24.4.jar | None |
| LCHIJA | buildcraftfactory | 7.99.24.4 | buildcraft-all-7.99.24.4.jar | None |
| LCHIJA | buildcraftrobotics | 7.99.24.4 | buildcraft-all-7.99.24.4.jar | None |
| LCHIJA | carryon | 1.12.3 | CarryOn+MC1.12.2+v1.12.3.jar | 55e88f24d04398481ae6f1ce76f65fd776f14227 |
| LCHIJA | cqrepoured | 1.5.1A | ChocolateQuestRepoured-1.12.2-1.5.1A.jar | None |
| LCHIJA | cleanview | 1.12.2-v1c | CleanView-1.12.2-v1c.jar | aaaf83332a11df02406e9f266b1b65c1306f0f76 |
| LCHIJA | coalprocessing | @VERSION@ | CoalProcessing-1.2.jar | None |
| LCHIJA | cyclopscore | 1.6.0 | CyclopsCore-1.12.2-1.6.0.jar | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
| LCHIJA | commoncapabilities | 2.4.5 | CommonCapabilities-1.12.2-2.4.5.jar | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
| LCHIJA | configurablecane | 1.0 | ConfigurableCane-1.0.jar | None |
| LCHIJA | cxlibrary | 1.6.1 | cxlibrary-1.12.1-1.6.1.jar | None |
| LCHIJA | diamondglass | 1.12.2-3.3.18 | diamondglass-1.12.2-3.3.18.jar | None |
| LCHIJA | dungeonmobs | 5.8.4 | dungeonmobs-5.8.4-MC1.12.2.jar | None |
| LCHIJA | gottschcore | 1.10.0 | GottschCore-mc1.12.2-f14.23.5.2768-v1.10.0.jar | None |
| LCHIJA | dungeons2 | 1.7.1 | Dungeons2-mc1.12.2-f14.23.5.2768-v1.7.1.jar | None |
| LCHIJA | dungeontactics | DT-0.16.6 | DungeonTactics-1.12.2-0.16.6.jar | None |
| LCHIJA | net.blacklab.lib | 6.0.2.5 | EBLib-6.0.2.5.jar | None |
| LCHIJA | emergingtechnology | 1.3.3 | EmergingTechnology-1.12.2-1.3.3.jar | None |
| LCHIJA | eplus | 5.0.176 | EnchantingPlus-1.12.2-5.0.176.jar | d476d1b22b218a10d845928d1665d45fce301b27 |
| LCHIJA | enchdesc | 1.1.15 | EnchantmentDescriptions-1.12.2-1.1.15.jar | d476d1b22b218a10d845928d1665d45fce301b27 |
| LCHIJA | evilcraft | 0.10.78 | EvilCraft-1.12.2-0.10.78.jar | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
| LCHIJA | evilcraftcompat | 1.0.0 | EvilCraft-1.12.2-0.10.78.jar | None |
| LCHIJA | extraanvils | @VERSION@ | Extra-Anvils-Mod-1.12.2.jar | None |
| LCHIJA | ezstorage | 2.5.0 | ezstorage-2.5.0-[1.12.2].jar | None |
| LCHIJA | farlanders | 1.0.1 | farlanders-1.12.2-1.0.1.jar | None |
| LCHIJA | fastleafdecay | v14 | FastLeafDecay-v14.jar | None |
| LCHIJA | forgelin | 1.8.4 | Forgelin-1.8.4.jar | None |
| LCHIJA | fpsreducer | mc1.12.2-1.14 | FpsReducer-mc1.12.2-1.14.jar | None |
| LCHIJA | globalxp | v1.4.10 | globalxp-1.12.2-v1.4.10.jar | None |
| LCHIJA | grimoireofgaia | 1.6.9.3 | GrimoireOfGaia3-1.12.2-1.6.9.3.jar | None |
| LCHIJA | jei | 4.15.0.293 | jei_1.12.2-4.15.0.293.jar | None |
| LCHIJA | mekanism | 1.12.2-9.8.3.390 | Mekanism-1.12.2-9.8.3.390.jar | None |
| LCHIJA | teslacorelib | 1.0.15 | tesla-core-lib-1.12.2-1.0.15.jar | d476d1b22b218a10d845928d1665d45fce301b27 |
| LCHIJA | industrialforegoing | 1.12.2-1.12.2 | industrialforegoing-1.12.2-1.12.13-237.jar | None |
| LCHIJA | infinitefluids | 1.2.0 | infinitefluids-1.11-1.2.0.jar | None |
| LCHIJA | inventorytweaks | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
| LCHIJA | jrftl | 1.1 | Just-Another-Rotten-Flesh-to-Leather-Mod-1.12.2.jar | None |
| LCHIJA | fluidtank | 12.4.9 | LargeFluidTank-12.4.9.jar | 617a4e95f0af9de5402bb9883abe0f53a6bfa230 |
| LCHIJA | fluidtank_ae2 | 12.4.9 | LargeFluidTank-12.4.9.jar | 617a4e95f0af9de5402bb9883abe0f53a6bfa230 |
| LCHIJA | fluidtank_theoneprobe | 12.4.9 | LargeFluidTank-12.4.9.jar | 617a4e95f0af9de5402bb9883abe0f53a6bfa230 |
| LCHIJA | levelup2 | ${version} | levelup2-1.2.1.jar | None |
| LCHIJA | limelib | 1.7.12 | limelib-1.12.2-1.7.12.jar | None |
| LCHIJA | linear | 1.2.2 | Linear+MC1.12.2+v1.2.2.jar | None |
| LCHIJA | lmreengaged | 8.0.1.66 | LittleMaidReengaged-8.0.1.66-unofficial-1.12.2.jar | None |
| LCHIJA | lucky | 7.6.0 | luckyblock-1.12.2-7.6.0.zip | None |
| LCHIJA | mekanismgenerators | 1.12.2-9.8.3.390 | MekanismGenerators-1.12.2-9.8.3.390.jar | None |
| LCHIJA | mekanismtools | 1.12.2-9.8.3.390 | MekanismTools-1.12.2-9.8.3.390.jar | None |
| LCHIJA | mendinggems | 1.0.0 | MendingGems-1.12.2-1.0.0.jar | None |
| LCHIJA | mmdlib | 1.0.0-rc2 | MMDLib-1.12-1.0.0-rc2.36.jar | None |
| LCHIJA | mod_autofish | 1.12-1.7 | mod_autofish_forge-1.12-1.7.jar | None |
| LCHIJA | multipagechest | 1.9.1 | MultiPageChest-1.12-1.9.1.jar | None |
| LCHIJA | neat | 1.4-17 | Neat+1.4-17.jar | None |
| LCHIJA | nethermetals | 1.2.0-rc2 | NetherMetals-1.12-1.2.0-rc2.76.jar | d476d1b22b218a10d845928d1665d45fce301b27 |
| LCHIJA | recipehandler | 0.13 | NoMoreRecipeConflict-0.13(1.12.2).jar | None |
| LCHIJA | orespawn | 3.3.1 | OreSpawn-1.12-3.3.1.172.jar | d476d1b22b218a10d845928d1665d45fce301b27 |
| LCHIJA | patchouli | 1.0-20 | Patchouli-1.0-20.jar | None |
| LCHIJA | prettybeaches | 1.0.4 | PrettyBeaches_1.12.2-1.0.4.jar | None |
| LCHIJA | playerstorage | 1.3.12 | projectstorage-1.12.2-1.3.jar | None |
| LCHIJA | reccomplex | 1.4.8.2 | RecurrentComplex-1.4.8.2.jar | None |
| LCHIJA | recycler | 3.2.4 | recycler-3.2.4-1.12.jar | None |
| LCHIJA | scenter | 1.12-3.11.0 | scenter-1.12.2-3.12.0.jar | None |
| LCHIJA | simplegrinder | @VERSION@ | SimpleGrinder-1.150.R1122.jar | None |
| LCHIJA | stackable | 1.3.3 | stackable-1.12.2-1.3.3.jar | None |
| LCHIJA | subcommonlib | 1.2.0.1 | subcommonlib-sublib-1.12.2-1.2.0.4.jar | None |
| LCHIJA | techguns | 2.0.2.0 | techguns-1.12.2-2.0.2.0_pre3.1.jar | None |
| LCHIJA | telepads | $version | telepads-1.12.2-1.1.0.7.jar | None |
| LCHIJA | theplopper | v1.2.1 | theplopper-1.12.x-v1.2.1.jar | None |
| LCHIJA | tombstone | 3.6.5 | tombstone-3.6.5-1.12.2.jar | None |
| LCHIJA | touhou_little_maid | 1.1.9 | touhoulittlemaid-1.12.2-1.1.9-release.jar | None |
| LCHIJA | treechopper | 1.2.4 | TreeChopper-1.12.2-1.2.4.jar | None |
| LCHIJA | vanillafix | 1.0.10-SNAPSHOT | VanillaFix-1.0.10-99.jar | None |
| LCHIJA | xaerominimap | 1.19.6 | Xaeros_Minimap_1.19.6_Forge_1.12.jar | None |
| LCHIJA | xaeroworldmap | 1.5.4 | XaerosWorldMap_1.5.4_Forge_1.12.jar | None |
| LCHIJA | phosphor-lighting | 1.12.2-0.2.6 | phosphor-1.12.2-0.2.6+build50-universal.jar | f0387d288626cc2d937daa504e74af570c52a2f1 |
| LCHIJA | minersadvantage | 1.3.19.242 | MinersAdvantage-1.12.2-1.3.19.243.jar | None |
| LCHIJA | moofluids | 1.12.2-1.7.11.02a | MooFluids-1.12.2-1.7.11.02a.jar | None |
| LCHIJA | teslacorelib_registries | 1.0.15 | tesla-core-lib-1.12.2-1.0.15.jar | None |
Loaded coremods (and transformers): Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
invtweaks.forge.asm.ContainerTransformer
PhosphorFMLLoadingPlugin (phosphor-1.12.2-0.2.6+build50-universal.jar)

ForgelinPlugin (Forgelin-1.8.4.jar)

MekanismCoremod (Mekanism-1.12.2-9.8.3.390.jar)
mekanism.coremod.KeybindingMigrationHelper
VanillaFixLoadingPlugin (VanillaFix-1.0.10-99.jar)

CXLibraryCore (cxlibrary-1.12.1-1.6.1.jar)
cubex2.cxlibrary.CoreModTransformer
IvToolkit (IvToolkit-1.3.3-1.12.jar)

Techguns Core (techguns-1.12.2-2.0.2.0_pre3.1.jar)
techguns.core.TechgunsASMTransformer
GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
Suspected Mods: Chocolate Quest Repoured Mod (cqrepoured), Techguns (techguns)
Profiler Position: N/A (disabled)
Player Count: 1 / 8; [EntityPlayerMP['JanRooru'/3, l='Ivonne', x=176.15, y=82.00, z=-586.59]]
Type: Integrated Server (map_client.txt)
Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by DerToaster98** [comment]
You better be sorry for that terrible report. Please use the issue template in the future and dont paste the whole log here, cause here that is barely readable. That bug should be fixed in the next build

**Comment by DerToaster98** [comment]
Also this issue shouldn’t appear if you actually had your configs deleted when we said that they needed to be deleted

**Comment by DerToaster98** [comment]
Also we do not support old versions, please update the mod
