### ISSUE TITLE
Lava on the outersides of the Volcano not moving?

### ISSUE THREAD

**Issue by Sagisolar** [TeamChocoQuest/ChocolateQuestRepoured#135]
**Describe the bug**
Honestly this very minor and nitpicky but the lava that spawns on the outside stays still.
![2020-01-22_20 37 23](https://user-images.githubusercontent.com/44548547/72932317-70ac2380-3d57-11ea-9709-766dc83f8aeb.png)

I should mention that it only seems to be when its facing outwards it stays still. If its facing inwards it flows like normal.
![2020-01-22_20 42 48](https://user-images.githubusercontent.com/44548547/72932524-d9939b80-3d57-11ea-92a2-a86ba2ece566.png)

**To Reproduce**
1. Find Volcano or spawn it in yourself.
2. See Lava thats frozen in place.

**Expected behavior**
To flow down the Volcano and touch the floor.

**Versions**
ChocolateQuestRepoured-1.12.2-1.5.2A
Forge: I use 2846 but I went back to 2768 and it still happened.
Minecraft: 1.12.2

**Other**
Singleplayer
Other mods (that are also installed): I had Toro's Health and thats it when I went back to 2768. Consider that It has nothing to do with structure spawning I doubt it was causing it.

**Comment by DerToaster98** [comment]
This is not a bug. It is caused by how minecraft handles blocks. Wait a lil bit or place blocks next to the lava

**Comment by DerToaster98** [comment]
static lava is definitely not the case in the latest release or since alpha 15 or 16
