### ISSUE TITLE
Conflict with mutant beasts Item rendering

### ISSUE THREAD

**Issue by ElfinHarasi** [TeamChocoQuest/ChocolateQuestRepoured#136]
**Describe the bug**
With mutant beasts mod, when I opened my inventory in creative, crashed.

**To Reproduce**
Put CQR and mutant beasts(any version) in mods, and just open and flip creative inventory.

**Expected behavior**
Crash.

**Screenshots**

**Versions**
Chocolate Quest Repoured:1.6.1A
Forge:14.23.5.2847
Minecraft:1.12.2
MutantBeasts-1.12.2-0.6.1

**Other**
Crash report: https://pastebin.com/H50ZkFkA
Logfile:
Singleplayer/Multiplayer:Single
Other mods (that are necessary to produce the bug):Mutant beasts-1.12.2-0.6.1
Other mods (that are also installed): In crash log.

**Comment by DerToaster98** [comment]
According to the crash report this seems to be a general issue with mutant beasts

This crash can however be fixed by disabling the spawn egg textures in mutant beasts config

To get it fully solved you should report this to mutant beasts developer
