### ISSUE TITLE
Invalid id 4096

### ISSUE THREAD

**Issue by QvreL** [TeamChocoQuest/ChocolateQuestRepoured#137]
**Description**
I am making my private stack of mods on 1.12.2, but I found this error that doesn't let me use my favourite dungeon crawler.
This error pops out while launching the game, it may be my fault since after all it's a little private modpack, but I am sending this so maybe you can work on compatibility.

**Crash Report**

WARNING: coremods are present:
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
  iceandfire (iceandfire-1.8.4.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  Quark Plugin (Quark-r1.6-177.jar)
  AstralCore (astralsorcery-1.12.2-1.10.22.jar)
  OTGCorePlugin (OTG-Core.jar)
  TransformLoader (DynamicSurroundings-1.12.2-3.6.0.2.jar)
  IvToolkit (IvToolkit-1.3.3-1.12.jar)
  TheBetweenlandsLoadingPlugin (TheBetweenlands-3.5.6-core.jar)
Contact their authors BEFORE contacting forge

// Hey, that tickles! Hehehe!

Time: 2/12/20 12:09 PM
Description: Initializing game

java.lang.RuntimeException: Invalid id 4096 - maximum id range exceeded.
	at net.minecraftforge.registries.ForgeRegistry.add(ForgeRegistry.java:295)
	at net.minecraftforge.registries.ForgeRegistry.add(ForgeRegistry.java:281)
	at net.minecraftforge.registries.ForgeRegistry.register(ForgeRegistry.java:113)
	at thebetweenlands.common.registries.BlockRegistry.registerBlocks(BlockRegistry.java:999)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1442_BlockRegistry_registerBlocks_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:845)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:630)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraftforge.registries.ForgeRegistry.add(ForgeRegistry.java:295)
	at net.minecraftforge.registries.ForgeRegistry.add(ForgeRegistry.java:281)
	at net.minecraftforge.registries.ForgeRegistry.register(ForgeRegistry.java:113)
	at thebetweenlands.common.registries.BlockRegistry.registerBlocks(BlockRegistry.java:999)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1442_BlockRegistry_registerBlocks_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:845)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:630)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 290922552 bytes (277 MB) / 2248146944 bytes (2144 MB) up to 10737418240 bytes (10240 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx10G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2847 Optifine OptiFine_1.12.2_HD_U_F5 79 mods loaded, 79 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                   | Version                  | Source                                        | Signature                                |
	|:----- |:-------------------- |:------------------------ |:--------------------------------------------- |:---------------------------------------- |
	| LCH   | minecraft            | 1.12.2                   | minecraft.jar                                 | None                                     |
	| LCH   | mcp                  | 9.42                     | minecraft.jar                                 | None                                     |
	| LCH   | FML                  | 8.0.99.99                | forge-1.12.2-14.23.5.2847.jar                 | None                                     |
	| LCH   | forge                | 14.23.5.2847             | forge-1.12.2-14.23.5.2847.jar                 | None                                     |
	| LCH   | ivtoolkit            | 1.3.3-1.12               | minecraft.jar                                 | None                                     |
	| LCH   | otgcore              | 1.12.2 - v8.3            | minecraft.jar                                 | None                                     |
	| LCH   | rpghud               | 3.6.6.2                  | [1.12]+RPG-HUD-3.6.6.2.jar                    | None                                     |
	| LCH   | aether_legacy        | 1.4.4                    | aether_legacy-1.12.2-v1.4.4.jar               | None                                     |
	| LCH   | ebwizardry           | 4.2.8                    | ElectroblobsWizardry-4.2.8-MC1.12.2.jar       | None                                     |
	| LCH   | ancientspellcraft    | 1.0.1                    | AncientSpellcraft-1.12.2-1.0.1.jar            | None                                     |
	| LCH   | aoa3                 | 3.2.4                    | AoA3-3.2.4.jar                                | 8bddeac148843f40e0b9f69201be2f4b3071700d |
	| LCH   | aquaculture          | 1.6.8                    | Aquaculture-1.12.2-1.6.8.jar                  | None                                     |
	| LCH   | arcane_essentials    | 1.0                      | Arcane+Essentials-0.9.2.jar                   | None                                     |
	| LCH   | baubles              | 1.5.2                    | Baubles-1.12-1.5.2.jar                        | None                                     |
	| LCH   | astralsorcery        | 1.10.22                  | astralsorcery-1.12.2-1.10.22.jar              | a0f0b759d895c15ceb3e3bcb5f3c2db7c582edf0 |
	| LCH   | atum                 | 2.0.16                   | Atum-1.12.2-2.0.16.jar                        | None                                     |
	| LCH   | jei                  | 4.15.0.291               | jei_1.12.2-4.15.0.291.jar                     | None                                     |
	| LCH   | tombstone            | 3.6.6                    | tombstone-3.6.6-1.12.2.jar                    | None                                     |
	| LCH   | quark                | r1.6-177                 | Quark-r1.6-177.jar                            | None                                     |
	| LCH   | autoreglib           | 1.3-32                   | AutoRegLib-1.3-32.jar                         | None                                     |
	| LCH   | bettercaves          | 1.12.2                   | bettercaves-1.12.2-1.6.0.jar                  | None                                     |
	| LCH   | openterraingenerator | v8.3                     | OpenTerrainGenerator-1.12.2+-+v8.3.jar        | None                                     |
	| LCH   | biomebundle          | 5.1                      | Biome_Bundle-1.12.2-v6.1.jar                  | None                                     |
	| LCH   | botania              | r1.10-363                | Botania+r1.10-363.jar                         | None                                     |
	| LCH   | llibrary             | 1.7.19                   | llibrary-1.7.19-1.12.2.jar                    | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| LCH   | cqrepoured           | 1.8.0A                   | ChocolateQuestRepoured-1.12.2-1.8.0A.jar      | None                                     |
	| LCH   | mantle               | 1.12-1.3.3.55            | Mantle-1.12-1.3.3.55.jar                      | None                                     |
	| LCH   | twilightforest       | 3.10.1013                | twilightforest-1.12.2-3.10.1013-universal.jar | None                                     |
	| LCH   | tconstruct           | 1.12.2-2.13.0.171        | TConstruct-1.12.2-2.13.0.171.jar              | None                                     |
	| LCH   | conarm               | 1.2.5.3                  | conarm-1.12.2-1.2.5.3.jar                     | 2484ef4d131fdc0dca0647aa21b7b944ddb935a1 |
	| LCH   | configmod            | v1.0                     | coroutil-1.12.1-1.2.36.jar                    | None                                     |
	| LCH   | extendedrenderer     | v1.0                     | coroutil-1.12.1-1.2.36.jar                    | None                                     |
	| LCH   | coroutil             | 1.12.1-1.2.36            | coroutil-1.12.1-1.2.36.jar                    | None                                     |
	| LCH   | customspawner        | 3.11.4                   | CustomMobSpawner-3.11.4.jar                   | None                                     |
	| LCH   | cyclopscore          | 1.6.0                    | CyclopsCore-1.12.2-1.6.0.jar                  | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
	| LCH   | dldungeonsjbg        | 1.12.10                  | DoomlikeDungeons-1.12.10-MC1.12.2.jar         | None                                     |
	| LCH   | mocreatures          | 12.0.5                   | DrZharks MoCreatures Mod-12.0.5.jar           | None                                     |
	| LCH   | dungeontactics       | DT-0.16.6                | DungeonTactics-1.12.2-0.16.6.jar              | None                                     |
	| LCH   | orelib               | 3.6.0.1                  | OreLib-1.12.2-3.6.0.1.jar                     | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| LCH   | dsurround            | 3.6.0.2                  | DynamicSurroundings-1.12.2-3.6.0.2.jar        | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| LCH   | embers               | 1.13-hotfix2             | EmbersRekindled-1.13-hotfix2.jar              | None                                     |
	| LCH   | everlastingabilities | 1.5.2                    | EverlastingAbilities-1.12.2-1.5.2.jar         | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
	| LCH   | extra_spells         | 1.1.4                    | ExtraSpells-1.12.2-1.1.4.jar                  | None                                     |
	| LCH   | heroicarmory         | 1.1.3                    | heroicarmory-1.2.0.jar                        | None                                     |
	| LCH   | waila                | 1.8.26                   | Hwyla-1.8.26-B41_1.12.2.jar                   | None                                     |
	| LCH   | iceandfire           | 1.8.4                    | iceandfire-1.8.4.jar                          | None                                     |
	| LCH   | infernalmobs         | 1.7.6                    | InfernalMobs-1.12.2.jar                       | None                                     |
	| LCH   | inventorypets        | 2.0.3                    | inventorypets-1.12-2.0.3.jar                  | None                                     |
	| LCH   | inventorytweaks      | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                      | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| LCH   | journeymap           | 1.12.2-5.5.8             | journeymap-1.12.2-5.5.8.jar                   | None                                     |
	| LCH   | jeresources          | 0.9.2.60                 | JustEnoughResources-1.12.2-0.9.2.60.jar       | None                                     |
	| LCH   | libraryex            | 1.0.12                   | LibraryEx-1.12.2-1.0.12.jar                   | None                                     |
	| LCH   | lost_aether          | 0.1.2                    | lost_aether-content-1.12.2-0.1.2.jar          | None                                     |
	| LCH   | moartinkers          | 0.6.0                    | moartinkers-0.6.0.jar                         | None                                     |
	| LCH   | mowziesmobs          | 1.5.4                    | mowziesmobs-1.5.4.jar                         | None                                     |
	| LCH   | mysticalworld        | 1.12.2-1.7.1             | mysticalworld-1.12.2-1.7.1.jar                | None                                     |
	| LCH   | neat                 | 1.4-17                   | Neat+1.4-17.jar                               | None                                     |
	| LCH   | patchouli            | 1.0-20                   | Patchouli-1.0-20.jar                          | None                                     |
	| LCH   | plustic              | 7.1.6.1                  | plustic-7.1.6.1.jar                           | None                                     |
	| LCH   | pyramidplunder       | 1.12.2-1.0               | PyramidPlunder-1.12.2-1.4.jar                 | None                                     |
	| LCH   | reccomplex           | 1.4.8.2                  | RecurrentComplex-1.4.8.2.jar                  | None                                     |
	| LCH   | roguelike            | 1.8.0                    | RoguelikeDungeons-1.12.2-1.8.0.jar            | None                                     |
	| LCH   | ruins                | 17.2                     | Ruins-1.12.2.jar                              | None                                     |
	| LCH   | savemystronghold     | 1.12.2-1.0.0             | savemystronghold-1.12.2-1.0.0.jar             | None                                     |
	| LCH   | t3s4ebw              | 1.0                      | SeedsForWizardry+1.0+For+MC+Forge+1.12.2.jar  | None                                     |
	| LCH   | spartanweaponry      | beta 1.3.8               | SpartanWeaponry-1.12.2-beta-1.3.8.jar         | None                                     |
	| LCH   | shinygear            | 1.5                      | shinygear-1.5.jar                             | None                                     |
	| LCH   | spartancompat        | @VERSION@                | spartancompat-1.2.2.jar                       | None                                     |
	| LCH   | spartanfire          | 0.07                     | spartanfire-0.07.jar                          | None                                     |
	| LCH   | stellarapi           | 1.12.2-0.4.2.9           | Stellar+API-1.12.2-0.4.2.9.jar                | None                                     |
	| LCH   | stellarsky           | 1.12.2-0.5.2.8           | Stellar+Sky-1.12.2-0.5.2.8.jar                | None                                     |
	| LCH   | taiga                | 1.12.2-1.3.3             | taiga-1.12.2-1.3.4.jar                        | None                                     |
	| LCH   | theeightfabledblades | 1.0.0                    | TheEightFabledBlades+V2.0.01.jar              | None                                     |
	| LCH   | tinkersjei           | 1.2                      | tinkersjei-1.2.jar                            | None                                     |
	| LCH   | tinkertoolleveling   | 1.12.2-1.1.0.DEV.b23e769 | TinkerToolLeveling-1.12.2-1.1.0.jar           | None                                     |
	| LCH   | wearablebackpacks    | 3.1.4                    | WearableBackpacks-1.12.2-3.1.4.jar            | None                                     |
	| LCH   | zombieawareness      | 1.12.1-1.11.16           | zombieawareness-1.12.1-1.11.16.jar            | None                                     |
	| LCH   | thebetweenlands      | 3.5.6                    | TheBetweenlands-3.5.6-universal.jar           | 38067d6878811efb38b6a045521cfd80b9b60b38 |
	| LCH   | mysticallib          | 1.12.2-1.6.0             | mysticallib-1.12.2-1.6.0.jar                  | None                                     |

	Loaded coremods (and transformers): 
llibrary (llibrary-core-1.0.11-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
iceandfire (iceandfire-1.8.4.jar)
  com.github.alexthe666.iceandfire.patcher.IceAndFireRuntimePatcher
Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  invtweaks.forge.asm.ContainerTransformer
Quark Plugin (Quark-r1.6-177.jar)
  vazkii.quark.base.asm.ClassTransformer
AstralCore (astralsorcery-1.12.2-1.10.22.jar)
  
OTGCorePlugin (OTG-Core.jar)
  com.pg85.otg.forge.asm.excluded.OTGClassTransformer
TransformLoader (DynamicSurroundings-1.12.2-3.6.0.2.jar)
  
IvToolkit (IvToolkit-1.3.3-1.12.jar)
  
TheBetweenlandsLoadingPlugin (TheBetweenlands-3.5.6-core.jar)
  thebetweenlands.core.TheBetweenlandsClassTransformer
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.6.13570 Compatibility Profile Context 19.7.4 26.20.13001.23001' Renderer: 'AMD Radeon RX 5700 XT'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- wailaIntegration (Enabled/Not Forced)
		- quarkIntegration (Enabled/Not Forced)

	Launched Version: 1.12.2-forge1.12.2-14.23.5.2847
	LWJGL: 2.9.4
	OpenGL: AMD Radeon RX 5700 XT GL version 4.6.13570 Compatibility Profile Context 19.7.4 26.20.13001.23001, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 12x AMD Ryzen 5 3600 6-Core Processor 
	OptiFine Version: OptiFine_1.12.2_HD_U_F5
	OptiFine Build: 20191204-141934
	Render Distance Chunks: 16
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.13570 Compatibility Profile Context 19.7.4 26.20.13001.23001
	OpenGlRenderer: AMD Radeon RX 5700 XT
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 12

Present mods are in crash log.

**Comment by DerToaster98** [comment]
Please put the crash report in its own FILE. it is barely readable likt it is now

**Comment by DerToaster98** [comment]
Also this does not seem to be a general problem and the error report tells us nothing here. We need the configs you use.

**Comment by DerToaster98** [comment]
Also that issue is caused by the betweenlands so ask them

**Comment by Meldexun** [comment]
This is not a bug in CQR. You just have too many mods. In MC 1.12 the amount of blocks that can be registered is 4096. So you can either remove some of your mods or i think there is a mod that extends the amount of blocks that can be registered.
