### ISSUE TITLE
I don't think this structure is supposed to generate at y=40 (using Open Terrain Generator)

### ISSUE THREAD

**Issue by inkdear** [TeamChocoQuest/ChocolateQuestRepoured#138]
**Describe the bug**
I found a structure generated such that it carved a huge square out of a lake, when it shouldn't have had trouble placing it on top of the terrain since it's just a flat grassy biome. (also, sea level is set at the normal level.) I'm using OTG with a preset of my own creation. I've seen these generate normally as well, not sure why this one is so low down.

**To Reproduce**
This is the first time I've seen this - I think it just happened randomly, I'm not sure it's directly reproduceable. 

**Expected behavior**
Structure sitting on top of the terrain

**Screenshots**
![2020-02-15_14 25 24](https://user-images.githubusercontent.com/41709276/74579431-43256380-4fff-11ea-9995-bca6f2b742e0.png)

**Versions**
Chocolate Quest Repoured: 1.6.1A
Forge: 14.23.5.2838
Minecraft: 1.12.2

**Other**
Crash report: no crash
Log file: no crash
Singleplayer/Multiplayer: singleplayer
Other mods (that are necessary to produce the bug): possibly open terrain generator (v8.3)
Other mods (that are also installed):
XL Food Mod
ResourceLoader
Beasts
DungeonMobs
ExtraCreatures
FertileSoil
llibrary
LootGames
OpenTerrainGenerator
PizzaCraft
rustic
sbirds
TimeCore
walljump

**Comment by DerToaster98** [comment]
At first: You are using an outdated version, we do not support outdated versions.

Second: This actually isnt a bug, it is just that we forgot something in the structure placement which chooses the y coordinate. In your case the dungeon position hit the ravine and it then chose the highest y at that coordinate which was the bottom of the ravine.
