### ISSUE TITLE
Weird nether city spawn

### ISSUE THREAD

**Issue by Zack7292** [TeamChocoQuest/ChocolateQuestRepoured#139]
**Describe the bug**
the nether city spawn with weird issue like flying spawns or flying blocks that are supposed to be attached to a wall

**To Reproduce**
1.go to the nether
2. find a nether city
3. look around it

**Expected behavior**
no flying blocks

**Screenshots**
https://imgur.com/c6mbGsG

**Versions**
Chocolate Quest Repoured: 1.8.0A
Forge: 1.12.2 - 14.23.5.2847
Minecraft: 1.12.2

**Other**
Crash report: none
Log file: none
Singleplayer/Multiplayer: single player
Other mods (that are necessary to produce the bug): better nether, since some of its block are floating
Other mods (that are also installed): look at this crash log for the full mod list (this crash log is not related in this issue): https://paste.dimdev.org/amecukekug.mccrash

**Comment by DerToaster98** [comment]
Those are supposed to fly. they spawn ghasts

**Comment by DerToaster98** [comment]
The shroom blocks that should be attached to a wall must have been generated after the nether city as the nether city generates a big air bubble around itself that gets rid of everything first

**Comment by DerToaster98** [comment]
Also i used cqr with better nether too, i never experienced that, so it is random or just your specific setup or you changed the config

**Comment by Zack7292** [comment]
ok
thx for the help!
