### ISSUE TITLE
ChocolateQuest Causing Crash

### ISSUE THREAD

**Issue by Alex-G3** [TeamChocoQuest/ChocolateQuestRepoured#143]
**Describe the bug**
Game crashes randomly, and seems to corrupt world as when I load it again it instantly crashes.

**To Reproduce**
2. Use item '....'
3. Place block '....'
.
.
.

**Expected behavior**

**Screenshots**

**Versions**
Chocolate Quest Repoured:
Forge:
Minecraft:

**Other**
[crash-2020-02-20_00.18.10-server.txt](https://github.com/TeamChocoQuest/ChocolateQuestRepoured/files/4232202/crash-2020-02-20_00.18.10-server.txt)

Crash report: 
[crash-2020-02-20_00.18.10-server.txt](https://github.com/TeamChocoQuest/ChocolateQuestRepoured/files/4232207/crash-2020-02-20_00.18.10-server.txt)

Log file:
Singleplayer/Multiplayer:
Other mods (that are necessary to produce the bug):
Other mods (that are also installed):

**Comment by DerToaster98** [comment]
Invalid.

**Comment by DerToaster98** [comment]
Also no support for outdated versions

**Comment by Alex-G3** [comment]
Huh? Invalid? I was told to post the crash report by someone

**Comment by Alex-G3** [comment]
Said something about a fix

**Comment by DerToaster98** [comment]
Fields required for a fix for us to work on are not filled out. And you use an outdated version we do nonlonger support

**Comment by Alex-G3** [comment]
I was just told to upload the crash report

**Comment by DerToaster98** [comment]
We expect some normal intelligence to actually read the template and fill it out

**Comment by Alex-G3** [comment]
Normal intelligence? Why are you being rude?

**Comment by Alex-G3** [comment]
Just go read the comment on the description on the mod

**Comment by DerToaster98** [comment]
Cause i dont love to deal with people unwilling to provide necessary information for us to actually work on this and i dont know a different word for it

**Comment by Alex-G3** [comment]
He said he wanted me to upload a crash report to maybe find a fix

**Comment by Alex-G3** [comment]
Why is it even you that's dealing with this? There's miscommunition now

**Comment by Alex-G3** [comment]
Shouldn't it be the two people that asked me?

**Comment by DerToaster98** [comment]
Cause im the lead dev

**Comment by Alex-G3** [comment]
Hold on

**Comment by Alex-G3** [comment]
![image](https://user-images.githubusercontent.com/61289338/74966526-2b762280-53e5-11ea-9bed-56dfc2858de4.png)

**Comment by Alex-G3** [comment]
![image](https://user-images.githubusercontent.com/61289338/74966591-51032c00-53e5-11ea-92cb-3287f4d7fa6f.png)

**Comment by DerToaster98** [comment]
Thats meldex, he is one of the devs. And im pretty sure he wanted you to correctly fill out the issue template and not just upload the crash here

**Comment by DerToaster98** [comment]
Also those images aren’t helping. There is no clear explanation for us on how to reproduce the issue

**Comment by Alex-G3** [comment]
Alright I'll try to fill out the template

**Comment by DerToaster98** [comment]
Thank you, at least fill out how to reproduce the bug step by step and what version you did use. At best try reproduce the bug with the latest version so we  actually know if the bug isnt fixed already
