### ISSUE TITLE
ChocolateQuest Causing crash and also corrupts world

### ISSUE THREAD

**Issue by Alex-G3** [TeamChocoQuest/ChocolateQuestRepoured#144]
**Describe the bug**
I am making a modpack, and all the mods versions state that they are for 1.12.2, but this mod states that it is for "forge". But in the description it said 1.12.2 so I tried to use it. Everything was going good until it randomly crashed and then I relaunched and loaded the world but it instantly crashes. I tried seeing if there was a was to force the crash to happen and there is. I'll explain in the steps.

**To Reproduce**
1. Start a world, then close it.
2. Change something in the configs.
3. Load same world again and it should crash.

**Expected behavior**

**Screenshots**

**Versions**
Chocolate Quest Repoured: 
![image](https://user-images.githubusercontent.com/61289338/74967434-f7036600-53e6-11ea-8b7e-c24c9f42eb9c.png)

Forge: 
![image](https://user-images.githubusercontent.com/61289338/74967504-19957f00-53e7-11ea-9bb2-5bf988cd8bb2.png)

Minecraft: 1.12.2

**Other**
Crash report:
[crash-2020-02-20_00.18.10-server.txt](https://github.com/TeamChocoQuest/ChocolateQuestRepoured/files/4232438/crash-2020-02-20_00.18.10-server.txt)

Log file:
Singleplayer/Multiplayer:
Other mods (that are necessary to produce the bug):
Other mods (that are also installed):

**Comment by LordEpos** [comment]
Can you be more specific about what you changed in the configs?

**Comment by DerToaster98** [comment]
Also maybe use the right forge version. The one you use is too old, you should use 2847

**Comment by Alex-G3** [comment]
I need the universal one since I'm using a mudpack, I'll try to find it

**Comment by DerToaster98** [comment]
That actually doesnt matter, except for technicpack

**Comment by Alex-G3** [comment]
That's what I'm using, technic launcher

**Comment by Alex-G3** [comment]
Okay I'm trying it with the latest forge

**Comment by Alex-G3** [comment]
Okay it still does the same

**Comment by Alex-G3** [comment]
Also, I change something in the configs of a different mod, so that's shouldn't be a problem

**Comment by Alex-G3** [comment]
I want to address what I meant by the mod version earlier

**Comment by Alex-G3** [comment]
![image](https://user-images.githubusercontent.com/61289338/74969866-59f6fc00-53eb-11ea-92fc-9d6ef27b49cf.png)

**Comment by Alex-G3** [comment]
This is some other mod I got

**Comment by Alex-G3** [comment]
![image](https://user-images.githubusercontent.com/61289338/74969901-6f6c2600-53eb-11ea-8220-7fbf413922d4.png)

**Comment by DerToaster98** [comment]
Blame curseforge’s page design for the version thing

**Comment by Alex-G3** [comment]
And this is Chocolatequestrepoured

**Comment by Alex-G3** [comment]
Why does this mod say Forge, and the others say 1.12.2 ?

**Comment by DerToaster98** [comment]
Blame curseforge’s page design for the version thing

**Comment by Alex-G3** [comment]
Yes I got that, but that's probably why it's not working no?

**Comment by LordEpos** [comment]
Technically it's set to both "1.12.2" and "forge" it just shows forge first for some reason.

**Comment by LordEpos** [comment]
That has nothing to do with why it's not working, it's just a category on a website, it's not anything in the mod.

**Comment by Alex-G3** [comment]
All my other mods say 1.12.2 but this is the only one that says Forge

**Comment by Alex-G3** [comment]
Okay

**Comment by Alex-G3** [comment]
Well I can't figure out why it doesn't work, have you looked at the crash report?

**Comment by LordEpos** [comment]
Can you try this on the latest version of CQR as well? The current build is 1.9.2A and we haven't been able to reproduce the crash on our end using that version.

**Comment by Alex-G3** [comment]
Sure I'll try that

**Comment by Alex-G3** [comment]
Okay! Looks like it's fixed now! Guess I just needed the latest versions

**Comment by Alex-G3** [comment]
Thanks for your help!
