### ISSUE TITLE
Golems not having their head completly rendered

### ISSUE THREAD

**Issue by Scarlet458** [TeamChocoQuest/ChocolateQuestRepoured#145]
**Describe the bug**
Golems have their lower head part invisible, allowing you to look inside their heads

**To Reproduce**
1. Spawn a golem
2. Look under their heads
3. See error

**Expected behavior**
Having their heads fully rendered

**Screenshots**
![2020-02-22_19 52 07](https://user-images.githubusercontent.com/61365401/75100697-0eda1600-55b0-11ea-930f-887d321f1eb1.png)

**Versions**
Chocolate Quest Repoured: 1.9.0A
Forge: 14.23.5.2838
Minecraft: 1.12.2

**Other**
Crash report:
Log:
Singleplayer/Multiplayer: Singleplayer
Other mods (that are necessary to produce the bug):
Other mods (that are also installed): Optifine, BetterFPS, Tinkers Construct, Mantle, llibrary, World Edit

**Comment by DerToaster98** [comment]
should be fixed now
