### ISSUE TITLE
Pregenerating world console error

### ISSUE THREAD

**Issue by Enchilada246** [TeamChocoQuest/ChocolateQuestRepoured#146]
I've used the worldborder pluguin to pregenerate a modded world using aternos and this error appears.
Chocolate Quest Repoured Mod loaded a new chunk [4, 36] in dimension 0 (overworld) while populating chunk [5, 35], causing cascading worldgen lag.
It asks me to report it to the mod's issue tracker, idk if this's the place to report it. Also, it says that this log can be disbled in the forge config. How can I enter there? Thanks!

**Comment by DerToaster98** [comment]
This is not a bug. also no support for aternos and that is not an error, it is a warning and can be ignored.
