### ISSUE TITLE
Realistic Terrain Generator Compatibility 

### ISSUE THREAD

**Issue by Dalethium** [TeamChocoQuest/ChocolateQuestRepoured#147]
**Describe the bug**
RTG usage along with BiomesOP and this mod cause floating birch tree forests along with a number of other generation errors.

**To Reproduce**
Install RTG, BiomesOP, Climatic biomes, and CQR, run a world with the level type of RTG.

**Expected behavior**
RTG generation should be normal.

**Versions**
Chocolate Quest Repoured: ChocolateQuestRepoured-1.12.2-1.9.2A.
Forge:14.23.5.2847
Minecraft:1.12.2

**Other**
Singleplayer/Multiplayer: MP
Other mods (that are necessary to produce the bug): BiomesOPlenty1.12.27.0.1.2444universal, ClimaticBiomes-2.14.16-MC1.12.2, RTG1.12.26.1.0.0snapshot.1
Other mods (that are also installed): https://github.com/WeNeedCoffee/Convergence/blob/56199d26aad3fbcd182211ce32fb4723bd511e68/mods.csv

**Comment by DerToaster98** [comment]
we won't reproduce it like that we dont have the time to do so. please provide a screenshot of that "errors"

**Comment by KenyMylankca** [comment]
@Dalethium try with this RTG 
[Desktop.zip](https://github.com/TeamChocoQuest/ChocolateQuestRepoured/files/4270160/Desktop.zip)

**Comment by KenyMylankca** [comment]
and uhm, you shouldn't use RTG and climatic biomes together. both requires to be selected as the world generation type. so use RTG **or** climatic biomes

**Comment by Dalethium** [comment]
I was under the impression that climactic biomes was a requirement for RTG, is it not? There are 2 mods with similar names I could have mixed them up. the MCF page for RTG showed Climactic as a dependency if you have BOP iirc. I'll check now.

**Comment by Dalethium** [comment]
Ah, this was entirely my mistake I apologize, it was ***climate control*** not climactic biomes. I'll go ahead and close this ticket now.

**Comment by KenyMylankca** [comment]
no rtg has no requirement
