### ISSUE TITLE
Volcano spawn rates

### ISSUE THREAD

**Issue by Dalethium** [TeamChocoQuest/ChocolateQuestRepoured#148]
**Describe the bug**
Volcano spawns are a bit high

**Expected behavior**
less than 200 mobs in one spot

**Screenshots**
![image](https://user-images.githubusercontent.com/22735418/75260170-0d6e4080-579e-11ea-9d0f-66cafa3cae88.png)
(this was after many of them died in lava)

**Versions**
Chocolate Quest Repoured: ChocolateQuestRepoured-1.12.2-1.9.2A.
Forge:14.23.5.2847
Minecraft:1.12.2

**Other**
Singleplayer/Multiplayer: MP
Other mods (that are also installed): https://github.com/WeNeedCoffee/Convergence/blob/56199d26aad3fbcd182211ce32fb4723bd511e68/mods.csv

**Comment by DerToaster98** [comment]
blame vanilla for their spawners. also i never encountered that many mobs. it always stopped for me when there were like 20

**Comment by DerToaster98** [comment]
lowering the spawn count may be taken into consideration after further testing
