### ISSUE TITLE
Crash after attacking an enemy

### ISSUE THREAD

**Issue by Enchilada246** [TeamChocoQuest/ChocolateQuestRepoured#149]
When I go to one of the dungeons, which is the Necromancer one, when I enter and attack at one of the skeletons of the entrance, the world just crashes

**Versions**
Chocolate Quest Repoured: 1.12.2-1.9.2A
Forge: 1.12.2-14.23.5.2847
Minecraft: 1.12.2

Log file: https://mclo.gs/HcU9xQI
[crash_report.txt](https://github.com/TeamChocoQuest/ChocolateQuestRepoured/files/4270771/crash_report.txt)

Multiplayer: These are all the mods within the server I play

SecurityCraft v1.8.15.jar 

Decocraft-2.6.3_1.12.2.jar 

PTRLib-1.0.4.jar 

PlayerRevive_v1.2.30_mc1.12.2.jar 

jei_1.12.2-4.15.0.293.jar 

Hwyla-1.8.26-B41_1.12.2.jar 

PlayerRevive_v1.2.30_mc1.12.2.jar

CreativeCore_v1.9.90_mc1.12.2.jar

Mo' Bends 0.24 for Minecraft 1.12

Morpheus-1.12.2-3.5.106.jar

journeymap-1.12.2-5.5.9

U-Team-Core-1.12.2-2.2.5.147

Useful-Backpacks-1.12.2-1.5.3.59

Chocolate Quest Repoured Alpha 15.2

**Comment by DerToaster98** [comment]
There is no "Necromancer-One" Dungeon. the necromancer can spawn in literally EVERY dungeon

**Comment by DerToaster98** [comment]
Also you seem to use a non-forge server, which we do not support

**Comment by DerToaster98** [comment]
we cant solve this issue properly without the server-software used, it is clearly not forge, as it says "craftbukkit" in the log

**Comment by Enchilada246** [comment]
Sorry. It's the dungeon that seems like a stadium or a coliseum where you have to pulse buttons to pvp with differents mobs before the main boss.
I was using Magma but I've just changed to Forge, and now it seems to not crash so, the problem may be the software

**Comment by DerToaster98** [comment]
The problem definitely is the software, as bukkit tries to cast all entities in the world to "EntityLiving", and the summoning circle entity is EntityLivingBase, which in class hierarchy is lower than EntityLiving. So it tries to cast and than crashes. Also: Please use the latest CQR version, not an outdated one
