### ISSUE TITLE
Bug Necromancer vs Sponge - Server Crashes

### ISSUE THREAD

**Issue by pjindras** [TeamChocoQuest/ChocolateQuestRepoured#150]
Hello, i have an server 1.12.2 and when i find a Necromancer it always crashes. I have sponge and the errors in my console are from sponge.

Server 1.12.2
Sponge: spongeforge-1.12.2-2838-7.1.10
CQR: the newest

The crash error: https://pastebin.com/TzFzgTeX

The server is not laggy, the castle and npcs are loaded succesfully, but when i start the fight with necromancer, it happen.

**Comment by DerToaster98** [comment]
Sponge is not supported

**Comment by pjindras** [comment]
Ok and will it be supported in the future?

**Comment by DerToaster98** [comment]
95% no. However, this bug may not be caused by sponge, will be investigated

**Comment by pjindras** [comment]
ok, thanks :)

**Comment by DerToaster98** [comment]
should be fixed in alpha 17.1
