### ISSUE TITLE
Crash when generating Nethercity

### ISSUE THREAD

**Issue by cybercat5555** [TeamChocoQuest/ChocolateQuestRepoured#152]
**Describe the bug**
When trying to generate a Nethercity (the kind in the lava, not the floating kinds), the area is cleared, the roads generate, then it crashes, then makes you unable to enter the world. Possibly related, but the chained cities don't generate either, but they don't seem to cause a crash. I did delete both the CQR folder and the cqrepoured file in the configs folder before generating this, as was instructed, but got this crash.

**To Reproduce**
1. Go to the Nether
2. Fly around a bit until you come across a Nethercity
3. Let it generate, the area will be cleared, then the roads will generate, then crash
4. You are no longer allowed to enter the world

**Expected behavior**
The full city generates like normal and the game doesn't crash

**Screenshots**
https://i.imgur.com/39tGAwf.png
Nethercity roads and cleared area, this was taken right before it crashed

https://i.imgur.com/QzqB8CG.png
Glitchy chains, unsure if related or if this is its own unrelated bug

**Versions**
Chocolate Quest Repoured: 1.12.2-1.11.1A
Forge: 14.23.5.2838
Minecraft: 1.12.2

**Other**
Crash report: 
[crash-2020-03-15_01.18.05-server.txt](https://github.com/TeamChocoQuest/ChocolateQuestRepoured/files/4333808/crash-2020-03-15_01.18.05-server.txt)

Log file: 
[latest.log](https://github.com/TeamChocoQuest/ChocolateQuestRepoured/files/4333810/latest.log)

Singleplayer/Multiplayer: SP
Other mods (that are necessary to produce the bug): n/a, just cqr
Other mods (that are also installed): 
[list.txt](https://github.com/TeamChocoQuest/ChocolateQuestRepoured/files/4333811/list.txt)

**Comment by DerToaster98** [comment]
Chains are not glitched, it generated a floating city farther down

**Comment by DerToaster98** [comment]
Can't reproduce
