### ISSUE TITLE
I cant run server, some error in cqr

### ISSUE THREAD

**Issue by pjindras** [TeamChocoQuest/ChocolateQuestRepoured#156]
Hello i have an issue with lastest cqr, i can run my server.
Can you help me please?
Thanks

https://pastebin.com/W9YY38i8
https://pastebin.com/zbthqpEt

**Comment by DerToaster98** [comment]
please use the issue template.

**Comment by pjindras** [comment]
ok https://github.com/TeamChocoQuest/ChocolateQuestRepoured/issues/157
