### ISSUE TITLE
I cant run server, some error in cqr

### ISSUE THREAD

**Issue by pjindras** [TeamChocoQuest/ChocolateQuestRepoured#157]
**Describe the bug**
Hello i have an issue with lastest cqr, i can run my server, it crashes.

**To Reproduce**

Technicpack.net modpack hexxcore, the server files and run it.
https://pastebin.com/W9YY38i8
https://pastebin.com/zbthqpEt
**Expected behavior**
Server start.
**Screenshots**

**Versions**
Chocolate Quest Repoured: Alpha 18.1
Forge: 14.23.5.2847 
Minecraft: 1.12.2

**Other**
Crash report: https://pastebin.com/W9YY38i8
Log file: https://pastebin.com/zbthqpEt
Multiplayer:
Other mods (that are necessary to produce the bug): see in crash report (idk)
Other mods (that are also installed): see in crash report

**Comment by DerToaster98** [comment]
Should be fixed in next build

**Comment by DerToaster98** [comment]
is fixed in newest version
