### ISSUE TITLE
Loading stops becaue of the LLibrary version error

### ISSUE THREAD

**Issue by foealke** [TeamChocoQuest/ChocolateQuestRepoured#158]
**Describe the bug**
Loading stops because of my LLibrary version is too old (1.7.12) even tho I have  version 1.7.19
**To Reproduce**
1. Put LLibrary 1.7.19 and Chocolate Quest (version Alpha 18.1) in the Mods folder
2. Run the games
4. See error "You must include the right dependencies for...blahblah"

**Expected behavior**
I think it should work with LLibrary 1.7.19, maybe it's forge issue, or LLibrary issue

**Versions**
Chocolate Quest Repoured:
Forge: On both forge 1.12.2 2768 and 1.12.2 2814
Minecraft: 1.12.2

**Comment by Meldexun** [comment]
We need a log file.

**Comment by DerToaster98** [comment]
At first: we need a log file

From what i can see i see that your forge version is not supported, we require the latest (not recommended ) forge version (2847)

**Comment by foealke** [comment]
Oh, I'm really sorry, but it turns out it was a weird windows explorer bug 🤔
when I rebooted my pc I saw I actually had version 1.7.12 in my mods folder even tho before rebooting I tried changing the file several times and nothing happend
