### ISSUE TITLE
Server do not start after updating the mods.

### ISSUE THREAD

**Issue by DArkes1312** [TeamChocoQuest/ChocolateQuestRepoured#161]
**Describe the bug**

The server simply do not start.
It was starting with an older version ( Alpha 16 ! )

I would like to say that I'm using CatServer https://github.com/Luohuayu/CatServer in case it change anything.

**To Reproduce**

Start server.

**Expected behavior**

server to start

**Versions**
Chocolate Quest Repoured: Alpha 18.1
Forge: 14.23.5.2847 
Minecraft: 1.12.2

**Other**
Crash report: https://pastebin.com/VhufBXw6
Log file: https://pastebin.com/dzp1YnqS
Singleplayer/Multiplayer: multiplayer
Other mods (that are necessary to produce the bug):
Other mods (that are also installed): https://niyah.eu/i/84601.png

**Comment by DerToaster98** [comment]
will be fixed in next update

**Comment by DerToaster98** [comment]
is fixed in newest version
