### ISSUE TITLE
Many Rails in Nether Cities Popped Off

### ISSUE THREAD

**Issue by DarianLStephens** [TeamChocoQuest/ChocolateQuestRepoured#165]
**Describe the bug**
A lot of Nether Cities have this weird rollercoaster thing. Every single one of them ends up with rails on the floor. Not all of the rails are dislodged, but it's a lot of them when it should be none.

**To Reproduce**
1. Go to a Nether City.
2. Find one of those rollercoasters.
3. See all the tracks popped off on the floor.

**Expected behavior**
For the rails to remain in there intended position, rather than instantly popping off.

**Screenshots**
![2020-03-29_10 16 22](https://user-images.githubusercontent.com/15375876/77836297-1d1be300-71a9-11ea-8f3f-c05f36e5b704.png)

**Versions**
Chocolate Quest Repoured: Alpha 19
Forge: 14.23.5.2847
Minecraft: 1.12.2

**Other**
Crash report: N/A
Log file: N/A
Singleplayer/Multiplayer: Either
Other mods (that are necessary to produce the bug): N/A
Other mods (that are also installed): N/A

**Comment by DerToaster98** [comment]
We know about this. It is because the structure files for the nether cities need to be exported again cause we made some internal changes

**Comment by DarianLStephens** [comment]
Ah, good to know.
Was there some 'Known Issues' section I missed?

**Comment by KalgogSmash** [comment]
No "known issues" section other than our internal to-do list since we are still in alpha. Still, thank you for the detailed report :)

**Comment by DerToaster98** [comment]
fixed in newest versions
