### ISSUE TITLE
Two-handed weapons issue

### ISSUE THREAD

**Issue by samakotleta** [TeamChocoQuest/ChocolateQuestRepoured#166]
**Describe the bug**
An 1-63 (not 64) item stack held in the second hand when you receive a two-handed weapon in the main hand is BANISHED FROM REALITY.

**To Reproduce**
1. get 1-63 stackable items in second hand
2. get big swordo or spear in main
3. ?????
4. help its gone

**Expected behavior**
placing second hand items back to inventory i guess?

**Screenshots**

**Versions**
Chocolate Quest Repoured: 19 alpha
Forge: latest
Minecraft: 1.12.2

**Other**
Singleplayer/Multiplayer: both
64 item stacks and no-stack items working all-right.

**Comment by DerToaster98** [comment]
It is supposed that you cant equip a second item if you have a item in one that needs two hands.

However, it shouldnt remove the item entirely except your inventory is full....

**Comment by samakotleta** [comment]
64 torches in second hand.
Occasionally scroll inventory bar to just looted greatsword.
Torches are gone for ever. Same with blocks.

Must say, bows and shields are ok: they just getting back into inventory.

**Comment by DerToaster98** [comment]
did you check if your inventory was full? If it is full, it will attempt to drop the itemstack in the offhand. if it has space in the inventory, it will move the itemstack to your inventory. if that doesnt work it seems to be an issue with forge internals

**Comment by samakotleta** [comment]
No, it wasn't full and torches are gone.

**Comment by samakotleta** [comment]
I tested it again. Yes, full item stacks (64) getting back into inventory, but if there is 1-63 - they are disappearing.

**Comment by DerToaster98** [comment]
fixed in newest versions
