### ISSUE TITLE
Randomly Generated Castle Lag

### ISSUE THREAD

**Issue by chriscote1** [TeamChocoQuest/ChocolateQuestRepoured#167]
I've been experiencing extreme lag when attempting to go near any of the large procedurally-generated castles. I can understand some lag when it is generating, but the issue is that when I am near one that has fully generated, the lag drops my FPS down to 4, and I just have to leave the area. 

This issue remains even if I stay in the area for a long time to ensure that everything has loaded, as well as when I fly around the castle in creative to ensure that it has all loaded. The issue seems to be with the castle itself.

I experience a bit of lag while inside of other structures which have fully generated as well. It seems to become more intense based on the size of the structure.

The issue isn't my PC, as I can run heavily modded Minecraft with high-end shaders on, etc.

Has anyone else experienced this? I'd like to be able to explore these larger castles, but have had to disable them for the time being.

**Comment by KalgogSmash** [comment]
Which version of the mod are you running?

**Comment by chriscote1** [comment]
I'm running the Alpha 19 release.

**Comment by Meldexun** [comment]
Can you start the game with the output log opened and create a super flat world and generate a castle and wait until it says "Generated dungeon!" in the output log and then test if it's lagging.

**Comment by chriscote1** [comment]
Just tried in both superflat and regular with the console open. Waited until it said that it finished generating

Superflat is definitely not quite as bad, but it still occurs. 

The console outputs a "Can't keep up! Is the server overloaded?" message whenever the lag is most intense. 

This issue occurs mostly when I am in the center of the castle, and it seems to depend on where I am looking. If I am facing the center, the lag is intense, but not bad at all by the edges, especially if I am looking away from the castle. Running up and down the main hall causes the lag to get progressively worse as I get closer to the center of the castle, and better as I reach the ends of the hall.

This issue occurs both when I use the dungeon spawner, and when spawning naturally.

**Comment by Meldexun** [comment]
So in your testing you generated the dungeon (waited until it says "Dungeon generated!" in log) and then you walked through the dungeon and it was lagging. Is that right? And were you in survival or creative mode?

**Comment by chriscote1** [comment]
Yes, it did say "Dungeon generated!" in the log.

I've had the lag on both survival and creative (first encountered it in survival, then replicated it in creative).

**Comment by KalgogSmash** [comment]
When you replicated it in creative, did the lag happen with all the monster spawners "unspawned" i.e. still looking like a cage? 

My first guess would be that it is the large amount of entities in the castle, because there are no special blocks or tile entities in the castle I can think of that usually cause large amounts of lag. I tested it in creative myself and only got lag during generation.

**Comment by KalgogSmash** [comment]
I am not able to reproduce in creative or survival. May be due to other mods and/or a large number of mobs spawning - try turning down spawnerRollChance in RandomizedCastles.properties in the CQR dungeon config to reduce the amount of enemies that generate in a random castle.

**Comment by DerToaster98** [comment]
You could also try to turn down the spawnerActivationDistance in the config as well as decreasing your render distance.

I cant reproduce this "bug" too. It is either an issue with other mods (if you are using any other mods other than llibrary and cqr) or it is your computer
