### ISSUE TITLE
Potential Sound Loading Bug

### ISSUE THREAD

**Issue by chriscote1** [TeamChocoQuest/ChocolateQuestRepoured#168]
I am not certain that this is being caused by CQR, but I am trying to see which mod is causing an issue I am having, which happens to often happen near CQR structures. The error is:

**13:56:15.896
Error in class 'SourceLWJGL OpenAL'
13:56:15.896
Invalid enumerated parameter value.**

The above error repeats frequently forever, causing the game to freeze every few seconds.

Is it possible that this is caused by CQR? My understanding is that this is caused by a type of sound loading, so maybe a dev can chime in on whether CQR uses this method or not. My understanding is that it isn't used by most mods, so it could help to narrow it down.

Restarting Minecraft seems to fix the issue.

**To Reproduce**
1. Go to any CQR dungeon (in my most recent case, the castle with the giant turtle in it).
2. Just hang around for a while, fight stuff, etc. It seems to happen to me pretty randomly.

**Expected behavior**
I am not sure if it can be replicated, I haven't replicated it without other mods installed, but am trying to (it doesn't happen often even with them installed, but when it does it makes the game unplayable). I am not certain CQR causes it, as I don't know how it loads sounds.

**Versions**
Chocolate Quest Repoured: Alpha 19.1
Forge:  14.23.5.2847
Minecraft: 1.12.2

**Other**
Crash report:
Log file:
Singleplayer/Multiplayer:
Other mods (that are also installed):
Too many to list. I am trying to narrow this bug down.

**Comment by chriscote1** [comment]
[2020-04-01-5.log](https://github.com/TeamChocoQuest/ChocolateQuestRepoured/files/4417462/2020-04-01-5.log)
Error log attached

Mods:
AI Improvements:0.0.1.3, Aether II:0.2.7, Aether Legacy:1.4.4, Animania:1.7.3, AppleCore:3.2.0, Atum 2:2.0.16, AutoRegLib:1.3-32, Baubles:1.5.2, Behgameon:1.0.4, Better Advancements:0.1.0.77, Better Animals Plus:8.2.0, Better Foliage:2.2.0, BiblioCraft:2.4.5, Bigger Packets, please !:1.2, Biomes O' Plenty:7.0.1.2444, Bloodmoon:1.5.3, Bookshelf:2.3.585, Bookworm Library:1.12.2-2.5.0, Bountiful Baubles:0.0.1, Bountiful:2.2.1, Bring me the rings!:0.4, CT-GUI:1.0.0, CTM:MC1.12.2-1.0.1.30, Chameleon:1.12-4.1.3, Chance Cubes:1.12.2-5.0.2.345, Charm:1.12.2-1.3.6, Chest Transporter:2.8.8, ChickenChunks:2.4.2.74, Chisel:MC1.12.2-1.0.1.44, Chocolate Quest Repoured Mod:1.13.0A, Clumps:3.1.2, CodeChicken Lib:3.2.3.358, Comforts:1.4.1.3, Cooking for Blockheads:6.5.0, Copy Paste:1.1, Corail Tombstone:3.7.0, CosmeticArmorReworked:1.12.2-v4b, CraftStudio API:1.0.0, CraftTweaker JEI Support:2.0.3, CraftTweaker2:4.1.20, Custom Main Menu:2.0.9.1, CustomNPCs:1.12, Cyclic:1.19.20, Cyclops Core:1.6.1, Dimensional Doors:3.0.9+287, Doomlike Dungeons:1.13.2, DrZhark's Mo'Creatures Mod:12.0.5, DungeonTactics:DT-0.16.6, Dynamic Trees BOP:1.12.2-1.4.1e, Dynamic Trees:1.12.2-0.9.5, Electroblob's Wizardry:4.2.10, Embers Rekindled:1.13-hotfix2, Embersified:1.0.3, Enchantment Descriptions:1.1.15, EverlastingAbilities:1.5.2, FTB Backups:1.1.0.1, FTB Guides:2.0.0.52, FTB Library:5.4.7.0, FTB Money:1.1.0.42, FTB Quests:1.8.0.237, FTB Utilities:5.4.0.124, Farming for Blockheads:3.1.28, FastFurnace:1.3.1, FastWorkbench:1.7.3, FoamFix:0.10.10-1.12.2, FoamFixCore:7.7.4, Forge Mod Loader:8.0.99.99, Future Versions:1.2.2, Game Stages:2.0.115, Global GameRules:2.2, Grimoire of Gaia 3:1.7.2, Headcrumbs:2.0.4, Heroic Armory:1.1.3, Ice and Fire:1.8.4, Ido - 1.12 movement enhancement:1.0.6, Improved Backpacks:1.12.2-1.4.1.0, Infernal Mobs:1.7.6, Inventory Pets:2.0.3, Inventory Tweaks:1.63+release.109.220f184, Iron Chest:1.12.2-7.0.67.844, Item Filters:1.0.3.12, Item Stages:2.0.49, ItemPhysic:1.4.0, IvToolkit:1.3.3-1.12, JourneyMap:1.12.2-5.7.0, Just Enough Items:4.15.0.291, JustEnoughIDs:1.0.3-48, LLibrary:1.7.19, LadyLib:2.1, LibrarianLib Stage 2:4.20, LibrarianLib:4.20, LibraryEx:1.1.1, Login Shield:1.12.2-3-g7c6e7ac, LootTweaker:0.1.6, Lost Aether Content:0.1.2, Lumen:0.4.0, LunatriusCore:1.2.0.42, Lycanites Mobs:2.0.6.6 - MC 1.12.2, Mantle:1.12-1.3.3.55, Mega Loot:0.2.40, Midnight:0.3.5, Mine and Slash:1.9.3, Minecraft Coder Pack:9.42, Minecraft Comes Alive:6.1.0, Minecraft Forge:14.23.5.2847, Minecraft:1.12.2, Mo' Bends:0.24, Mo' Villages:1.5.4, Mouse Tweaks:2.10, Mowzie's Mobs:1.5.4, MrCrayfish's Furniture Mod:6.3.1, Mutant Beasts:1.12.2-0.6.3, Mystical Lib:1.12.2-1.7.0, Mystical World:1.12.2-1.8.2, Nature's Compass:1.8.5, NetherEx:2.1.1, NetherPortalFix:5.3.17, NoMoreRecipeConflict:0.13, Nomadic Tents:9.5.2, OrbisLib:0.2.0, Pam's HarvestCraft:1.12.2zb, Patchouli:1.0-20, Phosphor Lighting Engine:1.12.2-0.2.6, Placebo:1.6.0, Potion Core:1.9_for_1.12.2, Progressive Bosses:1.5.4, Project: Vibrant Journeys:1.6.4, Pyramid Plunder:1.12.2-1.0, Quality Tools:1.0.7_for_1.12.2, Quark:r1.6-178, RE-Sound:1r, Random Loot Mod:1.7.3, RandomPatches:1.12.2-1.21.0.0, ReAuth:3.6.0, Recurrent Complex:1.4.8.2, Reliquary:1.12.2-1.3.4.796, Resource Loader:1.5.3, Rin's So Many Enchantments?:0.4.4, Roguelike Dungeons:1.8.0, Rough Mobs 2:2.0.0, Ruins Mod:17.2, Rustic:1.1.2, Serene Seasons:1.2.18, Shadowfacts' Forgelin:1.8.4, Simple Storage Network:1.7.10, Sound Filters:0.12_for_1.12, Spartan Shields:1.5.4, SpawnerControl:1.6.3b, Spice of Life: Carrot Edition:1.8.3, Stackie:1.6.0.48, Storage Drawers:1.12.2-5.4.1, Stuff A Sock In It:1.1.30, Subterranean Switcheroo:1.1.0, Surge:2.0.77, SwingThroughGrass:1.12.2-1.2.3, Thaumcrafft Inventory Scanning:2.0.10, Thaumcraft:6.1.BETA26, The Betweenlands:3.5.7, The Farlanders:1.0.1, The Twilight Forest:3.10.1013, ToroQuest:1.12.2-5.3, Totemic:1.12.2-0.11.6, Trample Stopper:1.2.0.4, Tumbleweed:1.12-0.4.7, Tweaker GUI:0.5-beta, Underground Biomes:1.3.7, Unique Crops:0.2.1, Vanilla Tweaks:1.12.2-1.5.6, VanillaFix:1.0.10-SNAPSHOT, Waila:1.8.26, Waystones:4.1.0, XP From Harvest:1.1.0, YUNG's Better Caves:1.12.2, §3Dynamic Surroundings: HUDs:3.5.4.0, §3Dynamic Surroundings:3.6.0.2, §3OreLib Support Library:3.6.0.1

**Comment by chriscote1** [comment]
I should add that I know this is a pretty ridiculous bug to report, considering how many mods I am running which could be conflicting with CQR or causing the bug themselves. I am more or less looking to find out if it would even be possible for CQR to produce this type of bug, so that I can test it further.

**Comment by DerToaster98** [comment]
Issue will be closed as there was/is no reply from the creator of the issue
