### ISSUE TITLE
the game dont open 

### ISSUE THREAD

**Issue by nsadj** [TeamChocoQuest/ChocolateQuestRepoured#170]
**Describe the bug**
i have other two mods need llibrary the problem is chocolate quest need llibrary and this produce the launchher dont open 
**To Reproduce**
the game dont open and vanilla fix create this link
https://paste.dimdev.org/dejawixaho.mccrash
**Versions**
Chocolate Quest Repoured:the game dont open
Forge:1.12.2-14.23.5.2811
Minecraft:1.12.2

**Other**
Crash report: https://paste.dimdev.org/dejawixaho.mccrash
Singleplayer
Other mods (that are necessary to produce the bug): ice and fire, rats, llibrary, chocolate quest, 
Other mods (that are also installed):
itemphysic      
       | LC    | ivtoolkit         | 
       | LC    | foamfixcore       | 
       | LC    | craftstudioapi    | 
       | LC    | harvestcraft      | 
       | LC    | animania          | 
       | LC    | baubles           | 
       | LC    | astralsorcery     | 
       | LC    | bettercombatmod   | 
       | LC    | forgelin          | 
       | LC    | betterfoliage     |
       | LC    | chunkanimator     | 
       | LC    | codechickenlib    | 
       | LC    | customspawner     
       | LC    | orelib            
       | LC    | dsurround         
       | LC    | reccomplex        | 
       | LC    | dynamictrees      |
       | LC    | dynamictreesphc   |        |
       | LC    | jei               | 
       | LC    | mantle            |
       | LC    | tconstruct       
       | LC    | extrautils2       |
       | LC    | Fishs_Undead_Rising-1.0.13.jar          
       | LC    | foamfix           | 
       | LC    | foamflower        | 
       | LC    | llibrary          | 
       | LC    | fossil            |
       | LC    | cfm               | 
       | LC    | globalxp          | 
       | LC    | howlingmoon       | 
       | LC    | waila            
       | LC    | iceandfire        
       | LC    | ido               
       | LC    | improvedbackpacks |              |
       | LC    | infernalmobs     
       | LC    | jeiintegration    |
       | LC    | journeymap        
       | LC    | jeresources      
       | LC    | malisiscore      
       | LC    | malisisdoors   
       | LC    | mca               
       | LC    | mocreatures       
       | LC    | mowziesmobs       
       | LC    | recipehandler                                        |
       | LC    | nei              }
       | LC    | rats                                          |
       | LC    | rustic            
       | LC    | soulboundarmory                                       |
       | LC    | spartanshields    |                                    |
       | LC    | spartanweaponry   |
       | LC    | tombstone                                            |
       | LC    | vanillafix                                         |
       | LC    | thejungle        
chocolate quest

**Comment by DerToaster98** [comment]
Too old forge version

Use the latest (2847, you use 2811)
