### ISSUE TITLE
Cursed Bone Summon

### ISSUE THREAD

**Issue by Kyyrick** [TeamChocoQuest/ChocolateQuestRepoured#172]
**Describe the bug**
Cursed Bones creates the animation for summoning when used by a player, but does not summon mobs accordingly. Mobs summoned with the bone will appear if a player relogs but will be hostile to players. Occurs in single or multiplayer. 

**Versions**
Chocolate Quest Repoured: 1.13.1A

**Comment by DerToaster98** [comment]
Why is noone able to read that that is wip?!

This is known and will be fixed in the next build
