### ISSUE TITLE
Cursed Bone Crash

### ISSUE THREAD

**Issue by Kyyrick** [TeamChocoQuest/ChocolateQuestRepoured#173]
**Version**: 1.12.2-1.14.0A

Cursed Bone now crashes the game upon use.
[crash-2020-04-15_04.35.41-server.txt](https://github.com/TeamChocoQuest/ChocolateQuestRepoured/files/4480019/crash-2020-04-15_04.35.41-server.txt)

**Comment by DerToaster98** [comment]
Why cant you just use the issue template ?!
