### ISSUE TITLE
Crash while hitting enemy walker

### ISSUE THREAD

**Issue by zEpiixz** [TeamChocoQuest/ChocolateQuestRepoured#174]
https://pastebin.com/kmNgKdiW

**To Reproduce**
Just hit a walker.

Chocolate Quest Repoured:Alpha 20
Forge:latest
Minecraft:1.12.2

**Comment by DerToaster98** [comment]
Use the issue template

**Comment by DerToaster98** [comment]
Also this is caused by „mistyworld“, not cqr
