### ISSUE TITLE
Encountering any enemy from the mod crashes whole server.

### ISSUE THREAD

**Issue by Darkleckk** [TeamChocoQuest/ChocolateQuestRepoured#175]
Well, title says it all, mod works well, but when my friends and I went to a dungeon and encountered a mob from cqr it just stopped.

It just stops the server, it doesn't crash, it just closes without a crash-report which is pretty weird.

I just expected for it to work without problems, I tested dungeons in creative though, not survival, when it starts targetting you it happens.

I can't screenshot it because it doesn't look like nothing's wrong.

I'm using ChocolateQuestRepoured-1.12.2-1.14.0A.jar and forge-1.12.2-14.23.5.2847. Also using Minecraft version 1.12.2

This is the last log from last night, when it happened.
[2020-04-17-7.log.gz](https://github.com/TeamChocoQuest/ChocolateQuestRepoured/files/4492370/2020-04-17-7.log.gz)
There isn't any crash reports tho.
As I said before, I'm on a multiplayer forge server with 4 people.
My mod list: 
Surge-1.12.2-2.0.79
mtqfix-1.12.2-1.1.0
OpenTerrainGenerator-1.12.2+-+v8.3
Biome_Bundle-1.12.2-v6.1
CustomStartingGear-1.12-1.2.0.9-universal
AttributeFix-1.12.2-1.0.4
llibrary-1.7.19-1.12.2
MorePlayerModels_1.12.2-(05Dec19)
lycanitesmobs-1.12.2-2.0.6.6
[1.12.2]DamageIndicatorsMod-3.5.1
ChocolateQuestRepoured-1.12.2-1.14.0A
luckyblock-1.12.2-7.6.0
CreativePlus+MC1.12.2+v1.0.2
Varied-Commodities-Mod-1.12.2 
worldedit-forge-mc1.12.2-6.1.10-SNAPSHOT-dist
mclib-1.0.3-1.12.2
subcommonlib-sublib-1.12.2-1.2.0.4
Armourers-Workshop-1.12.2-0.49.1
CustomMobSpawner-3.11.4
DrZharks MoCreatures Mod-12.0.5
CustomNPCs_1.12.2-(01Oct19)
MCA-1.12.2-6.0.1-universal 
RadixCore-1.12.x-2.2.1-universal
So+Many+Enchantments+V0.4.2
Infinity-0.13.2
Metallurgy-4-Reforged-0.2.0

Hope you find what is wrong, thanks!

**Comment by DerToaster98** [comment]
use. the. issue. template. please

**Comment by DerToaster98** [comment]
Also we need a crash report AND the log file. you only provide the log file, to actually see what caused the crash we need the crash report

**Comment by Darkleckk** [comment]
There isnt any crash report, that's the problem, and sorry about the template, I thought I should replace my issues there.

**Comment by Darkleckk** [comment]
Do I reupload it with the template?

**Comment by DerToaster98** [comment]
no but remember it for the fututre please

**Comment by Darkleckk** [comment]
Okay, sorry.

**Comment by DerToaster98** [comment]
on the crash cause: 
Please try the following: remove every mod that isnt cqr itself or one of its dependencies. also delete the world on the server (or rename it) and try to cause the crash again (also remove all other mods on the client). if it doesnt crash it isnt a bug on our side, then you re-add one mod at a time and try to reproduce the crash until you found the mod that causes the crash

**Comment by Darkleckk** [comment]
Alright I'll try doing that, I'll tell you if something happens.

**Comment by Meldexun** [comment]
It's more efficient to remove the half of the mods and then test it. Then again remove half of the mods and so on.
And can you test it again and send the latest.log file from the server and from the client (and the crash report from the server and the client if one exists). Because in that log file it just says that it loaded the world and then you connected and disconnected two times.

**Comment by Darkleckk** [comment]
Alright I'll check and let's see if I can get a crash report.

**Comment by DerToaster98** [comment]
Also can you verify that this is the case with *every* cqr entity? Or is it just a specific one?

**Comment by Darkleckk** [comment]
It looks like it happens with all entities.

**Comment by DerToaster98** [comment]
Thats not a verification

**Comment by Darkleckk** [comment]
I mean, I tested with Minotaurs, Boarmans, Gremlins, Dwarfs, Skeletons, Zombies, Mandrils, Abyss walkers and pirates and does the same, server freezes, everyone disconnects from the server, and you cannot log in anymore until I reset the server.

**Comment by Darkleckk** [comment]
Should I try with all of them?

**Comment by DerToaster98** [comment]
thats not every entity, can you verify it with bosses too?

And what *exactly* do you do? Just look at them and they do nothing? 
What do you do and what does the entity do before it "crashes"?

**Comment by Darkleckk** [comment]
Alright, I'll try with bosses, and what I do is, I spawn them in creative, I can hit them, move them, but, when I go into survival it does something similar like excesive lag, you cannot drop items, you can't hit entities, you don't receive drops from blocks, you don't have fall damage, you can't use commands, etc.

**Comment by DerToaster98** [comment]
does it react to you in any way before that? I mean does *the entity* do something like looking at you, stand up, etc.?

**Comment by Darkleckk** [comment]
It stands up, yeah, like he targets me and proceeds to try and attack me I guess, but when he stands up it's where it stops

**Comment by Darkleckk** [comment]
I just tried without any mods, only CQR, spawned some enemies and it worked, spawned a Lich and served closed.

**Comment by Darkleckk** [comment]
[crash-2020-04-17_12.33.21-server.txt](https://github.com/TeamChocoQuest/ChocolateQuestRepoured/files/4492631/crash-2020-04-17_12.33.21-server.txt)

**Comment by DerToaster98** [comment]
ok. but then the original problem is caused by a different mod. lich issue will be worked on

**Comment by Darkleckk** [comment]
I guess, now I'll try to find which mod does it, thanks anyway.

**Comment by DerToaster98** [comment]
on that lich thing: could you also upload a log file too? as i said we need both, crash report and log file (latest.log)

**Comment by Darkleckk** [comment]
[2020-04-17-6.log.gz](https://github.com/TeamChocoQuest/ChocolateQuestRepoured/files/4492675/2020-04-17-6.log.gz)

**Comment by Darkleckk** [comment]
Ok, I think I found the issue, turns up that is something from CQR I think. You see, when I spawn an entity and go survival (Only with CQR) it freezed for 2 seconds then the entity started going after me. When I'm adding mods, that ``freeze´´ is higher, to the point it just times the player out of the server, so when I did with all my 36 mods and went into a dungeon with like 9 or 10 entities in a room, server couldn't handle it. I don't know if that is supposed to happen or is it just a server issue.

**Comment by Meldexun** [comment]
Could you also test the necromancer and walker king?

**Comment by Darkleckk** [comment]
Yeah sure.

**Comment by Darkleckk** [comment]
So turns up it doesn't happen with bosses, necromancer and walker king summon and beat up eachother without problems. Maybe it's a problem when the entity is sitting and stands up?

**Comment by Darkleckk** [comment]
Yeah, I think it is indeed that, I tested with some pirates and waited them to sit up right next to the bosses who were fighting, when I went survival and they stood up the ``freeze´´ happened.

**Comment by Meldexun** [comment]
Ok, so to be sure could you remove all mods except CQR and LLibrary and create a super flat world with your server. But with dungeonsInFlat disabled in the CQR config (is disabled by default) and also "/gamerule doMobSpawning false". Then summon only one kind of CQR mob and go into survival.
Because in a normal world the problem could also be another mob which is maybe in a dungeon that is 100 blocks away.

**Comment by Darkleckk** [comment]
Alright, I'll try it

**Comment by Darkleckk** [comment]
Yeah it still does that ``freeze´´ thing

**Comment by DerToaster98** [comment]
How much resources did you give to the server?

**Comment by Darkleckk** [comment]
You mean RAM?

**Comment by DerToaster98** [comment]
Not only

**Comment by Darkleckk** [comment]
What do you mean then?

**Comment by DerToaster98** [comment]
Disc space, memory/ram, cpu (clockrate and core count)

**Comment by Darkleckk** [comment]
But, I don't have any kind of lag problems in my server, it only does that with CQR entities though, does CQR require a lot?

**Comment by Darkleckk** [comment]
It has enough disc space, 2 GB of RAM and all my CPU cores for it, I don't know about clock rate or giving it to the server

**Comment by Meldexun** [comment]
Hm... So when you followed my last instructions (flat land world with no dungeons or other CQR mobs) your hardware shouldn't be a problem (when you have a decent cpu). How many entities did you spawn? And is it only happening when they try to fight you/a player or also when for example a cqr illager fights a cqr golem?

**Comment by Meldexun** [comment]
So maybe it helps when you upload a debug log file. But currently we are not able to reproduce this. And because it just freezes without any error occuring it just looks like a performance problem.

**Comment by DerToaster98** [comment]
Since there hasn't be any activity on this for the life time period of two builds this will be closed
