### ISSUE TITLE
Cursed Bone Causes Crash

### ISSUE THREAD

**Issue by Kyyrick** [TeamChocoQuest/ChocolateQuestRepoured#178]
I saw there was already an open bug for this but I figure more data helps. 

**Describe the bug**
Using the Cursed Bone item causes a crash quickly after use. 

**To Reproduce**
1. Get the Cursed Bone (creative or from mob drop, there is no difference).
2. Use the cursed bone summoning effect (hold right click).
3. See error

**Expected behavior**
I believe the cursed bone is supposed to summon an ally skeleton mob like in better dungeons.

**Screenshots**
Using: ![Bone Bug 1](https://user-images.githubusercontent.com/63609475/80039125-168d3c80-84c5-11ea-86ed-8191dc1d1b7c.png)

After Use: ![Bone bug 2](https://user-images.githubusercontent.com/63609475/80039168-2d339380-84c5-11ea-8663-996f520f4613.png)

**Versions**
Chocolate Quest Repoured: 1.12.2-1.15.1A.jar (Alpha 21.1)
Forge: 1.12.2-14.23.5.2847
Minecraft: 1.12.2

**Other**
Crash report: 
[2020-04-22-4.log](https://github.com/TeamChocoQuest/ChocolateQuestRepoured/files/4519288/2020-04-22-4.log)
[crash-2020-04-22_18.12.43-server.txt]

Log file: (https://github.com/TeamChocoQuest/ChocolateQuestRepoured/files/4519279/crash-2020-04-22_18.12.43-server.txt)
Singleplayer/Multiplayer: Tested on singleplayer only. 
Other mods (that are necessary to produce the bug): llibrary (llibrary-core-1.0.11-1.12.2.jar)
Other mods (that are also installed): llibrary (llibrary-core-1.0.11-1.12.2.jar)

**Comment by DerToaster98** [comment]
1) That's not the crash report, it's the startup log. The log file you provide actually is the crash report, those are different things!
2) This is not related to the other cursed bone crashes (you would know this if you could read crash reports, which we don't expect) so it is good that you reported it
3) It will be fixed in the next update

**Comment by DerToaster98** [comment]
should be fixed in newest build
