### ISSUE TITLE
Daggers have too low attack speed and correspondingly to high damage

### ISSUE THREAD

**Issue by TheFunnyFace** [TeamChocoQuest/ChocolateQuestRepoured#18]
All the existing daggers have an atack speed of 1.6, which is the same like swords. Spmething like 2.5 would eventually work better.
By changin that the damage should be reworked as well. A monking dagger with e.g. 2.5 speed and then 7 damage is way to overpowered.

**Comment by LordEpos** [comment]
Dragon helmet + monking dagger in the current build can one-shot a zombie with a backstab.
