### ISSUE TITLE
Server Crash when fighting mobs

### ISSUE THREAD

**Issue by NotJoosh** [TeamChocoQuest/ChocolateQuestRepoured#181]
**Describe the bug**
Server crash upon fighting Illagers (this has happened before but with mummies)

**To Reproduce**
Not sure how exactly to describe this since it doesn't happen every time I go into a dungeon. (in this case, I entered the Giant Turtle dungeon)

**Expected behavior**
**Screenshots**

**Versions**
Chocolate Quest Repoured: 1.12.2-1.15.1A
Forge: 1.12.2-14.23.5.2847-universal
Minecraft: 1.12.2

**Other**
Crash report:
[crash-2020-04-23_22.37.02-server.txt](https://github.com/TeamChocoQuest/ChocolateQuestRepoured/files/4526391/crash-2020-04-23_22.37.02-server.txt)

Log file:
[2020-04-23-7.log](https://github.com/TeamChocoQuest/ChocolateQuestRepoured/files/4526389/2020-04-23-7.log)

Singleplayer/Multiplayer: Multiplayer 
Other mods (that are necessary to produce the bug):
Other mods (that are also installed): Can be viewed in the log file

**Comment by DerToaster98** [comment]
Please use the latest CQR version, it can be downloaded here on the github, on curseforge or on our discord server.

This bug has been already patched in the latest version
