### ISSUE TITLE
Still crashing with the walker king

### ISSUE THREAD

**Issue by Yranic** [TeamChocoQuest/ChocolateQuestRepoured#183]
even though its supposed to be fixed it still crashes

**Versions**
Chocolate Quest Repoured:ChocolateQuestRepoured-1.12.2-1.15.2A
Forge:forge-14.23.5.2847
Minecraft:1.12.2

**Other**
Crash report:
[crash-2020-04-24_16.54.00-server.txt](https://github.com/TeamChocoQuest/ChocolateQuestRepoured/files/4529662/crash-2020-04-24_16.54.00-server.txt)
Log file:
[latest.log](https://github.com/TeamChocoQuest/ChocolateQuestRepoured/files/4529684/latest.log)

Singleplayer

Other mods (that are also installed):
Baubles-1.12-1.5.2.jar
BetterFps-1.4.8.jar
ChocolateQuestRepoured-1.12.2-1.15.2A.jar
CTM-MC1.12.2-1.0.2.31.jar
[1.12.2]DamageIndicatorsMod-3.5.1.jar
foamfix-0.10.10-1.12.2.jar
iceandfire-1.9.0.jar
InventoryTweaks-1.63.jar
jei_1.12.2-4.15.0.291.jar
llibrary-1.7.19-1.12.2.jar
malisiscore-1.12.2-6.5.1.jar
malisisdoors-1.12.2-7.3.0.jar
Mapmaker's Gadgets-1.2_for_1.12.x.jar
MobBattleMod-1.12.2-2.3.3.jar
mowziesmobs-1.5.4.jar
MutantBeasts-1.12.2-0.7.1.jar
Welcome To The Jungle-1.2006.1222.jar
worldedit-forge-mc1.12.2-6.1.10-SNAPSHOT-dist.jar
OptiFine_1.12.2_HD_U_F5

**Comment by DerToaster98** [comment]
Still that has NOTHING TO DO WITH THE WALKER KING!

If you ACTUALLY READ the crash log you would see that

**Comment by DerToaster98** [comment]
will be fixed in next build
