### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by tidspessimist** [TeamChocoQuest/ChocolateQuestRepoured#185]
Game crashes when trying to start it, even while not having any other mods. Not sure what the problem is at all. 
[crash-2020-04-26_16.33.25-client.txt](https://github.com/TeamChocoQuest/ChocolateQuestRepoured/files/4535510/crash-2020-04-26_16.33.25-client.txt)

**Comment by DerToaster98** [comment]
Next time plase use the issue template. this is invalid and CANT be worked with

The problem is that your forge version is too old. You use 2816, cqr requires forge 2847
