### ISSUE TITLE
Volcano crashing world

### ISSUE THREAD

**Issue by ZcanKal** [TeamChocoQuest/ChocolateQuestRepoured#186]
**Describe the bug**
A volcano generated in my world in an Extreme hills biome, and reached the height limit, so while it was generating, it crashed my world trying to build over the height limit, I assume.

**To Reproduce**
1. Go near the top of the skybox
2. Generate a volcano

**Versions**
Chocolate Quest Repoured: Alpha 21.1
Forge: Forge 1.12.2-14.23.5.2847
Minecraft: 1.12.2

**Other**
Log file:
[crash-2020-04-26_12.49.22-server.txt](https://github.com/TeamChocoQuest/ChocolateQuestRepoured/files/4536366/crash-2020-04-26_12.49.22-server.txt)

Singleplayer/Multiplayer: Singleplayer
Other mods (that are necessary to produce the bug):
Other mods (that are also installed): too many.  I'm not listing all 250~ other mods.

**Comment by DerToaster98** [comment]
bug should be fixed in the latest version. please download that and try to reproduce the bug on a new world
