### ISSUE TITLE
[Suggestion] Config to prevent Dungeons near worldspawn

### ISSUE THREAD

**Issue by Freebi85** [TeamChocoQuest/ChocolateQuestRepoured#187]
Hello =)
As the title suggests, it would be great to have a config that wouldn't allow the spawn of all the dungeons near the worldspawn. Very useful for very specific modpacks :P 

Cheers, Freebi

**Comment by DerToaster98** [comment]
That already exists. read the wiki, it is explained there.

**Comment by Freebi85** [comment]
Mybad, didn't see the main config file. I'm sorry for the circumstances
