### ISSUE TITLE
Longshot and Hookshot dont work on server

### ISSUE THREAD

**Issue by zEpiixz** [TeamChocoQuest/ChocolateQuestRepoured#190]
**Describe the bug**
Hookshot and longshot dont drag the player on server but in singleplayer it works.
**To Reproduce**
2. Use item '....'
3. Place block '....'
.Use them on a server
.
.

**Expected behavior**
You get dragged
**Screenshots**

**Versions**
Chocolate Quest Repoured:Alpha 23
Forge:Latest
Minecraft:1.12.2

**Other**
Crash report:
Log file:
Singleplayer/Multiplayer:Multiplayer
Other mods (that are necessary to produce the bug):
Other mods (that are also installed):

**Comment by DerToaster98** [comment]
Please fill out the issue template correctly, the "non-fat" text is a explanation of what you should write there instead of that explanation text

**Comment by DerToaster98** [comment]
Also "Latest" as forge version is NOT acceptable
