### ISSUE TITLE
Incompatibility with spongeForge / NPE on world unload

### ISSUE THREAD

**Issue by Zytheus** [TeamChocoQuest/ChocolateQuestRepoured#192]
**Common sense Info**
 - I play...
   - [x] With a large modpack
   - [ ] Only with CQR and it's dependencies
 - The issue occurs in...
   - [ ] Singleplayer
   - [X] Multiplayer
 - [X] I have searched for this or a similar issue before reporting and it was not previously reported.

 - [X] I am using the latest version of the mod (all versions can be found on github under releases)
 - [ ] I reproduced the bug without any other mod's except forge, cqr and it's dependencies 
        (I should probably do this huh?)
 - [ ] The game crashes because of this bug
 
 
 **Versions**
Chocolate Quest Repoured: Alpha 23
Forge: SpongeForge 7.2.2 RC4024 (Forge 14.23.5.2838)
Minecraft: 1.12.2

**Describe the bug**
Upon unloading a dimension, the error is thrown. I'm not sure what it affects in the slightest. I don't see any actual problem with the server. I don't know if it's harmful or harmless. That's what I'm here to find out.

debug.log attached since not everyone likes truncated logs.

**To Reproduce**
Save world.

**Expected behavior**
Nothing. Just save the world.

**Screenshots**

Truncated log - https://hastebin.com/renoqulexi.rb
debug.log below.

**Other**
Crash report: None.
Log file:
[debug.log](https://github.com/TeamChocoQuest/ChocolateQuestRepoured/files/4618018/debug.log)

Multiplayer Server.
Other mods (that are necessary to produce the bug): SpongeForge
Other mods (that are also installed): In Log

**Comment by DerToaster98** [comment]
We don't officially support spongeforge.

Can you replicate that exact bug with normal forge too?

**Comment by DerToaster98** [comment]
Also please update spongeforge to use minecraftforge 2847, you use an older version (2838)
![grafik](https://user-images.githubusercontent.com/38782719/81739661-03560700-949c-11ea-96bd-793e755eac7c.png)

**Comment by DerToaster98** [comment]
To answer if that causes serious problems: Basically it causes only one problem, that is the actual saving of protection region data, if you don't care about this you are fine. Also that bug should be thrown on every world save event.

**Comment by DerToaster98** [comment]
Ok, to make sure that this is not an incompatbility with sponge forge please do the following:
Try replicating this bug with forge instead of spongeforge

**Comment by Zytheus** [comment]
It's definitely an incompatibility with SpongeForge.

Unfortunately I cannot update the forge version as long as I use SpongeForge as SpongeForge only functions on 2838 as of now.

Personally don't care about the error too much as it isnt affecting anything I'm worried about. No lag spikes (other than the world save). No missing data. It's all fine. 

I didn't notice that CQR was built for 2847. Would make sense since a lot of mods are nowadays. It IS the recommended build after all. That's a likely root for the problem as I had to remove other mods with similar dependencies. 

I'm at work right now. I can't do any replication as of right now, but your answer about whether it causes serious problems is enough for me. I'll post back here if I get the chance to replicate under the conditions that: 

a) Forge + SpongeForge installed + CQR - OtherMods
b) Forge + CQR - OtherMods
c) Forge + CQR + OtherMods

**Comment by DerToaster98** [comment]
Could you re-upload that error log please? Can't access it. Also what were the results of the tests?

**Comment by DerToaster98** [comment]
Bug in faction system with player login will be fixed in next release.

As i did not receive feedback on the world saving thing: Can i have feedback on it regarding the points in the posts above?

**Comment by Rongmario** [comment]
I believe this also happens in vanilla forge with TerraFirmaCraft installed. https://pastebin.com/E704jPK2

**Comment by DerToaster98** [comment]
Issue will be closed cause the issue reporter seems to be unwilling to cooperate, without cooperation we can't solve this issue.

Also this should be fixed in the latest release
