### ISSUE TITLE
Cqr update does not crash single player but for some reason crashes the server

### ISSUE THREAD

**Issue by blitzinfinity** [TeamChocoQuest/ChocolateQuestRepoured#193]
**Common sense Info**
 - I play...
   - [ ✅] With a large modpack
   - [ ] Only with CQR and it's dependencies
 - The issue occurs in...
   - [ ] Singleplayer
   - [ ✅] Multiplayer
 - [ ✅] I have searched for this or a similar issue before reporting and it was either (1) not previously reported, or (2) previously fixed  and I'm having the same problem.
 - [ ✅] I am using the latest version of the mod (all versions can be found on github under releases)
 - [ ] I reproduced the bug without any other mod's except forge, cqr and it's dependencies
 - [✅ ] The game crashes because of this bug
 
 
 **Versions**
Chocolate Quest Repoured:
Forge:
Minecraft:

**Describe the bug**

**To Reproduce**
2. Use item '....'
3. Place block '....'
.
.
.

**Expected behavior**

**Screenshots**

**Other**
Crash report:
Log file:
Singleplayer/Multiplayer:
Other mods (that are necessary to produce the bug):
Other mods (that are also installed):

On Wed, May 20, 2020 at 1:17 AM Matoo, Kayan I <kmatoo@albany.edu> wrote:
---- Minecraft Crash Report ----
// On the bright side, I bought you a teddy bear!

Time: 2020-05-20 01:02:57 EDT
Description: Exception in server tick loop

java.lang.NoClassDefFoundError: net/minecraft/client/model/ModelBiped
    at com.teamcqr.chocolatequestrepoured.init.ModItems$ItemRegistrationHandler.registerItems(ModItems.java:336)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_312_ItemRegistrationHandler_registerItems_Register.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:850)
    at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:630)
    at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:99)
    at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:333)
    at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:125)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
    at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.model.ModelBiped
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
    ... 12 more
Caused by: java.lang.NullPointerException

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Linux (amd64) version 3.10.0-957.12.2.el7.x86_64
  Java Version: 1.8.0_252, Oracle Corporation
  Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 5441523752 bytes (5189 MB) / 6372720640 bytes (6077 MB) up to 6372720640 bytes (6077 MB)
  JVM Flags: 4 total; -Xmx6144M -Xms6144M -XX:+UseConcMarkSweepGC -XX:+CMSClassUnloadingEnabled
  IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
  FML: MCP 9.42 Powered by Forge 14.23.5.2847 124 mods loaded, 124 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State | ID                          | Version                 | Source                                              | Signature                                |
       |:----- |:--------------------------- |:----------------------- |:--------------------------------------------------- |:---------------------------------------- |
       | LCH   | minecraft                   | 1.12.2                  | minecraft.jar                                       | None                                     |
       | LCH   | mcp                         | 9.42                    | minecraft.jar                                       | None                                     |
       | LCH   | FML                         | 8.0.99.99               | forge1122.jar                                       | None                                     |
       | LCH   | forge                       | 14.23.5.2847            | forge1122.jar                                       | None                                     |
       | LCH   | ivtoolkit                   | 1.3.3-1.12              | minecraft.jar                                       | None                                     |
       | LCH   | foamfixcore                 | 7.7.4                   | minecraft.jar                                       | None                                     |
       | LCH   | srm-hooks                   | 1.12.2-1.0.0            | minecraft.jar                                       | None                                     |
       | LCH   | damageindicatorsmod         | 1.0                     | [1.12.2]DamageIndicatorsMod-3.5.1.jar               | None                                     |
       | LCH   | bspkrscore                  | 7.6.0.1                 | [1.12]bspkrsCore-universal-7.6.0.1 (1).jar          | None                                     |
       | LCH   | treecapitator               | 1.43.0                  | [1.12]TreeCapitator-client-1.43.0 (1).jar           | None                                     |
       | LCH   | jei                         | 4.15.0.291              | jei_1.12.2-4.15.0.291.jar                           | None                                     |
       | LCH   | abyssalcraft                | 1.9.19                  | AbyssalCraft-1.12.2-1.9.19.jar                      | 220f10d3a93b3ff5fbaa7434cc629d863d6751b9 |
       | LCH   | advanced-fishing            | 1.3.3                   | Advanced-Fishing-1.12.2-1.3.3.jar                   | None                                     |
       | LCH   | aether_legacy               | 1.4.4                   | aether_legacy-1.12.2-v1.4.4.jar                     | None                                     |
       | LCH   | alcatrazcore                | 1.0.4                   | alcatrazcore-1.0.4.jar                              | 3c2d6be715971d1ed58a028cdb3fae72987fc934 |
       | LCH   | animcolle                   | 1.0.0b3                 | AnimColle+Legacy+1.0.0+patch+7+Official+Release.jar | None                                     |
       | LCH   | tammodized                  | 0.15.6                  | TamModized-1.12.2-0.15.6.jar                        | None                                     |
       | LCH   | aov                         | 0.11.7                  | AoV-1.12-0.11.7.jar                                 | None                                     |
       | LCH   | ebwizardry                  | 4.2.11                  | ElectroblobsWizardry-4.2.11-MC1.12.2.jar            | None                                     |
       | LCH   | arcane_essentials           | 1.0                     | Arcane+Essentials-1.0.0-alpha-6.jar                 | None                                     |
       | LCH   | carrots                     | 1.0.0b1                 | carrotslib-mc1.12.2-1.0.0b1.jar                     | None                                     |
       | LCH   | armorunder                  | 1.0.0                   | armorunder-mc1.12.2-1.0.0.jar                       | None                                     |
       | LCH   | quark                       | r1.6-178                | Quark-r1.6-178.jar                                  | None                                     |
       | LCH   | autoreglib                  | 1.3-32                  | AutoRegLib-1.3-32 (1).jar                           | None                                     |
       | LCH   | gorecore                    | 1.12.2-0.4.5            | avatarmod-1.5.17-alpha.jar                          | None                                     |
       | LCH   | avatarmod                   | 1.5.17-alpha            | avatarmod-1.5.17-alpha.jar                          | None                                     |
       | LCH   | baubles                     | 1.5.2                   | Baubles-1.12-1.5.2 (3).jar                          | None                                     |
       | LCH   | mujmajnkraftsbettersurvival | 1.4.1                   | better_survival-1.4.1.jar                           | None                                     |
       | LCH   | bettercombatmod             | 1.5.6                   | BetterCombat-1.12.2-1.5.6.jar                       | None                                     |
       | LCH   | bloodmoon                   | 1.5.3                   | Bloodmoon-MC1.12.2-1.5.3.jar                        | d72e0dd57935b3e9476212aea0c0df352dd76291 |
       | LCH   | bookshelf                   | 2.3.590                 | Bookshelf-1.12.2-2.3.590.jar                        | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCH   | thaumcraft                  | 6.1.BETA26              | Thaumcraft-1.12.2-6.1.BETA26 (2).jar                | None                                     |
       | LCH   | botania                     | r1.10-363               | Botania+r1.10-363.jar                               | None                                     |
       | LCH   | chesttransporter            | 2.8.8                   | ChestTransporter-1.12.2-2.8.8.jar                   | None                                     |
       | LCH   | llibrary                    | 1.7.19                  | llibrary-1.7.19-1.12.2 (2).jar                      | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
       | LCH   | cqrepoured                  | 1.18.0A                 | ChocolateQuestRepoured-1.12.2-1.18.0A (1).jar       | None                                     |
       | LCH   | clumps                      | 3.1.2                   | Clumps-3.1.2 (1).jar                                | None                                     |
       | LCH   | redstoneflux                | 2.1.1                   | RedstoneFlux-1.12-2.1.1.1-universal.jar             | None                                     |
       | LCH   | cofhcore                    | 4.6.6                   | CoFHCore-1.12.2-4.6.6.1-universal.jar               | None                                     |
       | LCH   | coherentvillages            | v0.0.5.10               | coherent_villages-pre-release_v0.0.5.10.jar         | None                                     |
       | LCH   | coralreef                   | 2.0                     | CoralReef-2.5-1.12.2.jar                            | None                                     |
       | LCH   | dawnoftimebuilder           | 1.0.5                   | dawnoftime_builder_edition-1.0.5.jar                | None                                     |
       | LCH   | disenchanter                | 1.6                     | disenchanter-[1.12]1.6.jar                          | None                                     |
       | LCH   | dldungeonsjbg               | 1.12.10                 | DoomlikeDungeons-1.12.10-MC1.12.2.jar               | None                                     |
       | LCH   | enchanting_tweaks           | 1.2.1                   | enchanting_tweaks-1.2.1.jar                         | None                                     |
       | LCH   | eplus                       | 5.0.176                 | EnchantingPlus-1.12.2-5.0.176 (2).jar               | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCH   | endreborn                   | 0.3.7                   | EndReborn+III+[0.3.7].jar                           | None                                     |
       | LCH   | ezstorage                   | 2.5.0                   | ezstorage-2.5.0-[1.12.2].jar                        | None                                     |
       | LCH   | farseek                     | 2.5                     | Farseek-1.12-2.5.jar                                | None                                     |
       | LCH   | firstaid                    | 1.6.13                  | firstaid-1.6.14.jar                                 | 7904c4e13947c8a616c5f39b26bdeba796500722 |
       | LCH   | mod_lavacow                 | 1.0.13                  | Fishs_Undead_Rising-1.0.13 (1).jar                  | None                                     |
       | LCH   | foamfix                     | 0.10.9-1.12.2           | foamfix-0.10.9-1.12.2.jar                           | None                                     |
       | LCH   | forgelin                    | 1.8.4                   | Forgelin-1.8.4.jar                                  | None                                     |
       | LCH   | gargoyles                   | 1                       | Gargoyles+mod+1.12.2+patch+1.jar                    | None                                     |
       | LCH   | globalgamerules             | 2.2                     | GlobalGameRules-1.12.2-2.2.7.jar                    | None                                     |
       | LCH   | grimoireofgaia              | 1.7.2                   | GrimoireOfGaia3-1.12.2-1.7.2.jar                    | None                                     |
       | LCH   | herobrinemod                | 0.5.0                   | herobrinemod-0.5.0.jar                              | None                                     |
       | LCH   | waila                       | 1.8.26                  | Hwyla-1.8.26-B41_1.12.2.jar                         | None                                     |
       | LCH   | iceandfire                  | 1.9.1                   | iceandfire-1.9.1-1.12.2.jar                         | None                                     |
       | LCH   | ichunutil                   | 7.2.2                   | iChunUtil-1.12.2-7.2.2 (1).jar                      | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
       | LCH   | infernalmobs                | 1.7.6                   | InfernalMobs-1.12.2.jar                             | None                                     |
       | LCH   | inventorytweaks             | 1.64+dev.146.2180b27    | InventoryTweaks-1.64+dev.146.jar                    | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
       | LCH   | journeymap                  | 1.12.2-5.5.6            | journeymap-1.12.2-5.5.6.jar                         | None                                     |
       | LCH   | kineticclearlag             | 1.4                     | Kinetic+Clear+LagV1.4.jar                           | None                                     |
       | LCH   | levelup2                    | ${version}              | Level Up! 2-1.1.23-1.12.jar                         | None                                     |
       | LCH   | librarianlib                | 4.20                    | librarianlib-1.12.2-4.20-release.jar                | None                                     |
       | LCH   | libraryex                   | 1.1.2                   | LibraryEx-1.12.2-1.1.2.jar                          | None                                     |
       | LCH   | mahoutsukai                 | 1.12.2-v1.17.4          | mahoutsukai-1.12.2-v1.17.4.jar                      | None                                     |
       | LCH   | malisiscore                 | 1.12.2-6.5.1-SNAPSHOT   | malisiscore-1.12.2-6.5.1.jar                        | None                                     |
       | LCH   | malisisdoors                | 1.12.2-7.3.0            | malisisdoors-1.12.2-7.3.0.jar                       | None                                     |
       | LCH   | megaloot                    | 0.2.30                  | megaloot-1.12.2-0.2.30.jar                          | None                                     |
       | LCH   | mightyenderchicken          | 7.3.0                   | MightyEnderChicken-1.12.2-7.3.0.jar                 | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
       | LCH   | mobends                     | 0.24                    | mobends-0.24_for_MC-1.12.jar                        | None                                     |
       | LCH   | mowziesmobs                 | 1.5.4                   | mowziesmobs-1.5.4.jar                               | None                                     |
       | LCH   | shetiphiancore              | 3.5.9                   | shetiphiancore-1.12.0-3.5.9.jar                     | None                                     |
       | LCH   | multistorage                | 1.4.14                  | multistorage-1.12.0-1.4.14.jar                      | None                                     |
       | LCH   | mutantbeasts                | 1.12.2-0.7.2            | MutantBeasts-1.12.2-0.7.2.jar                       | 25e0dcff5b5a7325d7c28898af41ff8b0ba41b77 |
       | LCH   | netherex                    | 2.1.5                   | NetherEx-1.12.2-2.1.5.jar                           | None                                     |
       | LCH   | notreepunching              | 2.0.20                  | notreepunching-2.0.20.jar                           | 3c2d6be715971d1ed58a028cdb3fae72987fc934 |
       | LCH   | patchouli                   | 1.0-20                  | Patchouli-1.0-20 (2).jar                            | None                                     |
       | LCH   | presentstand                | r-1.1                   | presentstand-r-1.1 (2).jar                          | None                                     |
       | LCH   | realistictorches            | 2.1.1                   | RealisticTorches-1.12.2-2.1.1.jar                   | None                                     |
       | LCH   | reccomplex                  | 1.4.8.2                 | RecurrentComplex-1.4.8.2.jar                        | None                                     |
       | LCH   | roguelike                   | 1.8.0                   | RoguelikeDungeons-1.12.2-1.8.0.jar                  | None                                     |
       | LCH   | roughtweaks                 | 1.0                     | roughTweaks0.2.4-1.12.2.jar                         | None                                     |
       | LCH   | ruins                       | 17.2                    | Ruins-1.12.2.jar                                    | None                                     |
       | LCH   | secretroomsmod              | 5.6.4                   | secretroomsmod-1.12.2-5.6.4.jar                     | None                                     |
       | LCH   | t3s4ebw                     | 1.0                     | SeedsForWizardry+1.0+For+MC+Forge+1.12.2 (1).jar    | None                                     |
       | LCH   | silentlib                   | 3.0.13                  | SilentLib-1.12.2-3.0.13+167.jar                     | None                                     |
       | LCH   | somanyenchantments          | 0.4.4                   | So+Many+Enchantments+V0.4.4.jar                     | None                                     |
       | LCH   | spartanweaponry             | beta 1.3.8              | SpartanWeaponry-1.12.2-beta-1.3.8.jar               | None                                     |
       | LCH   | spartanfire                 | 0.08                    | spartanfire-0.08.jar                                | None                                     |
       | LCH   | spartanshields              | 1.5.4                   | SpartanShields-1.12.2-1.5.4.jar                     | None                                     |
       | LCH   | spartanweaponryarcana       | beta 1.0.3              | SpartanWeaponryArcana-1.12.2-beta-1.0.3.jar         | None                                     |
       | LCH   | streams                     | 0.4.8                   | Streams-1.12-0.4.8.jar                              | None                                     |
       | LCH   | surge                       | 2.0.77                  | Surge-1.12.2-2.0.77.jar                             | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCH   | twilightforest              | 3.10.1013               | twilightforest-1.12.2-3.10.1013-universal.jar       | None                                     |
       | LCH   | tfspellpack                 | 1.0.1                   | TFSpellPack-1.0.1-MC1.12.2.jar                      | None                                     |
       | LCH   | theeightfabledblades        | 1.0.0                   | TheEightFabledBlades+V2.0.01.jar                    | None                                     |
       | LCH   | toolbelt                    | 1.9.12                  | ToolBelt-1.12.2-1.9.12.jar                          | None                                     |
       | LCH   | tc                          | 1.1                     | ToolsCombine[1.12.2].jar                            | None                                     |
       | LCH   | toughasnails                | 3.1.0.141               | ToughAsNails-1.12.2-3.1.0.141-universal.jar         | None                                     |
       | LCH   | travellersbackpack          | 1.0.23.23               | TravellersBackpack-1.12.2-1.0.23.23.jar             | None                                     |
       | LCH   | traverse                    | 1.6.0                   | Traverse-1.12.2-1.6.0-69.jar                        | None                                     |
       | LCH   | xat                         | 0.28.1                  | Trinkets and Baubles-1.12.2-0.28.1.jar              | None                                     |
       | LCH   | trumpetskeleton             | 1.12-1.0.2.1            | trumpetskeleton-1.12-1.0.2.1.jar                    | None                                     |
       | LCH   | uniquee                     | 1.9.0                   | Unique+Enchantments+V1.12.2-1.9.jar                 | None                                     |
       | LCH   | universalbestiary           | 1.3.1                   | universalbestiary-1.12.2-1.3.1.jar                  | None                                     |
       | LCH   | vanillafix                  | 1.0.10-SNAPSHOT         | VanillaFix-1.0.10-99.jar                            | None                                     |
       | LCH   | varodd                      | 5.2                     | varodd-1.12.2-5.2.jar                               | None                                     |
       | LCH   | waystones                   | 4.0.72                  | Waystones_1.12.2-4.0.72.jar                         | None                                     |
       | LCH   | wings                       | 1.1.6                   | wings-1.1.6-1.12.2.jar                              | None                                     |
       | LCH   | mowzies_wings               | 1.0.0                   | wings-1.1.6-1.12.2.jar                              | None                                     |
       | LCH   | bauble_wings                | 1.0.0                   | wings-1.1.6-1.12.2.jar                              | None                                     |
       | LCH   | mobends_wings               | 1.0.0                   | wings-1.1.6-1.12.2.jar                              | None                                     |
       | LCH   | xpfromharvest               | 1.1.0                   | xpfromharvest-1.12.2-1.1.0.jar                      | None                                     |
       | LCH   | xpbook                      | v1.1.4                  | xptome-1.12.2-v1.1.4.jar                            | None                                     |
       | LCH   | craftstudioapi              | 1.0.0                   | CraftStudio-1.0.1.95-mc1.12-alpha.jar               | None                                     |
       | LCH   | cyclopstek                  | 1.0.34                  | cyclopstek-1.0.34.jar                               | None                                     |
       | LCH   | structurize                 | 1.12.2-0.10.277-RELEASE | structurize-1.12.2-0.10.277-RELEASE.jar             | None                                     |
       | LCH   | betteranimalsplus           | 9.0.1                   | betteranimalsplus-1.12.2-9.0.1.jar                  | None                                     |
       | LCH   | minecolonies                | 1.12.2-0.11.804-RELEASE | minecolonies-1.12.2-0.11.804-RELEASE-universal.jar  | None                                     |
       | LCH   | thebetweenlands             | 3.6.0                   | TheBetweenlands-3.6.0-universal.jar                 | 38067d6878811efb38b6a045521cfd80b9b60b38 |
       | LCH   | librarianliblate            | 4.20                    | librarianlib-1.12.2-4.20-release.jar                | None                                     |
  Loaded coremods (and transformers): wings (wings-1.1.6-1.12.2.jar)
                                        me.paulf.wings.server.asm.WingsRuntimePatcher
                                        me.paulf.wings.server.asm.mobends.WingsMoBendsRuntimePatcher
                                      FarseekCoreMod (Farseek-1.12-2.5.jar)
                                        farseek.core.FarseekClassTransformer
                                      Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.9-1.12.2.jar)
                                        pl.asie.foamfix.coremod.FoamFixTransformer
                                      ForgelinPlugin (Forgelin-1.8.4.jar)
                                        
                                      Inventory Tweaks Coremod (InventoryTweaks-1.64+dev.146.jar)
                                        invtweaks.forge.asm.ContainerTransformer
                                      iceandfire (iceandfire-1.9.1-1.12.2.jar)
                                        com.github.alexthe666.iceandfire.patcher.IceAndFireRuntimePatcher
                                      LoadingPlugin (Bloodmoon-MC1.12.2-1.5.3.jar)
                                        lumien.bloodmoon.asm.ClassTransformer
                                      llibrary (llibrary-core-1.0.11-1.12.2.jar)
                                        net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
                                        net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
                                      LibrarianLib Plugin (librarianlib-1.12.2-4.20-release.jar)
                                        com.teamwizardry.librarianlib.asm.LibLibTransformer
                                      Quark Plugin (Quark-r1.6-178.jar)
                                        vazkii.quark.base.asm.ClassTransformer
                                      ShetiPhian-ASM (ShetiPhian-ASM-1.12.0.jar)
                                        shetiphian.asm.ClassTransformer
                                      VanillaFixLoadingPlugin (VanillaFix-1.0.10-99.jar)
                                        
                                      SecretRoomsMod-Core (secretroomsmod-1.12.2-5.6.4.jar)
                                        com.wynprice.secretroomsmod.core.SecretRoomsTransformer
                                      TheBetweenlandsLoadingPlugin (TheBetweenlands-3.6.0-core.jar)
                                        thebetweenlands.core.TheBetweenlandsClassTransformer
                                      MalisisCorePlugin (malisiscore-1.12.2-6.5.1.jar)
                                        
                                      SurgeLoadingPlugin (Surge-1.12.2-2.0.77.jar)
                                        
                                      BetterFoliageLoader (BetterFoliage-MC1.12-2.2.0.jar)
                                        mods.betterfoliage.loader.BetterFoliageTransformer
                                      IvToolkit (IvToolkit-1.3.3-1.12.jar)
                                        
                                      LoadingPlugin (ChunkAnimator-MC1.12-1.2.jar)
                                        lumien.chunkanimator.asm.ClassTransformer
  Suspected Mods: Chocolate Quest Repoured Mod (cqrepoured)
  Profiler Position: N/A (disabled)
  Is Modded: Definitely; Server brand changed to 'fml,forge'
  Type: Dedicated Server (map_server.txt)

**Comment by DerToaster98** [comment]
Invalid

Crash log: Please attach it as a **FILE** and DONT paste it as text, that is barely readable.

Also fill out all the required fields please, not just the checkboxes

**Comment by DerToaster98** [comment]
Also: Have you installed llibrary?

**Comment by blitzinfinity** [comment]
Yes i do have library installed and I will resubmit in the correct format

**Comment by DerToaster98** [comment]
Also: We won't work on this until you made sure that this is a problem with CQR and not another mod in the modpack

**Comment by blitzinfinity** [comment]
Okay no problem

**Comment by DerToaster98** [comment]
Was a mistake on our end, will be patched in next release

**Comment by blitzinfinity** [comment]
I have no clue what you did so fast but the bug was fixed and the server is
running, thank you very much
