### ISSUE TITLE
Cursed Bone crash while in Survival Mode

### ISSUE THREAD

**Issue by crater-git** [TeamChocoQuest/ChocolateQuestRepoured#196]
**Common sense Info**
 - I play...
   - [X] With a large modpack
   - [ ] Only with CQR and it's dependencies
 - The issue occurs in...
   - [X] Singleplayer
   - [ ] Multiplayer
 - [X] I have searched for this or a similar issue before reporting and it was either (1) not previously reported, or (2) previously fixed  and I'm having the same problem.
 - [X] I am using the latest version of the mod (all versions can be found on github under releases)
 - [X] I reproduced the bug without any other mod's except forge, cqr and it's dependencies
 - [X] The game crashes because of this bug **(Note: crashes and forces a relaunch (or rejoin, if VanillaFix is enabled), but does not cause the world to become un-loadable/otherwise corrupted)**
 
*(Note: Untested in multiplayer as of yet. Bug was discovered while using a medium-large modpack in SP, but then I reproduced it multiple times in "vanilla CQR" instances)*
 
 **Versions**
Chocolate Quest Repoured: 1.12.2-1.19.0A.jar / Alpha 25
Forge: 14.23.5.2854
Minecraft: 1.12.2

**Describe the bug**

While in Survival mode, attacking a friendly skeleton summoned by the Cursed Bone results in a crash. The bug doesn't occur in Creative Mode.

This was discovered by accidentally damaging a friendly skeleton with a spell from Electroblob's Wizardry - so I initially believed it was a mod conflict, but the crash report suggested it might solely be a CQR issue.

I then tested on a fresh instance of 1.12.2 with Forge 2854 and **only** LLibrary and CQR loaded, finding that the same crash can be reproduced much more easily just by punching the summoned skeleton.

I'm not sure what kind of damage specifically causes it, but I could consistently reproduce with punching/attacking with a weapon/etc. Didn't test if the same crash occurs from non-player damage.

I did try splash potions of harming briefly which didn't cause a crash, but those also seemed to not affect the skeleton at all. That protection might be intended behavior on your part though, not sure.

As stated above, the EBW magic mod does seem to trigger it with several of its damage spells, but I'm not sure if that's of any note or if it'd require additional fixes for modded damage sources.

**To Reproduce**

1. Install CQR and its dependencies in a clean instance, or in any existing modpack
2. Acquire a Cursed Bone through any means, either from a mob drop or Creative Mode
3. Ensure that you're in Survival Mode before continuing
4. Summon a skelebro on any surface by holding right click until he appears
5. Betray the skelebro's trust by punching him as hard as you can
6. Evil necromancers around the world laugh at you as your game immediately crashes to desktop (or back to main menu, if using VanillaFix)

**Expected behavior**

I didn't mean to damage the friendly skeleton, I swear. But I also hold the *somewhat controversial opinion* that friendly fire shouldn't be punished with a full server/game crash, despite how hilarious that is conceptually.

**Other**

Hopefully I didn't miss any details, but I can provide other stuff if you need me to.

 - Link to Crash report file: https://pastebin.com/9c8MQ7Fq

**Comment by DerToaster98** [comment]
will be fixed in next build

**Comment by DerToaster98** [comment]
is fixed in Alpha 25.1 / 1.19.1A
