### ISSUE TITLE
Pirate Captain Flee Spell Crash on Server

### ISSUE THREAD

**Issue by TheWitherlord** [TeamChocoQuest/ChocolateQuestRepoured#198]
In the pirate hideout you will eventually get to the pirate captain and he does his flee spell, he has a chance to crash the game, in this case, the server entirely.

https://pastebin.com/bYwFfRfX

**Comment by DerToaster98** [comment]
You use the wrong forge version (2854, cqr requires 2847)
Also please use the issue template and fill it out completely and correctly next time
