### ISSUE TITLE
alpha 26 crash server random

### ISSUE THREAD

**Issue by 9229tony** [TeamChocoQuest/ChocolateQuestRepoured#200]
**Common sense Info**
 - I play...
   - [ ] With a large modpack
   - [x] Only with CQR and it's dependencies
 - The issue occurs in...
   - [ ] Singleplayer
   - [x] Multiplayer
 - [x] I have searched for this or a similar issue before reporting and it was either (1) not previously reported, or (2) previously fixed  and I'm having the same problem.
 - [x] I am using the latest version of the mod (all versions can be found on github under releases)
 - [x] I reproduced the bug without any other mod's except forge, cqr and it's dependencies
 - [x] The game crashes because of this bug
 
 
 **Versions**
Chocolate Quest Repoured: Alpha 26
Forge: 14.23.5.2854
Minecraft: 1.12.2

**Describe the bug**
the server crashes randomly

**To Reproduce**
1. Go to 'minecraft 1.12.2'
2. Use item 'tried pirate capitan mob'
3. the game will work for a couple  minutes and then crash'

 - Link to Crash report file:
https://pastebin.com/4ASw0aHF
 - Link to Log file:
https://pastebin.com/uQbeYAK8

**Comment by Meldexun** [comment]
There is an issue template but why didn't you use it?

**Comment by 9229tony** [comment]
sorry for that, i edit the post

**Comment by Meldexun** [comment]
Thank you. Will look into it. Because we have some other things to fix there will probably be a hotfix tomorrow which will probably also fix this.

**Comment by DerToaster98** [comment]
This is not related to the pirate captain, it is related to the fireball AI. will be fixed in next build
