### ISSUE TITLE
[BUG] No Structure spawned

### ISSUE THREAD

**Issue by Geezt435** [TeamChocoQuest/ChocolateQuestRepoured#201]
**Common sense Info**
 - I play...
   - [ x ] With a large mod pack
   - [ ] Only with CQR and it's dependencies
 - The issue occurs in...
   - [ x ] Singleplayer
   - [ ] Multiplayer
 - [ ] I have searched for this or a similar issue before reporting and it was either (1) not previously reported, or (2) previously fixed  and I'm having the same problem.
 - [ x ] I am using the latest version of the mod (all versions can be found on Github under releases)
 - [ ] I reproduced the bug without any other mod's except forge, CQR and it's dependencies
 - [ ] The game crashes because of this bug
 
 
 **Versions**
Chocolate Quest Repoured: 1.20.1A
Forge: 14.23.5.2854
Minecraft: 1.12.2

**Describe the bug**
Only the dirt or the grounds spawns, nothing else than that. I also tried deleting JEID, but also still no structures.

**To Reproduce**
1. Load any world
2. Find any CQR Structure
3. Sees no structures

**Expected behavior**
For the structure to be loaded above the supposed ground with it's modded entities.

**Screenshots**
![2020-06-23_02 04 24](https://user-images.githubusercontent.com/46617557/85320624-ee867d80-b4f5-11ea-85d9-3bfd6f032ade.png)
![2020-06-23_02 04 06](https://user-images.githubusercontent.com/46617557/85320672-01994d80-b4f6-11ea-8552-c2fa7620779c.png)
![2020-06-23_02 03 47](https://user-images.githubusercontent.com/46617557/85320698-0d850f80-b4f6-11ea-81de-bececf916480.png)

**Other**
Please note: log files and crash reports should be uploaded as a FILE and not as a copy-paste of the text of it here. Upload the file to a site like Pastebin or similar and link it here!!
 - Link to Crash report file: - 
 - Link to Log file: https://paste.ubuntu.com/p/zjqyWJfq2T/
 - Other mods (that are necessary to produce the bug): Biome Bundle & OTG, NEID
 - Other mods (that are also installed): https://paste.ubuntu.com/p/7WtyYfpPRs/
 - CQR config folder (link, only if you changed the configs):   
 - Other mod's configs (link): Not changed |

**Comment by DerToaster98** [comment]
did you have update the mod and did not follow the update instructions?

If yes: just delete the CQR folder and restart the game, that will fix the issue

**Comment by DerToaster98** [comment]
also please use forge 2847 (you use 2854) as CQR depends on that

**Comment by DerToaster98** [comment]
also that log file is only a very small part of the startup log, we need the full log.

Side note: we are only able to help you if you cooperate and answer our questions

**Comment by Geezt435** [comment]
Nevermind, I found the issue, I have an old custom config for CQR, so in conclusion,
Solution: Exit Minecraft, then delete CQR Config Folder, then relaunch Minecraft again, BOOM! The structure spawned in a surely but slowly way.

Screenshots of after fix
![2020-06-23_02 19 12](https://user-images.githubusercontent.com/46617557/85322377-d5330080-b4f8-11ea-9d79-3e671aff1e6b.png)
:
Also the loading may be slow so I recommend lowering render distance or have dynamic chunk updates on

**Comment by DerToaster98** [comment]
uhm you did reset the cqrepoured file too? cause the last update (1.20.0 and 1.20.1) basically were a complete rewrite of the structure spawning system and it is way faster now, we recommend you to delete or rename the cqr folder (which you did) and also renaming or deleting the cqrepoured file cause we changed quite a bit there

**Comment by Geezt435** [comment]
> also that log file is only a very small part of the startup log, we need the full log.
> 
> Side note: we are only able to help you if you cooperate and answer our questions

Oh yeah sorry, I don't know I supposed to post the full logs

**Comment by Geezt435** [comment]
> did you update the mod recently, had a previous version installed before and did not follow the update instructions?
> 
> If yes: just delete the CQR folder and restart the game, that will fix the issue

Yes, this fix the issue

**Comment by DerToaster98** [comment]
(well full logs say much more than the startup stuff, in your case it wasn't relevant but remember it for the future as sometimes log files help a lot)

**Comment by Geezt435** [comment]
> uhm you did reset the cqrepoured file too? cause the last update (1.20.0 and 1.20.1) basically were a complete rewrite of the structure spawning system and it is way faster now, we recommend you to delete or rename the cqr folder (which you did) and also renaming or deleting the cqrepoured file cause we changed quite a bit there

wait, which cqrepured file?

**Comment by DerToaster98** [comment]
the one in the config folder, not the cqr folder, there also is a cqrepoured.conf file in the config folder which is CQR's main config (holds generation rates, global chances, etc)

**Comment by Geezt435** [comment]
ok check, I renamed it to something else
