### ISSUE TITLE
[Bug][Enhancement/Suggestion] Feedback on Nether Dragon

### ISSUE THREAD

**Issue by SandwichHorror** [TeamChocoQuest/ChocolateQuestRepoured#202]
**Common sense Info**
 - I play...
   - [x ] Only with CQR and it's dependencies
 - The issue occurs in...
   - [x ] Singleplayer
 - [ x] I have searched for this or a similar issue before reporting and it was either (1) not previously reported, or (2) previously fixed  and I'm having the same problem.
 - [x ] I am using the latest version of the mod (all versions can be found on github under releases)
 - [x ] I reproduced the bug without any other mod's except forge, cqr and it's dependencies
 
 **Versions**
Chocolate Quest Repoured: 1.12.2-1.20.1A
Forge: latest 1.12.2
Minecraft: 1.12.2

**Describe the bug**
Multiple issues with boss AI, projectiles. I've included several suggestions, but in many cases I think my suggestions are also related to bugs (i.e. nether dragon is not interested in player -> issue with AI and player tracking as well as feature suggestion for new AI behavior/greater difficulty)

1) **The Nether Dragon is largely disinterested in the player**, and spends much time floating around slowly. *My suggestion:* it should occasionally make direct charges towards the player to attack you with melee. It should be even more aggressive in Stage 2.

2) **The Nether Dragon does not aim its fire breath.** It spins around aimlessly and fires at nothing, rather than its actual target.

3) **The Nether Dragon's fireball projectiles are extremely slow.** If you want this boss to be easy, perhaps a config could control the speed - but by default, the fireballs take around 10-30 seconds to reach you from the moment they're fired, making them essentially a non-factor.

4) **The Nether Dragon's fireball projectiles often fail to detonate.** They just float in space, still on fire. They never explode with player or block collision.

5) **The Nether Dragon's fireball projectiles often detonate strangely, creating ghost blocks.** It's as if the blocks or a solid invisible entity are still there - you will bump into "nothing" and be unable to move forward. If you jump and land in one of these "ghost block craters", you may get completely stuck.

6) **The Nether Dragon becomes invisible before it dies in its second stage.** It normally loses segments as its health decreases, but I watched the skull and last two segments blink out of existence after shooting it with an arrow. It continued to attack me and fire projectiles, despite the skull being completely invisible. It still had about 1/10 of its health left.

7) ***(enhancement/known issues - probably)*** The Nether Dragon's idle sounds are villager idle noises. There is no audio cue for its fire breath or obsidian fireball projectiles, which are sorely needed.

A different sound should be used when projectiles hit the dragon's body in the second stage, to convey the idea that the projectiles are only bouncing off.

8) *(enhancement)* A blacklist rather than whitelist for blocks that the Nether Dragon should break, to prevent the annoyance of adding in thousands of blocks in large modpacks.

9 *(enhancement)* The dragon has severe trouble with flying players. Giving it a charge attack would mitigate this issue.

10 *(enhancement)* The dragon should deal melee contact damage in its 1st and 2nd phase, to prevent the fight from becoming a complete joke if a player has acquired fire resistance and even wither resistance.

11) **The neck segment that joins the dragon's head to its body vibrates extremely rapidly, especially in its 1st stage**

**To Reproduce**
1. Summon and fight the Nether Dragon.

**Screenshots**
![2020-06-22_14 29 50](https://user-images.githubusercontent.com/59847281/85324167-58236f00-b497-11ea-8c32-e23419652ba3.png)

**Comment by DerToaster98** [comment]
1) and 2) are intended

3), 4), 5) are bugs and will be patched

6): I thought this was patched, apparently it is not

7) known, but i can't find fitting sounds, if you know any fitting sounds, be sure to create a feature request with the sources linked

8) Maybe

**Comment by DerToaster98** [comment]
also on 1) and 2): The nether dragon is supposed to be an easy boss and it actuallly directly charges at the player sometimes

On 2): it only spins when it flies back on it's circle, the firebreath is controlled by a timer and it is supposed to be shooting only at where it is looking

**Comment by DerToaster98** [comment]
10): Wither resistance doesn't exist in vanilla and we balance in comparison to vanilla, also it does melee damage

**Comment by SandwichHorror** [comment]
Dang, that was fast. I didn't even have time to finish adding my thoughts I just remembered (see 9, 10, 11).

As for 1 and 2... would you consider... _changing_ this? Please? :smile:  I just don't find it fun. 90% of the fight is spent waiting for it to come close enough to shoot or attack in melee. You've made a very cool boss but it seems wasted if it acts like it would rather be doing anything else but fighting you. Perhaps config for charge rate and accuracy of fire breath? The fire never came close to hitting me unless I was right next to it when it started.

 I'll try and find any sounds you need for any mobs. Are you OK with potentially "copyrighted" sounds? Huge mods like Mowzie's Mobs have been using copyrighted sounds from large franchises such as Dota 2 and World of Warcraft and have not gotten in any trouble.

**Comment by DerToaster98** [comment]
on 1) and 2): I'll try the fight again personally and decide after that, the speed is an issue with vanilla handling flying mobs, so it will maybe be changed

on fire breath: it's "hitbox" actually is pretty large but maybe not long enough to reach the floor, will take a look at it but no promises

(well *I* don't have a problem with copyrighted sounds, but arlo decides there and i guess he wouldn't like that...)

on 11): I know but there sadly is no proper way to fix this, it is probably caused by forge/mc positioning the entity. i can take a look at how the positions of the segemtns are calculated again but no promises

**Comment by KalgogSmash** [comment]
All in all this is really good and detailed feedback on the boss mechanics. Thank you for taking the time to write it all up and we are definitely taking these suggestions into consideration for the next iteration of the Nether Dragon.

**Comment by SandwichHorror** [comment]
Sure thing. I had kind of a text dump in the Lich issue thread, since it summarized a lot of my thoughts and recommendations for your mod and its bosses I've seen so far (Will write up feedback for the rest tomorrow.)

Hope I don't impose too much on you with those wall-of-text comments over there :stuck_out_tongue_winking_eye:

**Comment by KalgogSmash** [comment]
You're not imposing anything - we appreciate that you took the time to play through each boss and give constructive feedback rather than "XXX sucks and is broken" or our personal favorite, "please upgrade to 1.15." Since our mod is relatively new we haven't had a lot of players with the combination of a lot of mod experience + decent skill at minecraft + the ability to write up detailed suggestions so this is a big help for us.

**Comment by DerToaster98** [comment]
OH btw, can you send me your discord name and tag? I am thinking of sending you prototype builds that contain the changes to the bosses
