### ISSUE TITLE
[Bug][Enhancement/Suggestion]Feedback on Giant Tortoise Boss

### ISSUE THREAD

**Issue by SandwichHorror** [TeamChocoQuest/ChocolateQuestRepoured#203]
**Common sense Info**
 - I play...
   - [x ] Only with CQR and it's dependencies
 - The issue occurs in...
   - [x ] Singleplayer
 - [ x] I have searched for this or a similar issue before reporting and it was either (1) not previously reported, or (2) previously fixed  and I'm having the same problem.
 - [x ] I am using the latest version of the mod (all versions can be found on github under releases)
 - [x ] I reproduced the bug without any other mod's except forge, cqr and it's dependencies
 
 **Versions**
Chocolate Quest Repoured: 1.12.2-1.20.1A
Forge: latest 1.12.2
Minecraft: 1.12.2

**Describe the bug**
Boss fight is not working properly, unclear to player, causes major TPS spikes

1) **The Giant Tortoise takes damage from... doing absolutely nothing, and standing still is the most efficient way to defeat it**.  I am not sure if it's supposed to take damage from spinning while touching a block, but it very often takes damage and can become stuck in a loop. It spins in place, takes damage over several seconds, uses its bubble attack, and then repeats.

2) **There is no clearly communicated way to cause the tortoise to leave its shell, which leads to an extremely frustrating fight.** In one try, I fought the tortoise and never saw it leave its shell from 1-500 health. In another, I randomly triggered it to leave its shell for a few seconds, but then never again over the course of the fight. This needs to be clearer in order to have something resembling a boss fight (as in, a challenge for a game, where the goal is to have fun) instead of a brick wall of hitting a monster 1000+ times and dodging two attacks. I tried hitting it rapidly, hitting it slowly, using lava, using water, hitting it during its spin move, hitting it during its bubble move, hitting it after it performs these tasks, causing it to run into a block during its charge, falling onto its shell, using a critical strike, and none of these were the trigger for knocking it out of its protected mode.

I suggest adding a third attack, perhaps an upwards ascent and then downwards crash with AoE damage, with a clearly telegraphed wind-down period afterwards where the tortoise is vulnerable. (particle effect + turtle sound effect). If it takes X <configurable?> % of its health during this time, it pops out of its shell for a few seconds. The strategy then becomes dodge, strike, dodge, strike, leap out of the way, quickly focus fire for big chunk of damage, repeat, instead of "bash your head into a brick wall over and over" or realistically "stand still and watch its health tick down due to Bug 1)"

3) **The Giant Tortoise struggles immensely with targeting players above its location.** It seems to descend fine, and can handle elevation changes of a few blocks at a time, but often, it gets stuck against a wall, where a player can simply stand still and whack it, stepping back when it does its bubble attack.

4) **The Giant Tortoise causes massive TPS spikes**, freezing all entities on the world for up to minutes at a time. My computer was running normally with good FPS and TPS, but occasionally, hitting the tortoise caused everything to freeze.

5) **The Tortoise takes damage extremely quickly from lava, to the point of breaking the game.** Its health ticks down so fast that it usually triggers the TPS freeze above. Note: the TPS freeze also occurred on other occasions, but a lava bucket let me reproduce this issue twice.

6) **No clear way to avoid regeneration.** This feels like an artificial method to give the tortoise more health without going over a vanilla entity health limit or something. There appears to be no way to avoid this - perhaps at 250 health the tortoise pops entirely out of its shell, and rushes back to its shell within 3 seconds. If you let it get back to the shell in time, it will regenerate. If you delay it sufficiently, it automatically jumps into its shell at 100 health but does not regenerate further.

7) *(enhancement)* Note: I'm not sure how this fight is supposed to work, so perhaps I have something wrong about its charge attack... but anyway: the charge attack should break blocks like the Wither (rather than the Ender dragon) - stopping, but making a crashing sound and breaking any colliding blocks nearby. Perhaps this could do slight AoE damage around itself, with a particle effect of tiny shell fragments flying around, to prevent cheesing the tortoise by creating a whole bunch of dirt pillars.

8) *(enhancement)* A warn sound effect before charge attack, instead of this silent deadly tortoise hovering like a UFO, and a better shell-hit sound effect, sounding like a solid thunk instead of a mechanical construct (the default blaze noise).

**To Reproduce**
1. Summon and fight the Giant Tortoise.

**Screenshots**
![2020-06-22_15 07 59](https://user-images.githubusercontent.com/59847281/85328052-07fbdb00-b49e-11ea-8d65-5f870c5781e4.png)
Tortoise takes damage by itself as I stand still

![tortoisetps](https://user-images.githubusercontent.com/59847281/85328123-24981300-b49e-11ea-893a-4d50f139c526.PNG)
massive TPS spikes

**Comment by DerToaster98** [comment]
2): it is noted in a book found in one of the dungeons. you need to block it's spin with a shield

1): I forgot that still was a thing, should've been removed a while ago

3) that overall is an issue with every minecraft mob, might add a few checks in the tortoises AI to then ignore the player and go back to sleep

4) never experienced that, even when run on the test server which is an raspberry pi 3

5) why would you throw a poor tortoise into lava? Also it kinda is logical, it is a water animal, fire harms it. i'll maybe add something that let's the tortoise  destroy lava when it touches it

6) supposed, the tortoise will heal up about 3 times, each time the healing amount gets divided by two

7) breaking blocks: no, AoE damage: will be considered, will probably be something like an explosion

8) it actually spins up, with sounds: again, if you want better sounds send a source :) with a warning sound: i don't think that is a good idea, i might add some sweep particles around it when it starts to spin up

Overall the tortoise is meant to be fought in a large square area with walls around it, you need a few shields to combat it properly, also i think blocking the tortoises attack with a shield is kinda intuitive

I am not a big fan of the third attack as a jumping tortoise doesn't make sense (neither makes it sense that it sometimes begins to hover, which will be patched sometime)

Generally the tortoise is meant to be fought in a flat arena, not in uneven terrain, it also normally only can be found in castles and snow castles as a sort of "mini boss"

**Comment by SandwichHorror** [comment]
> 2): it is noted in a book found in one of the dungeons. you need to block it's spin with a shield
Makes sense, but at the same time doesn't when it isn't affected by running into say, a wall of obsidian, but is severely affected by bumping into a shield of wood and iron. I would recommend an additional, but tougher way to trigger it leaving its shell, to avoid these kind of situations where the fight simply isn't fun at all unless you figure out the one specific way to beat it (and I am aware of the Twilight Forest naga and Aether Aerwhale King, so I'm not sure why this didn't come to me - point being I think I'm decent with figuring stuff out usually but this just wasn't clear)

5) As noted before, was searching for a way to kill it. I do think it's a problem if it fairly consistently froze the game due to apparently no I-frames from lava for the tortoise

6) A way to prevent this as I suggested would make the fight much more fun and less like a slog and doing the same chore multiple times

7) seems to be easily trapped if it can't break blocks in any way, then. perhaps an emergency method if it considers itself "stuck" versus on every single charge attack

re: jump attack: it makes more sense that a tortoise would be able to "launch itself into the air and crash back down" than to be able to turn on a dime and zoom through the air (this is not a bug, that's just its normal movement). Having **both** would make the fight pretty dynamic imo, but of course this is your mod, not mine!

**Comment by DerToaster98** [comment]
hm maybe yes on the jump attack but i'm not really  sure, the arenas the tortoise is in aren't really tall

on 2): in the tortoises concept i had the idea flying around that it also gets out of it's shell when it hits a hard block, that also actually was implemented during development, will probably return in some way (tortoise is out of its shell for a shorter amount of time then probably)

on 7: ye we definitely need a way to unstuck the tortoise; will probably add the break blocks thing (which isn't that easy to add cause of the tortoises movement AI) but won't be able to break all blocks like the wither

on 6: maybe i'll add a way to interrupt the healing, it was also in it's concept that if one hit the tortoise hard enough whilst it was healing it would cause the tortoise to move out of itÄs shell, however, that would drastically shorten the fight

on 5: the rate at which it takes damage from lava: will be looked at as that definitely is not supposed
