### ISSUE TITLE
[Bug][Enhancement/Suggestion]Feedback on Lich

### ISSUE THREAD

**Issue by SandwichHorror** [TeamChocoQuest/ChocolateQuestRepoured#204]
**Common sense Info**
 - I play...
   - [x ] Only with CQR and it's dependencies
 - The issue occurs in...
   - [x ] Singleplayer
 - [ x] I have searched for this or a similar issue before reporting and it was either (1) not previously reported, or (2) previously fixed  and I'm having the same problem.
 - [x ] I am using the latest version of the mod (all versions can be found on github under releases)
 - [x ] I reproduced the bug without any other mod's except forge, cqr and it's dependencies
 
 **Versions**
Chocolate Quest Repoured: 1.12.2-1.20.1A
Forge: latest 1.12.2
Minecraft: 1.12.2

**Describe the bug**
Minion summoning causes lag, largely trivially easy/slow projectiles, no real counter against ranged players

1) **Lich's minion summoning causes lag spikes.** About 1/2 the time the lich summoned its four zombies, all entities stopped moving for about a second. Sometimes the game lagged too, but I think this is mostly a TPS thing.

2) **The lich has no defense against being cornered.** I understand that many of these boss fights are intended for specific structures, but even in naturally generated structures without player building, the basic strategy to win this fight is to knock the lich into a corner and wail away. *Suggestion*: a knockback melee swipe with the staff, used against the player when the player is close to the lich.

3) **The lich doesn't have a real answer for ranged players, either** Due to weak projectiles and lack of any sort of repositioning ability (warping, jumping, flying, hovering, blinking, dashing), you can basically just pin the lich against a wall with arrows over and over again. Its rate of projectile fire is so slow that when it does summon its lantern, you can run up and break it with your hand and run back away before it summons any zombies - not like it really had a melee attack to begin with.

4) **Projectiles are trivial to avoid.** The main attack (purple one) is very slow and appears to only deal raw damage. The poison attack has extremely low accuracy - the orbs just shoot out and arc downwards, colliding with a block and disappearing. Even the evoker fangs somehow seem underwhelming compared to the Evoker itself.
-> 
 **Projectile Suggestions:** 
- Faster main purple projectile, burst of 3-5 projectiles in a horizontal line, or more projectiles fired at once - or all of the above.
- Poison attack is in fact a poison spray, an automatic AOE all around the lich in a 3 block radius guaranteed to hit if you are within that radius.
- Standing in a red pentagram/rune when the zombie is summoned deals wither or fire damage.
- Lich spawns 3 lines of evoker fangs at once, or 5/7 in a star shape out from itself.

5) **Slow spellcasting animations invites mob bullying.** The animations seem extremely long : 1-3 seconds is a lot when you can swipe so quickly. This makes sense for something like health potions, where there is clear "counterplay" to burst down the humanoid mob before it can down the potion, but where the entire boss fight lies in the boss casting spells, the animations should not be such a glaring weakness. Perhaps a config to adjust the speed of these, which would allow a nice slider over difficulty of mob spells.

6) **Lantern/phylactery summoning is largely trivial but a great idea.** Most of the time when the lich summons its lantern, the lantern is just a few blocks away. It takes no effort to run over and break it. However, I LOVE this mechanic and it is such a wonderful concept! I recommend having some kind of system where the lantern is always placed far away from the player, up to a certain radius. Another method would be to always summon the lantern on a floating block that looks like some arcane pedestal or barrier - requiring the player to carefully jump and break it, pillar up, or use an explosive instead of mindlessly smashing the lantern after walking five blocks over to it on the ground. 

7) **All summoner-style mobs appear dark until they have lost approximately 20% of their health** Not sure if this is some feature to make the actual boss a "surprise", but I mean the boss bar appears right on the screen with their name, and many players use mods that display entity names. The Lich, Boarmage, and Necromancer all have dark hoods with red eyes until damaged sufficiently. They should have more distinctive appearances even after this is the case. If this is a feature due to the dynamic damage feature, and what I'm seeing is actually breaking their mage's hood or something, I still think the mobs should be clearly identifiable as lich, necromancer, boarmage, before their equipment is broken. 

8) *Suggestion: repositioning ability* As explained before, the lich has no way to deal with being pinned or trapped. A bucket of water into a corner renders it mostly helpless. A blink spell to the farthest available point from the player would avoid this situation.

9) *Suggestion (already known, obviously)* sound effects for each projectile, better projectile textures, projectile trail particle effect. I love a lot of the art you have in this mod, but the projectiles are lacking. The main attack looks like some kind of orange and purple gear from a children's toy robot. The acid particles are neon green. Neither have any sort of trail particle effect, making them look very plain.

**To Reproduce**
1. Summon and fight the Lich.

**Screenshots**
![2020-06-22_15 44 44](https://user-images.githubusercontent.com/59847281/85330618-c15caf80-b4a2-11ea-9cc2-4d8742392052.png)

Not in structure this time, but lich should have a way to get out of these sticky situations without just drinking health potions. Note: cobblestone was built and lich was trapped during the fight, not a premade arena

![2020-06-22_15 47 16](https://user-images.githubusercontent.com/59847281/85330659-d0436200-b4a2-11ea-909b-3a3a18f13844.png)
Lich bullied into the wall by arrows, player easily dodging its projectiles

**Comment by DerToaster98** [comment]
7) is supposed
2) can be avoided, set "enable strafe" in the config to true
6) when the phylactery gets placed it gets placed directly at the lich, the players should have a chance to reach the phylactery and not search for it outside the dungeon
5) spell casting durations may be reduced for all mobs
3), 4): the lich is supposed to be an easy boss, also we want every boss to be unique, giving him evoker fangs would make it too similar to the necromancer
1) never experienced that, not reproduceable

8) in the dungeons by default players are not able to place any blocks (except torches and 2-3 other blocks), and please stop burning all the bosses in lava

i like the "wither in pentagram" idea
projectile speed may be rebalanced
i don't like the relocate/teleport ability, the lich isn't an enderman and as mentioned before is not supposed to be a difficult boss

Btw, thanks for the feedback on bosses, it is sort of rare for us to receive such detailed and actually useful feedback

**Comment by DerToaster98** [comment]
now that i'm thinking about it: maybe all mages will receive some kind of projectile blocking abiltiy that has the chance to deflect the projectile 🤔

**Comment by DerToaster98** [comment]
on 7: will probably change the boss bar to not reveal the name until it is actually revealed

**Comment by DerToaster98** [comment]
ok, your suggestion on 8) is ok but needs internal discussion cause like mentioned: the bosses should've unique abilities, and teleporting is more of the walker king or pirate captain style

**Comment by SandwichHorror** [comment]
> when the phylactery gets placed it gets placed directly at the lich, the players should have a chance to reach the phylactery and not search for it outside the dungeon

perhaps "within lich line of sight"?  wouldn't go out of the dungeon

> giving him evoker fangs would make it too similar to the necromancer

But he already uses an evoker fang attack :flushed:  I saw it about a dozen times across about 5 lich fights! If he has it, it ought to be beefed up compared to the vanilla mob with 25 health, hence the multiple lines in a pattern reminiscent of the runes he uses to summon zombies

> will probably change the boss bar to not reveal the name until it is actually revealed

This sounds great - but even better would be a config option to enable/disable the hidden appearance and reveal, if you wouldn't mind!

> teleporting is more of the walker king or pirate captain style

Agreed! Perhaps temporary transition into a Vex-like animation, where he could glide through blocks for 3-5 seconds? Or just "magical hovering up and over obstacle, with a hand held out sorcerer-style, arcane fire at feet"? Gain a shield like for his lantern for a few seconds as he floats over to a new location? 

![94bbd65f372581cf98a0b593936f5bed](https://user-images.githubusercontent.com/59847281/85343453-e2c99580-b4ba-11ea-80c9-e793b1f16548.jpg)
Archetypal "hovering spellcaster" pose

**Comment by SandwichHorror** [comment]
> Btw, thanks for the feedback on bosses, it is sort of rare for us to receive such detailed and actually useful feedback

Of course! It frustrates me if someone just says "X mod is bad" or "Y is not fun" or "Change Z!" without providing details. Anyway, this mod is not only extremely promising by itself, but I have a particular investment in it! If it means anything to you, I'm one of the developers of the modpack [Rebirth of the Night ](https://www.curseforge.com/minecraft/modpacks/rebirth-of-the-night), and our next planned update is largely focused on adding new bosses, making existing bosses and minibosses more fun, and tying said bosses into progression more closely. The dungeons and trading mechanics also seem to be great fits for our survival/adventure/low-tech themed pack - I was just waiting for the "structure generation optimization" update to really begin checking it out.

> Wither resistance doesn't exist in vanilla and we balance in comparison to vanilla
[this was from the Nether dragon post] Totally makes sense. However I would argue this point: by continuing development in 1.12.2 (and I sure as hell hope you stay here for a while!), you're de facto going to attract a whole lot more modded players than vanilla players, who all definitely hyped up for the Nether Update. While **default balance** makes sense to be made in comparison to vanilla, the fact that in all likelihood, CQR will be experienced by most players in 1.12 modpacks makes it all the more important to me to have tons of robust configuration. I totally know it's alpha and it can be a pain to add configs for every little thing. But in my mind that ability for a pack creator to tailor a mod exactly how they like it is what separates a good mod from a great one - or an unusable one to the most versatile possible mod (like Quark).

>  please stop burning all the bosses in lava
If there's one thing I've learned from my pack that often has difficult and challenging mod encounters, it's that players are fantastic at cheesing! "Given the opportunity, players will optimize the fun out of a game." Minecraft mobs in general have huge trouble with water and lava buckets, being trapped in blocks, stunlocked/knocked back endlessly, or shot to death from a safe distance. I'm not trying to be a pain, but in my mind a boss or miniboss should have reasonable strategies to deal with most, if not all of these go-to strategies for anyone who considers a strategy beyond "drink potions and fight in melee!"

**Comment by SandwichHorror** [comment]
> re: Nether Dragon, Lich, etc. are "supposed to be easy bosses"
That totally makes sense. As does some of the other features I might mention, but are not intended in the default mod (being able to cheese a boss by building, not being able to identify a boss until quite a bit into the fight), etc. However, I would strongly urge if not now, then later on in "beta" or further in release, to have config options controlling many of these.

Many, many mods allow editing modded mobs' base stats. Any ground-based movement speed, melee attack damage, and health can easily be fixed, and I'd be able to modify these aspects of CQR mobs right now. Projectile damage, projectile speed, and flying mob speed are a lot more iffy to modify with other mods - so these attributes would be my preference if you add any configs at all.

As for raw difficulty, personally I would much rather have a complex boss with lower health and damage, than a simple boss with a huge health pool and a single attack. 
For an example from a game focused around bosses, consider how Terraria's normal to Expert mode adds new boss phases and AI in addition to increased health and damage... but its new Master mode just increases health and damage, with few if any boss AI changes, to the point of requiring optimization or even cheese. 

For this reason, I don't see harm in, say, giving a boss a "spread" of projectiles that must be dodged instead of a single projectile, because each one could deal less damage to compensate. Even better if that damage can be changed for those who wish to tweak all their bosses.


For the Nether Dragon example, having it charge 3x as frequently, but deal 1.5x less damage (or even 3x less damage) would make the fight far more exciting in my opinion. And then I, in my own pack, could swoop in and greatly increase its damage with "Rough Mobs Revamped" or "InControl" or something similar, and then something intended as an easy boss becomes 
comparatively more challenging - fitting for a mid-game encounter instead! 

But while a higher charge rate would be great, being able to **configure** things like projectile speed, charge rate, and so on? That's where you have such a huge amount of opportunity, where a given pack could place the Nether Dragon as something summoned within a few hours of play, or as something capable of ripping through players in the finest enchanted end-game armor.  Of course, configs are not easily implemented, and I know each little line in the .cfg files requires a lot of work.

**Comment by DerToaster98** [comment]
ok i will consider the fang thing, (wasn't sure which one did the fang attack lol)

vex like reposition form: i like the idea, will be considered

problem with configs is not implementing it, it is that you have a lot of calls to the config instance which can be annoying, it might be considered for some things, not everything but for some things.

Overall i will be working on a boss and boss attack rebalance, especially boarmage, nether dragon and walker king will receive a revisit.
(On nether dragon is slow: yes, i sadly wasn't able to increase it's movement speed as it's navigator AI atm is based on vanilla navigators which don't allow higher movement speed for flying entities, this will be chnaged)
