### ISSUE TITLE
[Bug][Enhancement/Suggestion]Feedback on Boarmage - Several Suggestions

### ISSUE THREAD

**Issue by SandwichHorror** [TeamChocoQuest/ChocolateQuestRepoured#205]
**Common sense Info**
 - I play...
   - [x ] Only with CQR and it's dependencies
 - The issue occurs in...
   - [x ] Singleplayer
 - [ x] I have searched for this or a similar issue before reporting and it was either (1) not previously reported, or (2) previously fixed  and I'm having the same problem.
 - [x ] I am using the latest version of the mod (all versions can be found on github under releases)
 - [x ] I reproduced the bug without any other mod's except forge, cqr and it's dependencies
 
 **Versions**
Chocolate Quest Repoured: 1.12.2-1.20.1A
Forge: latest 1.12.2
Minecraft: 1.12.2

**Describe the bug**
Lag during meteor summoning, ghost blocks after meteor explosion, other suggestions

1) **Boarmage meteors frequently cause a lag spike.** I have noticed this with **every boss that summons entities in this mod** - every time the entities would be summoned, there's about a 50-75% chance of a significant lag spike where everything stands still before they appear. I hate to say it, but I'm 99% sure it is something with this mod's coding or optimization. I've used many 1.12.2 mods with very unbalanced summoning mobs, such a spider that continually spawns dozens of tiny spiders, and never experienced so much as a hiccup. This issue also applies to every other humanoid boss mob I tested.

2) **Meteor craters frequently leave "Ghost blocks" behind.** Same issue with the Nether Dragon's fireballs. Invisible blocks/entities left behind in the craters that "trap" you if you jump in, upon which you are yanked up and down in a very glitchy way, like a lagging mob on an overloaded server.

3) *Suggestion: Meteors should be spawned directly above player's location - or just be bigger* It is currently far too easy to avoid meteors. Many times I stood still directly next to the boarmage, and the meteors exploded all around me without getting particularly close. I actually think the best choice would be to set the target point at the player's current location when the spell is finished, and then alter the other meteors in a slight varied pattern away from that point to account for basic movement variations/punish moving just slightly away without booking it. If that is not possible or not compatible with what you see the boss being, then I suggest simply making the meteor explosion radius bigger.

4) *Suggestion: Meteors should deal contact damage.* Meteorites are rocks crashing down from above. The explosion is caused by the rock slamming into the earth at high speed. So it stands to reason that they should deal significant physical damage, right? After fighting about six or seven boarmages with fire resistance, I am 90% sure the meteors deal only fire damage, which doesn't make sense. If they do deal physical damage, it should be greatly increased by default (damage config? :pleading_face:)

5) *Suggestion: Particles telegraphing boarmage's explosion spell attack.* The explosion spell is pretty underwhelming, and I almost never got hit by it, but at the same time, it's also completely random which blocks blow up. My suggestion is to have about a dozen explosions for that attack (up from 3-5), but each would have a little particle effect right above where the explosion will detonate. Instead of feeling like a complete gamble (and also being underpowered), instead the challenge would be in stepping into a safe spot before being blown to smithereens, like the world's deadliest game of Dance Dance Revolution.

6) *Suggestion: Additional fire spell(s)? based on above suggestion* The boarmage is neat, but she feels like one of the thematically weakest spellcaster boss mobs, with only two fire spells (that I noticed) and one explosion spell. I would love to see some more complex "fire pattern" attacks. One would be a huge pattern of embers that persist for about a second before exploding upwards into fire jets that remain active for 2-3 seconds. You'd have to get into a safe spot within the gaps in the pattern. Another would be a potential melee attack to get the player away - a downwards strike with the staff, with fire jets erupting outwards in a line away from the boarmage.

Telegraphing spell attacks in bosses is cool and good, honestly, because it actually allows you to increase the difficulty while simultaneously causing most player deaths to feel like they're your fault instead of "bullshit - I can't believe I was unlucky enough to be hit then!"
Wildstar was well known for its complex fights with lots of telegraphing, and I think the boarmage would be really unique to take some inspiration from that with her love of fire.

![WS_2014-05_Raids_Genetic_Archives_4](https://user-images.githubusercontent.com/59847281/85360962-9eed8500-b4e8-11ea-939c-a81d07dbbee3.jpg)

7) *Frivolous(?) Suggestion: Anti-Air Attack.* I mentioned how I think most bosses should have at least one anti-air ability. Even one ability usually isn't enough to prevent flight from making boss fights significantly more trivial, but it does prevent it from being completely stale. This may be completely against your philosophy for boss fights, or for keeping the Boarmage as an easy boss, or only ever intending bosses to be fought in their given structures and not used for other purposes in modpacks, but I'll include it here anyway. Almost all of the Boarmage's attacks are ground based or slow-moving, so she struggles in particular against players with a height advantage. I suggest that if the player is a certain interval above the boarmage, she raises her arms and "searing wind" or a "heat wave" begins scorching the player, dealing fire damage, pushing the player down to the ground, and maybe even dealing extra durability damage to armor as a deterrent. 

8) *Frivolous(?) Suggestion: Fire Tornado Movement* I mentioned how I think most bosses should have at least one repositioning ability, but I agree that kind of ability shouldn't just be a lazy "enderman blink" every time, that's not thematic or interesting. My idea for when the Boarmage is stuck (in blocks, in water, lava bucket, etc. or otherwise can't reach the player) is that she conjures a fiery tornado around her and spins up and over to a new location, dealing fire and some physical damage (from debris) around her in the radius.

![firetornado](https://user-images.githubusercontent.com/59847281/85361294-80d45480-b4e9-11ea-8f2c-8cfa56ed9598.PNG)

9) *Suggestion: Quick fireball if stuck*: Another way to deal with being stuck (behind blocks) would be that the Boarmage always fires a quick fireball in front of her when she's stuck, effectively blowing up any obstacle in the way.

10) *Suggestion: Boarmage uses pigman sounds.* I can guarantee that Mojang won't have a problem with it :wink: 

**To Reproduce**
1. Summon and fight the Boarmage.

**Screenshots**
![2020-06-22_20 19 56](https://user-images.githubusercontent.com/59847281/85361649-854d3d00-b4ea-11ea-910b-55e13474f9c3.png)
It's not her fault! She never learned how to swim!

**Comment by DerToaster98** [comment]
Boarmage sucks to be honest, it needs a complete rework as i am not content with it's attacks myself, also 2 of it's attacks don't work properly and are extremely bugged (might not be perceptable by the user cause it just doesn't work as intended)

didn't read through all your feedback here, will read it when i rework the boarmage

**Comment by DerToaster98** [comment]
3) and 4): will add that

5) i had a similar idea before (actually something extremely similar to it was in the boarmage's concept)

on 7) will be taken into consideration when changing the meteor attack

8) i have a different idea: it explodes into a fireball and reappers behind the player instantly casting it's firewall spell

10) yes, actually it uses the pigman sound inside the game, we didn't copy it, it will thus also be affected by resource packs

9) maybe

6) yes
