### ISSUE TITLE
[Bug][Suggestion/Enhancement]Feedback on Necromancer

### ISSUE THREAD

**Issue by SandwichHorror** [TeamChocoQuest/ChocolateQuestRepoured#206]
**Common sense Info**
 - I play...
   - [x ] Only with CQR and it's dependencies
 - The issue occurs in...
   - [x ] Singleplayer
 - [ x] I have searched for this or a similar issue before reporting and it was either (1) not previously reported, or (2) previously fixed  and I'm having the same problem.
 - [x ] I am using the latest version of the mod (all versions can be found on github under releases)
 - [x ] I reproduced the bug without any other mod's except forge, cqr and it's dependencies
 
 **Versions**
Chocolate Quest Repoured: 1.12.2-1.20.1A
Forge: latest 1.12.2
Minecraft: 1.12.2

**Describe the bug**
Lag during meteor summoning, ghost blocks after meteor explosion, other suggestions

1) **Skeleton, floating skull, and evoker spike summoning frequently causes a lag spike.** I have noticed this with **every boss that summons entities in this mod** - every time the entities would be summoned, there's about a 50-75% chance of a significant lag spike where everything stands still before they appear. 

2) **Evoker spike is rarely used.** If evoker spikes are supposed to be associated more with the necromancer than the lich, I'd expect the necromancer to use the attack more often. It seems to be fairly infrequent compared to the normal "purple gear" spell attack. *Suggestion*: more evoker spikes at once, maybe 3 in a slightly curved "claw" shape out from the necromancer, would be thematic and intimidating.

3) **Necromancer skulls are useless.** I am very confused by the skulls. What is their purpose? Whenever I fought a necromancer (and I did, about ten times), he summoned the skulls, which proceeded to float by the necromancer and do nothing else (but explode if killed). If they're meant to attack me, they definitely didn't. It would be cool if they both fanned out to send projectiles at you, and maybe shared a health pool where you had to reduce both to 1 health at the same time, or they'd be unable to be killed.

4) **Necromancer skulls do not have a formal entity name, only internal registry.**
![2020-06-22_20 26 15](https://user-images.githubusercontent.com/59847281/85362232-ecb7bc80-b4eb-11ea-9f6a-db81a0386368.png)

4) *Suggestion: Necromancer should.... necromance more.* The Lich is supposed to be a master of undead and spells, but a decent chunk of its power comes from its minions. Surely a Necromancer is almost solely defined by its minions? More frequent minion summoning would be nice - a spell to place ranged skeletons far away but within firing distance of the player would be nice, especially if timed right around when the necromancer needs to drink its healing potion - the archers would take some focus off the necromancer. Perhaps a cursed hand spell attack that grabs you and hold you in place for several seconds - imagine an evoker spike spell, but a single entity - hand rising up from the ground, then snaps shut in a fist. 

5) *Suggestion: Additional defense*. When the necromancer reaches 50% health, it should summon an aura of whirling bones around itself, which deflect ranged attacks, grant minor damage absorption to the necromancer, and deal damage to players that are within 2 blocks of the necromancer. These bones could possibly crumble over time, or for every X amount of magic damage the necromancer suffers.

6) *Suggestion: The Necromancer uses Illager sounds.* At least until something better can be found.

-----
7) *Frivolous(?) Suggestion: Anti-Air Vampiric Skull Attack.* I mentioned how I think most bosses should have at least one anti-air ability. For the Necromancer, I think he should fire a very accurate homing skull missile, like the Wither projectile, that leeches life from the player. This attack could also be a new normal attack, but it would be used much more frequently if the player was above the necromancer's Y-level.

8) *Frivolous(?) Suggestion: Chains of the Dead* I mentioned how I think most bosses should have at least one repositioning ability. I get the sense the Necromancer is supposed to be pretty easy given its health pool and damage, but this could be a neat alternative. Instead of having a new way to get out of obstacles, the Necromancer would make sure you aren't missing out on the fun. If the Necromancer is stuck, on fire, or in lava, it would send out a spectral chain projectile that functions as a fishing rod, grabbing you and yanking you towards him. Ideally it would then follow up with an evoker spike attack. This attack animation, coding, and appearance could be used a special spell for other mobs, or another boss, too.

**To Reproduce**
1. Summon and fight the Necromancer

**Comment by DerToaster98** [comment]
i am not content with the skulls behavior myself, they don't work as i wanted them.
on their name missing: that indeed is a bug, will be patched

Again, that lag is not reprodueceable for me.

I do like the bone "shield".

Necromancer will receive a change to it's minion summoning, it will be summoning more minions and more often

on 7): will be considered with skull rework

I like 8), might be considered, in current dev environment mobs with a hookshot are able to do something similar, they can hook a mob towards them and will attack them with their normal weapon once it is close enough

Also i think i'll change all bosses to be not affected by water pushing, normal mobs may receive an AI to drain water, though that is not easy to do as it isn't really easy to detect a single water source. also they'll all receive the ability to drink fire resistance potions when thrown in lava

on 7): the necromancer *is* a illager (though the texture needs a change, the red eyes aren't supposed to be visible)

on 9) will be considered when reworking the skull minions (which i will redo completely from scratch  as their code is a complete mess)
