### ISSUE TITLE
[Bug][Suggestion/Enhancement]Feedback on Abyss Walker King

### ISSUE THREAD

**Issue by SandwichHorror** [TeamChocoQuest/ChocolateQuestRepoured#207]
**Common sense Info**
 - I play...
   - [x ] Only with CQR and it's dependencies
 - The issue occurs in...
   - [x ] Singleplayer
 - [ x] I have searched for this or a similar issue before reporting and it was either (1) not previously reported, or (2) previously fixed  and I'm having the same problem.
 - [x ] I am using the latest version of the mod (all versions can be found on github under releases)
 - [x ] I reproduced the bug without any other mod's except forge, cqr and it's dependencies
 
 **Versions**
Chocolate Quest Repoured: 1.12.2-1.20.1A
Forge: latest 1.12.2
Minecraft: 1.12.2

**Describe the bug**
Lag during spell summoning, blindness spell too quick (?), mirror images nullified by lightning, pathfinding issues in water/lava 

1) **Mirror images and tornadoes frequently cause a lag spike.** I have noticed this with **every boss that summons entities in this mod** - every time the entities would be summoned, there's about a 50-75% chance of a significant lag spike where everything stands still, and sometimes you can't move at all, before they appear. 

2) **Mirror images are not immune to lightning.** This is very bizarre because the King has a habit of using the mirror image ability and then directly following it up with lightning strikes. It's extremely underwhelming to watch him destroy his own duplicates - they should be immune to all of his attacks.

3) **The King is lethargic in water and completely shuts down in lava.** I'm so sorry, you know I had to do it to him. He doesn't even use his *teleports behind you - nothing personal* ability. He just bobs up and down accepting his fate.
![2020-06-22_20 47 42](https://user-images.githubusercontent.com/59847281/85363789-c267fe00-b4ef-11ea-96ac-298c8f976de4.png)

![2020-06-22_20 48 16](https://user-images.githubusercontent.com/59847281/85363806-cdbb2980-b4ef-11ea-8248-b84a82797387.png)

He should always use his *teleports behind you* move if he's stuck, taking lava damage, or hasn't moved in a few seconds.

4) **Blindness attack is over too quickly?** I noticed the Walker King sometimes uses an attack that inflicts blindness, but it seems to last only about two seconds. If this is supposed to be this quick? I think a longer duration would more accurately give a feeling of paranoia, or being surrounded by shadows/"the abyss" that I think this attack is supposed to evoke.

5) **Lightning strikes are random to the point of being unfun.** They strike with such RNG that it's a complete crapshoot whether they all hit absolutely nothing or just slam down on you one after the other. It's essentially impossible to avoid damage in this fight, which is not the best design imo. Ideally, a good boss would be challenging, complex, but also theoretically possible to beat without taking any damage (think of Legend of Zelda or Dark Souls bosses). Obviously Minecraft's combat is a good deal less complex than those games, but that doesn't mean the bosses can't have cool spells and abilities rather than just "You take damage now. You will accept this." They should have a very brief flash on the ground before appearing - think reverse Evoker spikes - or even better, Mowzies Mobs' Barako Chief with his sun lasers. It would ideally be so fast it would be difficult to avoid, but a skilled player could dodge most of them, and it wouldn't feel so up to luck and fate whether you lived or died due to lightning.

If this is intended to be a "gear check" - "you must have this much health/armor to survive" - I can understand that. If that's the case, I would recommend slightly lowering the default damage of these strikes, but also adding telegraphed lightning strikes that do huge damage. As a proper attack rather than a sheer mechanic to make sure the player has enough armor (and fire resistance too, most like), the random lightning strikes are insufficient.

6) **Evoker ring is very inaccurate.** The ring of spikes the King summons is so close to him, most of the time you actually knock him back in time that the spikes are well out of range of ever hitting you. There should either be 2 rings of spikes - One large, then a smaller inner circle - or the circle should always attempt to intersect with the player rather than be based on the king's current location.

7) **Tornadoes are not very visible.** I hope this isn't intended, but right now I think the tornadoes are way too subtle, just small collections of little black particles. They should be more obvious, like the Whirlwinds mod from the days of yore - only bigger, and darker with shadowy rather than smoky particles.

![lHjs0](https://user-images.githubusercontent.com/59847281/85364450-24753300-b4f1-11ea-8983-8eaf591e2f0e.png)

8) **The healing potion is too much on a boss with this much health and defense.** The healing mechanic seems to work best for mobs with lower amounts of health and health. It prevents them from being burst down too quickly, or from being slowly chipped by weak little baby damage over time. It adds a level of intensity and desperation to the last slice of the boss health. But the Abyss Walker in particular is different. He blocks hits with his shield, he has a mirage ability, he has very high defense. He's a total tank. To see his health reset to 75% three times in a row after trading blows and dancing around him, dodging his projectiles... it's disheartening, to say the least. Especially because it's not like he gains new abilities each time his health resets. It feels like a damn grind. If this was a mobile game I would expect to be paying for new "energies" or "lives" to beat the Walker King after the second or third time he heals back up. It's this kind of grind that incentivizes players to find "cheese" rather than enjoying a boss fight. And in his current incarnation, it is genuinely a faster, safer, more efficient, and less frustrating strategy to wait out all his health potions by plopping down a single lava bucket than to actually engage with the boss fight. All the more reason why the health potion system gets looked at a bit more, imo, and the bosses get one or two more abilities.

9) *Suggestion: Leap ability.* A cursed abyss walker warrior with a huge sword *and* a jump attack? Who could have thought of that? Even with a teleport, evoker spike ring, duplicate, and lightning, the Walker King has a shitton of health and it starts to get repetitive strafing around his right side over and over again. I strongly recommend giving him a powerful jump attack that deals massive damage, but possibly leaves him open to a few quick slices in the back after he recovers. Creating a lingering pool of shadows underneath his landing location would be the icing on the cake.

10) *Suggestion: Creeping Shadows spell.* This boss has the most health of any in the mod right now, as far as I know, so he deserves the most attacks to justify that. I think it would be great if he had some kind of ability that spawned pools of shadow all around the arena, 2-3 blocks in diameter, that inflicted damage, blindness, and maybe wither as well when standing inside. (This would make avoiding the tornadoes even more important). Occasionally, the King would call the shadows back to him, where they'd begin oozing to his location. When they reach him, they'd grant him a temporary damage absorption shield, and a large damage bonus for a few seconds. The king's sword would have a shadowy particle effect during this time - incentivizing the player to go on the defensive for a few seconds, and switching up the pace of the fight. As the King's health gets lower, he would use this ability more and more often.

**To Reproduce**
1. Summon and fight the Abyss Walker King

(By the way, to whoever is reading all of these things, thank you for tolerating these reports...)

**Comment by DerToaster98** [comment]
4) that is intended, the blindess is part of the "summon mirages" ability, won't change

2) will be changed, the mirrors are only supposed to take hits from enemies

3) will be changed

8) actually he hasn't that much health, he has very strong resistances. might be considered

5) actually they are not random, they appear in 2 patterns: 
- growing circles around the king
- a spiral of lightnings with the walker king being the epicenter
Also there is an enchantment (lightning protection) for helmets that is meant to help you in this fight

6) that is one if his newer abilities, his evoker fangs will also change to be something like obsidian spikes coming out of the ground, will be changed to growing rings (like a earthquake)

7) I know, their appearance needs a makeover, the current appearance is like the ones in the aether mod, i will look at the whirlwinds in "days of yore", ty

9) maybe

10) doesn't sound bad, parts of it might be considered

on all your 1)'s: Like i said, i can't reproduce those, it must be something in your pack

**Comment by SandwichHorror** [comment]
Hmm. My modpack has 257 mods, including many that directly alter AI, and yet I only noticed occasional significant entity lag right after installing this mod. I assumed it was some competing entity tasks or whatever, so figured I'd test it on a blank slate before coming here complaining about entity lag with Epic Siege, Zombie Awareness, Special AI, and so on all active.

I made a new instance with just Forge, CQR, LLibrary, Ice & Fire, and Neat, and the entity summoning lag happens regularly and consistently with all the summoning bosses from CQR. I'll ask some friends to see if they can reproduce this issue.

**Comment by Meldexun** [comment]
Bosses should have only 1 healing potion since the last update but i seems i forgot to change it everywhere in the code. But the bosses in the prebuilt dungeons should have only 1 healing potion.

Also could you tell us what hardware you are using. I also don't get any lags while fighting any of the bosses.

**Comment by DerToaster98** [comment]
i agree with meldexun, information about the hardware you are using (and with that how much resources mc has as well as the java version you use) would be useful
