### ISSUE TITLE
[Bug][Suggestion/Enhancement]Feedback on Shelob

### ISSUE THREAD

**Issue by SandwichHorror** [TeamChocoQuest/ChocolateQuestRepoured#209]
**Common sense Info**
 - I play...
   - [x ] Only with CQR and it's dependencies
 - The issue occurs in...
   - [x ] Singleplayer
 - [ x] I have searched for this or a similar issue before reporting and it was either (1) not previously reported, or (2) previously fixed  and I'm having the same problem.
 - [x ] I am using the latest version of the mod (all versions can be found on github under releases)
 - [x ] I reproduced the bug without any other mod's except forge, cqr and it's dependencies
 
 **Versions**
Chocolate Quest Repoured: 1.12.2-1.20.1A
Forge: latest 1.12.2
Minecraft: 1.12.2

**Describe the bug**
Fire texture completely covers Shelob, hitbox is too large, projectiles are extremely inaccurate

1) **Shelob's hitbox is too large.** The vanilla spider and cave spider hitbox only includes its head and body, not its legs. The hitbox for Shelob resembles a giant rectangle and it leads to feeling like she's way larger than she actually is, hitting you without touching you. I strongly recommend changing this.
![2020-06-23_15 38 32](https://user-images.githubusercontent.com/59847281/85453996-71e1b680-b56a-11ea-9d15-2c9e5c23222b.png)

2) **Shelob is entirely obscured by her fire texture when she is on fire.** 
![2020-06-23_15 38 07](https://user-images.githubusercontent.com/59847281/85454088-8d4cc180-b56a-11ea-93f4-3fd2573775d1.png)

3) **Shelob's projectiles are extremely inaccurate.**
Her webs spray everywhere, and the poison spray (which is only used at low health, it seems?) has the same problem as when the lich/necromancer uses it. They have extremely low arcs/trajectories and rarely, if ever, come close to hitting the player.

4) **Shelob's web projectiles fail to place webs most of the time.** I don't know if they only place webs when they contact an entity, but I think they should be placed whenever they collide with a block. It's very underwhelming to see her shoot out these webs and watch them disappear instantly. I recommend creating a new temporary web block that automatically breaks after about 10 seconds for the use of her abilities.

5) *Suggestion: huge leap ability* Shelob is super underwhelming. From the 100 health pool I assume she's only a miniboss, but right now she doesn't even seem that. I recommend giving her a huge leap ability where she can clear any obstacles, free herself from being trapped, and land on the player in a deadly pounce.

![2020-06-23_15 47 26](https://user-images.githubusercontent.com/59847281/85455487-eff28d00-b56b-11ea-897d-b846e69cfcba.png)
If only she could jump up to me...

![2020-06-23_15 47 58](https://user-images.githubusercontent.com/59847281/85455511-f5e86e00-b56b-11ea-9349-bd3469e06730.png)
Even if only encountered in her building-restricted lair, arrows have enough knockback to completely keep her at bay.

6) *Suggestion: more defined acid spray ability* Same deal with as with the Lich, the acid spray is essentially useless. However, my recommendation is that instead of a spell-like effect that spreads out all around her, Shelob sprays poison more directly. Imagine the Nether Dragon's breath, but smaller, and with slime particles instead of fire. She'd use this when the player is out of her reach (with a cooldown) and alternate it into her attack cycle.

7) *Suggestion: egg spawn ability* Instead of only spawning cave spiders, Shelob should have an attack where she spawns about a dozen eggs around the arena, including nearby the player. These eggs twitch or emit a particle/sound effect for a few seconds and then burst, dealing poison damage nearby and hatching into baby spiders.

8) *Suggestion: cave spiders on back* Shelob should have 3-5 cave spiders on her back when she spawns, like a proper mother spider.

9) *Suggestion: web netting* Instead of only firing inaccurate web projectiles around her, Shelob should have an attack that is a direct "web net", which has a wide cone-like hitbox and places 5-8 spiderwebs when it collides with a block or entity. These would ideally be new temporary web blocks.

**To Reproduce**
1. Summon and fight Shelob

**Comment by DerToaster98** [comment]
Shelob is not done so this will be ignored for the moment until the final version is out and the final version has been tried

**Comment by DerToaster98** [comment]
egg spawn thing actually is on todo, the direct summoning is only temporary

**Comment by DerToaster98** [comment]
8) is imo more effort than it is worth it as that is mostly cosmetic

9) is also actually on todo

on 4) the web only gets placed when it hits an entity

on 3) it randomly chooses between web and poison projectiles for each projectile in the "wave", it is not dependant on health

on 5) it actually has a leap attack, but it also atm is the vanilla ai which is like a lot on this boss, temporary

**Comment by DerToaster98** [comment]
also please: there is a feature request template, please use that instead of the bug template

**Comment by SandwichHorror** [comment]
Gotcha, I was trying to lump 'em all in one issue page because several of the bosses had bugs and I didn't want to open up a hundred feature requests, especially when the line between bugfixing and a new feature request was blurred. 

Shelob was for sure the least buggy of all of them (ironic) so this post's ratio was mostly skewed towards the feature requests. I don't think I need to examine any more mobs as in-depth as these bosses, but if you do add any more I'll separate the bugs and features into two issues.
