### ISSUE TITLE
Server-side issue when generating dungeon

### ISSUE THREAD

**Issue by Zack7292** [TeamChocoQuest/ChocolateQuestRepoured#210]
**Common sense Info**
 - I play...
   - [x] With a large modpack
   - [ ] Only with CQR and it's dependencies
 - The issue occurs in...
   - [ ] Singleplayer
   - [x] Multiplayer
 - [x] I have searched for this or a similar issue before reporting and it was either (1) not previously reported, or (2) previously fixed  and I'm having the same problem.
 - [x] I am using the latest version of the mod (all versions can be found on github under releases)
 - [ ] I reproduced the bug without any other mod's except forge, cqr and it's dependencies
 - [x] The game crashes because of this bug
 
 
 **Versions**
Chocolate Quest Repoured: 26.1
Forge:2854
Minecraft:1.12.2

**Describe the bug**
while generating a dungeon of your mod inside a sever the server crashed

**To Reproduce**
go to a server and find a structure 

**Expected behavior**
the server crashed

**Screenshots**

![](https://cdn.discordapp.com/attachments/677119147615977472/725501761439400016/20200624_200346_HDR.jpg)

**Other**
Please note: log files and crash reports should be uploaded as a FILE and not as a copy paste of the text of it here. Upload the file to a site like pastebin or similar and link it here!!
 - Link to Crash report file: https://cdn.discordapp.com/attachments/677119147615977472/725502508998459502/crash-2020-06-24_17.03.13-server.txt
 - Link to Log file:
 - Other mods (that are necessary to produce the bug): your mod (as i know)
 - Other mods (that are also installed):  http://www.mediafire.com/file/cbdd61y31j12moz/InFex_V_Pr%25C3%25A9-0.0.3.zip/file
 - CQR config folder (link, only if you changed the configs):
 - Other mod's configs (link): in the file

**Comment by DerToaster98** [comment]
Won't be worked on until you reproduced this bug with solely forge and CQR and it's respective dependencies

**Comment by DerToaster98** [comment]
Also you are using a forge version not supported by us.
CQR depends on forge 2847, you are using 2854

**Comment by DerToaster98** [comment]
Also I can see that you didn't even bother to read the changelog and the update instructions inside of them!
You will have more problems (or it is even caused by this) if you do not update the mod correctly.
To update it correctly you need to stop your server, then you go into the config folder and DELETE OR RENAME (it has the same effect) the CQR folder and the cqrepoured.cfg file, then restart your server

**Comment by Zack7292** [comment]
might have forgot to remove it for the 27th time yea (since i've removed it dozens of times for this reason) and ima try to reproduce it alone, but i won't change my forge version, i'll come back with this probably tomorrow since my friend that got the server and everything is not free today,

**Comment by DerToaster98** [comment]
if you won't change the forge version we are unable to help, if it still crashes without changing the forge version it is cause of you using the wrong forge version

**Comment by Zack7292** [comment]
just a question tho: why don't you update to the latest forge? (i'll change it if it still crash btw)

**Comment by DerToaster98** [comment]
Cause the latest isn't always the best in terms of APIs and frameworks.
Also 2847 was the recommended version for 1.12.2 for a long time

**Comment by Zack7292** [comment]
yea true

**Comment by Zack7292** [comment]
crash still happen with the wrong forge version now we will gonna try with the good one

**Comment by Zack7292** [comment]
now, wth the good forge version, in serve ri don't even see what's inside of most creative tab the only one i see is the banner one, when i'm in solo tho they are still normally rendered (with latest forge too)

**Comment by Meldexun** [comment]
Can we have a log file? The crash report just says that a single tick took to long. So you could just increase the max-tick-time settings in the server.properties (if it's not caused by an infinite loop it should solve the problem).

**Comment by DerToaster98** [comment]
Closed cause of issue opener being unwilling to cooperate
