### ISSUE TITLE
Signifigantly more RAM use with custom dungeons

### ISSUE THREAD

**Issue by theland10** [TeamChocoQuest/ChocolateQuestRepoured#211]
**Common sense Info**
 - I play...
   - [x] With a large modpack
   - [ ] Only with CQR and it's dependencies
 - The issue occurs in...
   - [x] Singleplayer
   - [x] Multiplayer
 - [x] I have searched for this or a similar issue before reporting and it was either (1) not previously reported, or (2) previously fixed  and I'm having the same problem.
 - [x] I am using the latest version of the mod (all versions can be found on github under releases)
 - [x] I reproduced the bug without any other mod's except forge, cqr and it's dependencies
 - [ ] The game crashes because of this bug
 
 
 **Versions**
Chocolate Quest Repoured: Latest 1.20.1A
Forge: 14.23.5.2854
Minecraft: 1.12.2

**Describe the bug**
I have converted ~122 structures to CQR dungeons and created custom categories for some. With these dungeons installed the game uses significantly more RAM. I was able to reproduce the issue using only CQR and it's dependencies.

With only CQR and the default CQR dungeons and 8GB of ram allocated ram usage hovers between 12-25%.
With only CQR and my custom dungeons installed and 8GB of ram allocated ram usage hovers between 58-70%

You can download a copy of my CQR config folder here:
http://www.mediafire.com/folder/ld06axp2eqtam/CQR

**Comment by Meldexun** [comment]
So that download link is pretty useless because i don't have mediafire premium and thus i would have to download every file separately.

Also this is not a bug and everything is working as intended. At least mostly. So the default configuration for the structure caching might not be optimal. The default config will be changed in a future release. Till then I would suggest you to change cqrepoured.cfg -> advanced -> cachedStructureFilesMaxSize to 1 or 2.

**Comment by theland10** [comment]
Sorry, I did not realize that about mediafire. I knew I should've just zipped it and been done with it.

I asked about the ram issue on the wiki and was asked to post it here issue tracker. I did not even realize that config file existed. I thought all the configs were within the CQR folder.  I have since turned off structure caching entirely and it works like a charm.

Thanks!

**Comment by DerToaster98** [comment]
> 
> 
> So that download link is pretty useless because i don't have mediafire premium and thus i would have to download every file separately.
> 
> Also this is not a bug and everything is working as intended. At least mostly. So the default configuration for the structure caching might not be optimal. The default config will be changed in a future release. Till then I would suggest you to change cqrepoured.cfg -> advanced -> cachedStructureFilesMaxSize to 1 or 2.

Actually you don't need mediafire premium. You can download it using JDownloader.

**Comment by Meldexun** [comment]
Fixed since v1.21.0
