### ISSUE TITLE
No recipes for items?!

### ISSUE THREAD

**Issue by phantomiasXVI** [TeamChocoQuest/ChocolateQuestRepoured#212]
**Common sense Info**
 - I play...
   - [x ] With a large modpack
   - [ ] Only with CQR and it's dependencies
 - The issue occurs in...
   - [x ] Singleplayer
   - [x ] Multiplayer
 - [ ] I have searched for this or a similar issue before reporting and it was either (1) not previously reported, or (2) previously fixed  and I'm having the same problem.
 - [ x] I am using the latest version of the mod (all versions can be found on github under releases)
 - [ ] I reproduced the bug without any other mod's except forge, cqr and it's dependencies
 - [ ] The game crashes because of this bug
 
 
 **Versions**
Chocolate Quest Repoured: Newest as of 27 Juli 2020
Forge: Forge 1.12.2 V. 14.23.5.2854
Minecraft: 1.12.2

**Describe the bug**
I don't know if there is a bug happening or if the feature hasn't been added jet. I think there are some recipes missing for example: Slime armor can't be crafted (even though there is the item called Regenerating Slime Ball),same goes for the bull armor with ist bull leahter
There is also a texture missing (Flamethrower)

Maybe I am wrong or other mods im using are causing issues. But non the less there are it least some issues with other mods.

Happy to have this Mod:)
Looking Forward to coming updates

**To Reproduce**
2. Use item 'Regenerating Slime Ball and try making armor with it'
3. Place block '....'
.
.
.

**Expected behavior**

Armor to be craftable with items such as Regenerating Slime Ball

**Screenshots**

**Other**
Please note: log files and crash reports should be uploaded as a FILE and not as a copy paste of the text of it here. Upload the file to a site like pastebin or similar and link it here!!
 - Link to Crash report file:
 - Link to Log file:
 - Other mods (that are necessary to produce the bug):
 - Other mods (that are also installed):About 100 more 
 - CQR config folder (link, only if you changed the configs):
 - Other mod's configs (link):

**Comment by DerToaster98** [comment]
There are no recipes and that is intended. Only recipe in the mod should be the one for cloud boots.

Missing textures are not a bug, that is just something that hasn't been added yet.
