### ISSUE TITLE
Errors spammed in console

### ISSUE THREAD

**Issue by pjindras** [TeamChocoQuest/ChocolateQuestRepoured#213]
**Common sense Info**
 - I play...
   - [ ] With a large modpack
 - The issue occurs in...
   - [ ] Multiplayer
 - [ ] I have searched for this or a similar issue before reporting and it was either (1) not previously reported, or (2) previously fixed  and I'm having the same problem.

https://pastebin.com/E9bundQm
 
 
 **Versions**
Chocolate Quest Repoured: Alpha 26.1
Forge: 14.23.5.2836
Minecraft: 1.12.2

**Describe the bug**
Errors spammed in my server console, idk what it means.

**To Reproduce**
Run it on hexxcore server -> technicpack -> hexxcore -> %appdata% .technic hexxcore lanfiles

If you need my config or something else tell me and i will post it here.

Thanks

**Comment by DerToaster98** [comment]
you use an way too old foreg version. and it looks like you are running spongeforge or sponge on your server, we do not support that software
