### ISSUE TITLE
Dungeons spawning

### ISSUE THREAD

**Issue by pjindras** [TeamChocoQuest/ChocolateQuestRepoured#214]
**Common sense Info**
 - I play...
   - [ ] With a large modpack

 - The issue occurs in...

   - [ ] Multiplayer

 - [ ] I am using the latest version of the mod (all versions can be found on github under releases)

 
 
 **Versions**
Chocolate Quest Repoured: Alpha 27
Forge: 14.23.5.2836
Minecraft: 1.12.2

**Describe the bug**

Hi
Is it possible to spawn dungeons in biomes o plenty biomes?
My config looks like this: https://pastebin.com/4LDzJgsk

but i cant find any dungeon, any castle, any ship etc ... 

I have traveled many chunks but still nothing, i dont see any error, but i dont know what to do ...

Start log: https://pastebin.com/v8cdS3J4

(i know that the sponge is not supported by you but i dont see any conflict with it)

**Comment by DerToaster98** [comment]
you need to enter the biomes in correctly, you just do "value", but you need to do "key:value" (e.g. "minecraft:plains"), please refer to the wiki on how to do this, it is documented there

**Comment by DerToaster98** [comment]
But just for clearance: cqr works fine with bop, problem is your config here

**Comment by KirinFuji** [comment]
Might want to update that link to actually explain that you need to do <modid>:<biome_name>. I had to search until your explanation on this issue page to get the information. And yeah BoP works if  you throw in the biomes just this information is unnecessarily hidden...
