### ISSUE TITLE
Game freezes upon spawning Gremlin

### ISSUE THREAD

**Issue by guisvv** [TeamChocoQuest/ChocolateQuestRepoured#215]
**Common sense Info**
 - I play...
   - [x] With a large modpack
   - [ ] Only with CQR and it's dependencies
 - The issue occurs in...
   - [x] Singleplayer
   - [ ] Multiplayer
 - [x] I have searched for this or a similar issue before reporting and it was either (1) not previously reported, or (2) previously fixed  and I'm having the same problem.
 - [x] I am using the latest version of the mod (all versions can be found on github under releases)
 - [ ] I reproduced the bug without any other mod's except forge, cqr and it's dependencies
 - [kind of] The game crashes because of this bug
 
 
 **Versions**
Chocolate Quest Repoured: 1.21.0A
Forge: 14.23.5.2854
Minecraft: 1.12.2

**Describe the bug**
Get a gremlin spawn egg and use it. The mob won't spawn. Then, the game will "freeze": no other spawn egg will work, no chat messages will be sent (even in singleplayer). After trying to close the game, the minecraft launcher will pop up "the game has stopped working" (or something like that; my windows is in portuguese and so is the in-launcher popup message)

**To Reproduce**
1. Go to anywhere
2. Use item gremlin spawn egg
3. See error

**Expected behavior**
I expected the gremlin to spawn normally.

**Other**
 The game doesn't produce a crash report (at least it didn't in the two times the error occured. in both times i force closed the game, without waiting for it to properly crash.)
 - Other mods (that are also installed): AE2, BetterGeo, DynamicSurroundings, Traveler'sBackpack, JEI, IC2, Immersime Engineering, Fossils and Archeology, Biomes o Plenty (the worldtype i was using was not the BoP one since i don't know how to config the dungeons to spawn in modded biomes), some minor others
 - CQR config folder (link, only if you changed the configs): no config was changed

**update:** i tried spawning the nether dragon through an egg and the same thing happened. i didnt try spawning all mobs, but the mobs that spawned correctly are: giant lava silferfish, pollo/weird chicken, dummy, cqr zombie, ogre. this time, instead of force closing the game, i saved and quit to title and then rejoined the world. a "nether dragon" boss bar appeared on my screen, and a weird white flying snake-like thing appeared. i tried getting close to it to see its WAILA tag and see if it was the nether dragon but it kept running away. no sign of any gremlin though

**Comment by DerToaster98** [comment]
First things first: That "weird white flying snake-like thing" is the nether dragon.
Second: The mod works with BoP if configured correctly, should however work out of the box but may not support all biomes
Third: This "bug" is not reproduceable with only CQR, it either is you got that build from unofficial sites or assembled it yourself or another mod in your setup likes fucking around with other mod's entity AI or entities in general
