### ISSUE TITLE
Dungeon spawned at the end portal

### ISSUE THREAD

**Issue by GreenBudgie** [TeamChocoQuest/ChocolateQuestRepoured#216]
Dungeonspawned right in the Stronghold and the end portal disappeared because of it.
I play with custom modpack (singleplayer) with no conflicting mods, I guess.
![screenshot](https://user-images.githubusercontent.com/37713157/89112310-866a7600-d469-11ea-9a8d-5ecae37efac4.png)

**Comment by DerToaster98** [comment]
Thsi "bug" occurs cause ther eis no proper way to detect other mod's (minecraft is treated as such too in this context) structures, can't and won't be fixed.
