### ISSUE TITLE
Chocolate Quest Repoured/Open Terrain Generator Compatibility Issue

### ISSUE THREAD

**Issue by Fuedra** [TeamChocoQuest/ChocolateQuestRepoured#218]
**Common sense Info**
 - I play...
   - [X] With a large modpack
   - [ ] Only with CQR and it's dependencies
 - The issue occurs in...
   - [X] Singleplayer
   - [ ] Multiplayer
 - [X] I have searched for this or a similar issue before reporting and it was either (1) not previously reported, or (2) previously fixed  and I'm having the same problem.
 - [X] I am using the latest version of the mod (all versions can be found on github under releases)
 - [ ] I reproduced the bug without any other mod's except forge, cqr and it's dependencies
 - [ ] The game crashes because of this bug
 
 
 **Versions**
Chocolate Quest Repoured: 1.21.0A
Forge: 14.23.5.2854
Minecraft: 1.12.2

**Describe the bug**
OK, I seem to have found a compatibility issue between Chocolate Quest Repoured and the Open Terrain Generator mod, specifically with the Biomes Bundle O'Plenty. It seems that the spawning mechanics for the various dungeons conflict with how Open Terrain Generator constructs the world, and it causes the dungeons to spawn on a delay which often overwrites other areas entirely, such as villages and other structures in the world.

I have tested this with just Chocolate Quest Repoured, Open Terrain Generator, and Biomes Bundle O'Plenty installed along with their dependencies and the issue still persists.

I don't know if there will ever be a way to fix this, but I thought you should know.

**To Reproduce**
1. Ope the game with Chocolate Quest Repoured, Open Terrain Generator, and Biomes Bundle O'Plenty installed along with their dependencies, and then simply create a new world under the OTG World Option (Set to Creative if you want to move around the world faster).
2. Simply Travel around the world a bit, though preferable look out for places like villages or other structures, and then wait for the chunks to load a bit around that area, as the chunks loading seems to cause this bug to occur, and if you are near a village when this happens, it will often get erased or cut in half.

**Expected behavior**
I have seen this mod used in multiple mod packs in several lets plays, including CaptainSparklez Hexxit let's play, back when it was called the Better Dungeons Mod, and from what I have seen the dungeons spawned do not cut into or erase villages or other default structures. My best bet is it has to do with how Open Terrain Generator builds worlds, for when I played with it without Open Terrain Generator, the structures were already in the world, but since I have added Open Terrain Generator and Biomes Bundle O'Plenty to my growing modpack, the structures don't load into the world till after you have waited around an area for the chunks to finish loading, and then they begin building themselves out of nowhere like using those dungeon spawners in creative mode, except I'm not the one triggering them, they are just happening at random.

**Screenshots**
I will try tomorrow to grab screenshots, but it is rather late and I just want to get this posted for now.

**Comment by DerToaster98** [comment]
That "delay" is not a bug, it is intended behavior to reduce lag. 
Yes, the structures are unable to detect other mod's structures or villages, we won't add that cause there are way too many different ways mods are generating structures.

Better dungeons also did that. CQR and BD generates the structures based on a grid, both don't care about if a village or a similar thing sits on that grid. However, this "bug" (which isn't a bug) is pretty rare as it is dependant on 2 random values.

It is neither an issue with OTG or CQR.
The delay is best noticeable when the game is pretty busy placing a lot of blocks, so yes, it is more present with OTG as it generates more landmass than vanilla.

**Comment by DerToaster98** [comment]
However, thank you for reporting this, it got me to rethink the current way of avoiding to detect villages.

Result is: in the next update the generation will respect vanilla structures nearby and will eventually cancel the dungeon generation when it is too near (Tested it and it works, it however probably won't work with modded structures)

**Comment by Fuedra** [comment]
Ah, cool, thank you for the reply, and for the illumination on how the mod
runs. As for the generation itself, I have learned to live with it, but it
will be cool to see that update when it comes around, for as I mentioned on
the page itself, I never got to experience it back in 1.7.10 when it was
originally Better Dungeons and it is fun being able to experience the mod
for myself.
