### ISSUE TITLE
Partially implemented items

### ISSUE THREAD

**Issue by xJon** [TeamChocoQuest/ChocolateQuestRepoured#219]
**Info**
 - I play...
   - [ ] With a large modpack
   - [x] Only with CQR and it's dependencies
 - The issue occurs in...
   - [X] Singleplayer
   - [ ] Multiplayer
 - [X] I have searched for this or a similar issue before reporting and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
 - [X] I am using the latest version of the mod (all versions can be found on github under releases)
 - [X] I reproduced the bug without any other mod's except forge, cqr and it's dependencies
 - [ ] The game crashes because of this bug
 
 
 **Versions**
Chocolate Quest Repoured: `1.21.3A`
Forge: `14.23.5.2854`
Minecraft: `1.12.2`

**Describe the bug**
Hi,
I've been testing the mod thoroughly at its current state & I want to ask regarding partially implemented items.
I am aware some of the items in the mod are unfinished, but some seem to work perfectly apart from small needed changes.
Here is my list for your reference:

**Screenshots**
Thunder Staff seem to work, yet only missing a tooltip description
![Screenshot_1](https://user-images.githubusercontent.com/8945347/90999670-ea4b0f00-e5cf-11ea-9281-d6d5c595a14d.png)

King Crown renders above head and not over head
![Screenshot_2](https://user-images.githubusercontent.com/8945347/90999663-e7e8b500-e5cf-11ea-9109-a23401873d27.png)

Spiked Glove doesn't do any extra damage
![Screenshot_4](https://user-images.githubusercontent.com/8945347/90999666-e9b27880-e5cf-11ea-96e1-d9e855d627f5.png)

Alchemy Bag does not accept potions
![Screenshot_5](https://user-images.githubusercontent.com/8945347/90999668-e9b27880-e5cf-11ea-8604-f70f3c9271d5.png)

Full Bull Armor set does not seem to provide the charging ability
![Screenshot_6](https://user-images.githubusercontent.com/8945347/91000265-6eea5d00-e5d1-11ea-9cb6-8be131605148.png)

Gun Staff doesn't shoot ammo & current bullet texture is missing
![Screenshot_3](https://user-images.githubusercontent.com/8945347/90999665-e919e200-e5cf-11ea-85af-bf2a6d68835a.png)

Thank you for working on this project!

**Comment by DerToaster98** [comment]
All those ARE NO BUGS, except the potion bag one, which actually works in my copy.

- Thunder Stuff: Will be removed, and the functionality is there
- Crown: That is supposed, it IS NOT A HELMET, a crown is worn on the top of the head, not over it
- Spiked Gloves: They are not meant to deal extra damage. They are meant to climb walls, equip one in each hand and walk against a wall
- Bull armor: charging ability is NYI
- Gun Staff: Also NYI

**Comment by DerToaster98** [comment]
Oh wait: On alchemy bag: that is supposed. That item is not meant to be used by players. It is for equipping mobs, it only accepts throwable potions and lingering potions. It is given to mobs so that they can throw those potions. Won't receive functionality for players.

**Comment by DerToaster98** [comment]
not directly, you would need to modify the code. However, those will receive a tooltip someday
