### ISSUE TITLE
Crafting dyable armor

### ISSUE THREAD

**Issue by xJon** [TeamChocoQuest/ChocolateQuestRepoured#220]
**Info**
 - I play...
   - [ ] With a large modpack
   - [x] Only with CQR and it's dependencies
 - The issue occurs in...
   - [X] Singleplayer
   - [ ] Multiplayer
 - [X] I have searched for this or a similar issue before reporting and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
 - [X] I am using the latest version of the mod (all versions can be found on github under releases)
 - [X] I reproduced the bug without any other mod's except forge, cqr and it's dependencies
 - [ ] The game crashes because of this bug
 
 
 **Versions**
Chocolate Quest Repoured: `1.21.3A`
Forge: `14.23.5.2854`
Minecraft: `1.12.2`

**Describe the bug**
Crafting dyable armor with multiple pieces placed together is glitchy:
![gif](https://user-images.githubusercontent.com/8945347/91000557-17002600-e5d2-11ea-95c7-7d7d9639d3d6.gif)

**Comment by DerToaster98** [comment]
Is a bug but not a critical one. May be fixed sometimes

**Comment by DerToaster98** [comment]
Will be fixed in next update
