### ISSUE TITLE
Issue with going through nether portal? 

### ISSUE THREAD

**Issue by captinalex1** [TeamChocoQuest/ChocolateQuestRepoured#222]
**Common sense Info**
 - I play...
   - [x] With a large modpack
   - [ ] Only with CQR and it's dependencies
 - The issue occurs in...
   - [x] Singleplayer
   - [x] Multiplayer
 - [x] I have searched for this or a similar issue before reporting and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
 - [x] I am using the latest version of the mod (all versions can be found on github under releases)
 - [ ] I reproduced the bug without any other mod's except forge, cqr and it's dependencies
 - [x] The game crashes because of this bug
 
 
 **Versions**
Chocolate Quest Repoured: Alpha 27.3
Forge: 14.23.5.2847
Minecraft: 1.12.2

**Describe the bug**
What happens is everything runs smoothly and I can play fine and use the dungeons fine. I can fight without issue. What does happen is that when I go to the nether, I can go there fine, the problem occurs is when I come back. When loading into the overworld, I get a crash saying, Server Tick loop both in single and on my server. I've deleted the JSON files that are called, ops.jason and whitelist.json and it does let me back into the map only to occur again. I don't know what I did wrong or what is causing the issue. I'm not new to Minecraft modding either, been playing with mods since Minecraft Beta back in 2012. I've fixed issues before but not sure how to fix this one. 

**To Reproduce**
Go to the nether and then go through the portal and come back. I am playing on the Enigmatica 2 Expert modpack, and added the mods shown in the crash log posted to this message.

**Expected behavior**
What should happen is me coming back without a server tick loop.
[crash-2020-08-27_04.32.46-server.txt](https://github.com/TeamChocoQuest/ChocolateQuestRepoured/files/5139538/crash-2020-08-27_04.32.46-server.txt)

I also have 8 GBs of ram dedicated both to my client and server, that should be more than plenty. I'm the only player on the server I made.

**Comment by DerToaster98** [comment]
Bug will be fixed in one of the next builds.

However there is no clear reason for this bug to occur. Please try the following: Reproduce the bug only with CQR and it's dependencies, if it does not occur there, try adding the mods one by one and find out which mod causes that bug

**Comment by captinalex1** [comment]
I can look into that mhm! Something odd I did notice is so far I've been playing all night, about 8 hours just now after posting this post, I had gone into the nether and died and spawned back at home without issue. Not sure if when I set up the server, I did something or when config files being changed bugged the mod but so far things have been fine. Seems like you have an idea, what normally causes Tick Loops? Just so I know when running into them what I can do to fix or make sure they don't happen again. Thanks for your time! ^w^
Love the mod, and appreciate it being brought back. It carries so many memories with me back in Release days of MC.

**Comment by DerToaster98** [comment]
Your problem is not a tick loop. it is a null pointer exception occuring on when the world tries to save.

**Comment by DerToaster98** [comment]
the json files you mentioned are not from cqr, btw

Also "Exception in server tick loop" pretty much only means like "Something on the main server thread went wrong"

**Comment by captinalex1** [comment]
Oh I understand now. Guess I read the crash report wrong. I will look into trying cqr and its dependantsies by themselves and seeing if it happens again. But after creating this post, and continuing to play, things seem fine. Aroma Backups were backing up without issues, teleporting was working, testing the nether and trying to show my brother the crash, actually worked when I went there. Still wanna test a few more things but yeah, I don't think it magicly sorted itself out.

**Comment by captinalex1** [comment]
For the Json files, I just did that cause thats what I read when googling tick loop thinking that was my issue. Learning new things never stops. :p

**Comment by DerToaster98** [comment]
Issue should be patched in version 1.21.4A, you can download it here: [Download](https://cq-repoured.net/alpha-27-4/)

**Comment by captinalex1** [comment]
Thanks so much, I'll download and test it after work tonight. ^^

**Comment by captinalex1** [comment]
From what I can tell with some playing around, it's fixed. :D 
I'll close the issue since its fixed.
