### ISSUE TITLE
CQR structures arent generating at all, but others do.

### ISSUE THREAD

**Issue by Mateusz7073** [TeamChocoQuest/ChocolateQuestRepoured#223]
**Common sense Info**
 - I play...
   - [x] With a large modpack
   - [ ] Only with CQR and it's dependencies
 - The issue occurs in...
   - [x] Singleplayer
   - [ ] Multiplayer
 - [x] I have searched for this or a similar issue before reporting and it was either (1) not previously reported, or (2) previously fixed  and I'm having the same problem.
 - [x] I am using the latest version of the mod (all versions can be found on github under releases)
 - [ ] I reproduced the bug without any other mod's except forge, cqr and it's dependencies
 - [ ] The game crashes because of this bug
 
 
 **Versions**
Chocolate Quest Repoured: alpha 27.3
Forge:
Minecraft: 1.12.2

**Describe the bug**
Im just exploring the map of my world 

**To Reproduce**
You cant really reproduce it, Im playing on huge modpack made by myself. But I have a question. Look, before I have added more mods to my modpack everything was fine, CQR structures wasnt rare at all, the only mod I have added that changes the way in world generates is "climate control/geographicraft" which allows to generate the world in more realistic way. few days ago I have created a new world and after discovering a HUGE amount of my world, I have noticed that CQR structures arent generating at all, but structures from many other mods do. Could CQR be not compatible with this mod? 

**Expected behavior**
nah

**Screenshots**
nah

**Other**
Please note: log files and crash reports should be uploaded as a FILE and not as a copy paste of the text of it here. Upload the file to a site like pastebin or similar and link it here!!
 - Link to Crash report file:
 - Link to Log file:
 - Other mods (that are necessary to produce the bug):
 - Other mods (that are also installed):
 - CQR config folder (link, only if you changed the configs):
 - Other mod's configs (link):

**Comment by Meldexun** [comment]
I just generated a world with CQR, Climate Control and Chunk Pregenerator and dungeons were generating fine.

So could you follow these:
- deleting 'minecraft/config/CQR' and 'minecraft/config/cqrepoured.cfg'
- Launch minecraft
- Open the ingame config of CQR
- Set 'general -> dungeonSeparation' and 'general -> dungeonSpawnDistance' to 8
- Create a new world and explore the world
- Close minecraft
If you haven't found any dungeons:
- Open the 'minecraft/logs' folder and upload the latest.log file here

**Comment by Mateusz7073** [comment]
After I have found the first CQR structure building in my survival world it looked like this:
![2020-09-03_16 53 14](https://user-images.githubusercontent.com/64229729/92136930-e65b9000-ee0c-11ea-88a6-7021b996f66f.png)

I dunno what can cause it

**Comment by Meldexun** [comment]
That's a known typing error. Just open minecraft\config\CQR\dungeons\RandomizedCastles.properties and change 'supportblocktop = minecraft:glass' to 'supportblocktop = minecraft:grass'.
Also because that is another problem a new should be created instead of commenting on an existing issue (no need to that for this probelm though because it's already knwon and solved in development).
