### ISSUE TITLE
Feature request.

### ISSUE THREAD

**Issue by Mateusz7073** [TeamChocoQuest/ChocolateQuestRepoured#224]
# **General Info**
 - This is a..
   - [ ] Change request
   - [x] Feature request
 - [ ] This has already been asked before and the answer was 'No'
 - [ ] This has already been implemented by another mod (which is compatible) 
^I got the idea from Millenaire mod feature item "wand of Negation", but it works in a bit diffrent way.

# **Description**
Im requesting for a wand, that would remove dungeons basing on their dimensions

## Why should it be in the mod?
This is a weird feature request, because I know that this could be really hard to do (or perhaps impossible) but it could be really helpful. Im just bit frustrated because sometimes I want simply to destroy a CQR structure for some aesthetic reasons, but most of them are just HUGE, and destroying it manually with tnt is just painful, even with construction mods installed it is a great challenge to remove them...

## Detailed description
I think that there could be a single-use wand, which would drop from some of the dungeon bosses. It simply would allow to despawn a dungeon. If the player is willing to remove a dungeon, and he thinks that he have taken all needed valuables from it, with this wand he could despawn most of structures without any problems. There shouldnt be any drop from doing so, It should remove everything included in the generated structure and it should only work on dungeons which arent caves. 

# **Others**
*If you have something like a small code that implements your idea just post it here, this also includes things like models or textures for example*

**Comment by DerToaster98** [comment]
I recommend you this to destroy the structures: https://www.curseforge.com/minecraft/mc-mods/icbm-classic

Removing the dungeons with such a want is possible in theory. But it would either regenerate the covered terrain or just place air blocks in the volume of the protection zone.

Also most players use the conquered dungeons as a home.

Won't be implemented, to implement this properly it is more effort than it is worth it.

**Comment by Mateusz7073** [comment]
Well okay, I will take a look at it. By the way I also would like to know what other team members think about that though, so I will probably close it tommorow if no more ppl will write here.

**Comment by DerToaster98** [comment]
OK, we talked this over in our secret dev layer. We all agreed that it is not worth the effort and won't implement it. 
Anyway, thank you however for sharing your idea
