### ISSUE TITLE
Increase the chance of dungeons generating

### ISSUE THREAD

**Issue by AdriPlaysz** [TeamChocoQuest/ChocolateQuestRepoured#227]
# **General Info**
 - This is a..
   - [ x ] Change request
   - [ ] Feature request
 - [ ] This has already been asked before and the answer was 'No'
 - [ ] This has already been implemented by another mod (which is compatible)

# **Description**
I Think it would be great to increase the amount of dungeons that can generate.

## Why should it be in the mod?
It is really frustrating to find a dungeon, because they are so rare, the dungeons themself are great, but I dont want to walk through this empty minecraft terrain for an hour just to find a dungeon.

## Detailed description
It feels like trying to find a woodland mansion but without being able to buy a map from the villagers.
Another reason why increasing the chance of dungeons generating is that it acts like a barrikade in the world, so you have to think outside the box and avoid the dungeons or kill everyone inside.

**Comment by DerToaster98** [comment]
You can increase the dungeon spawn chances by yourself. You just need to edit the config files and adjust the weights and spawn chances. Also they are not that rare like woodland mansions.
