### ISSUE TITLE
Add JEI categories for hide items

### ISSUE THREAD

**Issue by SettingDust** [TeamChocoQuest/ChocolateQuestRepoured#228]
# **General Info**
 - This is a..
   - [x] Change request
   - [ ] Feature request

 - [ ] This has already been asked before and the answer was 'No'
 - [ ] This has already been implemented by another mod (which is compatible)

# **Description**
## Basic description
Add JEI categories for hide useless items. Such as mobs, dungeons and banners

**Comment by DerToaster98** [comment]
seems unnecessary, more effort than it is worth.

**Comment by SettingDust** [comment]
@DerToaster98 Then, how to hide the dev items from JEI? One by one?

**Comment by DerToaster98** [comment]
We don’t. And there are no „dev items“. No one forces you to use these items and all items in the published releases are functional, same for mobs. Some may be not obtainable at the moment.

If you have such a big problem with it: uninstall the mod, seriously.

**Comment by SettingDust** [comment]
> 
> 
> We don’t. And there are no „dev items“. No one forces you to use these items and all items in the published releases are functional, same for mobs. Some may be not obtainable at the moment.
> 
> If you have such a big problem with it: uninstall the mod, seriously.

Just hide, not remove. I think they should be hidden from players' JEI.

**Comment by DerToaster98** [comment]
And i don't think so. It is unnecessary and (like i said) more effort than it is worth it.

If you however think that it is really really really really needed and 100% more important than all the other features we still have to do, feel free to create a pull request for this thing.

**Comment by LordEpos** [comment]
You can 100% configure JEI to hide items all on your own. I've done it myself in the past while designing modpacks. Chocolate Quest Repoured gives creative mode users access to these items to create their own custom dungeons. I know I personally still use JEI in creative mode, so I think it's a reasonable assumption that others do as well. If I'm understanding correctly what you want, this would actively hinder creative users.
