### ISSUE TITLE
JEI overlapping trading GUI

### ISSUE THREAD

**Issue by xJon** [TeamChocoQuest/ChocolateQuestRepoured#232]
**Common sense Info**
 - I play...
   - [ ] With a large modpack
   - [X] Only with CQR and it's dependencies
 - The issue occurs in...
   - [X] Singleplayer
   - [ ] Multiplayer
 - [X] I have searched for this or a similar issue before reporting and it was either (1) not previously reported, or (2) previously fixed  and I'm having the same problem.
 - [X] I am using the latest version of the mod (all versions can be found on github under releases)
 - [X] I read through the FAQ and i could not find something helpful ([FAQ](https://wiki.cq-repoured.net/index.php?title=FAQ))
 - [X] I reproduced the bug without any other mod's except forge, cqr and it's dependencies
 - [ ] The game crashes because of this bug
 
 
 **Versions**
Chocolate Quest Repoured: `2.1.0B`
Forge: `14.23.5.2854`
Minecraft: `1.12.2`

**Screenshots**
![image](https://user-images.githubusercontent.com/8945347/99928288-1aca5280-2d51-11eb-8eaa-cd40d94488ed.png)

**Comment by DerToaster98** [comment]
Press „ctrl + O“, that‘ll hide JEI

**Comment by xJon** [comment]
> Press „ctrl + O“, that‘ll hide JEI

Hey, I know of this, I just thought that most mods provide compatibility with JEI so why shouldn't CQR?

**Comment by DerToaster98** [comment]
Cause the priority for this is so low that it is not important. Also there doesn't seem to be documentation on this.

Most integration of mods with JEI is to support special recipes (for example Botania machines), and this is not the case.

**Comment by DerToaster98** [comment]
Also honestly, "compatibility" is something completely different. 

What compatibility means: "Software X can work alongside with software Y"
