### ISSUE TITLE
THERE IS ANOTHER BUG. CAN YOU HEAR VOICE? DICTATOR?

### ISSUE THREAD

**Issue by SettingDust** [TeamChocoQuest/ChocolateQuestRepoured#233]
https://github.com/TeamChocoQuest/ChocolateQuestRepoured/blob/7a25def62a014d4d4d5a96975a97b169b6ae0758/src/main/java/com/teamcqr/chocolatequestrepoured/structuregen/generators/castleparts/rooms/segments/CastleMainStructWall.java#L115

@DerToaster98 

Even not see what am I say? You know everything?

If I report a bug. I have to be kicked from Discord, is it?

**Comment by DerToaster98** [comment]
I do know of this. Do you think i am too stupid to properly use NPP to search through all files to find all scala improts? No. I do not need and do not want your help regarding such stuff

**Comment by DerToaster98** [comment]
I kicked you for you assuming that i am too stupid to use a goddamn file content search
