### ISSUE TITLE
Structure  from another mod coolidates

### ISSUE THREAD

**Issue by LUFICK** [TeamChocoQuest/ChocolateQuestRepoured#234]
**Common sense Info**
 - I just playing, then find pub structure. After a while freakin' Millenaire village spawns destroying half of a building :-((
 - [x] With a large modpack
 - [ ] Only with CQR and it's dependencies
 - The issue occurs in...
   - [x] Singleplayer
   - [ ] Multiplayer
 - [ ] I have searched for this or a similar issue before reporting and it was either (1) not previously reported, or (2) previously fixed  and I'm having the same problem.
 - [x] I am using the latest version of the mod (all versions can be found on github under releases)
 - [ ] I read through the FAQ and i could not find something helpful ([FAQ](https://wiki.cq-repoured.net/index.php?title=FAQ))
 - [ ] I reproduced the bug without any other mod's except forge, cqr and it's dependencies
 - [ ] The game crashes because of this bug
 
 
 **Versions**
Chocolate Quest Repoured: Chocolate_Quest_Repoured-1.12.2-2.1.2B
Forge: The newest
Minecraft: 1.12.2

**Describe the bug**
Village from Millenaire mod spawns destroying CQR structure, it's not the first time it happens
**To Reproduce**
2. Use item '....'
3. Place block '....'
.
.
.

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/60813657/100455683-65383000-30bf-11eb-930b-30aff1030438.png)

**Other**
Please note: log files and crash reports should be uploaded as a FILE and not as a copy paste of the text of it here. Upload the file to a site like pastebin or similar and link it here!!
 - Link to Crash report file:
 - Link to Log file:
 - Other mods (that are necessary to produce the bug): Millenaire (with Millenaire Extended mod included)
 - Other mods (that are also installed): ... lot of mods, but not necessary to a situation
 - CQR config folder (link, only if you changed the configs):
 - Other mod's configs (link):

> We sadly can't fix this. It depends on the other mod providing information to us to detect it's structure. Please report this to the other mod.
> 
> CQR can only detect some structures, in detail the normal vanilla structures. Reason simply is that there are almost as many ways to generate structures as there are mods that generate structures.

I agree. Millenaire spawning system is also pretty weird tho.

**Comment by DerToaster98** [comment]
We sadly can't fix this. It depends on the other mod providing information to us to detect it's structure. Please report this to the other mod.

CQR can only detect some structures, in detail the normal vanilla structures. Reason simply is that there are almost as many ways to generate structures as there are mods that generate structures.

**Comment by DerToaster98** [comment]
One thing i forgot: If you're going to report this to millenaire, please send us the link to that report too so we can talk with the millenaire team
