### ISSUE TITLE
Ticking Entity error

### ISSUE THREAD

**Issue by Tobias15th** [TeamChocoQuest/ChocolateQuestRepoured#235]
**Common sense Info**
 - I play...
   - [x] With a large modpack
   - [ ] Only with CQR and it's dependencies
 - The issue occurs in...
   - [x] Singleplayer
   - [ ] Multiplayer
 - [x] I have searched for this or a similar issue before reporting and it was either (1) not previously reported, or (2) previously fixed  and I'm having the same problem.
 - [x] I am using the latest version of the mod (all versions can be found on github under releases)
 - [x] I read through the FAQ and i could not find something helpful ([FAQ](https://wiki.cq-repoured.net/index.php?title=FAQ))
 - [ ] I reproduced the bug without any other mod's except forge, cqr and it's dependencies
 - [x] The game crashes because of this bug
 
 
 **Versions**
Chocolate Quest Repoured: 2.1.3B
Forge: 14.23.5.2847
Minecraft: 1.12.2

Hi, I have been having this issue for a while and want to know if anything can be done.

It happened while I was raiding a walled village with the illager guards and a giant tortoise in the sewer. After quitting and reloading, it crashes as soon as I enter the world, the crash report is attached.

[crash-2020-12-08_22.11.23-server.txt](https://github.com/TeamChocoQuest/ChocolateQuestRepoured/files/5662382/crash-2020-12-08_22.11.23-server.txt)

If I am missing anything or if you need anything else, just let me know.

Thanks in advance.

**Comment by Meldexun** [comment]
Not caused by cqr. Should be reported to the fish mod/lava cow mod (not sure what the name of that mod is)
