### ISSUE TITLE
Redstone not functioning properly in Shelob Castle

### ISSUE THREAD

**Issue by Dreyethel** [TeamChocoQuest/ChocolateQuestRepoured#238]
**Common sense Info**
 - I play...
   - [ ] With a large modpack
   - [X ] Only with CQR and it's dependencies
 - The issue occurs in...
   - [ X] Singleplayer
   - [ ] Multiplayer
 - [X ] I have searched for this or a similar issue before reporting and it was either (1) not previously reported, or (2) previously fixed  and I'm having the same problem.
 - [ X] I am using the latest version of the mod (all versions can be found on github under releases)
 - [ X] I read through the FAQ and i could not find something helpful ([FAQ](https://wiki.cq-repoured.net/index.php?title=FAQ))
 - [ X] I reproduced the bug without any other mod's except forge, cqr and it's dependencies
 - [ ] The game crashes because of this bug
 
 
 **Versions**
Chocolate Quest Repoured: 2.1.3B
Forge: 14.23.5.2854
Minecraft: 1.12.2

**Describe the bug**
After triggering the "Loot-> Falling Sand" trap, the secret door leading to the necromancer does not open correctly. It appears to be that a piece of carpet is getting in the way of the piston, so only one block is being pushed instead of two. This prevents the player from accessing the necromancer, who must be killed before the player can break blocks and fix the issue manually (without using creative).

**To Reproduce**

1. Go to the Castle containing Shelob
2. Get to the room with the sign saying "loot --->"
3. Press the button at the end of the loot corridor
4. Walk back to the room with the sign
5. See error

**Expected behavior**
The door should open all the way.

**Screenshots**

![2021-01-04_10 56 02](https://user-images.githubusercontent.com/76965785/103564224-23ec2a80-4e8c-11eb-97fe-9d18982fe8e4.png)

![2021-01-04_12 58 09](https://user-images.githubusercontent.com/76965785/103564559-bab8e700-4e8c-11eb-9027-a5f7f6e3abd0.png)

**Other**
Please note: log files and crash reports should be uploaded as a FILE and not as a copy paste of the text of it here. Upload the file to a site like pastebin or similar and link it here!!
 - Link to Crash report file:
 - Link to Log file:
 - Other mods (that are necessary to produce the bug):
 - Other mods (that are also installed):
 - CQR config folder (link, only if you changed the configs):
 - Other mod's configs (link):

**Comment by DerToaster98** [comment]
Which exact castle is it? There is no „shelob castle“

**Comment by Dreyethel** [comment]
![2021-01-04_13 06 47](https://user-images.githubusercontent.com/76965785/103565128-c48f1a00-4e8d-11eb-91ba-2af5f0207bf9.png)

Apologies, this one!

**Comment by DerToaster98** [comment]
Thanks

**Comment by LordEpos** [comment]
Fixed for the next release, thanks for the report :)
