### ISSUE TITLE
Structure spawning

### ISSUE THREAD

**Issue by I3estOFF** [TeamChocoQuest/ChocolateQuestRepoured#240]
# **General Info**
 - This is a Feature request

# **Description**
## Basic description
Command/item which can spawn chosen structure, or list of stuctures with images

## Why should it be in the mod?
For modpack creators, to see how structure looks

**Comment by DerToaster98** [comment]
Such items already exist.

**Comment by I3estOFF** [comment]
In 1.12.2? how i can generate structure? which item?

**Comment by DerToaster98** [comment]
Structure spawning items, they have their own creative tab.

**Comment by DerToaster98** [comment]
Also we have screenshots of all structures available on our [website](https://www.cq-repoured.net/)

**Comment by I3estOFF** [comment]
I saw in config that i can disable one type of dungeon like ,,Castle".
But  don't want to delete all of them, some of them are just too big for my modpack, is here an option to disable just one of castles?
