### ISSUE TITLE
Trying to use some thermal foundation's liquids will crash the game

### ISSUE THREAD

**Issue by TCreopargh** [TeamChocoQuest/ChocolateQuestRepoured#241]
**Common sense Info**
 - I play...
   - [x] With a large modpack
   - [ ] Only with CQR and it's dependencies
 - The issue occurs in...
   - [x] Singleplayer
   - [ ] Multiplayer
 - [x] I have searched for this or a similar issue before reporting and it was either (1) not previously reported, or (2) previously fixed  and I'm having the same problem.
 - [x] I am using the latest version of the mod (all versions can be found on github under releases)
 - [x] I read through the FAQ and i could not find something helpful ([FAQ](https://wiki.cq-repoured.net/index.php?title=FAQ))
 - [x] I reproduced the bug without any other mod's except forge, cqr and it's dependencies
 Reproduced this with only cqr, thermal series and their dependencies
 - [x] The game crashes because of this bug
 
 
 **Versions**
Chocolate Quest Repoured: 2.2.1
Forge: 14.23.5.2855
Minecraft: 1.12.2

**Describe the bug**
Creosote Oil or Liquifacted Coal are liquids from thermal foundation, when trying to pour any liquid container containing them, or use these liquids for power generators etc, the game immediately crashes.

**To Reproduce**
1. Install cqr and thermal series
2. Use the creosote oil bucket
3. Boom, crash!

**Expected behavior**
It doesnt crash

**Screenshots**
none

**Other**
Please note: log files and crash reports should be uploaded as a FILE and not as a copy paste of the text of it here. Upload the file to a site like pastebin or similar and link it here!!
 - Link to Crash report file: https://paste.ubuntu.com/p/Rfd2M47hKN/
 - Link to Log file:
 - Other mods (that are necessary to produce the bug): Thermal foundation
 - Other mods (that are also installed): thermal foundation's dependencies
 - CQR config folder (link, only if you changed the configs): unchanged
 - Other mod's configs (link): unchanged

**Comment by DerToaster98** [comment]
This is caused by thermal not implementing fluidstacks properly. Please report it to them.

**Comment by TCreopargh** [comment]
Hmm here comes a problem, looks like their issue tracker is closed

**Comment by DerToaster98** [comment]
we can't properly patch this on our end. We *can* prevent the crash, but that causes mechanics to not work properly

**Comment by TCreopargh** [comment]
I put this issue in their discord channel, hope they can look into it

**Comment by DerToaster98** [comment]
You should probably report it to COFh core too, since all liquids from thermal use cofh-core as base classes and i think the issue derives from there.

**Comment by TCreopargh** [comment]
they use the same bug report zone for all cofh mods

**Comment by TCreopargh** [comment]
They told me that 1.12 isn't being supported anymore and won't get bug fixes :(

**Comment by DerToaster98** [comment]
ok, then we can try something on our end, but this has pretty low priority

**Comment by DerToaster98** [comment]
We made a patch for this, update will be available when we publish it.

**Comment by KingLemming** [comment]
Point to me where we weren't "implementing FluidStacks properly."

I just saw your fix. Seems that you weren't actually checking to see if it could be placed in world and just made some bad assumptions.

**Comment by DerToaster98** [comment]
Bug still existing in 2.2.2.B, created new issue #243
