### ISSUE TITLE
Suggestion: Weapon Modifier config

### ISSUE THREAD

**Issue by Glassimo-1** [TeamChocoQuest/ChocolateQuestRepoured#244]
# **General Info**
 - This is a..
   - [ ] Change request
   - [x] Feature request
 - [ ] This has already been asked before and the answer was 'No'
 - [ ] This has already been implemented by another mod (which is compatible)

# **Description**
## Basic description
*A config option to apply weapon type modifers(like spear range/thrust) to weapons from other mods/vanilla via config*

## Why should it be in the mod?
*It would be very useful for modpack makers to be able to assign these special bonuses to greatswords, daggers and spears added by other mods. Mainly for balancing reasons, but it would also help the mods items feel a little more integrated. Besides, theres no other mod i can think of that does this.*

## Detailed description
*A config file which lists the weapon types and allows to freely remove and add items to them. This is probably a major hassle to implement but it came to mind.*

**Comment by DerToaster98** [comment]
We WON'T add config option for the items of other mods, ask the respective mods, not us.

We already have config options for damage for each item afaik.

**Comment by DerToaster98** [comment]
What you want here is better of as a own mod. And we won't add it. You could take a look at Actually Additions, that one lets you had blocks, maybe it lets you add items too.

**Comment by DerToaster98** [comment]
Also this still is a dungeon mod and not a content-adder mod after all.

**Comment by DerToaster98** [comment]
However, if you want more spears/revolvers/muskets/daggers/greatswords: Feel free to create your own addon mod. You can just extend the base class of every item and then adjust the values you want, but we won't add this feature.

**Comment by Glassimo-1** [comment]
maybe i'll try my hand on it once i got the rest of my pack set up
