### ISSUE TITLE
Castles in the nether break the upper bedrock layer

### ISSUE THREAD

**Issue by gruegirl** [TeamChocoQuest/ChocolateQuestRepoured#249]
**Common sense Info**
 - I play...
   - [x] With a large modpack (Tekxit Pi)
   - [ ] Only with CQR and it's dependencies
 - The issue occurs in...
   - [*] Singleplayer
   - [ ] Multiplayer
 - [x] I have searched for this or a similar issue before reporting and it was either (1) not previously reported, or (2) previously fixed  and I'm having the same problem.
 - [] I am using the latest version of the mod (all versions can be found on github under releases) (However: later changelogs don't indicate a change in building-spawn behavior)
 - [x] I read through the FAQ and i could not find something helpful ([FAQ](https://wiki.cq-repoured.net/index.php?title=FAQ))
 - [ ] I reproduced the bug without any other mod's except forge, cqr and its dependencies
 - [ ] The game crashes because of this bug
 
 
 **Versions**
Chocolate Quest Repoured ('latest' IS NOT a valid version! Please use the version string that shows up in the mod overview of forge):2.2.3 B
Technic: launcher: v2.4.0
Minecraft: 1.12

**Describe the bug**
Structures (castles in particular) can form in The Nether high enough that they break the upper bedrock layer.

**To Reproduce**
*RECCOMENDED*: Use a Minimap mod to more easily find one,
1. Create a Nether Portal
2. Enter the Nether
3: Travel until you see a castle spawning very high up

4. Climb above the bedrock, see the error.

**Expected behavior**
Access to the bedrock above the nether shouldn't be normally possible without ender-pearl glitches

**Screenshots**
![image](https://user-images.githubusercontent.com/15755292/107018740-7314cc00-6766-11eb-9a5c-054204739766.png)

**Other**
Please note: log files and crash reports should be uploaded as a FILE and not as a copy paste of the text of it here. Upload the file to a site like pastebin or similar and link it here!!
 - Link to Crash report file:
 - Link to Log file:
 - Other mods (that are necessary to produce the bug):
 - Other mods (that are also installed):
 - CQR config folder (link, only if you changed the configs):
 - Other mod's configs (link):

**Comment by DerToaster98** [comment]
That castle is not one of our mod. Also we DO NOT spawn overworld castles in the nether. Please report it to the tekzit 3 dev and not us. Also please tell them to update CQR since v2.3.b is outdated

**Comment by shanzenos** [comment]
The castle's a community created structure from recurrent complex.

**Comment by DerToaster98** [comment]
> The castle's a community created structure from recurrent complex.

Thank you for that information.

Then since the structure isn't from CQR, but from recurrent complex i suggest @gruegirl to report this to recurrent complex and not to CQR cause it is not a CQR problem.
