### ISSUE TITLE
Cursed bone not working

### ISSUE THREAD

**Issue by UngaBunga42069** [TeamChocoQuest/ChocolateQuestRepoured#252]
**Common sense Info**
To check a checkbox: Insert a lower case X between the square brackets, you need to remove the space though.
 - I play...
   - [ ] With a large modpack
   - [ ] Only with CQR and it's dependencies
 - The issue occurs in...
   - [ X] Singleplayer
   - [ ] Multiplayer
 - [ ] I have searched for this or a similar issue before reporting and it was either (1) not previously reported, or (2) previously fixed  and I'm having the same problem.
 - [X ] I am using the latest version of the mod (all versions can be found on github under releases)
 - [X ] I read through the FAQ and i could not find something helpful ([FAQ](https://wiki.cq-repoured.net/index.php?title=FAQ))
 - [ ] I reproduced the bug without any other mod's except forge, cqr and it's dependencies
 - [ ] The game crashes because of this bug
 
 
 **Versions**
Chocolate Quest Repoured ('latest' IS NOT a valid version! Please use the version string that shows up in the mod overview of forge): 2.2.4B
Forge: 1.12.2 14.23.5.2854
Minecraft: 12.2

**Describe the bug**
The skeleton summoned with the cursed bone is just sitting there and not killing my enemies

**To Reproduce**
2. Use item 'Cursed Bone, that's it'
3. Place block '....'
.
.
.

**Expected behavior**
I expected the summoned skeleton to kill my enemies

**Screenshots**
https://imgur.com/a/Rr310O5

**Other**
Please note: log files and crash reports should be uploaded as a FILE and not as a copy paste of the text of it here. Upload the file to a site like pastebin or similar and link it here!!
 - Link to Crash report file:
 - Link to Log file:
 - Other mods (that are necessary to produce the bug):
 - Other mods (that are also installed):Davinci's Vessels, Farlanders, Twilight Forest, Flan's mod, Metamorph, Repair gem, Bullseye, Uncrafting table
 - CQR config folder (link, only if you changed the configs):
 - Other mod's configs (link):

**Comment by DerToaster98** [comment]
The cursed bone works as intended and is WIP
