### ISSUE TITLE
[1.12.2]Console warning

### ISSUE THREAD

**Issue by EnterFor** [TeamChocoQuest/ChocolateQuestRepoured#254]
**Common sense Info**
To check a checkbox: Insert a lower case X between the square brackets, you need to remove the space though.
 - I play...
   - [x] With a large modpack
   - [ ] Only with CQR and it's dependencies
 - The issue occurs in...
   - [ ] Singleplayer
   - [x] Multiplayer
 - [ ] I have searched for this or a similar issue before reporting and it was either (1) not previously reported, or (2) previously fixed  and I'm having the same problem.
 - [x] I am using the latest version of the mod (all versions can be found on github under releases)
 - [x] I read through the FAQ and i could not find something helpful ([FAQ](https://wiki.cq-repoured.net/index.php?title=FAQ))
 - [ ] I reproduced the bug without any other mod's except forge, cqr and it's dependencies
 - [ ] The game crashes because of this bug
 
 
 **Versions**
Chocolate Quest Repoured ('latest' IS NOT a valid version! Please use the version string that shows up in the mod overview of forge):
Forge:2855
Minecraft:1.12.2

**Describe the bug**
I'm not sure if this is a problem, as Phosphoor is no longer maintaining 1.12.
Probably won't make a difference...
I used the original Forge2855 server for my tests.
And the Chunk - Pregenerator mod

**To Reproduce**
1. install CQR
2. install Chunk - Pregenerator
3. install Phosphor
4. Run chunk-pregenerator in Hell
5. See error

**Expected behavior**

**Screenshots**

**Other**
Please note: log files and crash reports should be uploaded as a FILE and not as a copy paste of the text of it here. Upload the file to a site like pastebin or similar and link it here!!
 - Link to Crash report file:
 - Link to Log file:https://paste.ubuntu.com/p/mYk8CgbH6D/
 - Other mods (that are necessary to produce the bug):
 - Other mods (that are also installed):
 - CQR config folder (link, only if you changed the configs):
 - Other mod's configs (link):

**Comment by DerToaster98** [comment]
That can be ignored.
