### ISSUE TITLE
The great wall from mod Main page

### ISSUE THREAD

**Issue by michalun** [TeamChocoQuest/ChocolateQuestRepoured#255]
Mysteries of the known world
Far in the north of the known world lies a large wall. Adventurers, brave enough to travel there, report it is guarded by ghostly warriors wearing black.

They dedicated their lives to guard that wall. They have forgotten since when they guard. They’ve forgotten for who they guard. And they have forgotten why they guard it. It is the task of the brave adventurers to find out 

Is IT real or its just a joke if IT is real pls TELL me what version do i need 

And 1 more question is three aby triton dungeon od not pls add some or TELL me how to

**Comment by DerToaster98** [comment]
Well, it is a description of the wall in the north (in CQR since the first release, located at Z = -8000 by default (8000 blocks north from spawn)), it is more like a reference.

I don't get your second question.
