### ISSUE TITLE
i dont know is it bug but heres my problem TURTLE NEEDS NERF and some sugestions

### ISSUE THREAD

**Issue by michalun** [TeamChocoQuest/ChocolateQuestRepoured#256]
giant turtle is so op it is always in his shell and do op attacks also on the ladder in castle dungeon/structure it can bug and kill player in like 4 seconds becaz it block player in air and deal damage please nerf this boss like give it cooldowns  becaz it can slide infinite you cant even damage it becaz it is in the shell 
TURTLE NEEDS NERF

suggestion about new type of dungeon for tritons with triton boss

and pls add spectre dungeon like cementary and bug dungeon under it with something like spectre boss

and pls add this big monke from original mod

**Comment by DerToaster98** [comment]
1) Use a shield to block the tortoises spin attack, it will then be stunned and you can attack it.
2) No, tortoise doesn't need a nerf
3) Triton dungeons are planned, but no boss. Tritons are peaceful and friendly
4) "spectre dungeons" are not planned. However, spectres will appear in dungeons later and there is a boss planned.
5) All original content from the old mod will eventually reappear.

And please stop spamming our github issue tracker! If you have serious suggestions, either use the proper template and fill it out correctly or do that on the discord.

**Comment by michalun** [comment]
ma boi tritons are not friendly i entered skeleton castle i mean this randomized on plains or idk and entered prison / cage they wated to kill me so they are friendly  i got 1 suggestion more add ''the wall'' some loot pls

**Comment by DerToaster98** [comment]
tritons are neutral, if you attack them they will attack back. No there won't be loot on the wall.
