### ISSUE TITLE
beginners question 

### ISSUE THREAD

**Issue by mkowskyyy** [TeamChocoQuest/ChocolateQuestRepoured#258]
hi i want to know how to make a new category or something to build underwater dungeons and change Y on spawning structure 
i want to start creating my own dungeons

**Comment by DerToaster98** [comment]
Please don’t ask questions on the issue tracker. Ask them on curseforge or discord, also be sure to check out the faq and the wiki (wiki.cq-repoured.net, it holds the answer to that question)

**Comment by mkowskyyy** [comment]
ok thanks
but i dont understand wiki
