### ISSUE TITLE
Mod dungeon generation config

### ISSUE THREAD

**Issue by TheSexyYeti** [TeamChocoQuest/ChocolateQuestRepoured#260]
Just wondering if there was an option in the configs to disable the dungeons generated from this mod. And only generate custom dungeons that player creates. I've been looking to see if there was one but can't seem to find one. And if not could you put the option in?. I'm not trying to like knock the dungeons that this mod provides. I think they're amazingly well built. 

But I have my ideas for my own personal dungeons for this modpack I'm working on for 1.12.2. And only want those dungeons to spawn in the world. And was only using this mod purely as an alternative to Recurrent Complex because it came with something Recurrent Complex doesn't. The structure protection mechanic added by the force field nexus. And I wanted to create my own dungeons that you can't cheat to get through by breaking and placing blocks to circumvent that traps, puzzles and mazes.

I also wanted to combine this cheat protection function with the little tiles mod to create hidden passages to treasure or new routes to travers the dungeon. That players can only find if they find maps to these hidden passages or if their observant enough to find the subtle markings that are clues that the passage is there.

**Comment by DerToaster98** [comment]
Every dungeon config has a "enabled" option, be sure to check out the wiki (wiki.cq-repoured.net), it is documented there.

In order to let it only spawn your own custom dungeons: Create own dungeon configs and only enable those. For how to do that -> wiki.
