### ISSUE TITLE
crashing when at tavern 

### ISSUE THREAD

**Issue by Wank1111** [TeamChocoQuest/ChocolateQuestRepoured#261]
im using a fairly small modpack that mainly adds new buildings but nothing that would conflict i would always spawn the bar keepers and adventurers and it would crash when im near the tavern ive tried everything it would crash every time i have llibary and everything you would need

**Comment by DerToaster98** [comment]
1) Invalid cause template isn't used
2) Any useful information for us is missing
3) Try completely reinstalling CQR (also delete ALL Cqr configs)
4) Not reproduceable with standard installation.

**Comment by Wank1111** [comment]
strange well it keeps crashing for me no matter the version type or install i have it just crashes

**Comment by DerToaster98** [comment]
well still we can't help you cause you don't provide us any information at all.

**Comment by Wank1111** [comment]
because theres non to provide all it does is go to a white screen and crash for no reason but i fixed it using phosphor so thanks for the help

**Comment by DerToaster98** [comment]
ever heard of a crashreport? 

Anyway, for the next time you report something: Please use the issue template and fill it out correctly.
