### ISSUE TITLE
crashing when at friendly npc tavern 

### ISSUE THREAD

**Issue by Wank1111** [TeamChocoQuest/ChocolateQuestRepoured#262]
this is single player with a 40 mods loaded only structure mods everytime i load a new game and load npcs it crashes and gives me this message  java.lang.ArrayIndexOutOfBoundsException: 4 any ideas? thats all i have for info i have no idea what could be causing this

**Comment by Wank1111** [comment]
btw im using forge and sorry for making a new one its happening again

**Comment by DerToaster98** [comment]
Use. the. issue. template.
