### ISSUE TITLE
crashing when at tavern 

### ISSUE THREAD

**Issue by Wank1111** [TeamChocoQuest/ChocolateQuestRepoured#263]
**Common sense Info**
To check a checkbox: Insert a lower case X between the square brackets, you need to remove the space though.
 - I play...
   - [x ] With a large modpack
   - [x ] Only with CQR and it's dependencies
 - The issue occurs in...
   - [ x] Singleplayer
   - [ ] Multiplayer
 - [ ] I have searched for this or a similar issue before reporting and it was either (1) not previously reported, or (2) previously fixed  and I'm having the same problem.
 - [x ] I am using the latest version of the mod (all versions can be found on github under releases)
 - [x ] I read through the FAQ and i could not find something helpful ([FAQ](https://wiki.cq-repoured.net/index.php?title=FAQ))
 - [ ] I reproduced the bug without any other mod's except forge, cqr and it's dependencies
 - [x ] The game crashes because of this bug
 
 
 **Versions**
Chocolate Quest Repoured ('latest' IS NOT a valid version! Please use the version string that shows up in the mod overview of forge):x
Forge: 14.23.5.2854
Minecraft:1.12.2

**Describe the bug**
when i go near a tavern it crashes 
**To Reproduce**
1. Go to the tavern 
2. Use item '....'
3. Place block '....'
.let the npcs spawn in survival and then crash 
.
.

**Expected behavior**

**Screenshots**

**Other**
Please note: log files and crash reports should be uploaded as a FILE and not as a copy paste of the text of it here. Upload the file to a site like pastebin or similar and link it here!!
 - Link to Crash report file:
 - Link to Log file:
 - Other mods (that are necessary to produce the bug):
 - Other mods (that are also installed):
 - CQR config folder (link, only if you changed the configs):
 - Other mod's configs (link):

**Comment by DerToaster98** [comment]
did you read the instructions in this template? If yes, why didn't you give us the crash report? We DO NEED that to solve this.

**Comment by Wank1111** [comment]
sorry im just getting frustrated when it comes to this here  java.lang.ArrayIndexOutOfBoundsException: 4
thats all i got

**Comment by DerToaster98** [comment]
I think you are trying to troll. I won't answer you from this post on cause this leads nowhere.

**Comment by Wank1111** [comment]
well i have no more info im sorry if it seems like im trolling but really im trying my best to find whats going on

**Comment by Meldexun** [comment]
Just at least upload the `minecraft/logs/latest.log` file.

**Comment by Wank1111** [comment]
[latest.log](https://github.com/TeamChocoQuest/ChocolateQuestRepoured/files/6173862/latest.log)

**Comment by Wank1111** [comment]
there

**Comment by Meldexun** [comment]
It says nothing about a crash. Can you upload newest `minecraft/crash-reports/crash-[...].txt` file

**Comment by Wank1111** [comment]
that is the newest

**Comment by DerToaster98** [comment]
We can see in the log file that you use way more mods than just CQR and it's dependencies. Also this does not seem to be a crash report.

**Comment by Wank1111** [comment]
WAIT ok i actually found it i feel so fucking bad now ok so it was a small mod called miners lore i had no idea it was so combative with cqr and sorry for being sluggish and annoying ive been working on this modpack all night thanks for being patient

**Comment by DerToaster98** [comment]
Ok, thank you for finding this. We will try to examine if this is an incompatibility and will add it to a incompatible list.
