### ISSUE TITLE
game shuts itself off when using NEAT 

### ISSUE THREAD

**Issue by Wank1111** [TeamChocoQuest/ChocolateQuestRepoured#264]
**Common sense Info**
To check a checkbox: Insert a lower case X between the square brackets, you need to remove the space though.
 - I play...
   - [x ] With a large modpack
   - [ ] Only with CQR and it's dependencies
 - The issue occurs in...
   - [x ] Singleplayer
   - [ ] Multiplayer
 - [ ] I have searched for this or a similar issue before reporting and it was either (1) not previously reported, or (2) previously fixed  and I'm having the same problem.
 - [x ] I am using the latest version of the mod (all versions can be found on github under releases)
 - [ x] I read through the FAQ and i could not find something helpful ([FAQ](https://wiki.cq-repoured.net/index.php?title=FAQ))
 - [x ] I reproduced the bug without any other mod's except forge, cqr and it's dependencies
 - [x ] The game crashes because of this bug
 
 
 **Versions**
Chocolate Quest Repoured ('latest' IS NOT a valid version! Please use the version string that shows up in the mod overview of forge):
Forge:
Minecraft:1.12.2

**Describe the bug**
crashes when using the Neat mod
**To Reproduce**
2. Use item '....'
3. Place block '....'
.use the Neat mod with chocolate quest and it just crashes thats all it does and its getting really annoying 

.

**Expected behavior**
mobs load in then it crashes
**Screenshots**

**Other**
Please note: log files and crash reports should be uploaded as a FILE and not as a copy paste of the text of it here. Upload the file to a site like pastebin or similar and link it here!!
 - Link to Crash report file: [crash-2021-03-19_16.43.34-client.txt](https://github.com/TeamChocoQuest/ChocolateQuestRepoured/files/6174526/crash-2021-03-19_16.43.34-client.txt)
 - Link to Log file: 
 - Other mods (that are necessary to produce the bug):
 - Other mods (that are also installed):
 - CQR config folder (link, only if you changed the configs):
 - Other mod's configs (link):

**Comment by Meldexun** [comment]
Why do you think CQR is the cause of the crash?

**Comment by Wank1111** [comment]
i dont think its cqr by itself i think its neat not liking the newer version i tried this on a separate mod pack and it did the same thing any ideas?

**Comment by Wank1111** [comment]
oh i forgot to add it only happens when its cqr mobs so i dont know

**Comment by Meldexun** [comment]
I don't see how this could be caused by cqr. You should report this to the neat author.

**Comment by Wank1111** [comment]
i did they have no idea whats going on it only happens when the neat UI renders on your mobs its only happening on the most recent version the older one is completely fine i tested it maybe find out what it is? i tried it on different mods/modpacks and it only happened with the cqr mod

**Comment by DerToaster98** [comment]
That’s clearly caused by neat. The crash report points to their mod.

**Comment by edgaradr223** [comment]
sure, the problem is neat, when only crashes with your mod, yes yes of course

**Comment by edgaradr223** [comment]
Thread: Client thread
Stacktrace:
	at vazkii.neat.HealthBarRenderer.renderHealthBar(HealthBarRenderer.java:153)
	at vazkii.neat.HealthBarRenderer.onRenderWorldLast(HealthBarRenderer.java:73)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1944_HealthBarRenderer_onRenderWorldLast_RenderWorldLastEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.client.ForgeHooksClient.dispatchRenderLast(ForgeHooksClient.java:196)
	at sun.reflect.GeneratedMethodAccessor104.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.optifine.reflect.Reflector.callVoid(Reflector.java:660)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1951)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1613)




happening ONLY when your monsters spawn from monster boxes, have a pack with over 226 mods and never had a problem with neat until now

**Comment by DerToaster98** [comment]
Issue is solved in development environment, patch will be published with the next update.
