### ISSUE TITLE
World crashes when trying to log into it

### ISSUE THREAD

**Issue by BIG-Viljo** [TeamChocoQuest/ChocolateQuestRepoured#266]
**Common sense Info**
To check a checkbox: Insert a lower case X between the square brackets, you need to remove the space though.
 - I play...
   - [x] With a large modpack
   - [ ] Only with CQR and it's dependencies
 - The issue occurs in...
   - [x] Singleplayer
   - [ ] Multiplayer
 - [ ] I have searched for this or a similar issue before reporting and it was either (1) not previously reported, or (2) previously fixed  and I'm having the same problem.
 - [x] I am using the latest version of the mod (all versions can be found on github under releases)
 - [ ] I read through the FAQ and i could not find something helpful ([FAQ](https://wiki.cq-repoured.net/index.php?title=FAQ))
 - [ ] I reproduced the bug without any other mod's except forge, cqr and it's dependencies
 - [x] The game crashes because of this bug
 
 
 **Versions**
Chocolate Quest Repoured ('latest' IS NOT a valid version! Please use the version string that shows up in the mod overview of forge): Chocolate_Quest_Repoured-1.12.2-2.4.0B
Forge: 14.23.5.2854
Minecraft: 1.12.2

**Describe the bug**
Bug crashes world every time when trying to connect after triggering it. It didn't happen until beta 4 arrived. Yesterday, the day before releasing new beta, everything was working just fine.

**To Reproduce**
1. Find Necromancer (or spawn one using commands/spawn egg)
2. Wait until he uses one of his summoning attacks (I am not sure which one specifically, either blindness, skeletons or fangs)
3. One of these attacks should trigger the crash

**Expected behavior**
After doing what is described above, the world should crash. Trying to reconnect crashes the world instantly.

**Screenshots**
Triggering the bug: https://drive.google.com/file/d/1Vzo9iH6khT224pXVOZFn-3gwlDubJWyK/view?usp=sharing
When trying to reconnect: https://drive.google.com/file/d/1MHe26XENBkdLzV310WlyGJkvzrngoPiN/view?usp=sharing

**Other**
Please note: log files and crash reports should be uploaded as a FILE and not as a copy paste of the text of it here. Upload the file to a site like pastebin or similar and link it here!!
 - Link to Crash report file: https://pastebin.com/bfxvQwaN
 - Link to Log file: https://drive.google.com/file/d/15hbDX3o-uka7_3pk2p-wzr_aRbB4NRB5/view?usp=sharing
 - Other mods (that are necessary to produce the bug):
 - Other mods (that are also installed): https://pastebin.com/1sC9zVfR
 - CQR config folder (link, only if you changed the configs): (only turned off the "april fools" option)
 - Other mod's configs (link): https://drive.google.com/file/d/1HE1dY5AAgvBFTy2TxISnPiYNvg8P6xBU/view?usp=sharing

**Comment by DerToaster98** [comment]
Caused by an untested feature being in the code which i forgot. Patch update will be published on tuesday or saturday.

**Comment by DerToaster98** [comment]
Release 2.4.1 and later have a fix for this
