### ISSUE TITLE
old sounds

### ISSUE THREAD

**Issue by xyyz12341** [TeamChocoQuest/ChocolateQuestRepoured#267]
# **General Info**
 - This is a..
   - [ ] Change request
   - [x] Feature request
 - [ ] This has already been asked before and the answer was 'No'
 - [ ] This has already been implemented by another mod (which is compatible)

# **Description**
## Basic description
*Describe your idea in a few short sentences*
Hi. Im asking about adding old gremlin sounds from version 1.6.4 (smallmonsterhurt.ogg etc.) . i tried everything but always it says error with loading the mod. I really love these old sounds and if you guys can make version with them i'll be so happy. 
## Why should it be in the mod?
*Explain why your idea is cool and fits with the mod*
I just love these old sounds and they bring me good memories.
## Detailed description
*Explain in detail how your idea works*
The gremlins would have sounds when they talk, laught etc. like in old 1.6.4 BetterDuengons mod.
# **Others**
*If you have something like a small code that implements your idea just post it here, this also includes things like models or textures for example*

**Comment by DerToaster98** [comment]
We legally are not allowed to use the old gremlin sounds cause they belong to chocolatin and we have no right to use them. You can create yourself a resourcepack for personal use that uses the old gremlin sounds to replace ours.

**Comment by xyyz12341** [comment]
> We legally are not allowed to use the old gremlin sounds cause they belong to chocolatin and we have no right to use them. You can create yourself a resourcepack for personal use that uses the old gremlin sounds to replace ours.

Okay, can you like write here how to exactly do it? I tried but it didn't work.

**Comment by DerToaster98** [comment]
The thing is: YOu do not exchange the files in the mod. YOu create a resourcepack and need to create a sounds.json file in it. It is explained on the minecraftwiki.

**Comment by xyyz12341** [comment]
> The thing is: YOu do not exchange the files in the mod. YOu create a resourcepack and need to create a sounds.json file in it. It is explained on the minecraftwiki.

Ohh okay tysm

**Comment by DerToaster98** [comment]
here's the relevant page: https://minecraft.fandom.com/wiki/Sounds.json

Oversimplified steps to create that pack:
1) Figure out how the cqr gremlin sounds are called (for reference see the sounds.json file in the mod itself, located somewhere in assets/cqrepoured)
2) Write your own sounds.json file where you re-define the cqr sounds and mark them as replacement
3) Put your actual sound files in the resourcepack and make them match the specified paths in your sounds.json
