### ISSUE TITLE
CQR dungeon protection possibly causing crashes.

### ISSUE THREAD

**Issue by Slayer5934** [TeamChocoQuest/ChocolateQuestRepoured#268]
**Common sense Info**
To check a checkbox: Insert a lower case X between the square brackets, you need to remove the space though.
 - I play...
   - [x] With a large modpack
   - [ ] Only with CQR and it's dependencies
 - The issue occurs in...
   - [x] Singleplayer
   - [x] Multiplayer
 - [x] I have searched for this or a similar issue before reporting and it was either (1) not previously reported, or (2) previously fixed  and I'm having the same problem.
 - [x] I am using the latest version of the mod (all versions can be found on github under releases)
 - [x] I read through the FAQ and i could not find something helpful ([FAQ](https://wiki.cq-repoured.net/index.php?title=FAQ))
 - [ ] I reproduced the bug without any other mod's except forge, cqr and it's dependencies
 - [x] The game crashes because of this bug
 
 
 **Versions**
Chocolate Quest Repoured ('latest' IS NOT a valid version! Please use the version string that shows up in the mod overview of forge): 2.4.3B
Forge: 14.23.5.2854
Minecraft: 1.12.2

**Describe the bug**
During some edge case block placement a crash occurse when the CQR protection system tries to read the value from the block.
It is also worth noting that the XP Shower is never suppose to be able to get placed on the top or bottom of a block, and without CQR this does not occur; I think it might have something to do with that.

**To Reproduce**
1. Install openblocks
2. Place XP Shower on the top or bottom of any block (This is not suppose to be possible anyways)
3. Crash

**Other**
Please note: log files and crash reports should be uploaded as a FILE and not as a copy paste of the text of it here. Upload the file to a site like pastebin or similar and link it here!!
 - Link to Crash report file: https://paste.mod.gg/bubotaveke.mccrash
 - Link to Log file: [latest.log](https://github.com/TeamChocoQuest/ChocolateQuestRepoured/files/6333404/latest.log)
 - Other mods (that are necessary to produce the bug): openblocks
 - Other mods (that are also installed): [Mods.txt](https://github.com/TeamChocoQuest/ChocolateQuestRepoured/files/6333406/Mods.txt)
 - CQR config folder (link, only if you changed the configs): [CQR.zip](https://github.com/TeamChocoQuest/ChocolateQuestRepoured/files/6333409/CQR.zip)

**Comment by DerToaster98** [comment]
we can't really fix this from our end. Please pass this to open blocks. Issue is probably how their "open block" class treats the metadata when it tries to get it for placement, and it doesn't like it when the item meta is passed to the block.

I made a workaround, but that solution is not ideal cause it doesn't really fix the problem, it only prevents the game from crashing

**Comment by Slayer5934** [comment]
I created the issue on OpenBlocks but that mod has not been updated since mid-2019 so a fix on their end is unfortunately unlikely, I am unsure if there are any valid branches/forks to use instead that someone is updating however.

**Comment by DerToaster98** [comment]
well, that could be a problem. However i just tested the workaround and it works, but like i said, it isn't really the best solution.

**Comment by Slayer5934** [comment]
There is a 1.16 branch that is recently active, however I doubt the 1.12.2 version will get backported changes. I appreciate you going through the trouble to catch the crash even if it's not the best possible solution though, hopefully the mod author proves me wrong :p
