### ISSUE TITLE
CQR Iron Door AI Bug

### ISSUE THREAD

**Issue by minekraftminer** [TeamChocoQuest/ChocolateQuestRepoured#269]
**Common sense Info**
To check a checkbox: Insert a lower case X between the square brackets, you need to remove the space though.
 - I play...
   - [x] With a large modpack
   - [ ] Only with CQR and it's dependencies
 - The issue occurs in...
   - [x] Singleplayer
   - [x] Multiplayer
 - [x] I have searched for this or a similar issue before reporting and it was either (1) not previously reported, or (2) previously fixed  and I'm having the same problem.
 - [x] I am using the latest version of the mod (all versions can be found on github under releases)
 - [x] I read through the FAQ and i could not find something helpful ([FAQ](https://wiki.cq-repoured.net/index.php?title=FAQ))
 - [x] I reproduced the bug without any other mod's except forge, cqr and it's dependencies
 - [ ] The game crashes because of this bug
 
 
 **Versions**
Chocolate Quest Repoured ('latest' IS NOT a valid version! Please use the version string that shows up in the mod overview of forge): Beta 4.3
Forge: 1.12.2-forge-14.23.5.2854
Minecraft: 1.12.2

**Describe the bug**
CQR Mobs don't walk through iron doors. Instead, they just sit there waiting at the door for you to kill them. This may not seem like a big deal, until you realize majority of the dungeons are filled with iron doors. This leads to a common strategy of luring mobs to the door and then camping them out with your weapon

**To Reproduce**
1. Go to 'a dungeon with a iron door' (or just make a box and place a iron door)
2. 'Have a CQR mob chase you'
3. 'Wait at iron door'
4. 'CQR mob will wait at the door and do nothing'

**Expected behavior**
I'd expect for the mob to walk through the door,

 just like how they can go through wooden doors.

**Screenshots** (or video in this case)
https://www.youtube.com/watch?v=RUPa3peSMZk

**Other**
Please note: log files and crash reports should be uploaded as a FILE and not as a copy paste of the text of it here. Upload the file to a site like pastebin or similar and link it here!!
 - Link to Crash report file: (no game crash)
 - Link to Log file: (can that even exist without a game crash?)
 - Other mods (that are necessary to produce the bug): (tested with CQR Only)
 - Other mods (that are also installed): (tested with CQR Only)
 - CQR config folder (link, only if you changed the configs): (I'm pretty sure they are default)
 - Other mod's configs (link): (tested with CQR Only)

**Comment by DerToaster98** [comment]
Hm ye, that is not supposed. Will look at it later. But to be clear: They do not have an 'iron door ai' and neither can they open them.

**Comment by DerToaster98** [comment]
Ok, this seems to be a vanilla bug. We probably won't fix it. 

We use the vanilla pathnode processor internally so it is too much effort for us to fix this, though when looking in the code it should work theoretically. Anyways, probably won't fix. Report to mojang that mobs (tested with vindicator) can't go through open iron doors.

**Comment by minekraftminer** [comment]
alright, thanks for replying!
