### ISSUE TITLE
Everytime I go anywhere near an NPC it crashes

### ISSUE THREAD

**Issue by CrumbsBoi** [TeamChocoQuest/ChocolateQuestRepoured#271]
**Common sense Info**
To check a checkbox: Insert a lower case X between the square brackets, you need to remove the space though.
 - I play...
   - [x] With a large modpack
   - [ ] Only with CQR and it's dependencies
 - The issue occurs in...
   - [ ] Singleplayer
   - [x] Multiplayer
 - [1] I have searched for this or a similar issue before reporting and it was either (1) not previously reported, or (2) previously fixed  and I'm having the same problem.
 - [x] I am using the latest version of the mod (all versions can be found on github under releases)
 - [x] I read through the FAQ and i could not find something helpful ([FAQ](https://wiki.cq-repoured.net/index.php?title=FAQ))
 - [x] I reproduced the bug without any other mod's except forge, cqr and it's dependencies
 - [x] The game crashes because of this bug
 
 
 **Versions**
Chocolate Quest Repoured ('latest' IS NOT a valid version! Please use the version string that shows up in the mod overview of forge): 1.12.2-2.5.1B
Forge: 1.12.2 (14.23.5.2855)
Minecraft: 1.12.2

**Describe the bug**
As the title suggests, everytime either me or my friend comes near an NPC naturally generated dungeon it just crashes

**To Reproduce**
1. Go to 'any naturally generated dungeon'
2. Get close to it
3. See error

**Expected behavior**
Since I'm running on a server, the server just suddenly stops, and closes itself again, (server site is aternos.org)

**Screenshots**
n/a

**Other**
[Crash Report.txt](https://github.com/TeamChocoQuest/ChocolateQuestRepoured/files/6366496/Crash.Report.txt)

**Comment by DerToaster98** [comment]
Patched in Beta 5.2 (https://cq-repoured.net/beta-5-2/)
