### ISSUE TITLE
Game says it needs Geckolib even if it is in the folder

### ISSUE THREAD

**Issue by SpookLad** [TeamChocoQuest/ChocolateQuestRepoured#272]
**Common sense Info**
To check a checkbox: Insert a lower case X between the square brackets, you need to remove the space though.
 - I play...
   - [ ] With a large modpack
   - [x] Only with CQR and it's dependencies
 - The issue occurs in...
   - [x] Singleplayer
   - [ ] Multiplayer
 - [ ] I have searched for this or a similar issue before reporting and it was either (1) not previously reported, or (2) previously fixed  and I'm having the same problem.
 - [x] I am using the latest version of the mod (all versions can be found on github under releases)
 - [ ] I read through the FAQ and i could not find something helpful ([FAQ](https://wiki.cq-repoured.net/index.php?title=FAQ))
 - [x] I reproduced the bug without any other mod's except forge, cqr and it's dependencies
 - [ ] The game crashes because of this bug
 
 
 **Versions**
Chocolate Quest Repoured ('latest' IS NOT a valid version! Please use the version string that shows up in the mod overview of forge): Beta 5.1
Forge: 1.12.2-forge-14.23.5.2854
Minecraft: 1.12.2

**Describe the bug**
When you boot Minecraft with the latest version of Chocolate Quest and the latest version of GeckoLib, the game says it's missing GeckoLib, and will refuse to open to the title screen. 

**To Reproduce**
1. Put chocolate quest repoured and geckolib for 1.12 into the mods folder
2. Open the latest version of forge 1.12.2
3. The game will then say "You must include the right dependencies for Chocolate Quest Repoured Mod: Requires geckolib3 3.0.0 or above"

**Expected behavior**
The game boots to the title screen with chocolate quest active

**Screenshots**
![Minecraft 1 12 2 4_23_2021 1_36_14 PM](https://user-images.githubusercontent.com/83087893/115909269-edcdb900-a430-11eb-8db6-ad0095dd2b15.png)
![mods 4_23_2021 1_45_24 PM](https://user-images.githubusercontent.com/83087893/115910055-fe326380-a431-11eb-9861-fc3f31b7c1c8.png)

**Comment by DerToaster98** [comment]
And where’s the modlist? You don’t provide enough information for us to help

**Comment by Meldexun** [comment]
The best way would be to click the `Open Mods Folder` button and make a screenshot

**Comment by SpookLad** [comment]
I get what you guys are saying, but it's literally just CQR and GeckoLib

**Comment by DerToaster98** [comment]
try redownloading geckolib. The geckolib3 b7 file should be about 3.5 MB, yours is 0.2MB, the file is not complete. Try redownloading it.

**Comment by DerToaster98** [comment]
and where exactly did you download it from?

**Comment by SpookLad** [comment]
I downloaded it from curseForge, and thanks for the help!

**Comment by DerToaster98** [comment]
so you redownloaded it and now it works?

**Comment by SpookLad** [comment]
It does, thank you!
