### ISSUE TITLE
Whenever I go near a dungeon, server crashes.

### ISSUE THREAD

**Issue by Winforce69** [TeamChocoQuest/ChocolateQuestRepoured#273]
Basically, whenever I go near a CQR dungeon, my server crashes with the cause of ticking entity, I have to enable the option for the forge config to kill erroneous entities and this is near every single dungeon

**Comment by DerToaster98** [comment]
1) use the issue template
2) this is known and will be fixed in the next update, however because you provide us sooooo much information about the crash we will fix it asap (no, this was sarcasm)

**Comment by Winforce69** [comment]
[crash-2021-04-23_13.49.26-server.txt](https://github.com/TeamChocoQuest/ChocolateQuestRepoured/files/6367899/crash-2021-04-23_13.49.26-server.txt)
[crash-2021-04-23_14.01.36-server.txt](https://github.com/TeamChocoQuest/ChocolateQuestRepoured/files/6367900/crash-2021-04-23_14.01.36-server.txt)
[crash-2021-04-23_14.12.19-server.txt](https://github.com/TeamChocoQuest/ChocolateQuestRepoured/files/6367901/crash-2021-04-23_14.12.19-server.txt)
[crash-2021-04-23_16.21.14-server.txt](https://github.com/TeamChocoQuest/ChocolateQuestRepoured/files/6367902/crash-2021-04-23_16.21.14-server.txt)
[crash-2021-04-23_13.43.32-server.txt](https://github.com/TeamChocoQuest/ChocolateQuestRepoured/files/6367903/crash-2021-04-23_13.43.32-server.txt)
[crash-2021-04-23_13.45.54-server.txt](https://github.com/TeamChocoQuest/ChocolateQuestRepoured/files/6367904/crash-2021-04-23_13.45.54-server.txt)

**Comment by DerToaster98** [comment]
Ok, this is the same problem as #271 

Like i said, will be fixed in the next update. In the mean time you can downgrade to cqr v2.4.3B, but that one has other bugs.

For the next time: FIll out the issue template, otherwise: No support
