### ISSUE TITLE
Editing custom npc???

### ISSUE THREAD

**Issue by TheSexyYeti** [TeamChocoQuest/ChocolateQuestRepoured#277]
I don't know if your wiki is outdated or the the mods bugged. But when I spawn a custom NPC. Their menu is nothing like the way it describes in the wiki. How do I edit the NPC?.
![Untitled](https://user-images.githubusercontent.com/50222286/116623725-ace41180-a914-11eb-8315-9247888fc2da.png)

**Comment by Meldexun** [comment]
You are probably looking at the wiki of the original Better Dungeons/Chocolate Quest mod (only available up MC 1.7.10).
This mod (Chocolate Quest Repoured, only available for MC 1.12.2) is rewrite of the original and also created by other people.

**Comment by TheSexyYeti** [comment]
hmmm well from what I can tell the new wiki has some bugs too. Every time I try to go to the webpage I keep getting an error message saying "hmmm can't reach this page".

**Comment by DerToaster98** [comment]
That’s not a bug, the ssl certificate is just outdated

**Comment by DerToaster98** [comment]
However, maybe you use the wrong wiki url (there was a fandom one which we shut down), this is the correct URL: http://wiki.cq-repoured.net
