### ISSUE TITLE
Crash on servers when approaching CQR mobs, or, when approaching bosses 

### ISSUE THREAD

**Issue by RaiderxD404** [TeamChocoQuest/ChocolateQuestRepoured#278]
[crash-2021-05-05_18.12.23-server (1).txt](https://github.com/TeamChocoQuest/ChocolateQuestRepoured/files/6428721/crash-2021-05-05_18.12.23-server.1.txt)
[crash-2021-05-05_17.50.50-server.txt](https://github.com/TeamChocoQuest/ChocolateQuestRepoured/files/6428723/crash-2021-05-05_17.50.50-server.txt)
Crash on servers when approaching CQR mobs, or, when approaching bosses 

Version: 2.5.3B

Modpack: https://www.mediafire.com/file/bk5m7p7ld0bfo8u/mods.rar/file

I have not tried
 these bugs with only the mod ... but I hope it is a bug of the mod and a problem of the modifications, and if so, that the mod that is incompatible is open source and they can fix it, since it is quite annoying when I play on a server with this modpack

**Comment by RaiderxD404** [comment]
sorry is duplicate

**Comment by DerToaster98** [comment]
Can't be caused by us. Must be a conflict with some other mod that loves to hijack the vanilla path navigator which destroys our calls to fields from that

**Comment by DerToaster98** [comment]
Here's some proof if you don't believe me: https://youtu.be/LzF69bktTyc

**Comment by DerToaster98** [comment]
If you want the bug fixed: Find the mod that conflicts with CQR and tell us so we can list it as incompatible. Also tell it the author of that mod so they can fix it.

**Comment by DerToaster98** [comment]
could also be caused by magma, which is most likely the cause. We do not support server software other than forge.

**Comment by DerToaster98** [comment]
Problem is Magma, however it ran fine with CQR v2.3.0B, you can find it on our website (NOT CURSEFORGE) or here on the github under releases

**Comment by DerToaster98** [comment]
Problem is on magmas end, they either removed the "currentEntity" field from the PathNavigate class or they added a mapping for it which is not defined in the stable_39 mappings which are used for 1.12.2 afaik and those mappings don't provide a mapping for that specific field which leads to the crash

**Comment by RaiderxD404** [comment]
Yes, the npcs work, but a structure generated naturally with the npcs crashes immediately, sorry to explain it so badly, I did not know where to find the template

**Comment by RaiderxD404** [comment]
Well thank you very much for the help

**Comment by DerToaster98** [comment]
The missing field we need is added by forge. For whatever reason magma decides to not provide it. If you want it fixed: report to magma that the forge-added field „currentEntity“ in NodeProcessor is missing. This won’t be worked on.

**Comment by DerToaster98** [comment]
I switched to mohist, and it works on mohist. If you want to have it fixed on magma, report it to magma.

**Comment by UeberallGebannt** [comment]
Issue got fixed in this [Magma commit](https://github.com/magmafoundation/Magma/commit/faa39350ae745c41ddef6f3f53d3679fff1f8121), it was caused by an unused java patch
