### ISSUE TITLE
Stone pedestal with same function as table

### ISSUE THREAD

**Issue by TheFunnyFace** [TeamChocoQuest/ChocolateQuestRepoured#28]
Would love to have something like a stone pedestal to place some blocks in an more epic and also sometimes more fiiting way.
![unbenannt](https://user-images.githubusercontent.com/17514508/52021435-c9a6fa00-24fd-11e9-9120-4f6a2f5d924f.PNG)

**Comment by LordEpos** [comment]
Also a Pupur one with an end rod on the bottom for the end.

**Comment by TheFunnyFace** [comment]
Are we going to implement this? Models are already finished
