### ISSUE TITLE
Daggers don't lose durability

### ISSUE THREAD

**Issue by minekraftminer** [TeamChocoQuest/ChocolateQuestRepoured#281]
**Common sense Info**
To check a checkbox: Insert a lower case X between the square brackets, you need to remove the space though.
 - I play...
   - [x] With a large modpack
   - [ ] Only with CQR and it's dependencies
 - The issue occurs in...
   - [x] Singleplayer
   - [ ] Multiplayer
 - [x] I have searched for this or a similar issue before reporting and it was either (1) not previously reported, or (2) previously fixed  and I'm having the same problem.
 - [x] I am using the latest version of the mod (all versions can be found on github under releases)
 - [x] I read through the FAQ and i could not find something helpful ([FAQ](https://wiki.cq-repoured.net/index.php?title=FAQ))
 - [x] I reproduced the bug without any other mod's except forge, cqr and it's dependencies
 - [ ] The game crashes because of this bug
 
 
 **Versions**
Chocolate Quest Repoured ('latest' IS NOT a valid version! Please use the version string that shows up in the mod overview of forge): Beta 5.3
Forge: 1.12.2-forge-14.23.5.2854
Minecraft: 1.12.2

**Describe the bug**

The Issue is pretty simple, When you attack a mob with a dagger, it doesn't lose durability. Basically making the daggers unbreakable (unless you mines enough blocks with it, but like why?)

**To Reproduce**
1. Get a Dagger
2. Attack a mob with Dagger
3. Dagger doesn't lose durability 

**Expected behavior**
I'd expect for the dagger to lose durability like any other weapon

**Screenshots**
(my graphics card keeps uninstalling my recording software for some reason, and I cant really take a screenshot of this so...)

**Other**
Please note: log files and crash reports should be uploaded as a FILE and not as a copy paste of the text of it here. Upload the file to a site like pastebin or similar and link it here!!
 - Link to Crash report file: doesn't crash
 - Link to Log file: doesn't crash
 - Other mods (that are necessary to produce the bug): Happens with CQR alone
 - Other mods (that are also installed): happens with CQR alone
 - CQR config folder (link, only if you changed the configs): only added the medium tavern, and made caves generate
 - Other mod's configs (link): Happens with CQR alone

**Comment by DerToaster98** [comment]
Issue is already fixed in workspace

**Comment by DerToaster98** [comment]
Patch will be contained in the next update

**Comment by DerToaster98** [comment]
Fixed in 2.6.0B
