### ISSUE TITLE
I play with hexxit updated a mod pack with 90 mods so little large, the issue occurs in both, it was not previously reported. I am using the latest version of the mods. The issue is that the knight htat is sitting down that we can trade wtih turns my whole screen green and makes it unplayable and crashing my whole game.

### ISSUE THREAD

**Issue by lolsnman** [TeamChocoQuest/ChocolateQuestRepoured#282]
**Common sense Info**
To check a checkbox: Insert a lower case X between the square brackets, you need to remove the space though.
 - I play...
   - [ ] With a large modpack
   - [ ] Only with CQR and it's dependencies
 - The issue occurs in...
   - [ ] Singleplayer
   - [ ] Multiplayer
 - [ ] I have searched for this or a similar issue before reporting and it was either (1) not previously reported, or (2) previously fixed  and I'm having the same problem.
 - [ ] I am using the latest version of the mod (all versions can be found on github under releases)
 - [ ] I read through the FAQ and i could not find something helpful ([FAQ](https://wiki.cq-repoured.net/index.php?title=FAQ))
 - [ ] I reproduced the bug without any other mod's except forge, cqr and it's dependencies
 - [ ] The game crashes because of this bug
 
 
 **Versions**
Chocolate Quest Repoured ('latest' IS NOT a valid version! Please use the version string that shows up in the mod overview of forge):
Forge:
Minecraft:

**Describe the bug**

**To Reproduce**
2. Use item '....'
3. Place block '....'
.
.
.

**Expected behavior**

**Screenshots**

**Other**
Please note: log files and crash reports should be uploaded as a FILE and not as a copy paste of the text of it here. Upload the file to a site like pastebin or similar and link it here!!
 - Link to Crash report file:
 - Link to Log file:
 - Other mods (that are necessary to produce the bug):
 - Other mods (that are also installed):
 - CQR config folder (link, only if you changed the configs):
 - Other mod's configs (link):

**Comment by DerToaster98** [comment]
What the actual …

1) WHY on earth is the title so long?
2) Mod version is?
3) Crash report?
4) Steps to reproduce?

Seriously though: is it so hard to use common sense to fill this out? It is not that difficult.

anyway, „latest“ for mod version is wrong, that lodpack was last updated on the 23rd of march. Last cqr update went live on the 27th of march. Also your problem is not reproducible.

**Comment by DerToaster98** [comment]
Oh and in the case you still believe that that bug exists, here is some footage showing the opposite: https://www.youtube.com/watch?v=IOU06Be5OxY

**Comment by TheHolyTopBob** [comment]
I think his game is soft-locked or something. Which I don't think would produce a crash report. But he should send the mod version, how to reproduce etc. And try playing without the other mods.

**Comment by TheHolyTopBob** [comment]
wait its not updated

**Comment by TheHolyTopBob** [comment]
Nevermind
