### ISSUE TITLE
Abyss Walker King

### ISSUE THREAD

**Issue by BuilderJD06** [TeamChocoQuest/ChocolateQuestRepoured#283]
**Common sense Info**
To check a checkbox: Insert a lower case X between the square brackets, you need to remove the space though.
 - I play...
   - [x] With a large modpack
   - [ ] Only with CQR and it's dependencies
 - The issue occurs in...
   - [x] Singleplayer
   - [ ] Multiplayer
 - [x] I have searched for this or a similar issue before reporting and it was either (1) not previously reported, or (2) previously fixed  and I'm having the same problem.
 - [ ] I am using the latest version of the mod (all versions can be found on github under releases)
 - [x] I read through the FAQ and i could not find something helpful ([FAQ](https://wiki.cq-repoured.net/index.php?title=FAQ))
 - [ ] I reproduced the bug without any other mod's except forge, cqr and it's dependencies
 - [x] The game crashes because of this bug
 
 
 **Versions**
Chocolate Quest Repoured ('latest' IS NOT a valid version! Please use the version string that shows up in the mod overview of forge): 2.5.2B
Forge:  14.23.5.2854
Minecraft: 1.12.2

**Describe the bug**
While Fighting the Abyss Walker Kind, sometimes when the boss uses the Walker Tornado ability the game crashes
**To Reproduce**
1. Go to 'Snow Castle'
2. Use item 'Any'
3. Place block 'N/A'
https://paste.mod.gg/ovutocijam.mccrash
**Expected behavior**
Immediately as boss uses ability game freezes for about 2 seconds and then follows with a crash. 

**Screenshots**
None Available

**Other**
Please note: log files and crash reports should be uploaded as a FILE and not as a copy paste of the text of it here. Upload the file to a site like pastebin or similar and link it here!!
 - Link to Crash report file: https://paste.mod.gg/ovutocijam.mccrash
 - Link to Log file: https://github.com/TeamChocoQuest/ChocolateQuestRepoured/files/6788674/2021-07-08-1.log
 - Other mods (that are necessary to produce the bug): None
 - Other mods (that are also installed): Texkit Pi Modpack - Latest Version With added mods; Chicken Chunks, ProjectE
 - CQR config folder (link, only if you changed the configs): N/A
 - Other mod's configs (link): Default

**Comment by DerToaster98** [comment]
Update the mod, this has been fixed in v2.5.3B
