### ISSUE TITLE
Ticking Entity that doesn't result in crash?

### ISSUE THREAD

**Issue by thedeerirty** [TeamChocoQuest/ChocolateQuestRepoured#284]
**Common sense Info**
To check a checkbox: Insert a lower case X between the square brackets, you need to remove the space though.
 - I play...
   - [X] With a large modpack
   - [ ] Only with CQR and it's dependencies
 - The issue occurs in...
   - [ ] Singleplayer
   - [X] Multiplayer
 - [X] I have searched for this or a similar issue before reporting and it was either (1) not previously reported, or (2) previously fixed  and I'm having the same problem.
 - [X] I am using the latest version of the mod (all versions can be found on github under releases)
 - [X] I read through the FAQ and i could not find something helpful ([FAQ](https://wiki.cq-repoured.net/index.php?title=FAQ))
 - [ ] I reproduced the bug without any other mod's except forge, cqr and it's dependencies
 - [ ] The game crashes because of this bug

Chocolate Quest Repoured ('latest' IS NOT a valid version! Please use the version string that shows up in the mod overview of forge): Beta 5.2
Forge: 1.12.2-14.23.5.2855
Minecraft: 1.12.2

**Describe the bug**
Simply put, entities are getting forced-despawn upon selecting a task, I believe, that involves the player. Only occurs in multiplater, and I'm not sure what could be causing incompatiblity. AI reducer? No clue. I've included a log that contains the error my console throws.

**To Reproduce**
1. Approach entity in dungeon
2. It looks at you and vanishes
3. Profit(?)

**Expected behavior**
I do in fact, fight and mayhaps kill the entity.

**Other**
Please note: log files and crash reports should be uploaded as a FILE and not as a copy paste of the text of it here. Upload the file to a site like pastebin or similar and link it here!!
 - Link to Crash report file:
 - Link to Log file: 
[latest.log](https://github.com/TeamChocoQuest/ChocolateQuestRepoured/files/7088575/latest.log)

 - Other mods (that are necessary to produce the bug): AI Reducer? It's all I can think of. 
 - Other mods (that are also installed): Several, several. Will update once I get the list exactly as I'm trying to remember the command prompt command that lets you just paste it in a text file

**Comment by DerToaster98** [comment]
First: Update the mod, you're using an outdated version

Second: The problem is either your forge version or some mod that decides to remove methods from forge. Try downgrading to forge 2847

**Comment by Meldexun** [comment]
That bug was fixed in CQR-1.12.2-2.5.3B
