### ISSUE TITLE
Entity IDS

### ISSUE THREAD

**Issue by edgaradr223** [TeamChocoQuest/ChocolateQuestRepoured#285]
Hi everyone, having an issue using neat which someone on your staff stated its going to be solved within next environment patch, as of now i need to keep my server running and my idea is to try and blacklist your entities from rendering using the neat config file that goes this way:

# Blacklist uses entity IDs, not their display names. 
    S:Blacklist <
        Shulker
        CustomNpc
        ArmorStand
        IceDragon
        FireDragon

**What would be the entity ID i need to enter in that file in order to try and solve until new release comes?**

I also want to say that your mod is the best exploration/questing surface mod out there for 1.12.2 i spiced it up with some quest chests and its absolutely great, thank yoyu for that.

**Comment by DerToaster98** [comment]
You can find them out yourself by typing "/summon cqrepoured:" and then pressing TAB, it will spit out a list of all cqr entity ids.

The entities you need to blacklist are these:
- Abyss Walker (cqrepoured:walker)
- Walker king (cqrepoured:walker_king)
- Enderman (cqrepoured:enderman)
- Triton (cqrepoured:triton)
- Golems (cqrepoured:golem)

Oh and btw: Sarcastic crap like you posted in the other issue helps nobody (and yes, we see the message history), so for the future just don't post such stuff, thanks.

**Comment by edgaradr223** [comment]
LOL i just got angry for the way you answered to the posts author, you need to be kind and humble or dont expect people to be the same with you, great mod but really disrespectful people, if you think youre doing us a favor you´re right , but it doesnt give you the right to talk to us that way. We are here because we have a problem, otherwise we wont be here, if you think this is very hard to do or understand maybe you should just close this github and forums and just state in your mod page you are not supporting anyone, i dont regret of what i posted before i deleted my comment not to make double posting not for regret. Oh and I sincerely expect this is the last time i need to open conversation with you and i know you agree with me, great mod bye bye.
