### ISSUE TITLE
Dungeons only spawn Skeletons and no other mod species in Strongholds and Randomized Castles

### ISSUE THREAD

**Issue by TarkinGithub** [TeamChocoQuest/ChocolateQuestRepoured#286]
**Common sense Info**
To check a checkbox: Insert a lower case X between the square brackets, you need to remove the space though.
 - I play...
   - [x ] With a large modpack
   - [ ] Only with CQR and it's dependencies
 - The issue occurs in...
   - [ ] Singleplayer
   - [ x] Multiplayer
 - [ x] I have searched for this or a similar issue before reporting and it was either (1) not previously reported, or (2) previously fixed  and I'm having the same problem.
 - [x ] I am using the latest version of the mod (all versions can be found on github under releases)
 - [x ] I read through the FAQ and i could not find something helpful ([FAQ](https://wiki.cq-repoured.net/index.php?title=FAQ))
 - [ x] I reproduced the bug without any other mod's except forge, cqr and it's dependencies
 - [ ] The game crashes because of this bug
 
 
 **Versions**
Chocolate Quest Repoured ('latest' IS NOT a valid version! Please use the version string that shows up in the mod overview of forge):
Forge:
Minecraft:

**Describe the bug**

**To Reproduce**
2. Use item '....'
3. Place block '....'
.
.
.

**Expected behavior**

**Screenshots**

**Other**
Please note: log files and crash reports should be uploaded as a FILE and not as a copy paste of the text of it here. Upload the file to a site like pastebin or similar and link it here!!
 - Link to Crash report file:
 - Link to Log file:
 - Other mods (that are necessary to produce the bug):
 - Other mods (that are also installed):
 - CQR config folder (link, only if you changed the configs):
 - Other mod's configs (link):

**Comment by DerToaster98** [comment]
No mandatory information as requested by the template is given. Thus we can't help you.

I can tell you though that that was a bug in a very old version and that the mob in dungeons depends on the distance to the world spawn.
