### ISSUE TITLE
I put the chocolatequest mod on a server with friends but some mini-bosses don't spawn

### ISSUE THREAD

**Issue by Wesadsf** [TeamChocoQuest/ChocolateQuestRepoured#287]
**Common sense Info**
To check a checkbox: Insert a lower case X between the square brackets, you need to remove the space though.
 - I play...
   - [ ] With a modpack created by me for a server with friends
 - The issue occurs in...
   - [ ] Multiplayer
 - [ ] I have searched for this or a similar issue before reporting and it was either (1) not previously reported, 
 - [ ] I am using the latest version of the mod (all versions can be found on github under releases)
 - [ ] I read through the FAQ and i could not find something helpful ([FAQ](https://wiki.cq-repoured.net/index.php?title=FAQ))
 - [ ] I reproduced the bug without any other mod's except forge, cqr and it's dependencies

 
 
 **Versions**
Chocolate Quest Repoured ('latest' IS NOT a valid version! Please use the version string that shows up in the mod overview of forge): 2.5.3B
Forge: 1.12.2-forge-14.23.4.2854
Minecraft: 1.12.2

**Describe the bug**
When generating the dungeon where the giant tortoise and spider boss miniboses appear, they are not generated and when attempting to spawn them with commands or with their spawneggs they are not generated,The bug only happens in multiplayer mode since if I go to a normal world with the same mods if the mini-boss is generated

**To Reproduce**
Go to the turtle miniboss dungeon

**Expected behavior**
When you go closer to the dungeon, only 2 boss bars appear and eliminate them all and go to the room of the miniboss this is not
**Screenshots**
![2021-10-13_12 45 05](https://user-images.githubusercontent.com/92452712/137186141-9d662692-fb37-4d99-9448-7307f85d133d.png)
![2021-10-13_12 45 09](https://user-images.githubusercontent.com/92452712/137186174-091dccc6-c50c-49bc-b768-d0e708088f88.png)
![2021-10-13_12 45 12](https://user-images.githubusercontent.com/92452712/137186211-2dc79cc6-3822-425e-af74-5fe1e3ef37e9.png)
The boss does not spawn neither with command nor with the spawnegg

**Other**
Please note: log files and crash reports should be uploaded as a FILE and not as a copy paste of the text of it here. Upload the file to a site like pastebin or similar and link it here!!
 - Link to Crash report fille:https://pastebin.com/PSwuZmt8
 - Link to Log file:
 - Other mods ):https://www.mediafire.com/folder/1b4f0hk44zfa4/mods
 - Other mods (that are also installed):
 - CQR config folder (link, only if you changed the configs):https://pastebin.com/sgWiu4r3
 - Other mod's configs (link):All mods have the base configuration
 - CQR mod: Chocolate_Quest_Repoured-1.12.2-2.5.3b

**Comment by DerToaster98** [comment]
OK, bug is reproduced, gotta figure out why it doesn't spawn.

**Comment by Wesadsf** [comment]
I hope and the update comes soon since I have to win from fighting with that boss with my friends

**Comment by DerToaster98** [comment]
The boss should work fine using LAN connections (aka LAN Party), the update will be published when it is ready. We currently don't have a lot of time to work on the mod. If progress stays like it is currently i guess that the next update will be published in at least two weeks (which is highly unlikely). We might think about publishing a different release without the new content but with just the fixes though.

**Comment by DerToaster98** [comment]
Fixed in newest release (2.6.0)
