### ISSUE TITLE
Holding a musket deletes items held in off-hand

### ISSUE THREAD

**Issue by xJon** [TeamChocoQuest/ChocolateQuestRepoured#290]
**Common sense Info**
To check a checkbox: Insert a lower case X between the square brackets, you need to remove the space though.
 - I play...
   - [X] With a large modpack
   - [X] Only with CQR and it's dependencies
 - The issue occurs in...
   - [X] Singleplayer
   - [X] Multiplayer
 - [X] I have searched for this or a similar issue before reporting and it was either (1) not previously reported, or (2) previously fixed  and I'm having the same problem.
 - [X] I am using the latest version of the mod (all versions can be found on github under releases)
 - [ ] I read through the FAQ and i could not find something helpful ([FAQ](https://wiki.cq-repoured.net/index.php?title=FAQ))
 - [X] I reproduced the bug without any other mod's except forge, cqr and it's dependencies
 - [ ] The game crashes because of this bug
 
 
 **Versions**
Chocolate Quest Repoured ('latest' IS NOT a valid version! Please use the version string that shows up in the mod overview of forge): `2.5.3B`
Forge: `14.23.5.2855`
Minecraft: `1.12.2`

**Describe the bug**
First reported over https://github.com/xJon/Hexxit-II/issues/2.
When holding any one of the four muskets, with a "non-gear" item in your off-hand, your off-hand item will get deleted.
If the item in your off-hand is a "gear" item according to CQR it will get unequipped instead.

**To Reproduce**
1. Hold an item in your off-hand
2. Hold a CQR musket in your main hand
3. Off-hand item will get deleted in most cases (or unequipped).

Thank you!

**Comment by DerToaster98** [comment]
Fixed in 2.6.0B
