### ISSUE TITLE
Tinker's Construct compat 

### ISSUE THREAD

**Issue by Xanfax** [TeamChocoQuest/ChocolateQuestRepoured#292]
I'm currently playing this mod in a private pack on a household server, and I love it right to death. But I've managed to find out by accident that the EFLN device from Tinker's Construct (and potentially other explosives I've not tested yet) can destroy protected blocks in survival.

I've also noticed that the config switch for lighting after generating dungeons seems to reduce worldgen lag by quite a bit in large packs without any noticeable visual degradation. By the time you're close enough to see the dungeon, it's already fully lit (in most cases). If it were me, I'd default that to lighting after generation and note the switch as a compatibility option for worlds with very short render distances. At 12 though, I never noticed a visual change. It just gens faster, which for servers is obviously key.

Thanks for the great mod, hope to see a release version soon!

Oh and as a side note-
So far this has been compatible with everything I've thrown at it including worldgen mods. Good work. And there are 106 other mods in my pack!

**Comment by DerToaster98** [comment]
The issue tracker is for problems only, for anything else please use the discord.
