### ISSUE TITLE
Iron spears can't be repaired using the anvil

### ISSUE THREAD

**Issue by BIG-Viljo** [TeamChocoQuest/ChocolateQuestRepoured#293]
**Common sense Info**
To check a checkbox: Insert a lower case X between the square brackets, you need to remove the space though.
 - I play...
   - [x] With a large modpack
   - [ ] Only with CQR and it's dependencies
 - The issue occurs in...
   - [x] Singleplayer
   - [x] Multiplayer
 - [x] I have searched for this or a similar issue before reporting and it was either (1) not previously reported, or (2) previously fixed  and I'm having the same problem.
 - [x] I am using the latest version of the mod (all versions can be found on github under releases)
 - [x] I read through the FAQ and i could not find something helpful ([FAQ](https://wiki.cq-repoured.net/index.php?title=FAQ))
 - [x] I reproduced the bug without any other mod's except forge, cqr and it's dependencies
 - [ ] The game crashes because of this bug
 
 
 **Versions**
Chocolate Quest Repoured ('latest' IS NOT a valid version! Please use the version string that shows up in the mod overview of forge): 2.5.3B
Forge: 14.23.5.2855
Minecraft: 1.12.2

**Describe the bug**
Iron spears can't be repaired in the anvil using iron ingots. Other iron weapons (dagger, longsword) can be repaired as well as all diamond weapons (including diamond spear).

**To Reproduce**
1. Get iron spear (method doesn't matter, enchantments don't matter, level of damage doesn't matter)
2. Break a block or hit something with it for it to lose durability
3. Try to put the iron spear into first slot and an iron ingot (or more of them) into second slot of anvil UI
4. The spear doesn't show up in the third slot ready to be repaired and neither does the price for the repair, implying that the recipe is missing

**Expected behavior**
The damaged iron spear when combined with iron ingots in anvil should show up in the third slot of anvil, ready to be repaired, retaining the enchantments (if it had any before the repair).

**Screenshots**
![2021-11-19_13 14 01](https://user-images.githubusercontent.com/81764255/142621221-dbb38066-6b7f-4a12-a062-0e6a5d949ac5.png)
![2021-11-19_13 13 25](https://user-images.githubusercontent.com/81764255/142621227-bab3c954-6858-4db7-b4b4-8105279802bc.png)
![2021-11-19_13 13 35](https://user-images.githubusercontent.com/81764255/142621228-d0f6c496-7f66-4f7d-9539-14021ca24da8.png)
![2021-11-19_13 13 40](https://user-images.githubusercontent.com/81764255/142621230-3da038a6-331a-4e69-8257-d5aeaa463aec.png)
![2021-11-19_13 13 52](https://user-images.githubusercontent.com/81764255/142621231-0ebe69f0-f0bc-43f3-8b42-e063a904d057.png)
![2021-11-19_13 13 57](https://user-images.githubusercontent.com/81764255/142621233-5610017f-1ad9-46d4-9e93-77ecef6efbcd.png)

**Other**
Please note: log files and crash reports should be uploaded as a FILE and not as a copy paste of the text of it here. Upload the file to a site like pastebin or similar and link it here!!
 - Link to Crash report file (only if the game crashes because of this bug, please use something like pastebin to upload it, then link it here): game doesn't crash
 - Link to Log file (only if the game crashes because of this bug, please use something like pastebin to upload it, then link it here):
 - Other mods (that are necessary to produce the bug): no other mods are needed
 - Other mods (that are also installed, at best: link a zip file that contains all the installed mods): no other mods are used
 - CQR config folder (link, only if you changed the configs): using only default config
 - Other mod's configs (link, only if any config was changed): using only default config

**Comment by DerToaster98** [comment]
Already fixed in development

**Comment by DerToaster98** [comment]
Fixed in 2.6.0B
