### ISSUE TITLE
Gecklib  dependence broken 

### ISSUE THREAD

**Issue by Brandonbr1** [TeamChocoQuest/ChocolateQuestRepoured#296]
**Common sense Info**
To check a checkbox: Insert a lower case X between the square brackets, you need to remove the space though.
 - I play...
   - [x] With a large modpack
 - The issue occurs in...
   - in all versions
 - [x] The game crashes because of this bug
 
 
 **Versions**
Chocolate Quest Repoured ('latest' IS NOT a valid version! Please use the version string that shows up in the mod overview of forge):
Forge:the newest version
Minecraft:1.12.2

**Describe the bug**
i cant get into the mod

**To Reproduce**
1.open up Minecraft
2. See error

**Expected behavior**

**Screenshots**

![1](https://user-images.githubusercontent.com/74426342/143115888-7df12a77-a7c7-412f-9aa6-d1631261deef.PNG)
![2](https://user-images.githubusercontent.com/74426342/143115993-01888367-7983-4c32-baeb-9a6e210cb55f.PNG)

**Other**
error here
[https://pastebin.com/sPuumW0v](https://pastebin.com/sPuumW0v)

**Comment by Kasia1403** [comment]
Same.

**Comment by DerToaster98** [comment]
We know about this and it is a problem on geckolibs side. Go on the discord and look in #news, there is a workaround for this

**Comment by DerToaster98** [comment]
Patched in version 2.6.1B
