### ISSUE TITLE
Seemingly a crash for dungeon generation

### ISSUE THREAD

**Issue by Smokedeuch** [TeamChocoQuest/ChocolateQuestRepoured#297]
**Common sense Info**
To check a checkbox: Insert a lower case X between the square brackets, you need to remove the space though.
 - I play...
   - [ ] With a large modpack
   - [ X] Only with CQR and it's dependencies
 - The issue occurs in...
   - [X] Singleplayer
   - [ ] Multiplayer
 - [ 1] I have searched for this or a similar issue before reporting and it was either (1) not previously reported, or (2) previously fixed  and I'm having the same problem.
 - [X ] I am using the latest version of the mod (all versions can be found on github under releases)
 - [ X] I read through the FAQ and i could not find something helpful ([FAQ](https://wiki.cq-repoured.net/index.php?title=FAQ))
 - [X ] I reproduced the bug without any other mod's except forge, cqr and it's dependencies
 - [ X] The game crashes because of this bug
 
 
 **Versions**
Chocolate Quest Repoured ('latest' IS NOT a valid version! Please use the version string that shows up in the mod overview of forge):
Forge:14.23.5.2855
Minecraft:1.12.2

**Describe the bug**

Seemingly a dungeon generation crash

**Screenshots**

**Other**
Please note: log files and crash reports should be uploaded as a FILE and not as a copy paste of the text of it here. Upload the file to a site like pastebin or similar and link it here!!
 - Link to Crash report file (only if the game crashes because of this bug, please use something like pastebin to upload it, then link it here):[crash-2021-11-23_15.14.04-server.txt](https://github.com/TeamChocoQuest/ChocolateQuestRepoured/files/7591117/crash-2021-11-23_15.14.04-server.txt)

**Comment by DerToaster98** [comment]
Will be fixed in the next patch (probably later today)

**Comment by DerToaster98** [comment]
Patched in version 2.6.1B
