### ISSUE TITLE
Spin to win mob hitbox broken

### ISSUE THREAD

**Issue by DarkCorgi** [TeamChocoQuest/ChocolateQuestRepoured#298]
**Common sense Info**
To check a checkbox: Insert a lower case X between the square brackets, you need to remove the space though.
 - I play...
   - [ ] With a large modpack
   - [x] Only with CQR and it's dependencies
 - The issue occurs in...
   - [x] Singleplayer
   - [ ] Multiplayer
 - [x] I have searched for this or a similar issue before reporting and it was either (1) not previously reported, or (2) previously fixed  and I'm having the same problem.
 - [x] I am using the latest version of the mod (all versions can be found on github under releases)
 - [x] I read through the FAQ and i could not find something helpful ([FAQ](https://wiki.cq-repoured.net/index.php?title=FAQ))
 - [x] I reproduced the bug without any other mod's except forge, cqr and it's dependencies
 - [ ] The game crashes because of this bug
 
 
 **Versions**
Chocolate Quest Repoured ('latest' IS NOT a valid version! Please use the version string that shows up in the mod overview of forge):
Beta 6.0
Forge: 14.23.5.2855
Minecraft:1.12.2

**Describe the bug**
When I am attacked by a skeleton using the spin ability it does not hit me.

**To Reproduce**
1. Find a skeleton with two weapons
2. wait for them to use spin attack
3. profit?
.
.
.
4.

**Expected behavior**
I expected to be hit by the attack and take damage

**Screenshots**
https://streamable.com/nks8es (Video link)

**Other**
I didn't include a screenshots but put a streamable link to a video of the bug occurring.
Please note: log files and crash reports should be uploaded as a FILE and not as a copy paste of the text of it here. Upload the file to a site like pastebin or similar and link it here!!
 - Link to Crash report file (only if the game crashes because of this bug, please use something like pastebin to upload it, then link it here):
 - Link to Log file (only if the game crashes because of this bug, please use something like pastebin to upload it, then link it here):
 - Other mods (that are necessary to produce the bug):
 - Other mods (that are also installed, at best: link a zip file that contains all the installed mods):
 - CQR config folder (link, only if you changed the configs):
 - Other mod's configs (link, only if any config was changed):

**Comment by DerToaster98** [comment]
We already know this, thanks for reporting anyways. 

It actually has nothing to do with the hitbox.

Path will be published in the next update (later today)

**Comment by DerToaster98** [comment]
Patched in version 2.6.1B
