### ISSUE TITLE
Spectral Balsam Incorrect Name

### ISSUE THREAD

**Issue by minekraftminer** [TeamChocoQuest/ChocolateQuestRepoured#300]
**Common sense Info**
To check a checkbox: Insert a lower case X between the square brackets, you need to remove the space though.
 - I play...
   - [x] With a large modpack
   - [ ] Only with CQR and it's dependencies
 - The issue occurs in...
   - [x] Singleplayer
   - [ ] Multiplayer
 - [x] I have searched for this or a similar issue before reporting and it was either (1) not previously reported, or (2) previously fixed  and I'm having the same problem.
 - [x] I am using the latest version of the mod (all versions can be found on github under releases)
 - [x] I read through the FAQ and i could not find something helpful ([FAQ](https://wiki.cq-repoured.net/index.php?title=FAQ))
 - [x] I reproduced the bug without any other mod's except forge, cqr and it's dependencies
 - [ ] The game crashes because of this bug
 
 
 **Versions**
Chocolate Quest Repoured: Beta 6.1  (2.6.1)
Forge: 14.23.5.2855
Minecraft: 1.12.2

**Describe the bug**
Technically not a "Bug", but Spectral Balsam is mistakenly named "Sharpness"

**To Reproduce**
1. Go To 'Creative Menu'
2. Search 'Sharpness'
3. There should be 2 sets of sharpness books, and no spectral balsam.

**Expected behavior**
Spectral Balsam should have its correct name

**Screenshots**
"Screen Shot has JEI and Enchantment Book Descriptions Installed"
![image](https://user-images.githubusercontent.com/82829316/143470252-4f7ad727-babb-45b0-bf1f-9e860854720f.png)

**Comment by DerToaster98** [comment]
Fixed in development, will be patched in the next update
