### ISSUE TITLE
Server crash after update to new version

### ISSUE THREAD

**Issue by Tot7uafag** [TeamChocoQuest/ChocolateQuestRepoured#301]
**Common sense Info**
To check a checkbox: Insert a lower case X between the square brackets, you need to remove the space though.
 - I play...
   - [x] With a large modpack
   - [ ] Only with CQR and it's dependencies
 - The issue occurs in...
   - [x] Singleplayer
   - [x] Multiplayer
 - [x] I have searched for this or a similar issue before reporting and it was either (1) not previously reported, or (2) previously fixed  and I'm having the same problem.
 - [x] I am using the latest version of the mod (all versions can be found on github under releases)
 - [x] I read through the FAQ and i could not find something helpful ([FAQ](https://wiki.cq-repoured.net/index.php?title=FAQ))
 - [ ] I reproduced the bug without any other mod's except forge, cqr and it's dependencies
 - [x] The game crashes because of this bug
 
 
 **Versions**
Chocolate Quest Repoured ('latest' IS NOT a valid version! Please use the version string that shows up in the mod overview of forge):
Forge: 14.23.5.2855
Minecraft: 1.12.2
Chocolate_Quest_Repoured-1.12.2-2.6.1B.jar
geckolib-forge-1.12.2-3.0.11.jar

**Describe the bug**
Game crashes

**To Reproduce**
1. I was just walking through a newly generated world when world crashed, tried to relog after crash and world automatically shut down, tried in multiplayer having the same result. Tried in a different new world having the same result. No config file changes, using defaults, not happening with prior versions of cqr BUT if i try to use a prior version (including old geckolib) in a world loaded with latest version it just crashes.

Log file: https://pastebin.com/Ae85p5ut

**Comment by DerToaster98** [comment]
Please try to reproduce this with new configs (standard configs of CQR).

If it still doesn't work, please try with just cqr and it's dependencies.

**Comment by DerToaster98** [comment]
Also: Did you delete the CQR folder before updating?

**Comment by Tot7uafag** [comment]
> Also: Did you delete the CQR folder before updating?

yes i did, also moved old configs to config folder when tried with prior versions (i always have a backup) so im going to try and reproduce with cqr and report back

**Comment by Tot7uafag** [comment]
> Please try to reproduce this with new configs (standard configs of CQR).
> 
> If it still doesn't work, please try with just cqr and it's dependencies.

Nope, unable to reproduce with only cqr - geckolib installed, may be an issue caused by another mod. I guess ill just use prior version again which is not problem as the mod is still awesome, i tracked the issue in my console and it shows a little bit more information i guess, ill paste this here https://pastebin.com/CaCBraNV for reference and will try removing groups of mods 10 by 10 to track the mod causing conflict with cqr

**Comment by DerToaster98** [comment]
Please don't use outdated versions

**Comment by Tot7uafag** [comment]
I found this, opened a ticket at geckolib, just in case someone else comes with the same issue
https://pastebin.com/pW7dzhGK

**Comment by DerToaster98** [comment]
That's odd. It seems to point at problems with molang, but we don't even use molang on our mobs....

I don't think it is geckolib to be honest...

**Comment by DerToaster98** [comment]
Fixed in 2.6.2B
