### ISSUE TITLE
Can only catch mobs in soul bottles when behind of grass or if the mob is a dragon

### ISSUE THREAD

**Issue by Tot7uafag** [TeamChocoQuest/ChocolateQuestRepoured#304]
**Common sense Info**
To check a checkbox: Insert a lower case X between the square brackets, you need to remove the space though.
 - I play...
   - [x] With a large modpack
   - [ ] Only with CQR and it's dependencies
 - The issue occurs in...
   - [x] Singleplayer
   - [x] Multiplayer
 - [x] I have searched for this or a similar issue before reporting and it was either (1) not previously reported, or (2) previously fixed  and I'm having the same problem.
 - [x] I am using the latest version of the mod (all versions can be found on github under releases)
 - [x] I read through the FAQ and i could not find something helpful ([FAQ](https://wiki.cq-repoured.net/index.php?title=FAQ))
 - [ ] I reproduced the bug without any other mod's except forge, cqr and it's dependencies
 - [ ] The game crashes because of this bug
 
 
 **Versions**
Chocolate_Quest_Repoured-1.12.2-2.6.2B
Forge:14.23.5.2859
Minecraft: 1.12.2

Instead of catching mobs in soul bottles i hit them, unless they are behind of grass or if the mob is an ice and fire dragon

1. Use an empty soul bottle on a mob and it hits the mob instead of catching it

![skeleton no grass](https://user-images.githubusercontent.com/92709869/145697079-097c7db4-db73-4cc4-a447-61d516f4ff90.png)

2. After I tried many things and removed many mods to debug the issue, i found out that i was able to catch mobs but only if there is grass between the mob and me as you can see in this picture: 

![skeletongrass](https://user-images.githubusercontent.com/92709869/145697115-c4630209-fcfd-4cac-9c8c-578f60e8a00b.png)

3. If the mob is an ice and fire dragon of any sort, or a big cyclops from cyclopstek mod the soul bottle doesnt fail at catching the mob, however, the ender dragon and the abyssal craft dragons failed to be caught so i assume its not about mob heights. 

![dragon1](https://user-images.githubusercontent.com/92709869/145697217-314694bd-ec04-4261-a517-4965db08a959.png)

.
![dragon2](https://user-images.githubusercontent.com/92709869/145697219-4824e709-caee-4831-8a51-5185267a4b98.png)

 - Other mods (that are necessary to produce the bug):

After removing mods to debug the issue i found out that this only happens when mods that use Mixin 0.7-0.8 Compatibility like aqua acrobatics are installed and mo'bends mod or/and immersive combat rebirth are present, i know that there is a compat issue between geckolib and mobends as mobends uses a folder to load their animations but i tried disabling the skeleton and zombie animations and got the same result, also tried with cows, pigs and other modded mobs but nope. I mean, i know this is not a major issue as the game is not crashing at all and already found a way to catch the mobs that is functional to me, but i wanted to report this to you guys just in case somebody else comes with the same issue.

**Comment by DerToaster98** [comment]
report this to the mods that cause it (apparently mo'bends or immersive combat), this is not a problem of CQR. Works fine with just CQ and Glib.

The only mobs in cqr that use GLib are some bosses, GLib is not the problem since it effectively only runs on the client
