### ISSUE TITLE
Texture loss

### ISSUE THREAD

**Issue by dogsking** [TeamChocoQuest/ChocolateQuestRepoured#307]
**Common sense Info**
To check a checkbox: Insert a lower case X between the square brackets, you need to remove the space though.
 - I play...
   - [ ~] With a large modpack
   - [ ] Only with CQR and it's dependencies
 - The issue occurs in...
   - [~ ] Singleplayer
   - [ ] Multiplayer
 - [ ] I have searched for this or a similar issue before reporting and it was either (1) not previously reported, or (2) previously fixed  and I'm having the same problem.
 - [ ] I am using the latest version of the mod (all versions can be found on github under releases)
 - [ ] I read through the FAQ and i could not find something helpful ([FAQ](https://wiki.cq-repoured.net/index.php?title=FAQ))
 - [ ] I reproduced the bug without any other mod's except forge, cqr and it's dependencies
 - [ ] The game crashes because of this bug
 
 
 **Versions**
Chocolate Quest Repoured ('latest' IS NOT a valid version! Please use the version string that shows up in the mod overview of forge):
Forge:14.23.5.2855
Minecraft:1.12.2

**Describe the bug**
The flame texture will become purple and black, just because of the new version

**To Reproduce**
Imported archived flames will not go wrong, but using new flames such as flint and magma will lose their texture

**Comment by DerToaster98** [comment]
And what version do you use? You don’t tell us anywhere

**Comment by DerToaster98** [comment]
Also this won’t be worked on unless proven that the problem is really this mod and not some other mod in the pack

**Comment by DerToaster98** [comment]
Tried to reproduce in the newest version (v2.6.2B, we only always support our newest version) and in development environment: Fire works and looks as it should.

This is not reproducible. Issue will be closed until you prove that this bug is from cqr and present in the newest version without any other mods except cqr and it's dependencies.
