### ISSUE TITLE
cqr_import_all yields error when a structure has a boss block in it

### ISSUE THREAD

**Issue by platinumphoenix2** [TeamChocoQuest/ChocolateQuestRepoured#308]
**Common sense Info**
To check a checkbox: Insert a lower case X between the square brackets, you need to remove the space though.
 - I play...
   - [ ] With a large modpack
   - [x] Only with CQR and it's dependencies
 - The issue occurs in...
   - [x] Singleplayer
   - [ ] Multiplayer
 - [ ] I have searched for this or a similar issue before reporting and it was either (1) not previously reported, or (2) previously fixed  and I'm having the same problem.
 - [x] I am using the latest version of the mod (all versions can be found on github under releases)
 - [x] I read through the FAQ and i could not find something helpful ([FAQ](https://wiki.cq-repoured.net/index.php?title=FAQ))
 - [x] I reproduced the bug without any other mod's except forge, cqr and it's dependencies
 - [ ] The game crashes because of this bug
 
**Describe the bug**
The command cqr_import_all will yield the error `Failed importing structures: java.lang.NullPointerException` when attempting to spawn a structure with a boss block with a soul bottle in it.

**Screenshots**
The structure that resulted in the error:
https://imgur.com/a/9ZnjXdD

**Comment by DerToaster98** [comment]
Not reproducable. Update your structures
