### ISSUE TITLE
Exterminator golem cause game crash

### ISSUE THREAD

**Issue by KELETU66666** [TeamChocoQuest/ChocolateQuestRepoured#309]
**Common sense Info**
To check a checkbox: Insert a lower case X between the square brackets, you need to remove the space though.
 - I play...
   - [√] With a large modpack
   - [ ] Only with CQR and it's dependencies
 - The issue occurs in...
   - [√] Singleplayer
   - [ ] Multiplayer
 - [ ] I have searched for this or a similar issue before reporting and it was either (1) not previously reported, or (2) previously fixed  and I'm having the same problem.
 - [√] I am using the latest version of the mod (all versions can be found on github under releases)
 - [√] I read through the FAQ and i could not find something helpful ([FAQ](https://wiki.cq-repoured.net/index.php?title=FAQ))
 - [ ] I reproduced the bug without any other mod's except forge, cqr and it's dependencies
 - [√] The game crashes because of this bug
 
 
 **Versions**
Chocolate Quest Repoured ('latest' IS NOT a valid version! Please use the version string that shows up in the mod overview of forge):
Forge:
Minecraft:

**Describe the bug**

**To Reproduce**
2. Use item '....'
3. Place block '....'
.
.
.
---- Minecraft Crash Report ----

WARNING: coremods are present:
  SpartanWeaponry-MixinLoader ([斯巴达的武器] SpartanWeaponry-1.12.2-1.4.0.jar)
  Thaumcraft Research Patcher Core Plugin (ThaumcraftResearchPatcher-1.12.2-1.1.3.jar)
  Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.14-1.12.2.jar)
  CQRPlugin (Chocolate_Quest_Repoured-1.12.2-2.6.2B.jar)
  ServerPropertiesLAN ([简单联机] ServerPropertiesLAN-2.65.jar)
  Thaumic Augmentation Core Plugin (ThaumicAugmentation-1.12.2-2.1.5.jar)
Contact their authors BEFORE contacting forge

// Who set us up the TNT?

Time: 12/26/21 7:11 PM
Description: Rendering entity in world

software.bernie.geckolib3.geo.exception.GeoModelException: cqrepoured:geo/exterminator.geo.json: Could not find model.
	at software.bernie.geckolib3.model.AnimatedGeoModel.getModel(AnimatedGeoModel.java:116)
	at software.bernie.geckolib3.renderers.geo.GeoEntityRenderer.doRender(GeoEntityRenderer.java:120)
	at team.cqr.cqrepoured.client.render.entity.RenderCQREntityGeo.doRender(RenderCQREntityGeo.java:70)
	at team.cqr.cqrepoured.client.render.entity.RenderCQREntityGeo.func_76986_a(RenderCQREntityGeo.java:32)
	at net.minecraft.client.renderer.entity.RenderManager.func_188391_a(RenderManager.java:413)
	at net.minecraft.client.renderer.entity.RenderManager.func_188388_a(RenderManager.java:393)
	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:850)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1808)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1621)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1390)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at software.bernie.geckolib3.model.AnimatedGeoModel.getModel(AnimatedGeoModel.java:116)
	at software.bernie.geckolib3.renderers.geo.GeoEntityRenderer.doRender(GeoEntityRenderer.java:120)
	at team.cqr.cqrepoured.client.render.entity.RenderCQREntityGeo.doRender(RenderCQREntityGeo.java:70)
	at team.cqr.cqrepoured.client.render.entity.RenderCQREntityGeo.func_76986_a(RenderCQREntityGeo.java:32)

-- Entity being rendered --
Details:
	Entity Type: cqrepoured:exterminator (team.cqr.cqrepoured.objects.entity.boss.exterminator.EntityCQRExterminator)
	Entity ID: 1452
	Entity Name: Exterminator Prototype
	Entity's Exact location: -545.50, 4.00, -353.50
	Entity's Block location: World: (-546,4,-354), Chunk: (at 14,0,14 in -35,-23; contains blocks -560,0,-368 to -545,255,-353), Region: (-2,-1; contains chunks -64,-32 to -33,-1, blocks -1024,0,-512 to -513,255,-1)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null

-- Renderer details --
Details:
	Assigned renderer: team.cqr.cqrepoured.client.render.entity.boss.exterminator.RenderCQRExterminator@3a734dbc
	Location: -1.25,0.00,0.58 - World: (-2,0,0), Chunk: (at 14,0,0 in -1,0; contains blocks -16,0,0 to -1,255,15), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Rotation: -98.43747
	Delta: 0.6999998
Stacktrace:
	at net.minecraft.client.renderer.entity.RenderManager.func_188391_a(RenderManager.java:413)
	at net.minecraft.client.renderer.entity.RenderManager.func_188388_a(RenderManager.java:393)
	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:850)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1808)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1621)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['keletu'/665, l='MpServer', x=-544.25, y=4.00, z=-354.08]]
	Chunk stats: MultiplayerChunkCache: 289, 289
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-523,4,-344), Chunk: (at 5,0,8 in -33,-22; contains blocks -528,0,-352 to -513,255,-337), Region: (-2,-1; contains chunks -64,-32 to -33,-1, blocks -1024,0,-512 to -513,255,-1)
	Level time: 266274 game time, 266274 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 60 total; [EntityItem['item.tile.dirt.default'/1281, l='MpServer', x=-517.76, y=2.00, z=-359.88], EntityItem['item.tile.dirt.default'/1283, l='MpServer', x=-518.49, y=1.00, z=-358.79], EntityItem['item.tile.dirt.default'/1285, l='MpServer', x=-519.51, y=1.00, z=-361.88], EntityItem['item.tile.dirt.default'/1287, l='MpServer', x=-521.88, y=1.00, z=-361.88], EntityItem['item.tile.dirt.default'/1289, l='MpServer', x=-520.44, y=1.00, z=-361.63], EntityItem['item.tile.dirt.default'/1290, l='MpServer', x=-518.13, y=1.00, z=-361.88], EntityItem['item.tile.dirt.default'/1170, l='MpServer', x=-522.88, y=1.00, z=-355.61], EntityItem['item.tile.dirt.default'/1174, l='MpServer', x=-517.13, y=1.00, z=-357.79], EntityPlayerSP['keletu'/665, l='MpServer', x=-544.25, y=4.00, z=-354.08], SubEntityNetherDragonSegment['不明'/925, l='MpServer', x=0.00, y=0.00, z=0.00], SubEntityNetherDragonSegment['不明'/926, l='MpServer', x=0.00, y=0.00, z=0.00], SubEntityNetherDragonSegment['不明'/927, l='MpServer', x=0.00, y=0.00, z=0.00], SubEntityNetherDragonSegment['不明'/928, l='MpServer', x=0.00, y=0.00, z=0.00], SubEntityNetherDragonSegment['不明'/929, l='MpServer', x=0.00, y=0.00, z=0.00], SubEntityNetherDragonSegment['不明'/930, l='MpServer', x=0.00, y=0.00, z=0.00], SubEntityNetherDragonSegment['不明'/931, l='MpServer', x=0.00, y=0.00, z=0.00], SubEntityNetherDragonSegment['不明'/932, l='MpServer', x=0.00, y=0.00, z=0.00], SubEntityNetherDragonSegment['不明'/933, l='MpServer', x=0.00, y=0.00, z=0.00], SubEntityNetherDragonSegment['不明'/934, l='MpServer', x=0.00, y=0.00, z=0.00], SubEntityNetherDragonSegment['不明'/935, l='MpServer', x=0.00, y=0.00, z=0.00], SubEntityNetherDragonSegment['不明'/936, l='MpServer', x=0.00, y=0.00, z=0.00], SubEntityNetherDragonSegment['不明'/937, l='MpServer', x=0.00, y=0.00, z=0.00], SubEntityNetherDragonSegment['不明'/938, l='MpServer', x=0.00, y=0.00, z=0.00], SubEntityNetherDragonSegment['不明'/939, l='MpServer', x=0.00, y=0.00, z=0.00], SubEntityNetherDragonSegment['不明'/940, l='MpServer', x=0.00, y=0.00, z=0.00], EntityCQRExterminator['Exterminator Prototype'/1452, l='MpServer', x=-545.50, y=4.00, z=-353.50], SubEntityNetherDragonSegment['不明'/941, l='MpServer', x=0.00, y=0.00, z=0.00], SubEntityNetherDragonSegment['不明'/942, l='MpServer', x=0.00, y=0.00, z=0.00], EntityItem['item.tile.dirt.default'/1198, l='MpServer', x=-519.10, y=1.00, z=-356.08], SubEntityNetherDragonSegment['不明'/943, l='MpServer', x=0.00, y=0.00, z=0.00], SubEntityNetherDragonSegment['不明'/944, l='MpServer', x=0.00, y=0.00, z=0.00], EntityItem['item.tile.dirt.default'/1200, l='MpServer', x=-518.19, y=1.00, z=-357.35], SubEntityNetherDragonSegment['不明'/945, l='MpServer', x=0.00, y=0.00, z=0.00], EntityItem['item.tile.dirt.default'/1201, l='MpServer', x=-517.40, y=1.00, z=-356.06], SubEntityNetherDragonSegment['不明'/946, l='MpServer', x=0.00, y=0.00, z=0.00], SubEntityNetherDragonSegment['不明'/947, l='MpServer', x=0.00, y=0.00, z=0.00], EntityItem['item.tile.dirt.default'/1203, l='MpServer', x=-520.38, y=1.00, z=-354.13], SubEntityNetherDragonSegment['不明'/948, l='MpServer', x=0.00, y=0.00, z=0.00], SubEntityNetherDragonSegment['不明'/949, l='MpServer', x=0.00, y=0.00, z=0.00], SubEntityNetherDragonSegment['不明'/950, l='MpServer', x=0.00, y=0.00, z=0.00], EntityItem['item.tile.dirt.default'/1206, l='MpServer', x=-517.13, y=1.00, z=-355.30], SubEntityNetherDragonSegment['不明'/951, l='MpServer', x=0.00, y=0.00, z=0.00], EntityItem['item.tile.dirt.default'/1207, l='MpServer', x=-520.67, y=1.00, z=-355.63], SubEntityNetherDragonSegment['不明'/952, l='MpServer', x=0.00, y=0.00, z=0.00], EntityItem['item.tile.dirt.default'/1209, l='MpServer', x=-519.53, y=1.00, z=-358.44], EntityItem['item.tile.dirt.default'/1210, l='MpServer', x=-518.13, y=1.00, z=-354.53], EntityItem['item.tile.dirt.default'/1211, l='MpServer', x=-519.13, y=2.00, z=-353.51], EntityItem['item.tile.dirt.default'/1234, l='MpServer', x=-525.65, y=1.00, z=-356.13], EntityItem['item.tile.dirt.default'/1236, l='MpServer', x=-521.89, y=1.00, z=-355.31], EntityItem['item.tile.dirt.default'/1239, l='MpServer', x=-524.13, y=1.00, z=-355.47], EntityItem['item.tile.dirt.default'/1240, l='MpServer', x=-524.40, y=1.00, z=-358.12], EntityItem['item.tile.dirt.default'/1242, l='MpServer', x=-525.88, y=1.00, z=-358.54], EntityItem['item.tile.dirt.default'/1244, l='MpServer', x=-525.72, y=2.00, z=-357.13], EntityItem['item.tile.dirt.default'/1248, l='MpServer', x=-524.88, y=1.00, z=-355.79], EntityItem['item.tile.dirt.default'/1267, l='MpServer', x=-524.81, y=1.00, z=-360.88], EntityItem['item.tile.dirt.default'/1268, l='MpServer', x=-520.13, y=1.00, z=-360.88], EntityItem['item.tile.dirt.default'/1269, l='MpServer', x=-523.25, y=1.00, z=-360.49], EntityItem['item.tile.dirt.default'/1270, l='MpServer', x=-524.88, y=1.00, z=-359.84], EntityItem['item.tile.dirt.default'/1271, l='MpServer', x=-520.65, y=1.00, z=-358.58], EntityItem['item.tile.dirt.default'/1279, l='MpServer', x=-518.93, y=1.00, z=-360.11]]
	Retry entities: 28 total; [SubEntityNetherDragonSegment['不明'/925, l='MpServer', x=0.00, y=0.00, z=0.00], SubEntityNetherDragonSegment['不明'/926, l='MpServer', x=0.00, y=0.00, z=0.00], SubEntityNetherDragonSegment['不明'/927, l='MpServer', x=0.00, y=0.00, z=0.00], SubEntityNetherDragonSegment['不明'/928, l='MpServer', x=0.00, y=0.00, z=0.00], SubEntityNetherDragonSegment['不明'/929, l='MpServer', x=0.00, y=0.00, z=0.00], SubEntityNetherDragonSegment['不明'/930, l='MpServer', x=0.00, y=0.00, z=0.00], SubEntityNetherDragonSegment['不明'/931, l='MpServer', x=0.00, y=0.00, z=0.00], SubEntityNetherDragonSegment['不明'/932, l='MpServer', x=0.00, y=0.00, z=0.00], SubEntityNetherDragonSegment['不明'/933, l='MpServer', x=0.00, y=0.00, z=0.00], SubEntityNetherDragonSegment['不明'/934, l='MpServer', x=0.00, y=0.00, z=0.00], SubEntityNetherDragonSegment['不明'/935, l='MpServer', x=0.00, y=0.00, z=0.00], SubEntityNetherDragonSegment['不明'/936, l='MpServer', x=0.00, y=0.00, z=0.00], SubEntityNetherDragonSegment['不明'/937, l='MpServer', x=0.00, y=0.00, z=0.00], SubEntityNetherDragonSegment['不明'/938, l='MpServer', x=0.00, y=0.00, z=0.00], SubEntityNetherDragonSegment['不明'/939, l='MpServer', x=0.00, y=0.00, z=0.00], SubEntityNetherDragonSegment['不明'/940, l='MpServer', x=0.00, y=0.00, z=0.00], SubEntityNetherDragonSegment['不明'/941, l='MpServer', x=0.00, y=0.00, z=0.00], SubEntityNetherDragonSegment['不明'/942, l='MpServer', x=0.00, y=0.00, z=0.00], SubEntityNetherDragonSegment['不明'/943, l='MpServer', x=0.00, y=0.00, z=0.00], SubEntityNetherDragonSegment['不明'/944, l='MpServer', x=0.00, y=0.00, z=0.00], SubEntityNetherDragonSegment['不明'/945, l='MpServer', x=0.00, y=0.00, z=0.00], SubEntityNetherDragonSegment['不明'/946, l='MpServer', x=0.00, y=0.00, z=0.00], SubEntityNetherDragonSegment['不明'/947, l='MpServer', x=0.00, y=0.00, z=0.00], SubEntityNetherDragonSegment['不明'/948, l='MpServer', x=0.00, y=0.00, z=0.00], SubEntityNetherDragonSegment['不明'/949, l='MpServer', x=0.00, y=0.00, z=0.00], SubEntityNetherDragonSegment['不明'/950, l='MpServer', x=0.00, y=0.00, z=0.00], SubEntityNetherDragonSegment['不明'/951, l='MpServer', x=0.00, y=0.00, z=0.00], SubEntityNetherDragonSegment['不明'/952, l='MpServer', x=0.00, y=0.00, z=0.00]]
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:532)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:419)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_261, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3132447216 bytes (2987 MB) / 4068474880 bytes (3880 MB) up to 7623147520 bytes (7270 MB)
	JVM Flags: 6 total; -XX:+UseG1GC -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmn256m -Xmx7270m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2855 Optifine OptiFine_1.12.2_HD_U_G5 41 mods loaded, 41 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                    | Version                       | Source                                                 | Signature                                |
	|:------ |:--------------------- |:----------------------------- |:------------------------------------------------------ |:---------------------------------------- |
	| LCHIJA | minecraft             | 1.12.2                        | minecraft.jar                                          | None                                     |
	| LCHIJA | mcp                   | 9.42                          | minecraft.jar                                          | None                                     |
	| LCHIJA | FML                   | 8.0.99.99                     | forge-1.12.2-14.23.5.2855.jar                          | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge                 | 14.23.5.2855                  | forge-1.12.2-14.23.5.2855.jar                          | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | splan                 | 2.65                          | minecraft.jar                                          | None                                     |
	| LCHIJA | foamfixcore           | 7.7.4                         | minecraft.jar                                          | None                                     |
	| LCHIJA | crafttweaker          | 4.1.20                        | CraftTweaker2-1.12-4.1.20.670.jar                      | None                                     |
	| LCHIJA | jei                   | 4.16.1.302                    | [JEI物品管理器] jei_1.12.2-4.16.1.302.jar                   | None                                     |
	| LCHIJA | baubles               | 1.5.2                         | [饰品栏] Baubles-1.12-1.5.2.jar                           | None                                     |
	| LCHIJA | xreliquary            | 1.12.2-1.3.4.796              | [圣遗物] Reliquary-1.12.2-1.3.4.796.jar                   | None                                     |
	| LCHIJA | gokistats             | 1.2.8.4                       | [天赋技能树] gokiStats-1.2.8.4.jar                          | None                                     |
	| LCHIJA | thaumcraft            | 6.1.BETA26                    | [神秘时代] Thaumcraft-1.12.2-6.1.BETA26.jar                | None                                     |
	| LCHIJA | lostmagic             | 1.0                           | [失落魔法]lostmagic-1.0.2.jar                              | None                                     |
	| LCHIJA | mm_lib                | 2.3.0                         | [妖怪之山通用库] MMLib-2.3.0.jar                              | None                                     |
	| LCHIJA | flammpfeil.slashblade | mc1.12-r33                    | [拔刀剑] SlashBlade-mc1.12-r33.jar                        | None                                     |
	| LCHIJA | slashblade_addon      | 1.6.0                         | [拔刀剑日系附属包] SJAP-1.6.0.jar                              | None                                     |
	| LCHIJA | spartanweaponry       | 1.4.0                         | [斯巴达的武器] SpartanWeaponry-1.12.2-1.4.0.jar              | None                                     |
	| LCHIJA | journeymap            | 1.12.2-5.7.1                  | [旅行地图] journeymap-1.12.2-5.7.1.jar                     | None                                     |
	| LCHIJA | twilightforest        | 3.11.1021                     | [暮色森林] twilightforest-1.12.2-3.11.1021-universal.jar   | None                                     |
	| LCHIJA | betterquesting        | 3.5.329                       | [更好的任务] BetterQuesting-3.5.329.jar                     | None                                     |
	| LCHIJA | bq_standard           | 3.4.173                       | [更好的任务-基础扩展] StandardExpansion-3.4.173.jar             | None                                     |
	| LCHIJA | biometweaker          | 3.2.369                       | [生物群系修改器] BiomeTweaker-1.12.2-3.2.369.jar              | 631f326344f7f5fd7df7eb940760ebd52b7c9c17 |
	| LCHIJA | grimoireofgaia        | 1.7.2                         | [盖亚魔典3] GrimoireOfGaia3-1.12.2-1.7.2.jar               | None                                     |
	| LCHIJA | thaumicperiphery      | 0.3.1                         | [神秘外饰]thaumicperiphery-0.3.1.jar                       | None                                     |
	| LCHIJA | thaumicwonders        | 1.8.2                         | [神秘奇境]thaumicwonders-1.8.2.jar                         | None                                     |
	| LCHIJA | mutantbeasts          | 1.12.2-1.0.2                  | [突变生物重置版] MutantBeasts-1.12.2-1.0.2.jar                | None                                     |
	| LCHIJA | biomesoplenty         | 7.0.1.2325                    | [超多生物群系] BiomesOPlenty-1.12.2-7.0.1.2325-universal.jar | None                                     |
	| LCHIJA | ruins                 | 17.2                          | [遗迹] Ruins-1.12.2.jar                                  | None                                     |
	| LCHIJA | geckolib3             | 3.0.11                        | geckolib-forge-1.12.2-3.0.12.jar                       | None                                     |
	| LCHIJA | cqrepoured            | 2.6.2B                        | Chocolate_Quest_Repoured-1.12.2-2.6.2B.jar             | None                                     |
	| LCHIJA | ctgui                 | 1.0.0                         | CraftTweaker2-1.12-4.1.20.670.jar                      | None                                     |
	| LCHIJA | crafttweakerjei       | 2.0.3                         | CraftTweaker2-1.12-4.1.20.670.jar                      | None                                     |
	| LCHIJA | elementalcreepers     | v4.3.3.g5616356               | ElementalCreepers-1.12.2.jar                           | None                                     |
	| LCHIJA | foamfix               | 0.10.14-1.12.2                | foamfix-0.10.14-1.12.2.jar                             | None                                     |
	| LCHIJA | increasemobs          | 1.1.0                         | IncreaseMobs_1.12.2-v1.1.0.jar                         | None                                     |
	| LCHIJA | lootbags              | 2.5.8.7                       | lootbags-2.5.8.7.jar                                   | None                                     |
	| LCHIJA | loottweaker           | 0.3.1                         | LootTweaker-0.3.1+MC1.12.2.jar                         | None                                     |
	| LCHIJA | lotsoffoodrev         | 1.2                           | LotsOfFoodRev-1.12.x-v1.2.jar                          | None                                     |
	| LCHIJA | tcresearchpatcher     | 1.12.2-1.1.3                  | ThaumcraftResearchPatcher-1.12.2-1.1.3.jar             | 8f678591ba6f78d579e553a8aa94b4c4766cb13d |
	| LCHIJA | thaumicaugmentation   | 1.12.2-2.1.5                  | ThaumicAugmentation-1.12.2-2.1.5.jar                   | 8f678591ba6f78d579e553a8aa94b4c4766cb13d |
	| LCHIJA | bamboomod             | Minecraft1.12.2 var4.0.0.12.2 | 竹和风测试版.jar                                             | None                                     |

	Loaded coremods (and transformers): 
SpartanWeaponry-MixinLoader ([斯巴达的武器] SpartanWeaponry-1.12.2-1.4.0.jar)
  
Thaumcraft Research Patcher Core Plugin (ThaumcraftResearchPatcher-1.12.2-1.1.3.jar)
  thecodex6824.tcresearchpatcher.Transformer
Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.14-1.12.2.jar)
  pl.asie.foamfix.coremod.FoamFixTransformer
CQRPlugin (Chocolate_Quest_Repoured-1.12.2-2.6.2B.jar)
  team.cqr.cqrepoured.asm.CQRClassTransformer
ServerPropertiesLAN ([简单联机] ServerPropertiesLAN-2.65.jar)
  JaideepSinghHeer.Minecraft.mod.SPLANtransformerPort
Thaumic Augmentation Core Plugin (ThaumicAugmentation-1.12.2-2.1.5.jar)
  thecodex6824.thaumicaugmentation.core.TATransformer
	GL info: ' Vendor: 'Intel' Version: '4.6.0 - Build 27.20.100.9664' Renderer: 'Intel(R) UHD Graphics'
	Launched Version: 异世界2
	LWJGL: 2.9.4
	OpenGL: Intel(R) UHD Graphics GL version 4.6.0 - Build 27.20.100.9664, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: 简体中文 (中国)
	Profiler Position: N/A (disabled)
	CPU: 12x Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz
	OptiFine Version: OptiFine_1.12.2_HD_U_G5
	OptiFine Build: 20210124-142939
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 - Build 27.20.100.9664
	OpenGlRenderer: Intel(R) UHD Graphics
	OpenGlVendor: Intel
	CpuCount: 12

**Comment by DerToaster98** [comment]
Update geckolib and redownload cqr.

That crash is the result of the animation file of the exterminator being renamed or missing entirely, it is not reproducible with the official published file.

**Comment by KELETU66666** [comment]
> Update geckolib and redownload cqr.
> 
> That crash is the result of the animation file of the exterminator being renamed or missing entirely, it is not reproducible with the official published file.

thanks
