### ISSUE TITLE
Bull armor gives to much extra atack damage? + Confusing description

### ISSUE THREAD

**Issue by TheFunnyFace** [TeamChocoQuest/ChocolateQuestRepoured#31]
In the 1.7.10 version each piece gives +1 damage, not 1,5 like right now.
Also the description says you get extra damage as the set bonus. So do you get even more damage on top? Not sure if that is not game braking.
I could also imagine a speed boost for the set bonus, because the bull sprinted around all the time when fighting him.

**Comment by Tiviacz1337** [comment]
Actually there's speed boost for the set bonus

**Comment by TheFunnyFace** [comment]
Then the description is definitly wrong.
