### ISSUE TITLE
Exterminator Prototype terminated Minecraft (game crash to desktop)

### ISSUE THREAD

**Issue by Ty0nline** [TeamChocoQuest/ChocolateQuestRepoured#310]
**Common sense Info**
To check a checkbox: Insert a lower case X between the square brackets, you need to remove the space though.
 - I play...
   - [ ] With a large modpack
   - [x] Only with CQR and it's dependencies
 - The issue occurs in...
   - [x] Singleplayer
   - [ ] Multiplayer
 - [x] I have searched for this or a similar issue before reporting and it was either (1) not previously reported, or (2) previously fixed  and I'm having the same problem.
 - [x ] I am using the latest version of the mod (all versions can be found on github under releases)
 - [x ] I read through the FAQ and i could not find something helpful ([FAQ](https://wiki.cq-repoured.net/index.php?title=FAQ))
 - [x] I reproduced the bug without any other mod's except forge, cqr and it's dependencies
 - [x ] The game crashes because of this bug
 
 
 **Versions**
Chocolate Quest: Beta 6.2
Forge:14.23.5.2859
Minecraft:1.12.2

**Describe the bug**
A clear and concise description of what the bug is:

Game crash do to some render issues with Exterminator Prototype Boss.

**To Reproduce**
1. Go to '...' a new flat world
2. Use item '....' spawn egg for the Boss
3. Place block '....' no block needed 
.
.
.
Description: Rendering entity in world

java.lang.AbstractMethodError: software/bernie/geckolib3/renderers/geo/GeoLayerRenderer.render(Lnet/minecraft/entity/EntityLivingBase;FFFFFFLjava/awt/Color;)V
**Expected behavior**

Games shouldn't die/crash

**Screenshots**
none

**Other**
**Personal Note:**
I already tried to downgrade step by step the CQR mod and its dependencies.
**This issue appear with the newest version from geckolib that was released 6days ago.**
I started fresh with a bigger modpack and it works now fine with an older geckolib build from 4 December 2021.

Hope this hint helps!

**_I wish all of you a Merry Christmas and a Happy New Year!_** 
_My English writing skills are not the yellow from the egg but I did my best._
**Link to crashreport**: https://paste.gg/p/anonymous/a567664fbb6549b0984ec1ff5497434f

Please note: log files and crash reports should be uploaded as a FILE and not as a copy paste of the text of it here. Upload the file to a site like pastebin or similar and link it here!!
 - Link to Crash report file (only if the game crashes because of this bug, please use something like pastebin to upload it, then link it here):
 - Link to Log file (only if the game crashes because of this bug, please use something like pastebin to upload it, then link it here):
 - Other mods (that are necessary to produce the bug):
 - Other mods (that are also installed, at best: link a zip file that contains all the installed mods):
 - CQR config folder (link, only if you changed the configs):
 - Other mod's configs (link, only if any config was changed):

**Comment by DerToaster98** [comment]
Not reproducable, report to geckolib.

Will talk to the geckolib devs later.

You're also running cqr v2.6.1B (taken from your crashlog), update it.
