### ISSUE TITLE
Giant tortoise cant be killed by any means in hexxit 2

### ISSUE THREAD

**Issue by lilpwnage36** [TeamChocoQuest/ChocolateQuestRepoured#311]
It drops to about 80 health then it goes into an immortal phase where it can't take damage at all from players, void, other mobs, potions, or unique damage types from other mods. It gets back up to around 260 health, goes into an attacking phase where it's still immortal but bounces off walls. Then after a certain point it stops attacking for a bit while it heals up to full health.

**Comment by DerToaster98** [comment]
Block the spin attack with a shield, that way it will get stunned. You need to hit the green parts.

general notice: most of the more advanced cqr bosses aren’t defeatable by just stupidly hitting them
