### ISSUE TITLE
Crash with Ice and Fire

### ISSUE THREAD

**Issue by mxnmnm** [TeamChocoQuest/ChocolateQuestRepoured#313]
**General Information**
To check a checkbox: Insert a X between the square brackets, you need to remove the space though.
 - I play...
   - [ ] With a large modpack
   - [x] Only with CQR and it's dependencies
 - The issue occurs in...
   - [x ] Singleplayer
   - [x ] Multiplayer
 - [x] I have searched for this or a similar issue before reporting and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
 - [x] I am using the latest version of the mod (all versions can be found on github under releases)
 - [x] I read through the FAQ and I could not find something helpful ([FAQ](https://wiki.cq-repoured.net/index.php?title=FAQ))
 - [x] I reproduced the bug without any other mod's except forge, cqr and it's dependencies
 - [x] The game crashes because of this bug
 
**Describe the bug**
Gorgons and cockatrices are having a fight and it makes the game crash :(
Also using the gorgon head on a cockatrice also crashes

**To Reproduce**
1. Spawn gorgons and cockatrices
2. Alternatively try to turn a cockatrice into stone using gorgon head
3. It also seemed to crash whenever cockatrices attacked things (even things unrelated to gorgons) although this only happened in my survival world with a lot of other mods. 

 
**Versions (Note that 'latest' is NOT a valid version!**
Chocolate Quest Repoured: 2.6.2B
Forge: 14.23.5.2860
Minecraft: 1.12.2
Other mods (necessary to reproduce the bug): Ice and Fire

**Log File**
https://gist.github.com/mxnmnm/429b3e1046ebddac88af6cbd737bfd40

**Comment by mxnmnm** [comment]
So I was bored and decided to experiment. I managed to fix it by deleting the files (com/github/alexthe666/iceandfire/entity) related to ice and fire because I guess stuff hasn't been fully implemented for that

**Comment by DerToaster98** [comment]
First: **Do not ever delete ANY class file from ANY compiled jar, that is stupid and will cause issues**

Second: Just fixed it, it was a typo. Your "fix" did work because i&f was installed, it will directly crash if you remove i&f from the installation.

Patch fiwll be published in the next update

**Comment by DerToaster98** [comment]
Sorry but we are not the support people for the ice and fire mod. Please consult them and not us
