### ISSUE TITLE
Crash issue

### ISSUE THREAD

**Issue by pixelboy664** [TeamChocoQuest/ChocolateQuestRepoured#314]
**General Information**
To check a checkbox: Insert a X between the square brackets, you need to remove the space though.
 - I play...
   - [ ] With a large modpack
   - [x] Only with CQR and it's dependencies
 - The issue occurs in...
   - [ ] Singleplayer
   - [X] Multiplayer (I havent checked it on singleplayer)
 - [X ] I have searched for this or a similar issue before reporting and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
 - [X] I am using the latest version of the mod (all versions can be found on github under releases)
 - [X] I read through the FAQ and I could not find something helpful ([FAQ](https://wiki.cq-repoured.net/index.php?title=FAQ))
 - [X] I reproduced the bug without any other mod's except forge, cqr and it's dependencies
 - [X] The game crashes because of this bug
 
**Describe the bug**
It is crashing the game when I come close to some of the structrures created by the mod. It is happening to my friend too, to fix it we have to log in on the server and move away as fast as we can from the structure. It is really annoying.

**To Reproduce**
1. Go to structure like on the screenshot
2.Come to close and it will instantly crash you

**Screenshots**
 
![2022-01-01_14 01 31](https://user-images.githubusercontent.com/93058634/147851115-467e45d0-d221-43f7-aa84-b7781fa874d2.png)

**Versions (Note that 'latest' is NOT a valid version!**
Chocolate Quest Repoured: Chocolate_Quest_Repoured-1.12.2-2.6.2B
Forge:forge-1.12.2-14.23.5.2860
Minecraft: 1.12.2

**Log File**
https://gist.github.com/pixelboy664/306de644da722c570ffa838b67d29ee7

**Comment by DerToaster98** [comment]
First: Update the mod and geckolib
Second: This is an issue with geckolib, not cqr
