### ISSUE TITLE
Giant Tortoise impossible to kill with less than 3 players.

### ISSUE THREAD

**Issue by Pantheris2019** [TeamChocoQuest/ChocolateQuestRepoured#316]
**General Information**
To check a checkbox: Insert a X between the square brackets, you need to remove the space though.
 - I play...
   - [X] With a large modpack
   - [ ] Only with CQR and it's dependencies
 - The issue occurs in...
   - [x] Singleplayer
   - [x] Multiplayer
 - [x] I have searched for this or a similar issue before reporting and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
 - [x] I am using the latest version of the mod (all versions can be found on github under releases)
 - [x] I read through the FAQ and I could not find something helpful ([FAQ](https://wiki.cq-repoured.net/index.php?title=FAQ))
 - [ ] I reproduced the bug without any other mod's except forge, cqr and it's dependencies
 - [ ] The game crashes because of this bug
 
**Describe the bug**
Because of the way the Giant Tortoise works, it is literally impossible to kill with less than 3 players.

**To Reproduce**
1. find dungeon with Giant Tortoise.
2. Attempt to kill it in single player or in multiplayer with 2 players.
3. Find it impossible to kill

**Versions (Note that 'latest' is NOT a valid version!**
Chocolate Quest Repoured: 2.6.2B
Forge: 14.23.5.2855
Minecraft: 1.12.2
Other mods (necessary to reproduce the bug): Optional. I know what I'm doing and I do believe this one is an issue with the mod and the way it works, other mods not needed to reproduce this.

**Comment by DerToaster98** [comment]
It is perfectly beatable in single player

**Comment by DerToaster98** [comment]
As you can see here it is perfectly beatable in singleplayer in the newest version (2.6.3B, 2.6.2B is **not** supported anymore, it should work the same way there too though).

https://streamable.com/k9ylp0
