### ISSUE TITLE
saveAllReputationData FactionRegistry Server Crash

### ISSUE THREAD

**Issue by thejbone** [TeamChocoQuest/ChocolateQuestRepoured#318]
**General Information**
To check a checkbox: Insert a X between the square brackets, you need to remove the space though.
 - I play...
   - [X] With a large modpack
   - [ ] Only with CQR and it's dependencies
 - The issue occurs in...
   - [ ] Singleplayer
   - [X] Multiplayer
 - [X] I have searched for this or a similar issue before reporting and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
 - [X] I am using the latest version of the mod (all versions can be found on github under releases)
 - [X] I read through the FAQ and I could not find something helpful ([FAQ](https://wiki.cq-repoured.net/index.php?title=FAQ))
 - [ ] I reproduced the bug without any other mod's except forge, cqr and it's dependencies
 - [ ] The game crashes because of this bug
 
**Describe the bug**
A server crash, unsure of origin. It states an issue with saveAllReputationData FactionRegistry server tick loop exception.

**To Reproduce**
Not sure. 
 
**Versions (Note that 'latest' is NOT a valid version!**
Chocolate Quest Repoured:  2.6.4B 
Forge: 14.23.5.2860
Minecraft: 1.12.2
Other mods (necessary to reproduce the bug):
https://www.technicpack.net/modpack/hexxit-ii.896745/mods

**Log File**
https://pastebin.com/pNT0imUr

**Comment by DerToaster98** [comment]
Fixed in v2.6.5B
