### ISSUE TITLE
Game crashes after taking the End Portal back to the Overworld: Exception in server tick loop

### ISSUE THREAD

**Issue by platinumphoenix2** [TeamChocoQuest/ChocolateQuestRepoured#320]
**General Information**
To check a checkbox: Insert a X between the square brackets, you need to remove the space though.
 - I play...
   - [ ] With a large modpack
   - [ ] Only with CQR and it's dependencies
 - The issue occurs in...
   - [X] Singleplayer
   - [ ] Multiplayer
 - [ ] I have searched for this or a similar issue before reporting and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
 - [X] I am using the latest version of the mod (all versions can be found on github under releases)
 - [ ] I read through the FAQ and I could not find something helpful ([FAQ](https://wiki.cq-repoured.net/index.php?title=FAQ))
 - [X] I reproduced the bug without any other mod's except forge, cqr and it's dependencies
 - [X] The game crashes because of this bug
 
**Describe the bug**
The game crashes whenever you travel back to the overworld from the End - use the portal that spawns after the Ender Dragon is defeated.

**To Reproduce**
1. Travel to the End and defeat the Ender Dragon.
2. Attempt to travel back to the overworld dimension by using the portal that spawns after defeating the dragon.
3. Crash.

While testing, I killed the Ender Dragon manually while it was stuck in the Bedrock Pillar where the overworld portal spawns.

However, when I killed the dragon using the command below, the crash didn't happen - - I'm not sure if it has to do with the command itself or with the fact that the Ender Dragon was not near the Bedrock pillar.
/kill @e[type=Ender_Dragon]
Point being, to replicate, do not use the command to kill the dragon and (maybe?) kill the dragon in the same location as I did.

This was tested on both, a Flat World and a non-flat world.
 
**Versions (Note that 'latest' is NOT a valid version!**
Chocolate Quest Repoured: 1.12.2-2.6.5B
Forge: 1.12.2-14.23.5.2860
Minecraft: 1.12.2
Other mods (necessary to reproduce the bug): I had BetterFPS and Optifine alongside the core mods.

**Log File**
Crash Log: https://pastebin.com/4BWUGCK2

**Comment by DerToaster98** [comment]
That has nothing to do with any entity. It is a problem of world unloading (yes, any dimension is a world actually).

Will be fixed later today

**Comment by platinumphoenix2** [comment]
There is another issue I'd like to report but I'm not sure if it's related to this one - if not, I can make a separate bug report.

I don't have much information, except that the crash happened instantly after I killed an entity that spawned out of a Boss Block within a protected structure - - the boss was a Boarman but the structure was a custom one, not a CQ structure.
The crash doesn't happen all the time, in fact, it's rare.

Here's the crash log: https://pastebin.com/P4kGpc1a

**Comment by DerToaster98** [comment]
Patched in 2.6.6B
