### ISSUE TITLE
Error when using VanillaFix and trading with CQ NPC: Error executing task

### ISSUE THREAD

**Issue by platinumphoenix2** [TeamChocoQuest/ChocolateQuestRepoured#322]
**General Information**
To check a checkbox: Insert a X between the square brackets, you need to remove the space though.
 - I play...
   - [ ] With a large modpack
   - [ ] Only with CQR and it's dependencies
 - The issue occurs in...
   - [X] Singleplayer
   - [ ] Multiplayer
 - [ ] I have searched for this or a similar issue before reporting and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
 - [X] I am using the latest version of the mod (all versions can be found on github under releases)
 - [ ] I read through the FAQ and I could not find something helpful ([FAQ](https://wiki.cq-repoured.net/index.php?title=FAQ))
 - [ ] I reproduced the bug without any other mod's except forge, cqr and it's dependencies
 - [ ] The game crashes because of this bug
 
**Describe the bug**
Note: This error only occurs with the VanillaFix mod and does not crash the game.
Trading with a Chocolate Quest NPC yields an error when attempting to trade with that NPC.

**To Reproduce**
1. Create a trade with a Chocolate Quest NPC.
2. Trade with the NPC. It'll allow you to trade, and everything appears to function correctly, but it'll yield an error each time you trade.
 
**Versions (Note that 'latest' is NOT a valid version!**
Chocolate Quest Repoured: 1.12.2-2.6.5B
Forge: 1.12.2-14.23.5.2860
Minecraft: 1.12.2
Other mods (necessary to reproduce the bug): VanillaFix

**Log File**
https://pastebin.com/RDCfBjJT

My trade parameters:
![trade](https://user-images.githubusercontent.com/22579004/149521763-2e634deb-37bc-4423-9bad-4ac3a5f9170a.png)

**Comment by DerToaster98** [comment]
if it is an issue with vanillafix report it to them and not us.

**Comment by DerToaster98** [comment]
Actually if you would've looked at the error and tested without vanilla fix you would've seen taht this has nothign to do with a certain trader or vanillafix. The problem is that this is an edge case when there no trade it could restock and it attempts to restock.

**Comment by DerToaster98** [comment]
Patched in 2.6.6B
