### ISSUE TITLE
Rendering Block Entity and Cannot get property PropertyDirection

### ISSUE THREAD

**Issue by platinumphoenix2** [TeamChocoQuest/ChocolateQuestRepoured#323]
**General Information**
To check a checkbox: Insert a X between the square brackets, you need to remove the space though.
 - I play...
   - [X] With a large modpack
   - [ ] Only with CQR and it's dependencies
 - The issue occurs in...
   - [X] Singleplayer
   - [ ] Multiplayer
 - [X] I have searched for this or a similar issue before reporting and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
 - [X] I am using the latest version of the mod (all versions can be found on github under releases)
 - [ ] I read through the FAQ and I could not find something helpful ([FAQ](https://wiki.cq-repoured.net/index.php?title=FAQ))
 - [ ] I reproduced the bug without any other mod's except forge, cqr and it's dependencies
 - [X] The game crashes because of this bug
 
**Describe the bug**
The crash report refers to the Exporter Chest and property direction:
`Cannot get property PropertyDirection`
`TileEntityExporterChestRenderer`
I also see that Entity Culling may have been involved.

After loading back into a world where I've spawned several structures using the in-game spawner item, this crash occurred.
Soon after, the graphics started to glitch (see the image I've attached) - - it appears that only entities and tile entities were showing along with random flickering.

**To Reproduce**
This crash has only happened once. I only know what's already been provided above.

**Versions (Note that 'latest' is NOT a valid version!**
Chocolate Quest Repoured: 1.12.2-2.6.6B
Minecraft: 1.12.2-forge-14.23.5.2860
Other mods (necessary to reproduce the bug): 

**Log File**
https://pastebin.com/pkWrbhAZ
![tile entity](https://user-images.githubusercontent.com/22579004/149659550-e89165d8-c55d-4e4d-81e1-708c8e885783.png)

**Comment by DerToaster98** [comment]
No support for pixelmon, works fine with just cq and entityculling

**Comment by platinumphoenix2** [comment]
Issue [319 ](https://github.com/TeamChocoQuest/ChocolateQuestRepoured/issues/319)was fixed even though it was related to Pixelmon.

Regardless, nothing in the crash report indicates that it was Pixelmon.

**Comment by DerToaster98** [comment]
from what i've heard pixelmon has many issues with fucking up other mod's rendering in general

**Comment by DerToaster98** [comment]
And no, issue #319 is a duplicate of #315 and has nothing to do with pixelmon or rendering at all

**Comment by DerToaster98** [comment]
The thing is: This issue occurs when the PixelMonPlayerRenderclass renders and we can not reproduce it.

So either reproduce this without pixelmon or the bug is in pixelmon
