### ISSUE TITLE
Grappling Hook Crashes Other Players

### ISSUE THREAD

**Issue by Foulest** [TeamChocoQuest/ChocolateQuestRepoured#325]
**General Information**
To check a checkbox: Insert a X between the square brackets, you need to remove the space though.
 - I play...
   - [X] With a large modpack
   - [ ] Only with CQR and it's dependencies
 - The issue occurs in...
   - [ ] Singleplayer
   - [X] Multiplayer
 - [X] I have searched for this or a similar issue before reporting and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
 - [X] I am using the latest version of the mod (all versions can be found on github under releases)
 - [X] I read through the FAQ and I could not find something helpful ([FAQ](https://wiki.cq-repoured.net/index.php?title=FAQ))
 - [ ] I reproduced the bug without any other mod's except forge, cqr and it's dependencies
 - [X] The game crashes because of this bug
 
**Describe the bug**
Using a grappling hook near other players can sometimes cause their clients to crash.
The crash seems to only happen when players are at a far-away distance.

**Screenshots**
Here's a video: https://youtu.be/5NLkof1Uacc

**Versions (Note that 'latest' is NOT a valid version!**
Chocolate Quest Repoured: In the crash report.
Forge: In the crash report.
Minecraft: In the crash report.
Other mods (necessary to reproduce the bug): In the crash report.

**Crash Report**
https://pastebin.com/raw/sndhhX7W

**Comment by DerToaster98** [comment]
Won't be worked on until reproduced with only CQR and it's dependencies.

**Comment by Foulest** [comment]
There are no other mods present in the stacktrace.

**Comment by Foulest** [comment]
The ProjectileHookShotHook entity has no vehicle (Entity's Vehicle: ~~ERROR~~ NullPointerException: null) which is reflected in the NullPointerException, causing the crash for other players.

**Comment by DerToaster98** [comment]
that is not really correct. THe NPE occurs cause the shooter is null, which only can occur if there is a problem in the base projectile.

The stacktrace also notices that the player class has changed to something non-vanilla and thus i don't care about your provided log until it is proven that this is a definite cqr problem.

**Comment by DerToaster98** [comment]
also that "entity's vehicle is null" is not an error, it is diagnostic information and hints that the entity is currently riding nothing, that can be ignored.

**Comment by DerToaster98** [comment]
and what you mentioned is not even the stacktrace. And just because another mod is not in the stacktrace doesn't mean that another mod can't cause it. That's just the call history that lead to the line causing the application to crash.

**Comment by Foulest** [comment]
Just tested it again with just CQR on a localhost server; it's a CQR issue.

Crash report: https://pastebin.com/raw/bpEWi0xX

**Comment by DerToaster98** [comment]
ok, then we'll look at it.

Probably it's just that the shooter information doesn't get synched across all tracking players

**Comment by DerToaster98** [comment]
should be patched in v2.6.7B
