### ISSUE TITLE
Please restore removed config feature

### ISSUE THREAD

**Issue by shanzenos** [TeamChocoQuest/ChocolateQuestRepoured#326]
**General Information**
To check a checkbox: Insert a X between the square brackets, you need to remove the space though.
 - I play...
   - [x] With a large modpack
   - [ ] Only with CQR and it's dependencies
 - The issue occurs in...
   - [x] Singleplayer
   - [x] Multiplayer
 - [x] I have searched for this or a similar issue before reporting and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
 - [x] I am using the latest version of the mod (all versions can be found on github under releases)
 - [x] I read through the FAQ and I could not find something helpful ([FAQ](https://wiki.cq-repoured.net/index.php?title=FAQ))
 - [x] I reproduced the bug without any other mod's except forge, cqr and it's dependencies
 - [ ] The game crashes because of this bug
 
 Not really a bug more of a removed feature restore request.
 
 The config's features for "overallDungeonChance" & ""dungeonSeparation" were removed in more recent versions. For those of us that prefer tuning CQR to be more rare this makes customization toward that end more difficult. I did however notice "generationMinDistanceToOtherStructure" tucked away in the configs, and been using that in place of the latter.

 
**Versions (Note that 'latest' is NOT a valid version!**
Chocolate Quest Repoured: Chocolate_Quest_Repoured-1.12.2-2.6.2B
Forge: forge-1.12.2-14.23.5.2860
Minecraft: 1.12.2

**Comment by platinumphoenix2** [comment]
Check the grids folder, perhaps that has what you're looking for.

**Comment by DerToaster98** [comment]
That was moved to the grid configs and we won’t revert that
