### ISSUE TITLE
recipe for the cloud boots

### ISSUE THREAD

**Issue by UndefinableSoul** [TeamChocoQuest/ChocolateQuestRepoured#327]
There are no (and won't be) recipes and that is intended. Only recipe in the mod should be the one for cloud boots.

Missing textures are not a bug, that is just something that hasn't been added yet.

_Originally posted by @DerToaster98 in https://github.com/TeamChocoQuest/ChocolateQuestRepoured/issues/212#issuecomment-664128744_

Hello,

Well i have the newest version and i dont have the recipe for the cloud boots.

Is this an Issue or it comes in future?

**Comment by platinumphoenix2** [comment]
See this commit - https://github.com/TeamChocoQuest/ChocolateQuestRepoured/commit/44d112251bd19fedbc79c127d85b477d53f2944d

> add cloud boots and golden feathers to tavern traders and add a new tavern as well

Cloud boots are no longer craftable.

**Comment by DerToaster98** [comment]
The recipe has been removed for being too cheap and for consistency
