### ISSUE TITLE
REQUEST: Compatibility with McHorse mods???

### ISSUE THREAD

**Issue by TheSexyYeti** [TeamChocoQuest/ChocolateQuestRepoured#328]
Not necessarily a bug as it is a request. Can you provide compatibility with McHorse's "Mappet" mod. Allowing the "Mob to Spawner Tool" and the "Soul Bottle" to capture Mappet NPCs and allow them to be spawned by the CQR spawners to spawn them in CQR dungeons. It would also be cool if you could add compatibility for McHorse's "Chameleon (Metamorph Add-on)" mod so the CQR NPCs can use blockbench models and animations.

**Comment by DerToaster98** [comment]
1.12 won’t get new features.

The mob to spawner tool and the soul bottle should work with any mob in theory and as long as data related to that mob is saved in it‘s npc data

allowing cqr mobs to use blockbench models is not possible for us cause it is too mich effort

**Comment by TheSexyYeti** [comment]
I just figure the Chameleon mod already took care of all the hard work in the way of using Blockbench models. That's technically what McHorse made that mod for. And I apologize if I assume too much, I'm not a coder anyways. And I don't know how to phrase this without coming off as an asshole. I just didn't think hooking into another mods capability for this purpose would pose as much of an technical issue is it would coding this functionality from scratch. But anyways I'll drop it. So are y'all developing this mod for newer versions of Minecraft then?.

**Comment by DerToaster98** [comment]
It is getting updated to 1.16 (won’t receive long term support) and then to 1.18
