### ISSUE TITLE
Crashreport for end. Generation dungeons test prop.

### ISSUE THREAD

**Issue by MRacingRU** [TeamChocoQuest/ChocolateQuestRepoured#330]
**General Information**
To check a checkbox: Insert a X between the square brackets, you need to remove the space though.
 - I play...
   - [X ] With a large modpack
   - [ ] Only with CQR and it's dependencies
 - The issue occurs in...
   - [ X] Singleplayer
   - [ X] Multiplayer
 - [X ] I have searched for this or a similar issue before reporting and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
 - [ ] I am using the latest version of the mod (all versions can be found on github under releases)
 - [ X] I read through the FAQ and I could not find something helpful ([FAQ](https://wiki.cq-repoured.net/index.php?title=FAQ))
 - [X ] I reproduced the bug without any other mod's except forge, cqr and it's dependencies
 - [ X] The game crashes because of this bug
 
**Describe the bug**

**To Reproduce**
1. Скачиваете от суда: https://www.curseforge.com/minecraft/mc-mods/better-dungeons/download/2227053
2. Закидываете в клиент.
3. Создаёте мир.
4. Переходите в творческий режим.
5. Строите портал в край.
6. Заходите в портал края.
7. Получаете краш репорт.
8. Ищите ошибку.
9. Исправляете ошибки с модом.
10. Заливаете на курси фордж новую версию.

**Screenshots**
 
![bandicam 2022-02-01 21-28-12-524](https://user-images.githubusercontent.com/98825365/151986837-bf870135-d093-45ac-a159-9d9d47b6114f.png)

**Versions (Note that 'latest' is NOT a valid version!**
Chocolate Quest Repoured: 1.0, 1.1, 1.1d
Forge: 10.13.4.1614
Minecraft: 1.7.10
Other mods (necessary to reproduce the bug):

**Log File**
Please use a paste site to upload the log file (for example https://gist.github.com/) and provide the link to the file here.
[crash-2022-02-01_14.23.09-server.txt](https://github.com/TeamChocoQuest/ChocolateQuestRepoured/files/7979203/crash-2022-02-01_14.23.09-server.txt)

**Comment by DerToaster98** [comment]
1) please use english
2) we aren‘t the developers of chocolate quest / better dungeons for 1.7.10 and thus don’t maintain or support it’s crashes
