### ISSUE TITLE
Tick lag on generation

### ISSUE THREAD

**Issue by HeavyLogic** [TeamChocoQuest/ChocolateQuestRepoured#331]
[screenshot](https://imgur.com/a/VOqEbrU)

I'm using Spark mod to check this. It lags the server even when small dungeons are being generated, like towers.

**Comment by DerToaster98** [comment]
use the issue template. 

The mod is pretty performance heavy, especially older versions.

If you really mean this serious use a proper java profiler.

Also install phosphor if you haven't already.
