### ISSUE TITLE
Shelob Suffocated Issue

### ISSUE THREAD

**Issue by FruynGames** [TeamChocoQuest/ChocolateQuestRepoured#334]
**General Information**
To check a checkbox: Insert a X between the square brackets, you need to remove the space though.
 - I play...
   - [X] With a large modpack
   - [ ] Only with CQR and it's dependencies
 - The issue occurs in...
   - [X] Singleplayer
   - [ ] Multiplayer
 - [1] I have searched for this or a similar issue before reporting and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
 - [X] I am using the latest version of the mod (all versions can be found on github under releases)
 - [ ] I read through the FAQ and I could not find something helpful ([FAQ](https://wiki.cq-repoured.net/index.php?title=FAQ))
 - [ ] I reproduced the bug without any other mod's except forge, cqr and it's dependencies
 - [ ] The game crashes because of this bug
 
**Describe the bug**
Shelob always spawns between stone blocks and suffocates

**To Reproduce**
1. Go where Shelob spawns and you will see him suffocated.

**Screenshots**
![2022-02-15_18 41 38](https://user-images.githubusercontent.com/99764309/154154178-13e57fa2-1a7f-4e83-9564-60c5e1a277d1.png)
 
**Versions (Note that 'latest' is NOT a valid version!**
Chocolate Quest Repoured: 2.6.7B
Forge: 14.23.5.2859
Minecraft: 1.12.2
Other mods (necessary to reproduce the bug):
Github doesn't support .jar files, so I'll send you the folder in a rar trough mediafire.
https://www.mediafire.com/file/d991hzwkktw0urf/mods.rar/file

**Comment by DerToaster98** [comment]
will be patched eventually, but doesn't have priority

**Comment by DerToaster98** [comment]
Reopening cause this problem still persists, an update of the structure file should fix that though.

**Comment by DerToaster98** [comment]
Patched in release 2.6.8B
