### ISSUE TITLE
Spiked gloves regaining durability

### ISSUE THREAD

**Issue by Rollin4rock** [TeamChocoQuest/ChocolateQuestRepoured#336]
**General Information**
To check a checkbox: Insert a X between the square brackets, you need to remove the space though.
 - I play...
   - [ ] With a large modpack
   - [X ] Only with CQR and it's dependencies
 - The issue occurs in...
   - [X ] Singleplayer
   - [ ] Multiplayer
 - [X ] I have searched for this or a similar issue before reporting and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
 - [X ] I am using the latest version of the mod (all versions can be found on github under releases)
 - [X ] I read through the FAQ and I could not find something helpful ([FAQ](https://wiki.cq-repoured.net/index.php?title=FAQ))
 - [ X] I reproduced the bug without any other mod's except forge, cqr and it's dependencies
 - [ ] The game crashes because of this bug
 
**Describe the bug**
Using spiked gloves used durability until you move them to a different slot then the durability repairs.
**To Reproduce**
1. Go to ... Creative menu or JEI and grab spiked gloves
2. Use item ... Use spiked gloves in main hand and offhand on a wall, moving them to a different slot while durability is down will set it to full durability
3. Place block ...
4. ...

**Screenshots**
 
![2022-02-18_21 50 49](https://user-images.githubusercontent.com/82691384/154785306-4f7b36c0-bfad-4c09-8b27-d29e281aa2f4.png)
![2022-02-18_21 50 52](https://user-images.githubusercontent.com/82691384/154785307-bfcc046e-6c0b-4d13-9a82-0014ca90584c.png)

**Versions (Note that 'latest' is NOT a valid version!**
Chocolate Quest Repoured: 2.6.7B
Forge: 14.23.5.2855
Minecraft:1.12.2
Other mods (necessary to reproduce the bug):

**Log File**
Please use a paste site to upload the log file (for example https://gist.github.com/) and provide the link to the file here.

**Comment by DerToaster98** [comment]
Patched in release 2.6.8B

**Comment by DerToaster98** [comment]
If the issue still persists: Please re-open this issue with a comment
