### ISSUE TITLE
Spear Enemies Have Infinite Vertical Range

### ISSUE THREAD

**Issue by minekraftminer** [TeamChocoQuest/ChocolateQuestRepoured#337]
**General Information**
To check a checkbox: Insert a X between the square brackets, you need to remove the space though.
 - I play...
   - [x] With a large modpack
   - [ ] Only with CQR and it's dependencies
 - The issue occurs in...
   - [x] Singleplayer
   - [ ] Multiplayer
 - [x] I have searched for this or a similar issue before reporting and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
 - [x] I am using the latest version of the mod (all versions can be found on github under releases)
 - [x] I read through the FAQ and I could not find something helpful ([FAQ](https://wiki.cq-repoured.net/index.php?title=FAQ))
 - [x] I reproduced the bug without any other mod's except forge, cqr and it's dependencies
 - [ ] The game crashes because of this bug
 
**Describe the bug**
CQR Mobs with spears have infinite range vertically

**To Reproduce**
1. Get a hostile spear mob
2. Stand above it

**Video**
https://youtu.be/TzhykwVFF8k
 
**Versions (Note that 'latest' is NOT a valid version!**
Chocolate Quest Repoured: 2.6.7
Forge: 14.23.5.2860
Minecraft: 1.12.2
Other mods (necessary to reproduce the bug): No Other Mods

**Log File**
Game Does Not Crash

**Comment by DerToaster98** [comment]
So you say this happened with a modpack and despise that claim no other mods are necessary to reproduce this bug?
Tbh this doesn't really sound credible so please reproduce it with just CQR, reachfix and geckolib.

**Comment by minekraftminer** [comment]
> So you say this happened with a modpack and despise that claim no other mods are necessary to reproduce this bug? Tbh this doesn't really sound credible so please reproduce it with just CQR, reachfix and geckolib.

I discovered the glitch in a large modpack, but the video I recorded WAS tested with only CQR reachfix and geckolib. I thought "I reproduced the bug without any other mod's except forge, cqr and it's dependencies" would have been enough. Sorry for the confusion.

If you want I can take another recording later showing my mod list.

**Comment by DerToaster98** [comment]
Closing cause it is fixed now.

**Comment by minekraftminer** [comment]
> Closing cause it is fixed now.

Cool, & Thanks!
