### ISSUE TITLE
Golden Feather offhand weird texture

### ISSUE THREAD

**Issue by TheFunnyFace** [TeamChocoQuest/ChocolateQuestRepoured#34]
![unbenannt](https://user-images.githubusercontent.com/17514508/52170712-10902c00-2758-11e9-96bc-5729a4c32b35.PNG)
Not sure if this needs a new texture or just and adjustment.

**Comment by Tiviacz1337** [comment]
![image](https://user-images.githubusercontent.com/34790800/52170820-7a590780-2751-11e9-8410-b6b0c96421c4.png) It appears with normal feather too, so I think I won't fix it
