### ISSUE TITLE
Mod not available in Minecraft.

### ISSUE THREAD

**Issue by DST-BFI-GROUP** [TeamChocoQuest/ChocolateQuestRepoured#340]
- I play...
   - [X ] With a large modpack
   - [ ] Only with CQR and it's dependencies
 - The issue occurs in...
   - [ X] Singleplayer
   - [ ] Multiplayer
 - [ X] I have searched for this or a similar issue before reporting and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
 - [X ] I am using the latest version of the mod (all versions can be found on github under releases)
 - [X ] I read through the FAQ and I could not find something helpful ([FAQ](https://wiki.cq-repoured.net/index.php?title=FAQ))
 - [ ] I reproduced the bug without any other mod's except forge, cqr and it's dependencies
 - [ ] The game crashes because of this bug
 
Not showing up in the mod list in Minecraft.
 
Chocolate Quest Repoured: 1.12.2
Forge: 1.12.2
Minecraft: 1.12.2
Other mods (necessary to reproduce the bug): See Attachment
![Screenshot 2022-03-22 004017](https://user-images.githubusercontent.com/93313051/159380486-da09decc-3988-4ea3-b95f-f547209e09f7.png)
![Screenshot 2022-03-22 004041](https://user-images.githubusercontent.com/93313051/159380489-1a5d30a7-efc1-4fb2-86d2-59e2950fc986.png)

**Comment by DerToaster98** [comment]
Not reproducible, it works just fine for us. Must be a problem with your installation
