### ISSUE TITLE
Xiraxis Spawns as a Dummy

### ISSUE THREAD

**Issue by minekraftminer** [TeamChocoQuest/ChocolateQuestRepoured#341]
**General Information**
To check a checkbox: Insert a X between the square brackets, you need to remove the space though.
 - I play...
   - [ ] With a large modpack
   - [x] Only with CQR and it's dependencies
 - The issue occurs in...
   - [x] Singleplayer
   - [ ] Multiplayer
 - [x] I have searched for this or a similar issue before reporting and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
 - [x] I am using the latest version of the mod (all versions can be found on github under releases)
 - [x] I read through the FAQ and I could not find something helpful ([FAQ](https://wiki.cq-repoured.net/index.php?title=FAQ))
 - [x] I reproduced the bug without any other mod's except forge, cqr and it's dependencies
 - [ ] The game crashes because of this bug
 
**Describe the bug**
Xiraxis spawns as a dummy

**To Reproduce**
1. Find the castle hes in or spawn one in

**Screenshots**
![image](https://user-images.githubusercontent.com/82829316/160329941-c48f4756-70ce-409a-998a-20b824f3e4c3.png)

 
**Versions (Note that 'latest' is NOT a valid version!**
Chocolate Quest Repoured: 2.6.8
Forge: 14.23.5.2860
Minecraft: 1.12.2
Other mods (necessary to reproduce the bug): No Other Mods Required

**Log File**
https://pastebin.com/HTuQDje3

**Comment by DerToaster98** [comment]
Fixed in 2.6.9B
