### ISSUE TITLE
Please stop deleting the older verisons of the mod on CurseForge.

### ISSUE THREAD

**Issue by JohnnyDabb2** [TeamChocoQuest/ChocolateQuestRepoured#343]
I am the author of a modpack and every time I go to export the pack to CurseForge, the version of Chocolate Quest Repoured in the pack has been removed.  I understand wanting to keep players on the newest versions of the mod but it's just annoying.  I looked on the wiki QnA page and all that and didn't find any explanation for this.  Maybe I missed something?

**Comment by DerToaster98** [comment]
The explanation literally is that we don't like people reporting issues on older versions that have been fixed in the newer ones.
 
 I can think of not-deleting them, afaik cursepacks can access archived files? Correct me if i'm wrong.

**Comment by JohnnyDabb2** [comment]
That totally works.  Thanks for doing this.
