### ISSUE TITLE
Certain Castle Generates too High consistently 

### ISSUE THREAD

**Issue by minekraftminer** [TeamChocoQuest/ChocolateQuestRepoured#344]
**General Information**
To check a checkbox: Insert a X between the square brackets, you need to remove the space though.
 - I play...
   - [ ] With a large modpack
   - [x] Only with CQR and it's dependencies
 - The issue occurs in...
   - [x] Singleplayer
   - [x] Multiplayer
 - [x] I have searched for this or a similar issue before reporting and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
 - [x] I am using the latest version of the mod (all versions can be found on github under releases)
 - [x] I read through the FAQ and I could not find something helpful ([FAQ](https://wiki.cq-repoured.net/index.php?title=FAQ))
 - [x] I reproduced the bug without any other mod's except forge, cqr and it's dependencies
 - [ ] The game crashes because of this bug
 
**Describe the bug**
I recall this castle spawning in a crater like area with the castle sitting inside of it. However it now generates without this crater and looks rather awkward.

**To Reproduce**
1. Find the Castle in The Photo (I dont know the name)

**Screenshots**
![image](https://user-images.githubusercontent.com/82829316/160951071-ea8182be-5a0c-462b-98c2-fac17c7fc458.png)

 
**Versions (Note that 'latest' is NOT a valid version!**
Chocolate Quest Repoured: 6.8
Forge: 14.23.5.2860
Minecraft: 1.12.2
Other mods (necessary to reproduce the bug): None

**Log File**
https://pastebin.com/iKucGRxF

**Comment by DerToaster98** [comment]
Was it like this in previous versions too? Cause afaik we didn'T touch that specific castle recently

**Comment by minekraftminer** [comment]
Yeah its been like this for a few updates, I kind of got lazy and assumed someone else would notice... whoops. I can probably track down which update this occurred in.

**Comment by DerToaster98** [comment]
That would be good to know

**Comment by minekraftminer** [comment]
Alright, This issue first started appearing in 2.6.3. Sorry for not reporting this sooner.

**Comment by DerToaster98** [comment]
Hmm... can you try with completely new configs and a new world? And spawning the structure by using the placer (just remove all NBT files except CastleLakeAlpha from the structures/castle/normal/ folder)

**Comment by minekraftminer** [comment]
I did infact check by deleting my config, generating a new world, and using the dungeon placer item on every version i tested.

**Comment by DerToaster98** [comment]
Ok, then i'll need to investigate after work

**Comment by minekraftminer** [comment]
Alright, Cool.

**Comment by DerToaster98** [comment]
Fixed in 2.6.9B
