### ISSUE TITLE
Randomized Castles Have Backwards Armor Stands

### ISSUE THREAD

**Issue by minekraftminer** [TeamChocoQuest/ChocolateQuestRepoured#345]
**General Information**
To check a checkbox: Insert a X between the square brackets, you need to remove the space though.
 - I play...
   - [ ] With a large modpack
   - [x] Only with CQR and it's dependencies
 - The issue occurs in...
   - [x] Singleplayer
   - [x] Multiplayer
 - [x] I have searched for this or a similar issue before reporting and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
 - [x] I am using the latest version of the mod (all versions can be found on github under releases)
 - [x] I read through the FAQ and I could not find something helpful ([FAQ](https://wiki.cq-repoured.net/index.php?title=FAQ))
 - [x] I reproduced the bug without any other mod's except forge, cqr and it's dependencies
 - [ ] The game crashes because of this bug
 
**Describe the bug**
I know this is the most subtle and nitpicky thing but I thought I might as well bring it up. Armor stands that generate in randomized castles are facing backwards.

**To Reproduce**
1. Find a randomized Castle
2. Place a armor piece on the armor stand (most noticeable with a helmet)

**Screenshots**
![image](https://user-images.githubusercontent.com/82829316/160966994-8b0c33cb-2051-4b5b-8716-23c0f19d987b.png)

 
**Versions (Note that 'latest' is NOT a valid version!**
Chocolate Quest Repoured: 6.8
Forge: 14.23.5.2860
Minecraft: 1.12.2
Other mods (necessary to reproduce the bug): None

**Log File**
https://pastebin.com/sQCMZB7k

**Comment by DerToaster98** [comment]
This has beeen present since quite some some, won't fix, but thanks for the report

**Comment by DerToaster98** [comment]
(Fixed it anyway cause it was no real effort)

**Comment by minekraftminer** [comment]
Wow, thanks for going out of your way to do it.

The armor stands will no longer haunt me every time I think of them now.

**Comment by DerToaster98** [comment]
Fixed in 2.6.9B
