### ISSUE TITLE
hi i contected the owner of morph mod cause my game crashes when i click [ ] to open morph menu all the sudden and he said to contact you and send the crash report

### ISSUE THREAD

**Issue by HunterTubeGaming** [TeamChocoQuest/ChocolateQuestRepoured#346]
**General Information**
To check a checkbox: Insert a X between the square brackets, you need to remove the space though.
 - I play...
   - [x] With a large modpack
   - [ ] Only with CQR and it's dependencies
 - The issue occurs in...
   - [ ] Singleplayer
   - [x] Multiplayer
 - [ ] I have searched for this or a similar issue before reporting and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
 - [ ] I am using the latest version of the mod (all versions can be found on github under releases)
 - [ ] I read through the FAQ and I could not find something helpful ([FAQ](https://wiki.cq-repoured.net/index.php?title=FAQ))
 - [ ] I reproduced the bug without any other mod's except forge, cqr and it's dependencies
 - [x] The game crashes because of this bug
 
**Describe the bug**

**To Reproduce**
1. Go to ...
2. Use item ...
3. Place block ...
4. ...

**Screenshots**
 
**Versions (Note that 'latest' is NOT a valid version!**
Chocolate Quest Repoured:
Forge:
Minecraft:
Other mods (necessary to reproduce the bug):

**Log File**
Please use a paste site to upload the log file (for example https://gist.github.com/) and provide the link to the file here.

**Comment by HunterTubeGaming** [comment]
[crash-2022-04-22_20.44.02-client.txt](https://github.com/TeamChocoQuest/ChocolateQuestRepoured/files/8546039/crash-2022-04-22_20.44.02-client.txt)

**Comment by DerToaster98** [comment]
Invalid, mandatory details are missing and you didn’t fill out the template
