### ISSUE TITLE
Game crashing, not sure but I believe it's caused by CQR

### ISSUE THREAD

**Issue by MaroVIII** [TeamChocoQuest/ChocolateQuestRepoured#347]
**General Information**
To check a checkbox: Insert a X between the square brackets, you need to remove the space though.
 - I play...
   - [ X ] With a large modpack
   - [ ] Only with CQR and it's dependencies
 - The issue occurs in...
   - [ X ] Singleplayer
   - [ ] Multiplayer
 - [ 1 ] I have searched for this or a similar issue before reporting and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
 - [ ] I am using the latest version of the mod (all versions can be found on github under releases)
 - [ X ] I read through the FAQ and I could not find something helpful ([FAQ](https://wiki.cq-repoured.net/index.php?title=FAQ))
 - [ ] I reproduced the bug without any other mod's except forge, cqr and it's dependencies
 - [ X ] The game crashes because of this bug
 
**Describe the bug**
Whenever I launch my Minecraft main world, the game crashes in a few moments (or right after I press the keybind for Morph mod). On fresh worlds it's completely fine. From what I could've registered in the crash file, it's because of CQR and some loading problems, not sure what to do.

**Screenshots**
 
**Versions (Note that 'latest' is NOT a valid version!**
Chocolate Quest Repoured: 6.8
Forge: 1.12.2
Minecraft: 1.12.2
Other mods (necessary to reproduce the bug):

**Log File**
https://gist.github.com/MaroVIII/e69c08a000ed602677ec9fd6187d773b

**Comment by Meldexun** [comment]
You can disable `advanced -> skipHiddenEntityRendering` in the CQR config as a workaround.

Another workaround is to install the [EntityCulling](https://www.curseforge.com/minecraft/mc-mods/entity-culling) mod. CQR has simple entity occlusion culling builtin (can be disabled with said config option) and when EntityCulling is installed CQRs culling system gets disabled.

**Comment by DerToaster98** [comment]
The version you use is outdated and not supported. Please try to reproduce this with the latest version. If the bug still occurs, create a new issue.

The report indicates a conflict with iChun's morph mod, so removing either CQR or the morph mod should fix that.

**Comment by DerToaster98** [comment]
> You can disable `advanced -> skipHiddenEntityRendering` in the CQR config as a workaround.
> 
> Another workaround is to install the [EntityCulling](https://www.curseforge.com/minecraft/mc-mods/entity-culling) mod. CQR has simple entity occlusion culling builtin (can be disabled with said config option) and when EntityCulling is installed CQRs culling system gets disabled.

That should do it too.

**Comment by MaroVIII** [comment]
> You can disable `advanced -> skipHiddenEntityRendering` in the CQR config as a workaround.
> 
> Another workaround is to install the [EntityCulling](https://www.curseforge.com/minecraft/mc-mods/entity-culling) mod. CQR has simple entity occlusion culling builtin (can be disabled with said config option) and when EntityCulling is installed CQRs culling system gets disabled.

Thank you, it worked by disabling "skipHiddenEntityRendering", I can finally play now! :D

**Comment by DerToaster98** [comment]
Update cqr either way please. We don't support old releases.
