### ISSUE TITLE
Crashed with Ender Calamity mob

### ISSUE THREAD

**Issue by dalekfan** [TeamChocoQuest/ChocolateQuestRepoured#349]
**General Information**
To check a checkbox: Insert a X between the square brackets, you need to remove the space though.
 - I play...
   - [X ] With a large modpack
   - [ ] Only with CQR and it's dependencies
 - The issue occurs in...
   - [X ] Singleplayer
   - [ ] Multiplayer
 - [ ] I have searched for this or a similar issue before reporting and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
 - [X ] I am using the latest version of the mod (all versions can be found on github under releases)
 - [X ] I read through the FAQ and I could not find something helpful ([FAQ](https://wiki.cq-repoured.net/index.php?title=FAQ))
 - [ ] I reproduced the bug without any other mod's except forge, cqr and it's dependencies
 - [X ] The game crashes because of this bug
 
**Describe the bug**
I just crashed out of nowhere. I assume it's because I spawned ender calamities while testing out my modpack and killed them, although somehow they're lingering. That's just how my log reads it.

**To Reproduce**
1. Spawn a ender calamity (I am guessing, if not, kill ender king)
2. Have it die or something
3. IDK
4. God help

**Screenshots**
 
**Versions (Note that 'latest' is NOT a valid version!**
Chocolate Quest Repoured:
Forge: 14.23.5.2860
Minecraft: 1.12.2
Other mods (necessary to reproduce the bug):

**Log File**
Please use a paste site to upload the log file (for example https://gist.github.com/) and provide the link to the file here.
Crashlog
https://justpaste.it/645jg

**Comment by DerToaster98** [comment]
What version of the mod do you use?

**Comment by DerToaster98** [comment]
Please reproduce with just cqr and it’s dependencies, else we won’t bother

**Comment by DerToaster98** [comment]
Will be fixed in the next update

**Comment by DerToaster98** [comment]
Fixed in update 6.10B
