### ISSUE TITLE
Lore friendly item descriptions???

### ISSUE THREAD

**Issue by TheFunnyFace** [TeamChocoQuest/ChocolateQuestRepoured#35]
I just thought about making the descriptions for the items less "practical", but more lore friendly. 
E.g. Instead of "Wearing the full set grants increased health regeneration and damage dealt to you back is ignored." we could say (/write) something like "Wearing pieces of this armor helps your inner turtle to come out by increasing your health and finally lets you become a real turtle by getting a functioning shell. ..."
So simply instead of giving out numbers we could just describe every feature with some small fancy texts.

Just an idea, need your opinion on it.

**Comment by LordEpos** [comment]
_Hardened Slime Juice_

**Comment by LordEpos** [comment]
I've started on this, but will need to work on it more later.

**Comment by TheFunnyFace** [comment]
@LordEpos So this means yes? Then I could give it a try as well for everything without it.
