### ISSUE TITLE
Game lags(tps drops to 0) when trying to go to a specific location

### ISSUE THREAD

**Issue by SlimeyBoi123** [TeamChocoQuest/ChocolateQuestRepoured#350]
**General Information**
To check a checkbox: Insert a X between the square brackets, you need to remove the space though.
 - I play...
   - [X] With a large modpack
   - [ ] Only with CQR and it's dependencies
 - The issue occurs in...
   - [X] Singleplayer
   - [X] Multiplayer
 - [ ] I have searched for this or a similar issue before reporting and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
 - [X] I am using the latest version of the mod (all versions can be found on github under releases)
 - [X] I read through the FAQ and I could not find something helpful ([FAQ](https://wiki.cq-repoured.net/index.php?title=FAQ))
 - [ ] I reproduced the bug without any other mod's except forge, cqr and it's dependencies
 - [ ] The game crashes because of this bug
 
**Describe the bug**
Whenever i go to a specific place with this seed -1195881383 the game just lags a ton for a good 2 mins then stops lagging for a few seconds then lags again, am able to still move around but chunks wont load and cant run commands, ive removed CQR from the mod list and it didnt have any issues in that location

Ive attempted to reproduce it with only CQR and also with BOP added (world type i used) and didnt have the issues

**To Reproduce**
1. Go to -504, y=66, z=328 on seed -1195881383 

**Screenshots**
 
**Versions (Note that 'latest' is NOT a valid version!**
Chocolate Quest Repoured: 2.6.9B
Forge: 14.23.5.2860
Minecraft: 1.12
Other mods (necessary to reproduce the bug): really not sure which additional mod could be helping to cause it, BOP world type required to find the desert it occurs in but BOP and CQR alone doesnt seem to be doing it

**Log File**
Please use a paste site to upload the log file (for example https://gist.github.com/) and provide the link to the file here.
[Debug log](https://gist.github.com/SlimeyBoi123/3cca7af25c48462d095b5cf4ec40ba63) issues seem to start at line 46578
[Log](https://gist.github.com/SlimeyBoi123/89e851f1d6f9c6bb62a24cc31c55c895) issues seem to start at line 9719

**Comment by DerToaster98** [comment]
disable multithreaded dungeon preparation, that shoiuld fix it.

Did you have a different version of the mod installed previously?

**Comment by DerToaster98** [comment]
Also you should've told us that that thing runs on spongeforge seemingly. We do NOT support weird servers (e.g. Magma, Spongeforge, MCPC+, Mohist etc.)

**Comment by DerToaster98** [comment]
Resolution: Don't use sponge or live with slow-worldgen (=> multithreaded dungeon preparation disabled)
