### ISSUE TITLE
Game Crash when getting close to CQR dungeon (exterminator prototype or giant tortoise entity)

### ISSUE THREAD

**Issue by iCharrles** [TeamChocoQuest/ChocolateQuestRepoured#351]
**General Information**
To check a checkbox: Insert a X between the square brackets, you need to remove the space though.
 - I play...
   - [ x] With a large modpack
   - [ ] Only with CQR and it's dependencies
 - The issue occurs in...
   - [x ] Singleplayer
   - [ x] Multiplayer
 - [x ] I have searched for this or a similar issue before reporting and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
 - [ x] I am using the latest version of the mod (all versions can be found on github under releases)
 - [x ] I read through the FAQ and I could not find something helpful ([FAQ](https://wiki.cq-repoured.net/index.php?title=FAQ))
 - [ ] I reproduced the bug without any other mod's except forge, cqr and it's dependencies
 - [x ] The game crashes because of this bug
 
**Describe the bug**
Whenever i get close to certain dungeons generated by cqr, my game crashes, only on the client side, the server does not crashes, only my game. It specially crashes on those ones that have stonebrick and looks like a house, i think is the one that haves the giant tortoise boss. I dont know if this happens because of a bug of the mod, or because other mod is causing the incompatibility and crash. Ive seen that this crash also happens when it renders the exterminator prototype, i will attach my crash reports also.

**To Reproduce**
1.  Go near a dungeon, close enough to a boss bar appear (has happened with giant tortoise and exterminator prototype entities)
2.  Crash

**Screenshots**
 
**Versions (Note that 'latest' is NOT a valid version!**
Chocolate Quest Repoured: Beta 6.9
Forge: 14.23.5
Minecraft: 1.12.2
Other mods (necessary to reproduce the bug): i dont know if other mod is causing this issue

**Log File**
Please use a paste site to upload the log file (for example https://gist.github.com/) and provide the link to the file here.

Here are my crash reports:
https://gist.github.com/iCharrles/20cd395b0a7041bfbbd11d8df6cd7b84

**Comment by DerToaster98** [comment]
Update CQR and don't lie about the version of cqr you use!

You state the installed cqr version is 2.6.9B
The log shows that the installed cqr version is 2.6.3B

Any cqr version before 2.6.8B is **not** compatible with geckolib versions <= 3.0.21

**Comment by iCharrles** [comment]
Thank you!, i really didnt know, thanks again for claryfying, just one more question, given that i play in cqr 2.6.3, which gecko version would you recommend for it?

**Comment by DerToaster98** [comment]
i don't recommend version 2.6.3, newer versions have a lot of fixes for critical game breaking bugs.
In general i disapprove it when people use old mod versions, we don't spend a lot of time fixing bugs just so it doesn't get used.

Any geckolib version before 3.0.21 should work though.
