### ISSUE TITLE
Got a failure with chocolate quest trying to place captured upper goblin mob from Twilight Forest.

### ISSUE THREAD

**Issue by dalekfan** [TeamChocoQuest/ChocolateQuestRepoured#352]
**General Information**
To check a checkbox: Insert a X between the square brackets, you need to remove the space though.
 - I play...
   - [X] With a large modpack
   - [ ] Only with CQR and it's dependencies
 - The issue occurs in...
   - [X] Singleplayer
   - [ ] Multiplayer
 - [X] I have searched for this or a similar issue before reporting and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
 - [X] I am using the latest version of the mod (all versions can be found on github under releases)
 - [X] I read through the FAQ and I could not find something helpful ([FAQ](https://wiki.cq-repoured.net/index.php?title=FAQ))
 - [ ] I reproduced the bug without any other mod's except forge, cqr and it's dependencies
 - [ ] The game crashes because of this bug
 
**Describe the bug**
_The soul bottle fails to place the captured mob inside it._

**To Reproduce**
1. Find a upper goblin knight from twilight forest mod.
2. Use soul bottle on it.
3. Try to place it.
4. Get error and see mob won't spawn.

**Screenshots**
![issue](https://user-images.githubusercontent.com/49622705/178042077-55afb820-6b3d-439e-8f0c-87984695053d.PNG)

 
**Versions (Note that 'latest' is NOT a valid version!**
Chocolate Quest Repoured: 2.6.9B
Forge: 14.23.5.2860
Minecraft: 1.12.2
Other mods (necessary to reproduce the bug):
Twilight Forest

**Log File**
Please use a paste site to upload the log file (for example https://gist.github.com/) and provide the link to the file here.
https://pastebin.com/w5E1CRsn

**Comment by DerToaster98** [comment]
Before i waste time on this: Will this be just another issue you simply won't reply to?

**Comment by DerToaster98** [comment]
Will be fixed in the next update

**Comment by DerToaster98** [comment]
Fixed in update 6.10B
