### ISSUE TITLE
Entity Ticking Game Crash?

### ISSUE THREAD

**Issue by minekraftminer** [TeamChocoQuest/ChocolateQuestRepoured#353]
**General Information**
To check a checkbox: Insert a X between the square brackets, you need to remove the space though.
 - I play...
   - [ ] With a large modpack
   - [x] Only with CQR and it's dependencies
 - The issue occurs in...
   - [x] Singleplayer
   - [ ] Multiplayer
 - [x] I have searched for this or a similar issue before reporting and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
 - [x] I am using the latest version of the mod (all versions can be found on github under releases)
 - [x] I read through the FAQ and I could not find something helpful ([FAQ](https://wiki.cq-repoured.net/index.php?title=FAQ))
 - [x] I reproduced the bug without any other mod's except forge, cqr and it's dependencies
 - [x] The game crashes because of this bug
 
**Describe the bug**
The game randomly crashes when approaching protected structures. Crash report describes a "Ticking Entity" as a problem.

**Video**
https://www.youtube.com/watch?v=kvSkyHiCRc0

**To Reproduce**
**(I do not have a consistent set up except for rejoining the world that crashes) (tested across multiple fresh worlds btw)**
1. Seed: -7231973107531599001
2. Coordinates: -1358,68,-2140
3. Game will presumably crash.

**Versions (Note that 'latest' is NOT a valid version!**
Chocolate Quest Repoured: 2.6.10
Forge: 14.23.5.2860
Minecraft: 1.12.2

**Log File**
https://pastebin.com/CtSptar3

**Crash Report**
https://pastebin.com/ZkCdsERX

**Comment by DerToaster98** [comment]
Will take a look when i'm home.

Relevant things for me: 
- https://github.com/Alex-the-666/Ice_and_Fire/blob/1.12.2/src/main/java/com/github/alexthe666/iceandfire/entity/EntityDragonBase.java#L1216 (junk and garbage)
- https://github.com/TeamChocoQuest/ChocolateQuestRepoured/blob/1.12.2/src/main/java/team/cqr/cqrepoured/event/world/structure/protection/ProtectedRegionEventHandler.java#L121 (CQR event handler)

**Comment by DerToaster98** [comment]
Fixed in 2.6.11B
