### ISSUE TITLE
[1.12.2] Cannot trade for items if the item you're offering has NBT Data.

### ISSUE THREAD

**Issue by Z-Tunic** [TeamChocoQuest/ChocolateQuestRepoured#359]
Minecraft: 1.12.2
Forge: 14.23.5.2860

Mods: 6
Chocolate_Quest_Repoured-1.12.2-2.6.10B
geckolib-forge-1.12.2-3.0.28
ReachFix-1.12.2-1.0.5
HadEnoughItems_1.12.2-4.22.0
QualityTools-1.0.7_for_1.12.2
PotionCore-1.9_for_1.12.2

---

![2022-07-15 06-58-20](https://user-images.githubusercontent.com/36653806/179219242-55c0f29d-baf4-4926-b48d-91cea93410f7.gif)

In the gif above... hopefully it shows, I can't trade for any of the items that this Inquisition Solder has since the armor that I'm offering him has NBT Data them, due to having Quality Tools installed. The Diamond Legs that I offered has a 'Thick' quality and even though it's technically the same item... he won't accept that as a valid trade due to the NBT data that the item has. If I drag the same item from JEI which prevents the item from getting a random quality... then he will accept it without any issues.

Quality Tools allows you to give tools, armor and trinkets, etc a 'quality' which will have some attribute modifiers depending on the quality it has. This can range from gaining/losing Health, Armor, Toughness, Attack Damage, Attack Speed, Movement Speed, etc. This also supports attributes from other mods. The quality gets added when the item enters your inventory/hotbar and because of this there's no possible way to complete the trade without dragging the items from JEI.

**Comment by DerToaster98** [comment]
Iirc the trades of that trader don't ignore nbt data so it is working as it should.

Also for the record: Two itemstacks are not the same if they have different nbt data.

**Comment by DerToaster98** [comment]
Yep, just checked. The trades are nbt and metadata sensitive, might be changed at some point

**Comment by DerToaster98** [comment]
Also, while the issue is structured in a good way, please use the issue template in the future

**Comment by DerToaster98** [comment]
Possible enhancement: make most trades not-nbt sensitive
