### ISSUE TITLE
NPE when shooting a Longshot into a Nether portal

### ISSUE THREAD

**Issue by xJon** [TeamChocoQuest/ChocolateQuestRepoured#362]
**General Information**
To check a checkbox: Insert a X between the square brackets, you need to remove the space though.
 - I play...
   - [ ] With a large modpack
   - [X] Only with CQR and it's dependencies
 - The issue occurs in...
   - [X] Singleplayer
   - [X] Multiplayer
 - [X] I have searched for this or a similar issue before reporting and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
 - [X] I am using the latest version of the mod (all versions can be found on github under releases)
 - [X] I read through the FAQ and I could not find something helpful ([FAQ](https://wiki.cq-repoured.net/index.php?title=FAQ))
 - [X] I reproduced the bug without any other mod's except forge, cqr and it's dependencies
 - [X] The game crashes because of this bug
 
**Describe the bug**
Game crashing when shooting a Longshot into a Nether portal.
Originally reported over https://github.com/xJon/Hexxit-II/issues/169.

**To Reproduce**
1. Shoot the Longshot into a portal. (make sure to aim into the sides of it)

**Versions (Note that 'latest' is NOT a valid version!**
Chocolate Quest Repoured: `2.6.11B`
Forge: `14.23.5.2860`
Minecraft: `1.12.2`
Other mods (necessary to reproduce the bug): `N/A`

**Log File**
Original crash log; https://mclo.gs/OZg8QqO
New crash log (only CQR): https://mclo.gs/T0lPWlV

**Comment by DerToaster98** [comment]
Does this also happen with the other hookshots?

**Comment by xJon** [comment]
Yes.

**Comment by DerToaster98** [comment]
Fixed in patch 2.6.12B
