### ISSUE TITLE
Crash report in my server

### ISSUE THREAD

**Issue by Rixxz287** [TeamChocoQuest/ChocolateQuestRepoured#363]
**General Information**
To check a checkbox: Insert a X between the square brackets, you need to remove the space though.
 - I play...
   - [ x] With a large modpack
   - [ ] Only with CQR and it's dependencies
 - The issue occurs in...
   - [ ] Singleplayer
   - [x ] Multiplayer
 - [ ] I have searched for this or a similar issue before reporting and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
 - [ ] I am using the latest version of the mod (all versions can be found on github under releases)
 - [ ] I read through the FAQ and I could not find something helpful ([FAQ](https://wiki.cq-repoured.net/index.php?title=FAQ))
 - [ ] I reproduced the bug without any other mod's except forge, cqr and it's dependencies
 - [ ] The game crashes because of this bug
 
**Describe the bug**
Im walking and crash the server
**To Reproduce**
1. Go to jungle

**Screenshots**
 
**Versions (Note that 'latest' is NOT a valid version!**
Chocolate Quest Repoured:Chocolate_Quest_Repoured-1.12.2-2.6.10B
Forge: 14.23.5.2860
Minecraft: 1.12.2
Other mods (necessary to reproduce the bug):

**Log File**
https://gist.github.com/Rixxz287/b25574301cbcf689468eac1a0e2f8fca

[crash-2022-07-30_18.13.26-server.txt](https://github.com/TeamChocoQuest/ChocolateQuestRepoured/files/9227789/crash-2022-07-30_18.13.26-server.txt)

**Comment by Meldexun** [comment]
Why do you think this has anything to do with CQR? CQR isn't even in the stack trace in the crash report.

Anyway, no CQR has nothing to do with this. Your server is just lagging and thus closed itself. You can increase the server timeout limit in the `server.properties`.
