### ISSUE TITLE
Double chest visual glitch

### ISSUE THREAD

**Issue by tier999** [TeamChocoQuest/ChocolateQuestRepoured#364]
**General Information**
To check a checkbox: Insert a X between the square brackets, you need to remove the space though.
 - I play...
   - [ ] With a large modpack
   - [X] Only with CQR and it's dependencies
 - The issue occurs in...
   - [X] Singleplayer
   - [ ] Multiplayer
 - [X] I have searched for this or a similar issue before reporting and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
 - [X] I am using the latest version of the mod (all versions can be found on github under releases)
 - [X] I read through the FAQ and I could not find something helpful ([FAQ](https://wiki.cq-repoured.net/index.php?title=FAQ))
 - [X] I reproduced the bug without any other mod's except forge, cqr and it's dependencies
 - [ ] The game crashes because of this bug
 
**Describe the bug**
The double chests appearing in dungeons visually glitch out of their hitboxes.

**To Reproduce**
1. Go to/generate a dungeon with double chests in tight spaces. Specifically encountered in: Castle_Ravine, Riverland_Castle, Castle_Snow_Spire.

**Screenshots**
![2022-08-23_00 27 13](https://user-images.githubusercontent.com/111809424/186026238-131bc95a-fe92-4143-957e-e51b8ae98585.png)
![2022-08-23_00 35 38](https://user-images.githubusercontent.com/111809424/186026243-c105c48f-54cc-4b66-8475-f057876d9e61.png)

**Versions (Note that 'latest' is NOT a valid version!**)
Chocolate Quest Repoured: 2.6.11
Forge: 14.23.5.2860
Minecraft: 1.12.2

**Comment by DerToaster98** [comment]
Patching the chests in the three castles you named. Could you maybe check the other castles for broken chests too?

**Comment by DerToaster98** [comment]
Fixed in patch 2.6.12B
