### ISSUE TITLE
Protected Dungeon Cursor Trail with Optifine

### ISSUE THREAD

**Issue by minekraftminer** [TeamChocoQuest/ChocolateQuestRepoured#366]
**General Information**
To check a checkbox: Insert a X between the square brackets, you need to remove the space though.
 - I play...
   - [ ] With a large modpack
   - [x] Only with CQR and it's dependencies
 - The issue occurs in...
   - [x] Singleplayer
   - [ ] Multiplayer
 - [x] I have searched for this or a similar issue before reporting and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
 - [x] I am using the latest version of the mod (all versions can be found on github under releases)
 - [x] I read through the FAQ and I could not find something helpful ([FAQ](https://wiki.cq-repoured.net/index.php?title=FAQ))
 - [x] I reproduced the bug without any other mod's except forge, cqr and it's dependencies
 - [ ] The game crashes because of this bug
 
**Describe the bug**
Whenever you approach a dungeon protected area with optifine installed, the green particles that appear when trying to break a protected block will always show up wherever your cursor is pointing.

**To Reproduce**
1. Find a protected dungeon
2. Enter the protected area

**Screenshots**
![image](https://user-images.githubusercontent.com/82829316/186789108-2066b864-b8b1-4e6d-b824-9c845f3dbdf7.png)

 
**Versions (Note that 'latest' is NOT a valid version!**
Chocolate Quest Repoured: 2.6.11
Forge: 14.23.5.2860
Minecraft: 1.12.2
Other mods (necessary to reproduce the bug): Optifine 1.12.2 (G5 & G6 Pre1)

**Log File**
https://pastebin.com/S6ELr3YT

(Log File's size was too big for pastebin so I cut out alot of stuff. I only Included the important stuff, the rest was just spam of the same error for... a long time)

**Comment by DerToaster98** [comment]
Optifine problem. We only spawn the particles whenever a player actually interacts.

There are more problems with optifine or shaders in general cause they are incompatible with geckolib and we use geckolib.

Honestly just remove optifine imo.

**Comment by DerToaster98** [comment]
Fixed in patch 2.6.12B
