### ISSUE TITLE
java.lang.IllegalAccessException: World is owned by 'Server thread' (ID: 78), but was accessed from thread 'CQR Dungeon Generator Thread' (ID: 80)

### ISSUE THREAD

**Issue by xAsio** [TeamChocoQuest/ChocolateQuestRepoured#367]
- I play...
   - [X] With a large modpack
   - [ ] Only with CQR and it's dependencies
 - The issue occurs in...
   - [X] Singleplayer
   - [ ] Multiplayer
 - [X] I have searched for this or a similar issue before reporting and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
 - [ ] I am using the latest version of the mod (all versions can be found on github under releases)
 - [X] I read through the FAQ and I could not find something helpful ([FAQ](https://wiki.cq-repoured.net/index.php?title=FAQ))
 - [ ] I reproduced the bug without any other mod's except forge, cqr and it's dependencies
 - [X] The game crashes because of this bug
 
**Describe the bug**
When exploring the world and when CQR tries to generate a dungeon it crashes

**To Reproduce**
1. Go to ... When loading the world
2. Use item ... -
3. Place block ... -
4. When CQR Tries to generate anything

**Screenshots**
 
**Versions (Note that 'latest' is NOT a valid version!**
Chocolate Quest Repoured: 2.2.0B
Forge:14.23.5.2860
Minecraft:1.12.2
Other mods (necessary to reproduce the bug):

**Log File**
Please use a paste site to upload the log file (for example https://gist.github.com/) and provide the link to the file here.
[latest.log](https://github.com/TeamChocoQuest/ChocolateQuestRepoured/files/9792580/latest.log)

**Comment by DerToaster98** [comment]
Update cqr, the version youhave installed is super old

after you updated turn off multithreaded dungwon preparation in the config or stop using weird forge+“something“ server software

**Comment by DerToaster98** [comment]
And don’t put everything in the tutle, thanks
