### ISSUE TITLE
bug with pizzacraft

### ISSUE THREAD

**Issue by rebarakuk** [TeamChocoQuest/ChocolateQuestRepoured#368]
**General Information**
To check a checkbox: Insert a X between the square brackets, you need to remove the space though.
 - I play...
   - [ X ] With a large modpack
   - [ ] Only with CQR and it's dependencies
 - The issue occurs in...
   - [ ] Singleplayer
   - [ X ] Multiplayer
 - [ 1 ] I have searched for this or a similar issue before reporting and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
 - [ X ] I am using the latest version of the mod (all versions can be found on github under releases)
 - [ X ] I read through the FAQ and I could not find something helpful ([FAQ](https://wiki.cq-repoured.net/index.php?title=FAQ))
 - [ ] I reproduced the bug without any other mod's except forge, cqr and it's dependencies
 - [ X ] The game crashes because of this bug
 
**Describe the bug**
I was just playing minecraft in survival mod and it crashed suddenly

**To Reproduce**
1. play minecraft
2. crashes randomly

**Screenshots**
 
**Versions (Note that 'latest' is NOT a valid version!**
Chocolate Quest Repoured: beta 6.12
Forge: 14.23.5.2860
Minecraft: 1.12.2
pizzacraft: 2.0.19
geckolib: 3.0.31
ReachFix: 1.0.6

**Log File**
[latest log](https://gist.github.com/rebarakuk/019d420df944df13c4db3e2cdafae7b7)

**Comment by DerToaster98** [comment]
And where’s the crashlog and why is this just a problem of cqrepoured and not pizzacraft too?

**Comment by DerToaster98** [comment]
And it looks like you’re using catserver which we DO NOT support. Issue closed

**Comment by DerToaster98** [comment]
Also checked the line where it begins to crash in cqr which is a call to the super class. Thus not a problem of cqr
