### ISSUE TITLE
Floating Castles Do Not Generate

### ISSUE THREAD

**Issue by minekraftminer** [TeamChocoQuest/ChocolateQuestRepoured#371]
**General Information**
To check a checkbox: Insert a X between the square brackets, you need to remove the space though.
 - I play...
   - [ ] With a large modpack
   - [x] Only with CQR and it's dependencies
 - The issue occurs in...
   - [x] Singleplayer
   - [x] Multiplayer
 - [x] I have searched for this or a similar issue before reporting and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
 - [x] I am using the latest version of the mod (all versions can be found on github under releases)
 - [x] I read through the FAQ and I could not find something helpful ([FAQ](https://wiki.cq-repoured.net/index.php?title=FAQ))
 - [x] I reproduced the bug without any other mod's except forge, cqr and it's dependencies
 - [ ] The game crashes because of this bug
 
**Describe the bug**
Floating Castles do not generate by default, due to not being added in the dungeon grids properties file

**To Reproduce**
1. Generate New World on Default Config
2. Locate Dungeon for a Floating Castle

**Screenshots**
![image](https://user-images.githubusercontent.com/82829316/204957208-42d23967-7ae3-45f7-bc16-c894658fa1d5.png)
![image](https://user-images.githubusercontent.com/82829316/204957361-580be9d3-ec9c-40bd-9076-79ae1db61519.png)

 
**Versions (Note that 'latest' is NOT a valid version!**
Chocolate Quest Repoured: 2.6.12
Forge: 14.23.5.60
Minecraft: 1.12.2
Other mods (necessary to reproduce the bug): None

**Comment by DerToaster98** [comment]
The description of this issue is misleading.

It should work if you just add the floatingcastle to one of the grids

**Comment by minekraftminer** [comment]
Sorry for not conveying that properly. yes adding it to the grids will fix it, however it isnt added to the grids by default, which I believe to be a mistake.

**Comment by DerToaster98** [comment]
More an oversight than a mistake, will fix it now

**Comment by minekraftminer** [comment]
thanks, sorry for the confusion.

**Comment by DerToaster98** [comment]
Will be patched in the next update

**Comment by DerToaster98** [comment]
Fixed in release 2.6.13B
