### ISSUE TITLE
Client crash on Server

### ISSUE THREAD

**Issue by voidswrath** [TeamChocoQuest/ChocolateQuestRepoured#372]
- I play...
   - With a large modpack

 - The issue occurs in...
   - [ ] Multiplayer

**Describe the bug**
When a player went into a particular chunk they crashed client side. The server did not crash. Another player went in the same chunk and experienced the same issue. 

 
**Versions (Note that 'latest' is NOT a valid version!**
Chocolate Quest Repoured: 6.12 beta
Forge: 2860 both server and client
Minecraft: 1.12.2

**Log File**
https://paste.ee/p/Rx3lP

**Comment by Meldexun** [comment]
This is already fixed since CQR-1.12.2-2.6.11B.
