### ISSUE TITLE
crash with morph

### ISSUE THREAD

**Issue by Natedogwoooof** [TeamChocoQuest/ChocolateQuestRepoured#374]
**General Information**
To check a checkbox: Insert a X between the square brackets, you need to remove the space though.
 - I play...
   - [x] With a large modpack
   - [  ] Only with CQR and it's dependencies
 - The issue occurs in...
   - [x] Singleplayer
   - [x] Multiplayer

 - [x] I am using the latest version of the mod (all versions can be found on GitHub under releases)
 - [x] I read through the FAQ and I could not find something helpful ([FAQ](https://wiki.cq-repoured.net/index.php?title=FQAQ))
 - [ ] I reproduced the bug without any other mod's except forge, cqr and it's dependencies
 - [x] The game crashes because of this bug
 
**Describe the bug** menu the game crashes
**To Reproduce**
open the morph menu with [ ] or whatever

**Screenshots**

 
**Versions (Note that 'latest' is NOT a valid version!**
Chocolate Quest Repoured:2.6.12B
Forge:14.23.5.2860
Minecraft:1.12.2
Other mods (necessary to reproduce the bug):
morph
ichunuti

crash log
https://pastebin.com/5iG1RC9j

**Comment by DerToaster98** [comment]
Morph mod provides us a null world, this is a known issue. 

We won't fix this.
However, iirc this can be prevented by setting "advanced.skipHiddenEntityRendering" to false or by installing EntityCulling by meldexun (which is recommended either way).

EntityCulling: https://www.curseforge.com/minecraft/mc-mods/entity-culling

**Comment by DerToaster98** [comment]
Fixed in release 2.6.13B
