### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Kasia0314** [TeamChocoQuest/ChocolateQuestRepoured#376]
To add compatibility with Phosphor and Hesperus 

Minecraft 1.12.2
CQR all versions
GeckoLib all versions
Forge all versions, but 14.23.5.2860 preferred at most
Phosphor and Hesperus all versions

If no suggestions allowed here, please give me a link to where I can post suggestions.

**Comment by Meldexun** [comment]
CQR is already fully compatible with Phosphor. Compatibility with Hesperus hasn't been tested but it should work fine.

**Comment by Kasia0314** [comment]
[crash-2023-02-11_18.30.57-server.txt](https://github.com/TeamChocoQuest/ChocolateQuestRepoured/files/10714733/crash-2023-02-11_18.30.57-server.txt)
[crash-2023-02-11_13.02.31-server.txt](https://github.com/TeamChocoQuest/ChocolateQuestRepoured/files/10714734/crash-2023-02-11_13.02.31-server.txt)

How about theese 2 crashes ?

**Comment by DerToaster98** [comment]
First: This is a bug report. Not a suggestion 

Second: you were blocked here before cause you kept spamming our issue tracker with nonsense, so this is ban-evasion. 

Third: i will close this now and block you again.

Fourth: even if you dislike issue templates: they are here for a reason and not using it cause one dislikes it is NOT a valid reason

**Comment by Kasia0314** [comment]
OK. Fixed I hink. I turned off retrogen from Metallurgy 4 Reforged.
