### ISSUE TITLE
Nether Dragon has a high probability of falling into Void when frozen

### ISSUE THREAD

**Issue by mingriyuan** [TeamChocoQuest/ChocolateQuestRepoured#377]
**General Information**
To check a checkbox: Insert a X between the square brackets, you need to remove the space though.
 - I play...
   - [ x] With a large modpack
   - [ ] Only with CQR and it's dependencies
 - The issue occurs in...
   - [x ] Singleplayer
   - [ ] Multiplayer
 - [ x] I have searched for this or a similar issue before reporting and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
 - [ ] I am using the latest version of the mod (all versions can be found on github under releases)
 - [ ] I read through the FAQ and I could not find something helpful ([FAQ](https://wiki.cq-repoured.net/index.php?title=FAQ))
 - [ ] I reproduced the bug without any other mod's except forge, cqr and it's dependencies
 - [ ] The game crashes because of this bug
 
**Describe the bug**

**To Reproduce**
    After being frozen by the Ice Dragonsteel Sword (mod:Ice and Fire), the Nether Dragon falls into the ground destroying a large number of blocks, and has a high probability of falling into Void. I suspect this effect can be repeated with all frozen weapons.
    The dragon seems to have no concept of the ground, it just drops to detect the surrounding blocks and destroys them in passing

**Screenshots**
 
**Versions (Note that 'latest' is NOT a valid version!**
Chocolate Quest Repoured:[Beta 6.12]
Forge:1.12.2-Forge_14.23.5.2859
Minecraft:1.12.2
Other mods (necessary to reproduce the bug):Ice and Fire

**Log File**
Please use a paste site to upload the log file (for example https://gist.github.com/) and provide the link to the file here.

**Comment by DerToaster98** [comment]
Nether dragon has no clip. so the behavior is actually ok. Freezing the nether dragon is not a intended feature of the mod.
Report to ice and fire that they should watch out a bit more  what mob to freeze.

**Comment by DerToaster98** [comment]
Just checked their github. There seems to be **no way** for us to fix this since they don't provide any API or possibility for other mods to prevent entities getting frozen without using ASM to rewrite their code.

Report to ice and fire, issue closed.
