### ISSUE TITLE
Tavernfolk do not attack Undead Mobs by default

### ISSUE THREAD

**Issue by minekraftminer** [TeamChocoQuest/ChocolateQuestRepoured#378]
**General Information**
To check a checkbox: Insert a X between the square brackets, you need to remove the space though.
 - I play...
   - [ ] With a large modpack
   - [x] Only with CQR and it's dependencies
 - The issue occurs in...
   - [x] Singleplayer
   - [ ] Multiplayer
 - [x] I have searched for this or a similar issue before reporting and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
 - [x] I am using the latest version of the mod (all versions can be found on github under releases)
 - [x] I read through the FAQ and I could not find something helpful ([FAQ](https://wiki.cq-repoured.net/index.php?title=FAQ))
 - [x] I reproduced the bug without any other mod's except forge, cqr and it's dependencies
 - [ ] The game crashes because of this bug
 
**Describe the bug**
Tavernfolk are not aggressive towards Undead enemies by default.

**To Reproduce**
1. Find a tavern with the default config
2. Have undead mob by the tavern

**Screenshots**
![image](https://user-images.githubusercontent.com/82829316/226197299-0b7c0e15-2922-41ab-b8fb-c6d60d66d23d.png)
![image](https://user-images.githubusercontent.com/82829316/226197709-043654bf-bea9-437d-8a44-12c7648fcf11.png)

 
**Versions (Note that 'latest' is NOT a valid version!**
Chocolate Quest Repoured: 2.6.12
Forge: 14.23.5.2860
Minecraft: 1.12.2
Other mods (necessary to reproduce the bug): None

**Comment by DerToaster98** [comment]
Fixed in release 2.6.13B
