### ISSUE TITLE
1.12.2 CQR and Furniture mod incompatibility.

### ISSUE THREAD

**Issue by Slayer5934** [TeamChocoQuest/ChocolateQuestRepoured#381]
**General Information**
To check a checkbox: Insert a X between the square brackets, you need to remove the space though.
 - I play...
   - [ ] With a large modpack
   - [X] Only with CQR and it's dependencies
 - The issue occurs in...
   - [X] Singleplayer
   - [ ] Multiplayer (not tested)
 - [X] I have searched for this or a similar issue before reporting and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
 - [X] I am using the latest version of the mod (all versions can be found on github under releases)
 - [X] I read through the FAQ and I could not find something helpful ([FAQ](https://wiki.cq-repoured.net/index.php?title=FAQ))
 - [X] I reproduced the bug without any other mod's except forge, cqr and it's dependencies
 - [ ] The game crashes because of this bug
 
**Describe the bug**
With CQR and it's dependencies installed MrCrayfish Furniture mod (possibly others) tile entities do not place/render correctly.

**To Reproduce**
1. Install CQR and Furniture mod
2. Place Grand Chair
3. It does not render correctly and right clicking makes it poof.

**Screenshots**
![Screenshot_20230425_073946](https://user-images.githubusercontent.com/20819543/234266379-bdde9a60-b395-4f86-96aa-3d651cceea24.png)

**Versions (Note that 'latest' is NOT a valid version!**
Chocolate Quest Repoured: chocolate-quest-repoured-1-12-2-2-6-12b
Forge: 14.23.5.2860
Minecraft: 1.12.2

Other mods (necessary to reproduce the bug):
MrCrayfish Furniture mod (possibly others)

**Log File**
[latest.log](https://github.com/TeamChocoQuest/ChocolateQuestRepoured/files/11322122/latest.log)

**Comment by Meldexun** [comment]
This is not an issue on CQRs side. MrCrayfish's Furniture Mod is calling `World#setBlockState` within `BlockGrandChair#getStateForPlacement`. This is unexpected behavior and should be fixed by MrCrayfish's Furniture Mod as other mods besides CQR might have the same issue.
