### ISSUE TITLE
compatibility issue with ohaiichun's morph mod

### ISSUE THREAD

**Issue by sampoundgamin** [TeamChocoQuest/ChocolateQuestRepoured#382]
**General Information**
To check a checkbox: Insert a X between the square brackets, you need to remove the space though.
 - I play...
   - [ x] With a large modpack
   - [ ] Only with CQR and it's dependencies
 - The issue occurs in...
   - [ x] Singleplayer
   - [x ] Multiplayer
 - [1 ] I have searched for this or a similar issue before reporting and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
 - [x ] I am using the latest version of the mod (all versions can be found on github under releases)
 - [ x] I read through the FAQ and I could not find something helpful ([FAQ](https://wiki.cq-repoured.net/index.php?title=FAQ))
 - [ ] I reproduced the bug without any other mod's except forge, cqr and it's dependencies
 - [x ] The game crashes because of this bug
 
**Describe the bug**
ive noticed that when using ohaiichun's morph mod for 1.12.2 and cqr the game will run, but after killing a mob from cqr and thus acquiring its morph if i try and open the morph menu the game will crash and it says it has trouble with loading the entity. this doesnt happen with other mods that add mobs so i dont know why it does with this one.

**To Reproduce**
use CQR and ohaiichuns morph mod, kill a CQR mob, and open morph menu with the "["  key  (a few exceptions so if it doesnt crash the first time kill a different CQR mob)

**Screenshots**
 
**Versions (Note that 'latest' is NOT a valid version!**
Chocolate Quest Repoured: beta 6.13
Forge: 14.23.5.2859
Minecraft: 1.12.2
Other mods (necessary to reproduce the bug): 

**Log File**
(https://gist.github.com/sampoundgamin/8926801e484325f9033e320b420f1607)

**Comment by DerToaster98** [comment]
Update cqr, this has been patched in v2.6.13, you're using 2.6.12B

Issue closed
