### ISSUE TITLE
[ARC] Dungeon Generation

### ISSUE THREAD

**Issue by LordEpos** [TeamChocoQuest/ChocolateQuestRepoured#39]
For alpha release, the mod should be able to:
- Dungeons should generate in the world.  - DONE
- Items in the creative inventory which summon each dungeon type. - DONE
- On generation, dungeons will maintain air blocks as air, and 'replace' null blocks with whatever was previously present in the world. - DONE
- On generation, dungeons will replace exporter chests with vanilla chests, and randomize loot pools for them based on config settings. - DONE
- Monster spawners of both types as well as other blocks, like vanilla chests and furnaces, should keep all metadata and settings upon export. DONE
- dungeons should generate with configurable vertical offsets, in configurable lists of biomes.  DONE
- dungeons should be capable of replacing dummies on generation with the correct mob types. 0% done, i need the dummies to exist first, would be functionality of spawner, not the dungeon, as the spawner knows if it is inside a dungeon - WORKING ON IT
- Exporter should be able to select an area and save it as a dungeon. about DONE

**Comment by DerToaster98** [comment]
@LordEpos 
COuld you move this whole thing into an own milestone? That makes it easier to update and keep track of its progress
