### ISSUE TITLE
Array Index out of Bounds on Dungeon Generation

### ISSUE THREAD

**Issue by WesleySnacks** [TeamChocoQuest/ChocolateQuestRepoured#408]
**General Information**
To check a checkbox: Insert a X between the square brackets, you need to remove the space though.
 - I play...
   - [X] With a large modpack
   - [ ] Only with CQR and it's dependencies
 - The issue occurs in...
   - [ ] Singleplayer
   - [X] Multiplayer
 - [X] I have searched for this or a similar issue before reporting and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
 - [X] I am using the latest version of the mod (all versions can be found on github under releases)
 - [X] I read through the FAQ and I could not find something helpful ([FAQ](https://wiki.cq-repoured.net/index.php?title=FAQ))
 - [ ] I reproduced the bug without any other mod's except forge, cqr and it's dependencies
 - [X] The game crashes because of this bug
 
**Describe the bug**
Sometimes, but not always, when generating a dungeon the server crashes.
On server restart the dungeon loads in fine, but it's impossible to know when the next dungeon generation will crash or if it will be fine.

**To Reproduce**
1. Explore the world.
2. Reach a location where a chocolate quest dungeon is going to appear [edited for clarity]
3. Get a server closed message.

**Versions (Note that 'latest' is NOT a valid version!**
Chocolate Quest Repoured: 2.16.14B
Forge: 14.23.5.2860
Minecraft: 1.12.2

**Log File**
https://gist.github.com/WesleySnacks/9b69442082cbd8570a86fcb5a48206f9

**Comment by DerToaster98** [comment]
Fixed in v2.6.15B
