### ISSUE TITLE
[1.12.2] Geckolib-modeled entities may not animate/glow with shaders

### ISSUE THREAD

**Issue by Vetpetmon** [TeamChocoQuest/ChocolateQuestRepoured#409]
**General Information**
 - I play...
   - [ ] With a large modpack
   - [X] Only with CQR and it's dependencies
 - The issue occurs in...
   - [X] Singleplayer
   - [X] Multiplayer
 - [X] I have searched for this or a similar issue before reporting and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
 - [X] I am using the latest version of the mod (all versions can be found on github under releases)
 - [X] I read through the FAQ and I could not find something helpful ([FAQ](https://wiki.cq-repoured.net/index.php?title=FAQ))
 - [ ] I reproduced the bug without any other mod's except forge, cqr and it's dependencies
 - [ ] The game crashes because of this bug
 
**Describe the bug**
When playing with shaders, either by optifine or by another mod, some Geckolib entities will play their animations just fine, but others may stop animating and enter their "T-pose." Additionally, glow layers may not render when shaders are enabled. This is a Geckolib issue & happens with the animations of other mods that rely on Geckolib.

**To Reproduce**
1. Install Optifine or a shader-providing mod
2. Activate a shaderpack
3. Spawn 2-4 mobs that utilize Geckolib, I used the Ender Calamity for testing.

**Screenshots**
![image](https://github.com/TeamChocoQuest/ChocolateQuestRepoured/assets/10699805/912e3730-cd4d-4589-954d-14c0c533fb03)
 
**Versions (Note that 'latest' is NOT a valid version!**
Chocolate Quest Repoured: 2.6.16B
Forge: 14.23.5.2830
Minecraft: 1.12.2
Other mods (necessary to reproduce the bug): 
- Optifine HD U G5
- Geckolib 3.0.31 (Required by CQR)
- Reachfix 1.0.9 (Required by CQR)

**Log File**
There is nothing printed into Debug or Logging files.

**Comment by DerToaster98** [comment]
Issue with shaders. The nature of shader mods is that they effectively completely nuke the render pipeline.

The glow effect is handled by a renderlayer on our side. And animating and glow effect are two very different things. 

The problem here is that shader mods break geckolib. Report this to the shader mods, but report it as "shaders break core functionality of geckolib" since that is more accurate.

**Comment by DerToaster98** [comment]
You mentioned that some geckolib mobs still animate fine. Could you tell me which those are?

Iirc it depends on the animations themselves, if they use a certain thing they get broken by shaders.

Probably won't change anything about the glow layer. Also in the provided screenshot the eyes render just fine, so the glow layer *does* render

**Comment by Vetpetmon** [comment]
> You mentioned that some geckolib mobs still animate fine. Could you tell me which those are?

The animations that don't break are _the same ones that do break_. It's inconsistent, so some entities will have their animations play perfectly fine, and others in the same frame will be stuck in their T-pose.

**Comment by DerToaster98** [comment]
Very weird. Well in that case neither we or geckolib can fix this. Report it to the shader mods please
