### ISSUE TITLE
Traitor Parrot unkillable

### ISSUE THREAD

**Issue by gwynhefar** [TeamChocoQuest/ChocolateQuestRepoured#410]
**General Information**
To check a checkbox: Insert a X between the square brackets, you need to remove the space though.
 - I play...
   - [x] With a large modpack
   - [ ] Only with CQR and it's dependencies
 - The issue occurs in...
   - [x] Singleplayer
   - [ ] Multiplayer
 - [x] I have searched for this or a similar issue before reporting and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
 - [x] I am using the latest version of the mod (all versions can be found on github under releases)
 - [x] I read through the FAQ and I could not find something helpful ([FAQ](https://wiki.cq-repoured.net/index.php?title=FAQ))
 - [ ] I reproduced the bug without any other mod's except forge, cqr and it's dependencies
 - [ ] The game crashes because of this bug
 
**Describe the bug**
The traitor parrot is marked as “Tamed” and is thus unkillable when combined with any mod that prevents “friendly fire” towards pets 

**To Reproduce**
1. Attempt to kill traitor parrot with friendly fire disabled
2. 
3. 
4. ...

**Screenshots**
 
**Versions (Note that 'latest' is NOT a valid version!**
Chocolate Quest Repoured:
Forge: 14.23.5.2860
Minecraft: 1.12.2
Other mods (necessary to reproduce the bug): I’m using Charm but there are others

**Log File**
Please use a paste site to upload the log file (for example https://gist.github.com/) and provide the link to the file here.

**Comment by DerToaster98** [comment]
Report it to that friendly fire mod please. Thatcparrot is „tamed“ on purpose. Maybe suggest to them that you only can’t damage your own or other team members pets?
