### ISSUE TITLE
Entity HP Increased To 10000+

### ISSUE THREAD

**Issue by Kazupathry** [TeamChocoQuest/ChocolateQuestRepoured#411]
**General Information**
 - I play...
   - [x] With a large modpack
 - The issue occurs in...
   - [X] Singleplayer
 - [X] I have searched for this or a similar issue before reporting and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
 - [X] I am using the latest version of the mod (all versions can be found on github under releases)
 - [X] I read through the FAQ and I could not find something helpful ([FAQ](https://wiki.cq-repoured.net/index.php?title=FAQ))
 
**Describe the bug**
The HP of all entities the mod adds is increased to 10000+ whenever I encounter them, it is probably a conflict with another mod however I'm not sure which one it is, this is something I can't ignore however, if possible help would be appreciated.

**To Reproduce**
1. Create World
2. Go To Structure
3. Let Entities Spawn

**Versions**
Chocolate Quest Repoured: 1.12.2 2.6.16B
Other Mods: Too Many To List

**Log File**
https://gist.github.com/Kazupathry/2b4a7434705314cc6bb3ecbd3fc7468d

![2024-06-27_21 27 53](https://github.com/TeamChocoQuest/ChocolateQuestRepoured/assets/133454883/dbbe7ca6-cce3-414e-873e-d01a3414bb14)

**Comment by DerToaster98** [comment]
The entity HP scales with the distance to the world's spawn point. So if you're far out the enemies will have a lot of health.

Can also be caused by mods that alter the spawnpoint (mods like that one mod that puts the spawnpoint on a random place everytime you die).

**Comment by DerToaster98** [comment]
You can disable that feature in the mod's config (enableHealthChangeOnDistance) though.
