### ISSUE TITLE
Sometimes bosses do not spawn while in survival mode, chunk was unloaded and reloaded, still did not spawn.

### ISSUE THREAD

**Issue by Slayer5934** [TeamChocoQuest/ChocolateQuestRepoured#93]
![Capture](https://user-images.githubusercontent.com/20819543/71633402-fe29a700-2be1-11ea-82b8-d985044a09b6.PNG)

**Comment by DerToaster98** [comment]
This is not a bug. The boss block actually isnt a spawner block, it is a placeholder. If there is still a boss block then wwe havent made the boss for the faction of that dungeon by now
