### ISSUE TITLE
[Feature Request] The volcano structure does not allow modded ores to spawn within the stone.

### ISSUE THREAD

**Issue by Slayer5934** [TeamChocoQuest/ChocolateQuestRepoured#96]
![Capture](https://user-images.githubusercontent.com/20819543/71633550-c5d69880-2be2-11ea-8a97-ace20bac31e7.PNG)

**Comment by jackowski626** [comment]
But, will it be a future feature?

**Comment by DerToaster98** [comment]
maybe

**Comment by DerToaster98** [comment]
yes it will be via config option

**Comment by xJon** [comment]
Does `oreBlocks` under `Volcano.properties` accept metadata?

**Comment by DerToaster98** [comment]
yes it does.
it has to look like this:
modnamespace:block:meta,modnamespace:block2:meta,etc.
