### ISSUE TITLE
Server crashes on launch, possibly due to another mod*, looks like its trying to start as client for the server.

### ISSUE THREAD

**Issue by Slayer5934** [TeamChocoQuest/ChocolateQuestRepoured#97]
[crash-2019-12-31_14.50.18-server.txt](https://github.com/TeamChocoQuest/ChocolateQuestRepoured/files/4013443/crash-2019-12-31_14.50.18-server.txt)

**Comment by DerToaster98** [comment]
@Meldexun is this fixed? If yes, please close the issue
