### ISSUE TITLE
[Maybe-Not-A-Bug] NPC do not consider friendly fire, and will shoot arrows even when friendly mob is 1 foot away.

### ISSUE THREAD

**Issue by Slayer5934** [TeamChocoQuest/ChocolateQuestRepoured#98]
![Capture](https://user-images.githubusercontent.com/20819543/71633668-aab85880-2be3-11ea-920d-23fa6a53ae92.PNG)

**Comment by DerToaster98** [comment]
Not enough explanation, this literally says nothing what the "bug" is

**Comment by Slayer5934** [comment]
When trying to fire an arrow at the player, the NPC will always fire even with a friendly in the way, this causes damage to the friendly NPC and the one firing the arrow will not stop.

**Comment by DerToaster98** [comment]
ok, thank you, well technically it isnt a bug, but more something of the sort of "we didnt thought about xxx", will be fixed asap

**Comment by LordEpos** [comment]
Vanilla behavior, we'll see what we can do about it, but it's bound to happen by accident at some point.
