### ISSUE TITLE
Sometimes when spawning multiple NPCs from a soul cage, one of the NPCs gets pushed into a wall, this NPC suffocates and dies.

### ISSUE THREAD

**Issue by Slayer5934** [TeamChocoQuest/ChocolateQuestRepoured#99]
![Capture](https://user-images.githubusercontent.com/20819543/71633799-88730a80-2be4-11ea-88ab-af39aa6b786c.PNG)

**Comment by DerToaster98** [comment]
Not a bug, is caused by vanilla pushing entities apart. the soul bottle actually places the mob where you clicked

**Comment by Slayer5934** [comment]
I should have clarified that this happens with the soul cages from the generating structures, but it is true this is a vanilla bug, and probably not big of a deal anyways :3

**Comment by DerToaster98** [comment]
ah, those are called spawners. that bug is known and being worked on

**Comment by Slayer5934** [comment]
Once you guys find a fix for that one, it could probably be implemented into the soul bottles (unless you just move the spawners from the wall, that would probs fix it) o;
